### ISSUE TITLE
fermata + beam interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#1028]
When a fermata collides with a beam, it is automatically moved to avoid the collision; however, the decision on where to vertically place the fermata is based on the bounding box of the beam, rather than a more refined placement relative to the portion of the beam that collides with the fermata.

Here is a case where the fermata fits without adjustment:

<img width="500" alt="Screen Shot 2019-03-27 at 1 16 17 PM" src="https://user-images.githubusercontent.com/3487289/55098081-8ac39980-5093-11e9-8f29-4d8090f29e54.png">

And here is a case where it needs to be moved up to avoid collision with the beam when the spacing is tighter:

<img width="458" alt="Screen Shot 2019-03-27 at 1 15 58 PM" src="https://user-images.githubusercontent.com/3487289/55098115-9ca53c80-5093-11e9-8d14-374dcd66be66.png">

The vertical placement of the fermata is related to the red horizontal line, but should be based on the green horizontal line.  A basic improvement would be to only consider the beam height at the side of the beam closest to the fermata.  This should be good for nearly all cases (but could break for very tight spacing and very steep beam angles).  Further refinement would calculate the vertical position of the beam at the intersection point of the collision with the left edge of the fermata (but that would probably be overkill).

This is related to issue https://github.com/rism-ch/verovio/issues/247, where the problem was between `<dir>` and `<slur>`.

**Comment by rettinghaus** [comment]
@craigsapp after #247 was closed, could you please check this one again?

**Comment by craigsapp** [comment]
This case is now handled correctly:
<img width="392" alt="Screen Shot 2022-02-20 at 5 53 49 AM" src="https://user-images.githubusercontent.com/3487289/154846012-fab01c50-f52a-4d3e-b7b9-9dc0ab85f318.png">


MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-02-20T05:54:18" version="3.9.0-dev-93a6934">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="map8ndb">
    <score xml:id="seht8gj">
     <scoreDef xml:id="s8ciwy4">
      <staffGrp xml:id="s821xbd">
       <staffDef xml:id="s1j7wce" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="sr8go2s" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <beam xml:id="beam-L3F1-L13F1">
          <note xml:id="note-L3F1" dur="16" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L4F1" dur="16" oct="5" pname="e" accid.ges="n" />
          <note xml:id="note-L5F1" dur="16" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L6F1" dur="16" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L7F1" dur="16" oct="4" pname="b" accid.ges="n" />
          <note xml:id="note-L8F1" dur="16" oct="4" pname="a" accid.ges="n" />
          <note xml:id="note-L9F1" dur="16" oct="4" pname="g" accid.ges="n" />
          <note xml:id="note-L10F1" dur="16" oct="4" pname="f" accid.ges="n" />
          <note xml:id="note-L11F1" dur="16" oct="4" pname="e" accid.ges="n" />
          <note xml:id="note-L12F1" dur="16" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L13F1" dur="16" oct="4" pname="c" accid.ges="n" />
         </beam>
         <note xml:id="note-L14F1" dur="4" oct="3" pname="b" accid.ges="n" />
        </layer>
       </staff>
       <fermata xml:id="fermata-L14F1" staff="1" startid="#note-L14F1" place="above" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```
