### ISSUE TITLE
MusicXML import puts staves into wrong measures when measure numbers repeat

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#1082]
This 4-part piece contains 3 different pieces/sections that each starts a measure count from "1". Therefore, the first part is imported correctly, but starting from the second, each measure named "1" is added to the very first measure. The reason is the function `MusicXmlInput::addMeasure()` matches a measure by its numberlike string, which may not be unique.: (https://github.com/rism-ch/verovio/blob/b6708c9386e6e1fefc510b46993f766be02b2124/src/iomusxml.cpp#L179 

The measure matching should be based on a measure count, such as used in #1078. What do you think?

This is the musicXML example 
[SinfoniaB-Dur.xml.txt](https://github.com/rism-ch/verovio/files/3218416/SinfoniaB-Dur.xml.txt)

Resulting in this MEI file: 
[SinfoniaB-Dur.mei.txt](https://github.com/rism-ch/verovio/files/3218417/SinfoniaB-Dur.mei.txt)

The first page (10 staves instead of 4 of a string quartet):
<img width="690" alt="grafik" src="https://user-images.githubusercontent.com/45632600/58353834-dade9280-7e6f-11e9-832f-778c071297e5.png">

**Comment by rettinghaus** [comment]
I think best approach would be to check if the part starts with a first measure create a new `<mdiv>` to contain the music.

**Comment by wergo** [comment]
Adding `<mdiv>` automatically is a great idea. But then Verovio should be able to render all mdivs at once (such as a complete Sonata or a collection of pieces that might end and start on the same page).

**Comment by rettinghaus** [comment]
@wergo as Verovio now supports rendering of multiple mdiv, you may want to get back to this?

**Comment by wergo** [comment]
Yes, this would be an important thing to look into. I lack resources at the moment; could you?

**Comment by lpugin** [comment]
I assume this not to be an issue anymore
