### ISSUE TITLE
Add pageWidth/HeightScaled parameters

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#1533]
The default value of `--unit` is 9, but it is unclear from the documentation/options, what this "9" means, i.e. what real-world units are meant. Internally it translates to 90 pixel for the output, which then is "scaled back" by 1 : 10 ratio in the svg between width/height and `viewBox`. Why has this way been chosen, and why are only integer value allowed/accepted for unit? 

Another problem is, that `--mm-output` doesn't translate the effective pixels correctly into mm, because px and mm are absolute values. 
Converting between units isn't just renaming them. If `--mm-output` is used, the `vu` isn't set to 9 pixels, nor to 9 millimeters, so it feels like just a random number controlling the staff height. 

The absolute values should be converted this way: 
in = inches (1in = 96px = 2.54cm)
px = pixels (1px = 1/96th of 1in)
pt = points (1pt = 1/72 of 1in)
pc = picas (1pc = 12 pt)

Or, to put it another way: using Verovio in a browser, independently of which unit is used for output, it should always look the same.

**Comment by lpugin** [comment]
> Why has this way been chosen, and why are only integer value allowed/accepted for unit?

This used to be thought for printed output with a staff space of 1.8mm (unit 0.9mm). Accordingly the default page size is 2970 and 2100 which coincidentally matches A4 mm times 10 

`--mm-output` was added to have the conversion from SVG to PDF to produce the desired size.

**Comment by lpugin** [comment]
To clarify the `--mm-output`: it does not mean 'converting' to mm, but instead output units in mm (actually 1/10mm). I agree we should clarify this. So do we need to clarify that default units are pixels.

(AFAIK, SVG does not make any assumptions on the dpi to be used for the conversion - CSS2 does, but not SVG. Some tools use 72dpi, some 90dpi, others 96dpi (e.g., browsers). This is notoriously problematic. So I think it is better to stay away from the idea that we can convert pixels to mm)

**Comment by rettinghaus** [comment]
So, why not use `mm` as default? All the default values are pointing to a A4 format layout. Instead we then could use a `--output-width` option (including unit), which sets svg's `@width` and `@height` accordingly, e.g. `500pt`, `382px`, or `12em`. That would be easier than trying to figure out a suitable solution with `scale` and `page-width` and `unit` …

**Comment by lpugin** [comment]
We could have --scaledPageHeight/Width options that avoids pre-calculation of the the dimensions. This was already requested before https://github.com/rism-ch/verovio/issues/1055 . I think that would be the same as what you are suggesting, wouldn't it?

**Comment by lpugin** [comment]
@rettinghaus do you want to add these options? Thinking about it, a preferred name would be `--pageHeightScaled` and `--pageWidthScaled`. I think it would work to have a minimal value of 100 but then initialize it with 0 internally which would indicate that `--pageHeight` should be used. Something like:
```c++
m_pageHeightScaled.Init(0, 100, 60000, true);
```

**Comment by rettinghaus** [comment]
I'll play around with this …

**Comment by lpugin** [comment]
Re-open if necessary.
