### ISSUE TITLE
pageMarginTop default value change (from 50 to 100)

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#1553]
The origin point for the `top-page-margin` options has changed recently.  It used to be above the top staff (maybe about 12 diatonic steps or more), but now the origin is set to the top staffline of the SVG image.

The old default value for `top-page-margin` was 50, but this should change to 100 in order to account for this change in origin.

Here is an illustration of the problem:

Using the default value of 50 for `top-page-margin` will cause high notes in the image to be clipped:

<img width="537" alt="Screen Shot 2020-07-13 at 8 45 11 AM" src="https://user-images.githubusercontent.com/3487289/87325044-ce8b1e00-c4e5-11ea-82a5-629d425e1b21.png">

The top of the SVG image viewport is at the boundary of the blue box of the VHV header.

If the `top-page-margin` is set to 100, the note does not get clipped:

<img width="537" alt="Screen Shot 2020-07-13 at 8 51 29 AM" src="https://user-images.githubusercontent.com/3487289/87325239-0d20d880-c4e6-11ea-9282-260b141d9258.png">

Moving the note an octave higher, there will be an additional automatic adjustment added to the top margin, but at `pageTopMargin=50` there is still clipping:

<img width="537" alt="Screen Shot 2020-07-13 at 8 53 11 AM" src="https://user-images.githubusercontent.com/3487289/87325430-49eccf80-c4e6-11ea-9339-2f767390ad8b.png">

While for `pageTopMargin=100` there is still no clipping:

<img width="537" alt="Screen Shot 2020-07-13 at 8 54 24 AM" src="https://user-images.githubusercontent.com/3487289/87325585-799bd780-c4e6-11ea-8261-4ad25e05dca4.png">

----------

Alternatively, it seems that `pageTopMargin=70` is the exact height for a bounding box with no extra padding:

<img width="638" alt="Screen Shot 2020-07-13 at 8 59 57 AM" src="https://user-images.githubusercontent.com/3487289/87326172-40179c00-c4e7-11ea-9803-0047cfb173c3.png">

Compare to 75, which puts a little padding above the l's in Allegro:

<img width="638" alt="Screen Shot 2020-07-13 at 9 00 44 AM" src="https://user-images.githubusercontent.com/3487289/87326252-56bdf300-c4e7-11ea-8ec7-bebfb3241c7d.png">

Compare to 100:

<img width="638" alt="Screen Shot 2020-07-13 at 9 01 41 AM" src="https://user-images.githubusercontent.com/3487289/87326354-7a813900-c4e7-11ea-9909-b27786215024.png">

and 50:

<img width="638" alt="Screen Shot 2020-07-13 at 9 02 08 AM" src="https://user-images.githubusercontent.com/3487289/87326409-8967eb80-c4e7-11ea-912d-5d07a76552f0.png">

and 0:

<img width="638" alt="Screen Shot 2020-07-13 at 9 02 31 AM" src="https://user-images.githubusercontent.com/3487289/87326457-971d7100-c4e7-11ea-9847-ea991c7030e8.png">

**Comment by lpugin** [comment]
> The origin point for the top-page-margin options has changed recently

I suspect this PR https://github.com/rism-ch/verovio/pull/1523/files but I am not absolutely sure

**Comment by craigsapp** [comment]
It is not a problem to me if the origin changes, but if it does, then the `pageMarginTop` default value should be updated.

**Comment by lpugin** [comment]
Should also be addressed by https://github.com/rism-digital/verovio/pull/2632
