### ISSUE TITLE
Remove the need for notationtype = 'neume' to render neumatic notation

### ISSUE THREAD

**Issue by martha-thomae** [rism-digital/verovio#1598]
Is it possible to remove the need for encoding `@notationtype = "neume"`on `<staffDef>` so that Verovio renders a file in neume notation? Currently, Verovio does not like `<syllable>` within `<layer>` unless it is neume notation and that is clearly indicated within `<staffDef>`.

This might be useful when you want to render a piece that contains symbols from different notation systems (like c_antus fractus_ for example, which mixes symbols from both neume and mensural in one voice, see https://github.com/music-encoding/music-encoding/issues/645#issuecomment-651931466).

**Comment by lpugin** [comment]
I don't think we can reasonably to this. I am putting it on the back-burner for now.
