### ISSUE TITLE
Delayed turn placement enhancements

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#1619]
Turns try to position themselves above the top line of a staff, and move upwards if they detected a collision.

Instead, it would be better if: (1) they are allowed to enter the staff if necessary, and (2) position themselves between the two notes of the turn (when the turn is delayed).

Here is an example from Beethoven piano sonata no. 19, mvmt. 1:

<img width="755" alt="Screen Shot 2020-08-19 at 2 41 04 PM" src="https://user-images.githubusercontent.com/3487289/90692843-aef4bd00-e22a-11ea-817c-bff14e8587c9.png">

A better placement would be closer to the level of the two adjacent notes related to the turn:

<img width="738" alt="Screen Shot 2020-08-19 at 2 45 33 PM" src="https://user-images.githubusercontent.com/3487289/90692879-bcaa4280-e22a-11ea-86d1-1f7ec306c012.png">

This would be somewhat similar to the automatic positioning for rests to avoid beams:

<img width="249" alt="Screen Shot 2020-08-19 at 2 47 34 PM" src="https://user-images.githubusercontent.com/3487289/90693039-0004b100-e22b-11ea-94b3-c415308b0fe0.png">

Almost never should the turn be placed further from the staff than a slur between the two adjacent turn notes.

Here is the original typesetting for the two turns:

<img width="341" alt="Screen Shot 2020-08-19 at 2 35 04 PM" src="https://user-images.githubusercontent.com/3487289/90693065-0c890980-e22b-11ea-9731-6bdca0dd512b.png">

<img width="335" alt="Screen Shot 2020-08-19 at 2 35 12 PM" src="https://user-images.githubusercontent.com/3487289/90693069-0e52cd00-e22b-11ea-8845-246d9a776298.png">

Here is an example from the same movement for the beam going in the opposite direction:

<img width="616" alt="Screen Shot 2020-08-19 at 2 36 04 PM" src="https://user-images.githubusercontent.com/3487289/90693242-540f9580-e22b-11ea-9d2d-567cc2e551eb.png">

In this case `@place="above"` would not try to place the turn between the two notes, since that would place the turn below the beam, but `@place="below"` should try to place the turn between the notes inside of the staff.

**Comment by Monceber** [comment]
Should be fixed by #2348.
