### ISSUE TITLE
options in MEI's virtual units

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#1673]
There are inconsistencies in the options. Some value are given in staff spaces instead of virtual units, e.g. `slurMinHeight` and `slurMaxHeight`.

**Comment by lpugin** [comment]
Are you sure?
https://github.com/rism-digital/verovio/blob/f6b6a1121bf54798c0822f8b3cf1e55ac1d169ad/src/options.cpp#L1117-L1123

https://github.com/rism-digital/verovio/blob/87d12a5a6beae99aaa6f3eef2e94710e5b0aab1e/src/view_slur.cpp#L538-L539
Please double check.

**Comment by rettinghaus** [comment]
Whatever went wrong there seems to be gone now.
