### ISSUE TITLE
Text font option not working with the JS toolkit

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#1708]
The MEI viewer currently display this:

![image](https://user-images.githubusercontent.com/689412/94576541-bf5e7580-0275-11eb-989f-22ec20262919.png)

`<dir>` and `<pgHead>` layout is broken.

**Comment by rettinghaus** [comment]
Lyric behaviour is also affected. CLI is working, though. I guess, it's connected to #1706, because `textFont` option isn't registered in the toolkit.

**Comment by lpugin** [comment]
As far as I can see it is registered
![image](https://user-images.githubusercontent.com/689412/94577290-ae623400-0276-11eb-828a-ce17f78004f4.png)

**Comment by lpugin** [comment]
OK, for now I reverted #1691. Let's see.

**Comment by lpugin** [comment]
Enabling the text font to be changed with the JS toolkit will not be straight forward because each font file will need to be passed and loaded into it. However, we can already have the feature merged back when it is simply leaves the JS toolkit working as before with the default font.
