### ISSUE TITLE
Check clang format on PR

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#1762]
It would be good to check that PRs are compliant with clang formatting. One simple way to do it would be to run clang-format on the code and fails if anything is not properly formatted. That is, if this yields any modifications.

Clang formatting call on the code should be:
```
clang-format -i -style=file include/vrv/*.h
clang-format -i -style=file src/*.cpp
```

One possible problem with this might be if the contributor uses a different version of clang-format resulting in different formatting output.

**Comment by lpugin** [comment]
> Wouldn't it be easier to run clang on any commit and PR from GH actions and not to fail but to provide the modifications in turn? Thus, the local version of clang-format would not matter...

I am not too sure about this. First I think it is a good for contributors to format their code before making a PR. But I think the main point is that making modification of the code during the PR then makes tracking who made a change more difficult because the last change will appear as having been done by the system and not by the contributors. 

So since just checking looks much simpler to put in place I would be interested to try with this first.

> Is it important from which path the clang formatting is called?

Yes, it needs to be called from the root directory because the configuration file `.clang-format` is there. (Alternatively, there must be a way to path the configuration file to the command.)

**Comment by musicEnfanthen** [comment]
> First I think it is a good for contributors to format their code before making a PR.

Yes, I agree. But I also agree with your statement above that this could result in problems if a contributor uses a different version of clang-format resulting in different formatting output. Or even with the same version? How would we guarantuee the setting running on gh-actions is accepting your local changes that are formatted with, let's say, the same settings, but resulting in a slightly different output (due to any reasons). You would never get your commit pushed to the repo because gh-actions formatter would complain again and again without changing anything.

**Comment by musicEnfanthen** [comment]
Best option would probably be to run clang-formatter automatically **before** any commit on a local repo, maybe as `pre-commit` [git hook](https://githooks.com/). But Ia m not sure if it is possible to propagate git hooks from project side to local clones.

**Comment by ahankinson** [comment]
Can you have a GH action set a label on the PR that labels it as needing attention?

**Comment by musicEnfanthen** [comment]
Yes, should be possible in principle:

https://github.com/actions-ecosystem/action-add-labels 
https://github.com/buildsville/add-remove-label

**Comment by lpugin** [comment]
> Can you have a GH action set a label on the PR that labels it as needing attention?

Yes, I thinks would be sufficient for now. Basically have an action on PR evaluating the clang-format status. If running clang-format yields modifications, then add a label (or some feedback) that shows that there is a formatting issue. What would be good to see is what the modifications are, but I am not sure how this could be stored / made visible.

Then we can decide manually if the PR should still go through because the formatting issue is something the contributor cannot fix.

**Comment by musicEnfanthen** [comment]
Actions native solution to apply label: https://github.com/actions/github-script#apply-a-label-to-an-issue
