### ISSUE TITLE
clef allowed in fTrem?

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#1804]
I was surprised to find that Verovio allows `clef` as a child element of `fTrem`, whereas the schema doesn't (neither MEI3 nor MEI4). 
I can imagine that this may happen, but we should add it to MEI then. 
@craigsapp do you have a visual example in mind?

**Comment by craigsapp** [comment]
It is definitely possible:

<img width="331" alt="Screen Shot 2020-11-07 at 2 17 05 PM" src="https://user-images.githubusercontent.com/3487289/98452409-ed9c6400-2103-11eb-8116-a7914adc627b.png">

but probably very rare and/or only present in modern scores (no actual example that I am aware of).   So probably no problem to remove it, and it could be added to MEI when a real-world example is encountered.

**Comment by rettinghaus** [comment]
Closing this, as it has been clarified on MEI side.
