### ISSUE TITLE
Possible improvements to the test suite output page

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#1814]
In the new test suite it would be handy to be able to copy and paste a link to view and reference the exact test.

**Comment by lpugin** [comment]
Possible improvements to the test suite evaluation page:
* [ ] Add ability to link to a test (at least by category, e.g., to https://www.verovio.org/test-suite.xhtml?cat=ligature)
* [ ] Add a link to the PR (sha) at the top of the page
* [ ] Sort tabs (i.e., test folders) alphabetically
* [ ] Add to the path (or as sub-directories) the date and the name of the branch / user of the PR

**Comment by lpugin** [comment]
Link to a test: we can easily build the link like this (example for test ligature/ligature-017.mei): https://www.verovio.org/test-suite.xhtml?cat=ligature#example-ligature-017

**Comment by ahankinson** [comment]
Ah -- I meant link to a test that has failed, e.g., "https://test-suite.verovio.org/1234/abc123456#beam-004"

**Comment by lpugin** [comment]
* [ ] Adding an anchor to be able to point to an example (comment above) - we also need to activate the correct tab

**Comment by lpugin** [comment]
Closing for now since none of the open points have a high priority
