### ISSUE TITLE
@staff value when @place="between"

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#1842]
When using `@place="between"`, what is the correct contents of `@staff`?

In the following example, the dynamics in the first measure are placed between using `@staff="1"` for `p` and `@staff="1 2" for `f`.   In both cases the placement is correct.   Are both of those values allowed?   In other words, if there is only one staff given, it will be assumed that the second staff for the between placement with be staff n+1?   Or is this undefined behavior that may change in the future?

<img width="372" alt="Screen Shot 2020-11-20 at 8 05 15 AM" src="https://user-images.githubusercontent.com/3487289/99822090-a355b280-2b07-11eb-8ff8-8b933f926345.png">

In the second measure the `@place` is changed to `"above"`.  When the `@staff` is a list, this will cause a duplication of the dynamics.  This is of general use, but when editing music to move from between places to non-between places, this will be a hassle, since the official way is to require two staves for between?   Allowing one `@staff` and assuming n+1 for the other staff needed in the between placement will be more convenient.  If so, then perhaps adjust the MEI documentation for `@place="between"`.   

One possible rare use of multiple staves when `@place="between"` would be to add multiple dynamics with between placement (such as a shared dynamic between two piano parts on the same system).

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-11-20T08:04:04" version="3.1.0-dev-94a4985-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001865410211">
    <score xml:id="score-0000000564961578">
     <scoreDef xml:id="scoredef-0000001082098391">
      <staffGrp xml:id="staffgrp-0000001532687081" symbol="brace" bar.thru="true">
       <staffDef xml:id="staffdef-0000001298200411" n="1" lines="5">
        <clef xml:id="clef-L3F2" shape="G" line="2" />
        <meterSig xml:id="metersig-L4F2" count="4" unit="4" />
       </staffDef>
       <staffDef xml:id="staffdef-0000000507525629" n="2" lines="5">
        <clef xml:id="clef-L3F1" shape="F" line="4" />
        <meterSig xml:id="metersig-L4F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000001345840270" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L6F2" dur="2" oct="5" pname="c" accid.ges="n" />
         <note xml:id="note-L7F2" dur="2" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-0000001383379601" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L6F1" dur="2" oct="3" pname="c" accid.ges="n" />
         <note xml:id="note-L7F1" dur="2" oct="3" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <dynam xml:id="dynam-L6F3" place="between" staff="1 2" tstamp="1.000000">p</dynam>
       <dynam xml:id="dynam-L7F3" place="between" staff="1" tstamp="3.000000">f</dynam>
      </measure>
      <measure xml:id="measure-L8">
       <staff xml:id="staff-L8F2N1" n="1">
        <layer xml:id="layer-L8F2N1" n="1">
         <note xml:id="note-L9F2" dur="2" oct="5" pname="c" accid.ges="n" />
         <note xml:id="note-L10F2" dur="2" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L8F1N1" n="2">
        <layer xml:id="layer-L8F1N1" n="1">
         <note xml:id="note-L9F1" dur="2" oct="3" pname="c" accid.ges="n" />
         <note xml:id="note-L10F1" dur="2" oct="3" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <dynam xml:id="dynam-L9F3" place="above" staff="1 2" tstamp="1.000000">mp</dynam>
       <dynam xml:id="dynam-L10F3" place="above" staff="1" tstamp="3.000000">mf</dynam>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by lpugin** [comment]
Verovio is too nice ;-) `@staff="1"` with `@place="between"` is actually not valid MEI. We could add a warning somewhere.

I see you point regarding the need to change continuously between `@staff="1 2"` and `@staff="1"` when changing from between to above. Maybe another way to encode this would be to do `@staff="1"` `@place="below"` and a new attribute `@between="true"` that indicates it should be place between that next staff. But this would be a change in MEI and also having to change two attribute when changing from between to above.

**Comment by craigsapp** [comment]
From the perspective of a user interface (and programming interface), it would be better to not use multiple staff entries in `@place` to control the `between` position.  Using multiple staves in `@staff` is contextual in its behavior depending on the contents of `@place`: for `above` and `below` it inserts multiple symbols, but for `between` there is a single symbol inserted with two staff values required in `@place`.  Hard-coding the meaning of "between" to mean "between the current staff and the staff below (or above)" should be sufficient, since the between case is needed for the grand staff.   Using "between" for non-grand staff situations is not semantic.

A three-parameter `staff/place/between` system would work well.

> But this would be a change in MEI and also having to change two attribute when changing from between to above.

A more restricted case using only two parameters should also work well: `staff/place` where `@place="between"` means "place below the specified staff, but center between the specified staff and the next lower staff".  If there is no next lower staff, then "between" converts implicitly to "below".

When placing a floating element with `@tstamp`, the dual `staff/place` system is exactly equivalent to the `staff/place/between` system.  When using `@startid`, there will be a limitation in the two-parameter system, since there could be an event on the bottom staff, but no analog on the top staff, so attaching to the top staff would not be possible, and attaching to the bottom staff element would place it below the staff.

So if the limitation to prefer`@tstamp` when using `@place="between"` is acceptable, then the two-parameter system would work.

If it is not sufficient, then I think the three-parameter system (`staff/place/between`) would be better and easier to use than the current `staff/place` system.   Conceptually it is more robust even though there are more parameters to deal with.  Essentially the `staff/place` system is functioning as three parameters, with `@staff` currently serving two purposes, which is an aesthetic that is otherwise avoided in MEI.

---------

Initial development of `@place="between"` discussed what the "between" referred to, and `@staff="1 2` was decided as the way of expressing between what two staves.  But I think that this is overly generalized.  In all reasonable cases `@staff="n"` can be inferred to be `@staff="n n+1"` in the `staff/place` system.

For the `staff/place/between` system, `@place="below"` would imply `@staff="n n+1"`, and `@place="above"` would imply `@staff="n n-1"` when `@between="true"`.

If the two staves are not adjacent, then either that should be forbidden (which is probably the best thing to do), or utilize `@staff="1 5"` to be used to set the two staves.  This sort of situation is not semantic, and instead should be controlled by some sort of offset if the need arises in the future (for modern notation cases perhaps).

**Comment by lpugin** [comment]
@craigsapp this should discussed in the music encoding repository. I am closing it here.
