### ISSUE TITLE
Use ECMAScript 6 compatible export instead of CommonJS module.exports for JavaScript toolkit

### ISSUE THREAD

**Issue by nccurry** [rism-digital/verovio#1908]
The verovio JavaScript toolkit is currently using the following [CommonJS syntax](https://nodejs.org/api/modules.html#modules_module_exports) to expose verovio

```
module.exports = {
    toolkit: verovio.toolkit,
    module: Module
};
```

I have a [VueJS 3](https://github.com/vuejs/vue-next) project using [vite](https://github.com/vitejs/vite) which only supports [ES6 module export / import syntax](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export). It would be great if verovio could either use ES6 syntax:

```
export default {
    toolkit: verovio.toolkit,
    module: Module
};
```

or use [UMD](https://github.com/umdjs/umd) syntax so that verovio is consumable by projects needing ES6 syntax.

The following provides more background on this issue:
https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1

Emscripten [supports this natively](https://github.com/emscripten-core/emscripten/pull/6483) via the [EXPORT_ES6](https://github.com/emscripten-core/emscripten/blob/2.0.11/src/settings.js#L1021) setting.

**Comment by craigsapp** [comment]
Will that also be compatible with all modern browsers?

**Comment by nccurry** [comment]
The [vite documentation](https://github.com/vitejs/vite#browser-support) has [this compatibility link](https://caniuse.com/es6-module) for es6-module syntax, which says ~92% of users.

There is also [this compatibility link](https://caniuse.com/es6-module-dynamic-import) for es6-module-dynamic-import, which also says ~92% of users.

Looking at ES6 features more generally it seems [compatibility](https://caniuse.com/?search=es6) is consistently in that 92%+ range.

It is also supported in NodeJS as of version [13.2.0](https://nodejs.medium.com/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663), which was released in October 22, 2019.

A workaround for this is just to modify the export syntax of verovio by hand once you pull it down via npm.

**Comment by craigsapp** [comment]
ES6 is getting close to being universally available in all major browsers:

https://caniuse.com/?search=es6

<img width="1353" alt="Screen Shot 2020-12-25 at 10 41 06 PM" src="https://user-images.githubusercontent.com/3487289/103146743-67af9900-4702-11eb-93dc-8907343a6cc2.png">

It seems that IE11 has partial support for ES6, which is the only laggard.  So in the worst case, there would be an ES5 version and an ES6 version of the toolkit.  Is IE or Edge the default Windows 10 browser (I would not know 😉 )

**Comment by nccurry** [comment]
Looks like Edge is the default in Windows 10.

https://www.computerworld.com/article/3229068/how-to-replace-edge-as-the-default-browser-in-windows-10-and-why-you-shouldnt.html

https://computing.which.co.uk/hc/en-gb/articles/206600069-Change-Windows-10-s-default-browser-from-Edge#:~:text=Windows%2010%20comes%20with%20the,by%20following%20these%20simple%20steps.

**Comment by craigsapp** [comment]
That is good.  Why wold anyone use IE? 😃

**Comment by nccurry** [comment]
Old habits? Masochism? 😃

**Comment by lpugin** [comment]
Please make a PR is this is still a problem.
