### ISSUE TITLE
octave line extension over offset notes

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#1942]
When the last chord under an octave line contains notes that are offset to the right, the octave line should be extended to include the offset notes:

<img width="408" alt="Screen Shot 2021-01-11 at 8 36 17 AM" src="https://user-images.githubusercontent.com/3487289/104210921-4defa080-53e8-11eb-9bec-c9a6aa9fb4c7.png">

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-11T08:36:19" version="3.1.0-dev-1666d80-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001224670730">
    <score xml:id="score-0000001638878795">
     <scoreDef xml:id="scoredef-0000000630368861">
      <staffGrp xml:id="staffgrp-0000001108249085">
       <staffDef xml:id="staffdef-0000001778395235" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000000513614324" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L6F1" dur="4" oct.ges="6" oct="5" pname="f" accid.ges="n" />
         <chord xml:id="chord-L7F1" dur="4">
          <note xml:id="note-L7F1S1" oct.ges="6" oct="5" pname="a" accid.ges="n" />
          <note xml:id="note-L7F1S2" oct.ges="6" oct="5" pname="f" accid.ges="n" />
         </chord>
        </layer>
        <layer xml:id="layer-L2F1N2" n="2">
         <space xml:id="space-L6F2" dur="4" />
         <chord xml:id="chord-L7F2" dur="4">
          <note xml:id="note-L7F2S1" oct.ges="6" oct="5" pname="e" accid.ges="n" />
          <note xml:id="note-L7F2S2" oct.ges="6" oct="5" pname="c" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <octave xml:id="octave-0000000146611170" staff="1" startid="#note-L6F1" endid="#chord-L7F1" dis="8" dis.place="above" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

Real-world example:

https://verovio.humdrum.org/?file=beethoven/sonatas/sonata07-2.krn#mh64

**Comment by rettinghaus** [comment]
It is correctly rendered, if you assign the correct `@endid`!
![ottavaEnd](https://user-images.githubusercontent.com/7693447/109804195-46978700-7c22-11eb-81ae-3ce073960e6e.png)

**Comment by craigsapp** [comment]
That level of control/distinction allows for problems in the visual semantics of the notation rendering that is not otherwise possible in actual music notation: all notes at a given timestamp on a staff must be either in or out of the octave transposition.

Currently the `@tstamp` system cannot be used for octave lines.  So this issue could be converted into allowing `@tstamp2` rather than `@endid` which is more semantically appropriate for octave lines anyway.   Here is the current behavior of `@tstamp`/`@tstamp2`:

<img width="280" alt="Screen Shot 2021-03-03 at 6 45 27 AM" src="https://user-images.githubusercontent.com/3487289/109822933-4bd9df00-7bec-11eb-9709-097ef9e16614.png">

Which incorrectly stops at the left side of the notes rather than the right edge of the notes.   The octave line end needs to be spatially adjusted to be after all notes on the staff at that tstamp (in a manner somewhat similar to dynamics and hairpin interactions). 

In addition to `@tstamp2` placement refinement, `@endid` should behave the same as placement using `@tstamp2`, considering notes in all layers of a staff at the given timestamp to determine the visual endpoint.  I.e., `@endid` should be treated like `@tstamp2` for octave lines.

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-11T08:36:19" version="3.1.0-dev-1666d80-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001224670730">
    <score xml:id="score-0000001638878795">
     <scoreDef xml:id="scoredef-0000000630368861">
      <staffGrp xml:id="staffgrp-0000001108249085">
       <staffDef xml:id="staffdef-0000001778395235" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000000513614324" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L6F1" dur="4" oct.ges="6" oct="5" pname="f" accid.ges="n" />
         <chord xml:id="chord-L7F1" dur="4">
          <note xml:id="note-L7F1S1" oct.ges="6" oct="5" pname="a" accid.ges="n" />
          <note xml:id="note-L7F1S2" oct.ges="6" oct="5" pname="f" accid.ges="n" />
         </chord>
        </layer>
        <layer xml:id="layer-L2F1N2" n="2">
         <space xml:id="space-L6F2" dur="4" />
         <chord xml:id="chord-L7F2" dur="4">
          <note xml:id="note-L7F2S1" oct.ges="6" oct="5" pname="e" accid.ges="n" />
          <note xml:id="note-L7F2S2" oct.ges="6" oct="5" pname="c" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <octave xml:id="octave-0000000146611170" staff="1" tstamp="1" tstamp2="0m+2" dis="8" dis.place="above" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by lpugin** [comment]
Yes, you are right. It should be able to handle it properly with the `@endid`. But then what if you want to have precisely the current rendering? So if possible it would be simpler to fix the encoding and use the other `@endid`. (Timestamp is not a good solution)

**Comment by craigsapp** [comment]
>  But then what if you want to have precisely the current rendering?

I can't think of a usage case where the current rendering would be desired.

> Timestamp is not a good solution

Why is that not a good solution?  It matches the indented meaning of octave lines, which is to apply the octave transposition to notes in all layers on the staff (including cross-staff notes).  This might be useful for cases where the ending of the ocatave line should visually extend past the last note it applies to.  Such as beat 2.5 in this case.  But of course this is not very important.

**Comment by lpugin** [comment]
> Why is that not a good solution?

As you well know, timestamps cannot represent all musical positions. In my opinion it would not work well if the end of the octava is the middle note of a tuplet - for example. So I assume you would want to use timestamp for a purely visual positioning, which is fine and actually already works:

```xml
<octave xml:id="octave-0000000146611170" staff="1" startid="#note-L6F1" tstamp2="2.6" dis="8" dis.place="above" />
```

![image](https://user-images.githubusercontent.com/689412/109921008-6333cd80-7cbb-11eb-8266-f3f8d937ebf6.png)
