### ISSUE TITLE
Tempo is rounded from MusicXML to MEI

### ISSUE THREAD

**Issue by hector** [rism-digital/verovio#1953]
When translating MusicXML to MEI the tempo number is rounded.

Example 1:

MusicXML:
```xml
<direction placement="above">
    <direction-type>
        <words default-x="-25.96" default-y="19.09" relative-y="20.00" font-weight="bold" font-size="12">
            Andante assai
        </words>
    </direction-type>
    <sound tempo="91.9998"/>
</direction>
```

MEI:
```xml
<tempo xml:id="tempo-0000000808480713" place="above" staff="1" tstamp="1.000000" midi.bpm="91">
    <rend xml:id="rend-0000000909617245" fontweight="bold">Andante assai</rend>
</tempo>
```

Example 2:

MusicXML:
```xml
<direction placement="above">
    <direction-type>
        <metronome parentheses="no" default-x="-25.96" relative-y="20.00">
            <beat-unit>quarter</beat-unit>
            <per-minute>88</per-minute>
        </metronome>
    </direction-type>
    <sound tempo="88.0002"/>
</direction>
```

MEI:
```xml
<tempo xml:id="tempo-0000000891101757" place="above" staff="1" tstamp="1.000000" mm="88" mm.unit="4">
    <rend xml:id="rend-0000002061742363" fontname="VerovioText"></rend> = 88
</tempo>
```

**Comment by rettinghaus** [comment]
This is no error, because in MEI `@midi.bpm` is indeed an integer.
See https://music-encoding.org/guidelines/v4/data-types/data.midibpm.html

However, this value should be rounded and not directly imported as an integer. Fixed with 6e87e7f60ac6168f05a5c83f4084f879d7706c94

**Comment by hector** [comment]
And what about Example 2? the "mm" attribute is also an integer?

**Comment by rettinghaus** [comment]
In your example you entered an integer: 
```xml
<per-minute>88</per-minute>
```

**Comment by hector** [comment]
I believe that is for display purposes. The internal value has decimals:
```xml
<sound tempo="88.0002"/>
```

**Comment by lpugin** [comment]
It think @hector question is why `tempo@mm` is not taken from the MusicXML `<sound>`. I think it would make sense. And that attribute can be a decimal https://music-encoding.org/guidelines/v4/data-types/data.tempovalue.html

**Comment by rettinghaus** [comment]
Wrong again, see here: 
https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-metronome.htm
https://music-encoding.org/guidelines/v4/attribute-classes/att.mmtempo.html

The sound element contains general playback parameters and the `tempo` attribute is equivalent to MEI's `midi.bpm`. https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-sound.htm

**Comment by lpugin** [comment]
@rettinghaus I haven't look at this precisely, but I don't think it is fair to assume that sound in MusicXML is equivalent to MIDI related attributes in MEI. I could imagine cases where users want to record this without any connection to MIDI. Maybe it would be interesting to hear a bit more about the context in which this is a problem for @hector ?

**Comment by hector** [comment]
I synthesize musicXML files into audio. Then I use Verovio to show the score in the web and highlight notes while the synthesized audio is played. For that I parse the MEI generated from Verovio.

In any case, I think that the translation from musicXML to MEI is not correct.
The musicXML element `per-minute` is a text: https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-per-minute.htm

In my opinion, Verovio should read the `tempo` attribute from the `sound` element and translate it to the MEI `mm` attribute in the `tempo` element.

This way the precision can be preserved since we move from "decimal" to "decimal" data type.
It does not seem a go idea to use `midi.bpm` in MEI since (as @rettinghaus said) it is an integer.
Also, `mm.unit` attribute should probably be included.

Most of this logic should already exist since `mm` and `mm.unit` are already being created in my Example 2. But the value needs to come from the musicXML `sound` element.

**Comment by rettinghaus** [comment]
No. The sound element always holds the tempo per quarter note, and that's what `midi.bpm` is. 
In your example you have quarters as `meter.unit`, but this may not be always the case. See these examples from MuseScore and their conversions to MEI: 

```xml
<direction placement="above">
        <direction-type>
          <metronome parentheses="no" default-x="-34.67" relative-y="20.00">
            <beat-unit>half</beat-unit>
            <per-minute>80</per-minute>
            </metronome>
          </direction-type>
        <sound tempo="160"/>
        </direction>
```

```xml
<tempo place="above" staff="1" tstamp="1.000000" midi.bpm="160" mm="80" mm.unit="2">
   <rend fontname="VerovioText"></rend> = 80</tempo>
```

or

```xml
      <direction placement="above">
        <direction-type>
          <metronome parentheses="no" default-x="-37.37" relative-y="20.00">
            <beat-unit>quarter</beat-unit>
            <beat-unit-dot/>
            <per-minute>87</per-minute>
            </metronome>
          </direction-type>
        <sound tempo="131.475"/>
        </direction>
```

```xml
<tempo place="above" staff="1" tstamp="1.000000" midi.bpm="131" mm="87" mm.unit="4" mm.dots="1">
   <rend fontname="VerovioText"></rend> = 87</tempo>
```

As you can see, the conversion to `@mm`, `@mm.unit`, and `@mm.dots` is correct. I do see the need to have decimal values allowed in `@midi.bpm`, but that's no Verovio issue, but a MEI issue, so please open a ticket over there. 

Also refers to these tickets: https://github.com/music-encoding/music-encoding/issues/171 and https://github.com/music-encoding/music-encoding/issues/295

**Comment by craigsapp** [comment]
I notice that `<per-minute>` in MusicXML can be free text:

```xml
<per-minute>c. 108</per-minute>
```

So it might also be useful for `tempo@mm` to also be allow floating-point number.  I have see scores that give the MM value with a decimal-point bpm.

Also in this case the tempo is approximately 108 beats per minute, so it would be nice to encode this formally in some attribute.  Another common case in music is a tempo range.  This would be useful to encode in parameters.  Perhaps in a similar manner to `@tstamp` and `tstamp2`, where the minimum and maximum tempo could be encoded.

**Comment by lpugin** [comment]
As it stands I do not see any reason why we need rounding `<per-minute>` to an integer when converting it `tempo@mm` since both allow the encoding of decimal value. I think this can be changed.

Obviously, the fact that `sound@tempo` in MusicXML goes into `@midi.bpm` is a different topic. Since both encode tempo per quarter note, it is quite legitimate. If find it a bit of a shortcut to say that *sound* is *midi* but I think it is OK and better not to change this. 

The change proposed by @rettinghaus makes sure that `sound@tempo` is always converted to `@midi.bpm` (event when `<per-minute>` is given), so I think this addresses the second example. We would still need MEI to be changed in order to address the first example.

Does this work for everybody - assuming that the change in MEI is acceptable?

**Comment by hector** [comment]
> Does this work for everybody - assuming that the change in MEI is acceptable?

Yep

**Comment by rettinghaus** [comment]
@lpugin while working on this, I noticed, that there is a bug in LibMEI, because `@mm` is actually read and written as int and not float or double. So the rounding issue here is not really the importer's fault.
