### ISSUE TITLE
--adjust-page-height in Verovio 3.1 not working properly

### ISSUE THREAD

**Issue by frakel** [rism-digital/verovio#1960]
If you are just interested in the pure bounding box of a music example (without margins at all) I use these arguments with Verovio:
  `verovio -t svg -f pae --adjust-page-height --page-width 1500 --page-margin-bottom 0 --page-margin-top 0 --page-margin-left 0 --page-margin-right 0 -a incipit.pae`
 for this PAE code:
```c++
       @clef:C-1
       @keysig:bBEA
       @timesig:c
       @data:=3/2-(4-)'B/2''E4.'G8G/2B4E''E/ED-'B/
```
Unfortunately in Version 3.1 the music is wrongly positioned and lower parts of the soprano clef are cut off:
![1635-2](https://user-images.githubusercontent.com/5627140/104817225-3406f100-5820-11eb-88f7-817a735241c0.png)

  Earlier versions of Verovio calculated the margin correctly. 
Here the output  of the same code and same options in Verovio 2.7:
![1635-2](https://user-images.githubusercontent.com/5627140/104817282-a081f000-5820-11eb-97b9-d458207d5965.png)

  Is this a bug or do I have to use different options in Verovio 3.1?
  Thank you.

**Comment by rettinghaus** [comment]
connected to #1183 and #1843
