### ISSUE TITLE
flagless grace notes + slur interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2012]
When there is a slur from a flagless grace note (quarter note or half note), there is not much space for slurs to the next note:

<img width="431" alt="Screen Shot 2021-01-29 at 6 34 07 AM" src="https://user-images.githubusercontent.com/3487289/106287783-12344380-61fc-11eb-8602-c7fdc83f96e5.png">

<details>
<summary>
Click to view MEI data for example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-01-29T06:43:25" version="3.2.0-dev-3227741">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000884570500">
    <score xml:id="score-0000000768608483">
     <scoreDef xml:id="scoredef-0000000691169514">
      <staffGrp xml:id="staffgrp-0000000909869619">
       <staffDef xml:id="staffdef-0000000223130456" n="1" lines="5">
        <clef xml:id="clef-0000001576958580" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000001287209710" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dur="4" oct="5" pname="d" grace="acc" accid.ges="n" />
         <chord xml:id="chord-L4F1" dur="2">
          <note xml:id="note-L4F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L4F1S2" oct="4" pname="a" accid.ges="n" />
         </chord>
         <note xml:id="note-L5F1" dur="4" oct="5" pname="d" grace="acc" accid.ges="n" />
         <chord xml:id="chord-L6F1" dur="2">
          <note xml:id="note-L6F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L6F1S2" oct="4" pname="a" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <slur xml:id="slur-L3F1-L4F1" staff="1" startid="#note-L3F1" endid="#chord-L4F1" />
       <slur xml:id="slur-L5F1-L6F1" type="placed" staff="1" startid="#note-L5F1" endid="#chord-L6F1" curvedir="below" />
      </measure>
      <measure xml:id="measure-L7" right="dbl" n="3">
       <staff xml:id="staff-L7F1N1" n="1">
        <layer xml:id="layer-L7F1N1" n="1">
         <note xml:id="note-L8F1" dur="16" oct="5" pname="d" grace="acc" accid.ges="n" />
         <chord xml:id="chord-L9F1" dur="2">
          <note xml:id="note-L9F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L9F1S2" oct="4" pname="a" accid.ges="n" />
         </chord>
         <note xml:id="note-L10F1" dur="16" oct="5" pname="d" grace="acc" accid.ges="n" />
         <chord xml:id="chord-L11F1" dur="2">
          <note xml:id="note-L11F1S1" oct="5" pname="c" accid.ges="n" />
          <note xml:id="note-L11F1S2" oct="4" pname="a" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <slur xml:id="slur-L8F1-L9F1" staff="1" startid="#note-L8F1" endid="#chord-L9F1" />
       <slur xml:id="slur-L10F1-L11F1" type="placed" staff="1" startid="#note-L10F1" endid="#chord-L11F1" curvedir="below" />
      </measure>
      <measure xml:id="measure-L12">
       <staff xml:id="staff-L12F1N1" n="1">
        <layer xml:id="layer-L12F1N1" n="1">
         <note xml:id="note-L13F1" dur="4" oct="4" pname="e" grace="acc" accid.ges="n" />
         <note xml:id="note-L14F1" dur="2" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <slur xml:id="slur-L13F1-L14F1" staff="1" startid="#note-L13F1" endid="#note-L14F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

The sixteenth-note grace notes in the second measure look good (relatively speaking :-).  This is because the flag adds a little space between the grace note and the next note, giving more space so that the slur can be given a reasonable length.

A good way to fix the slurs for flagless grace notes would be to pretend they have flags when it is slurs to the next note (which is not a grace note).  

Analog typesetting example:

<img width="83" alt="Screen Shot 2021-01-29 at 6 18 42 AM" src="https://user-images.githubusercontent.com/3487289/106287450-a7830800-61fb-11eb-95d0-4b634c414248.png">

Notice that the quarter-note grace note is pushed to the left to allow space for the slur to be readable.

This should only be necessary when the stem of the grace note is adjacent to the stem of the regular note as in the above example.  When the stems are not adjacent, there is not a problem (measure 3 of the verovio-rendered example):

<img width="76" alt="Screen Shot 2021-01-29 at 6 32 13 AM" src="https://user-images.githubusercontent.com/3487289/106287633-dc8f5a80-61fb-11eb-8ef4-0ccbe5c81639.png">

<img width="95" alt="Screen Shot 2021-01-29 at 6 37 15 AM" src="https://user-images.githubusercontent.com/3487289/106288079-6fc89000-61fc-11eb-9577-d2ce9f016081.png">

It might be better to give extra space after all quarter-note (and half-note) grace notes regardless of whether or not the note is slurred to the next note, since the tight spacing will tend to decrease readability (when the stems of the grace and regular notes are in the same direction).

**Comment by rettinghaus** [comment]
I would say that the start of the slur should as near to the note head of the grace note as possible. And whenever the main note/chord is in it's vicinity the slur shouldn't be too steep.

Perhaps it would make sense to limit the angle of slurs dependent on it's horizontal extent?

**Comment by craigsapp** [comment]
Yes, for the second case in each of the first two measures, it would be preferable that the slur goes from the grace note to the closest note in the regular chord.  This is related to slurs currently only attaching to chords rather than to individual notes in chords.
