### ISSUE TITLE
--breaks auto + pb interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2034]
Related to the implementation for https://github.com/rism-ch/verovio/issues/1931, `--breaks auto` now stops rendering when a page break is encountered.

If this is unintentional, then `<pb>` should be treated like `<sb>` again.  If it is intentional, then a new option such as `--breaks-page auto` should be implemented to make `<pb>` behave like `<sb>`.

Example where `--breaks auto` is being used:

<img width="620" alt="Screen Shot 2021-02-04 at 4 50 18 PM" src="https://user-images.githubusercontent.com/3487289/106974655-f3591400-6709-11eb-834f-b833e4106eea.png">

 
<details>
<summary>
Click to view MEI data for above example.
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-02-04T16:55:10" version="3.2.0-dev-751456e-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000043324409">
    <score xml:id="score-0000001624579327">
     <scoreDef xml:id="scoredef-0000001390193641" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000001492851988">
       <staffDef xml:id="staffdef-0000001357210866" n="1" lines="5">
        <clef xml:id="clef-0000000402084208" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <pb xml:id="pb-0000001649430478" />
      <measure xml:id="measure-L1">
       <staff xml:id="staff-0000001407833829" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L5">
       <staff xml:id="staff-L5F1N1" n="1">
        <layer xml:id="layer-L5F1N1" n="1">
         <note xml:id="note-L6F1" dur="1" oct="4" pname="d" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L7">
       <staff xml:id="staff-L7F1N1" n="1">
        <layer xml:id="layer-L7F1N1" n="1">
         <note xml:id="note-L8F1" dur="1" oct="4" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L9">
       <staff xml:id="staff-L9F1N1" n="1">
        <layer xml:id="layer-L9F1N1" n="1">
         <note xml:id="note-L10F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L11">
       <staff xml:id="staff-L11F1N1" n="1">
        <layer xml:id="layer-L11F1N1" n="1">
         <note xml:id="note-L12F1" dur="1" oct="4" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <sb xml:id="sb-L14F1" type="z" />
      <measure xml:id="measure-L14">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <note xml:id="note-L15F1" dur="1" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L16">
       <staff xml:id="staff-L16F1N1" n="1">
        <layer xml:id="layer-L16F1N1" n="1">
         <note xml:id="note-L17F1" dur="1" oct="4" pname="b" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L18">
       <staff xml:id="staff-L18F1N1" n="1">
        <layer xml:id="layer-L18F1N1" n="1">
         <note xml:id="note-L19F1" dur="1" oct="5" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L20">
       <staff xml:id="staff-L20F1N1" n="1">
        <layer xml:id="layer-L20F1N1" n="1">
         <note xml:id="note-L21F1" dur="1" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L22">
       <staff xml:id="staff-L22F1N1" n="1">
        <layer xml:id="layer-L22F1N1" n="1">
         <note xml:id="note-L23F1" dur="1" oct="5" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <pb xml:id="pb-L25F1" type="z" />
      <measure xml:id="measure-L25">
       <staff xml:id="staff-L25F1N1" n="1">
        <layer xml:id="layer-L25F1N1" n="1">
         <note xml:id="note-L26F1" dur="1" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L27">
       <staff xml:id="staff-L27F1N1" n="1">
        <layer xml:id="layer-L27F1N1" n="1">
         <note xml:id="note-L28F1" dur="1" oct="5" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L29">
       <staff xml:id="staff-L29F1N1" n="1">
        <layer xml:id="layer-L29F1N1" n="1">
         <note xml:id="note-L30F1" dur="1" oct="5" pname="a" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L31">
       <staff xml:id="staff-L31F1N1" n="1">
        <layer xml:id="layer-L31F1N1" n="1">
         <note xml:id="note-L32F1" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L33">
       <staff xml:id="staff-L33F1N1" n="1">
        <layer xml:id="layer-L33F1N1" n="1">
         <note xml:id="note-L34F1" dur="1" oct="4" pname="d" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <sb xml:id="sb-L36F1" type="z" />
      <measure xml:id="measure-L36">
       <staff xml:id="staff-L36F1N1" n="1">
        <layer xml:id="layer-L36F1N1" n="1">
         <note xml:id="note-L37F1" dur="1" oct="4" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L38">
       <staff xml:id="staff-L38F1N1" n="1">
        <layer xml:id="layer-L38F1N1" n="1">
         <note xml:id="note-L39F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L40">
       <staff xml:id="staff-L40F1N1" n="1">
        <layer xml:id="layer-L40F1N1" n="1">
         <note xml:id="note-L41F1" dur="1" oct="4" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L42">
       <staff xml:id="staff-L42F1N1" n="1">
        <layer xml:id="layer-L42F1N1" n="1">
         <note xml:id="note-L43F1" dur="1" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L44">
       <staff xml:id="staff-L44F1N1" n="1">
        <layer xml:id="layer-L44F1N1" n="1">
         <note xml:id="note-L45F1" dur="1" oct="4" pname="b" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <sb xml:id="sb-L47F1" type="z" />
      <measure xml:id="measure-L47">
       <staff xml:id="staff-L47F1N1" n="1">
        <layer xml:id="layer-L47F1N1" n="1">
         <note xml:id="note-L48F1" dur="1" oct="5" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L49">
       <staff xml:id="staff-L49F1N1" n="1">
        <layer xml:id="layer-L49F1N1" n="1">
         <note xml:id="note-L50F1" dur="1" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L51">
       <staff xml:id="staff-L51F1N1" n="1">
        <layer xml:id="layer-L51F1N1" n="1">
         <note xml:id="note-L52F1" dur="1" oct="5" pname="e" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L53">
       <staff xml:id="staff-L53F1N1" n="1">
        <layer xml:id="layer-L53F1N1" n="1">
         <note xml:id="note-L54F1" dur="1" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L55" right="end">
       <staff xml:id="staff-L55F1N1" n="1">
        <layer xml:id="layer-L55F1N1" n="1">
         <note xml:id="note-L56F1" dur="1" oct="5" pname="g" accid.ges="n" />
        </layer>
       </staff>
       <fermata xml:id="fermata-L56F1" staff="1" startid="#note-L56F1" place="above" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

The expected rendering should be to treat the `<pb>` as an `<sb>` until the full page height is filled in:

<img width="613" alt="Screen Shot 2021-02-04 at 4 50 01 PM" src="https://user-images.githubusercontent.com/3487289/106974649-ecca9c80-6709-11eb-8ff6-d4df0c0788fa.png">

**Comment by lpugin** [comment]
This is what I get with `--breaks auto` (or no option):
![image](https://user-images.githubusercontent.com/689412/106997782-c2b5c080-6783-11eb-942c-1fdcc6b01bc1.png)

This with `--breaks encoded`
![image](https://user-images.githubusercontent.com/689412/106997867-ee38ab00-6783-11eb-9723-edee8af6023b.png)

This with `--breaks smart`
![image](https://user-images.githubusercontent.com/689412/106997947-0d373d00-6784-11eb-9b0d-df9fb1e38392.png)

**Comment by craigsapp** [comment]
Oops, I meant with `--breaks encoded` (as you are getting).

**Comment by lpugin** [comment]
Sorry, but I don't understand what the regression is. It stops because it is the end of the page. This has always been like that.

**Comment by craigsapp** [comment]
> This has always been like that.

It has not, and it seems to have changed around the time of PR  https://github.com/rism-ch/verovio/issues/1931 (but could have changed before then without me noticing).  But never mind that: in that case the change can be considered intentional, and I propose that an option such as `--breaks-page auto|encoded` be implemented with the default being `auto` to allow ignoring or utilizing embedded `<pb>` to force a new page in verovio.  In other words, it would be useful to use both `--breaks encoded` (for encoded `<sb>`) and `--breaks-page auto` to ignore the `<pb>`.

The problem is that if `--pageHeight` is given, then it is expected that `-breaks-page auto` is being used, but now `--breaks-page encoded` equivalent is not being used because of `--breaks encoded`, which stops filling in the rest of the page when a `<pb>` element is found, which is in conflict with the  `--pageHeight` option. 

In VHV, the default rendering options are `pageHeight: 60000` and `adjustPageHeight: 1` to placed all of the music onto a single page.  This used to work when `breaks: encoded` was also used, but now the music stops after the second `<pb>` in the data (with the first one initializing the start of the score).  I can disable converting `<pb>` in the humdrum-to-MEI conversion to recover the original behavior, but the best thing will be to allow for a `--breaks-page` option.

Alternatively there could be three options `--breaks` which would behave as currently, affecting both system and page breaks, and two new options `--breaks-system` and `--breaks-page` to override on or the other breaking styles for systems and pages.

**Comment by lpugin** [comment]
Ideally the data should be changed before being passed to Verovio. But I understand that it can be useful to do automatic layout only for `sb` and not for `pb`. I am sure somebody will one day come with the wish to have the opposite...

What about adding `encoded-sb` as a possible value for `--breaks`, and the `encoded-pb` to the opposite? I think that would be simpler to implement - even though still cumbersome.

**Comment by craigsapp** [comment]
Yes, adding `--breaks encoded-sb`  is good, particularly for proofreading against an original score.  `--breaks encoded-pb` is less interesting by itself, but if it is easy too implement it would be useful for symmetry -- it could be useful for creating parts, where the page break location is important, but the system breaks on the page are not.

**Comment by lpugin** [comment]
@craigsapp could you clarify the current state of this issue? Thanks

**Comment by craigsapp** [comment]
Thanks!  It is working as expected again.

Example of single-page mode in VHV (`breaks: "auto"`), which was previously working:

https://verovio.humdrum.org/?file=beethoven/sonatas/sonata01-1.krn

<img width="1335" alt="Screen Shot 2021-10-01 at 10 23 12 AM" src="https://user-images.githubusercontent.com/3487289/135661872-4362fd8b-8dc4-4856-8be1-df5642e1cad2.png">

Still in single-page mode, but forcing encoded linebreaks (`breaks: "line"`) now works again (this is done by clicking on the jagged three horizontal line icon in the toolbar):

<img width="1335" alt="Screen Shot 2021-10-01 at 10 29 46 AM" src="https://user-images.githubusercontent.com/3487289/135662636-c960ef2e-e712-47fe-b915-4b176b51d4ba.png">

Previously this was having problems, since the music stoped at the first (technically second) encoded page break.  Now the display music continues to the end of the page, including all encoded pages of music.

------------------------------------------

Multi-page mode:  (activated by clicking on the "map" icon in the top right corner of the page) (`breaks: "auto"`):

Using automatic line breaks in multi-page mode (behaved correctly also before fix):

<img width="1335" alt="Screen Shot 2021-10-01 at 10 24 23 AM" src="https://user-images.githubusercontent.com/3487289/135662001-f6ccaa0d-f0b0-42e6-958b-c5f5b9b91b0c.png">


Forcing encoded line breaks in multi-page mode now works as expected again (`breaks: "line"`):


<img width="1335" alt="Screen Shot 2021-10-01 at 10 32 44 AM" src="https://user-images.githubusercontent.com/3487289/135662984-2eb745c8-11d5-427a-bb65-b25d5136c651.png">


Scrolling to page 2 (clicking on the right arrow in the top right corner, or using right-arrow keyboard shortcut (`breaks: "line"`):

<img width="1335" alt="Screen Shot 2021-10-01 at 10 26 03 AM" src="https://user-images.githubusercontent.com/3487289/135662193-edbcbb9f-53cf-4b20-9115-f15ed6c66a5b.png">
