### ISSUE TITLE
Add option to render ligatures as notes and brackets

### ISSUE THREAD

**Issue by martha-thomae** [rism-digital/verovio#2081]
It would be useful to include an option in Verovio that would allow to render ligatures as individual notes with a bracket showing the group of notes belonging to the ligature. In this way, the individual note values can be seen, which are useful to see the note alignment in score layout, but also we keep the information about the presence of a ligature.

This issue is related to the [PR#771 in the music-encoding repo](https://github.com/music-encoding/music-encoding/pull/771). Here, we are addressing the issue of "breaking the ligatures into the individual mensural notes and using a bracket" in Verovio rather than in the encoding itself.

We want to be able to render something like this:
<img src="https://user-images.githubusercontent.com/13948831/109432352-b4507280-79d8-11eb-8b88-4d61dadfe4a8.png" width="500"/>

which is the score version of the music in: 
<img src="https://user-images.githubusercontent.com/13948831/109432375-d3e79b00-79d8-11eb-8f1c-3b6cde343763.png" width="600"/>

**Comment by lpugin** [comment]
Implemented https://github.com/rism-digital/verovio/pull/2278

**Comment by craigsapp** [comment]
You are not going to reveal the option name in this issue?:

```
--ligature-as-bracket
```

😜
