### ISSUE TITLE
C clefs below staff not extending the height of the SVG

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#2095]
When a C clef extends below the staff, the SVG height is not calculated to cover the clef, and it is cut off.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/163183/110770898-2edf8480-825a-11eb-96dd-7587e20a8024.png">

The following options are used:

```
{
    "footer": 'none',
    "header": 'none',
    "pageMarginTop": 0,
    "pageMarginBottom": 0,
    "pageMarginLeft": 0,
    "pageMarginRight": 0,
    "adjustPageWidth": "true",
    "spacingStaff": 1,
    "scale": 40,
    "adjustPageHeight": "true",
    "svgHtml5": "true",
    "svgFormatRaw": "true",
    "svgRemoveXlink": "true"
}
```

A PAE example showing this is:

```
@start:pae-file
@clef:C-1
@keysig:bB
@key:d
@timesig:None
@data:=2//:2.'D4D/1A/2''DD/1C/2'B4BB/2A4AB/
@end:pae-file
```

Adjusting the 'height' parameter on the SVG output, or increasing `pageMarginBottom`, will fix this, but I don't think this behaviour is intended.

**Comment by rettinghaus** [comment]
Duplicate of #1960

**Comment by ahankinson** [comment]
Sorry! I did look to see if it was already reported; I can close this one and comment on that one.
