### ISSUE TITLE
MusicXML partwise import: <direction> without <staff> is unhandled

### ISSUE THREAD

**Issue by petermcculloch** [rism-digital/verovio#2115]
When importing MusicXML, if a <direction> does not contain a <staff> element (which is optional in the MusicXML standard), the resulting MEI will also not have a staff number, and consequently will not be rendered by Verovio.  

The attached test code includes the .musicxml and the .mei created from importing the .musicxml.  The hairpin in the piano part is rendered correctly (because it has `<staff>1</staff>`), but the hairpin in the violin staff is not rendered. (because in the MEI, there is no staff in the `<hairpin>`)

I encountered this issue because MuseScore does not add the <staff> element in partwise MusicXML export when the part has a single staff.  

![Screen Shot 2021-03-27 at 7 41 13 PM](https://user-images.githubusercontent.com/1436870/112737891-72addb80-8f34-11eb-9ee3-125bba02e4c9.png)

The MusicXML code for the hairpin in the Violin:
```
      <direction placement="below">
        <direction-type>
          <wedge type="diminuendo" number="1"/>
          </direction-type>
        </direction>
```

The MEI code for the hairpin in the Violin:
```
<hairpin xml:id="hairpin-0000001278388697" tstamp="1.000000" tstamp2="2m+4.5000" form="dim" place="below" vgrp="200" />`
```

The MusicXML code for the hairpin in the Piano:
```
     <direction placement="below">
        <direction-type>
          <wedge type="diminuendo" number="1"/>
          </direction-type>
        <staff>1</staff>
        </direction>
```

The MEI code for the hairpin in the Piano:
```
<hairpin xml:id="hairpin-0000000106899815" staff="2" tstamp="1.000000" tstamp2="2m+4.5000" form="dim" place="below" vgrp="200" />
```

[DimTest.zip](https://github.com/rism-digital/verovio/files/6216603/DimTest.zip)

**Comment by rettinghaus** [comment]
This is because the staff is not initialised yet, if the direction appears before a note. Fix provided in #2116.
