### ISSUE TITLE
Export plaine and easie code from Javascript vrvToolkit

### ISSUE THREAD

**Issue by davidrizo** [rism-digital/verovio#2143]
Hi,
is it able to export PAE from the Javascript vrvToolkit?
If not, how could I add it? By adding some entry to emscripten/verovio-proxy.js ?
Thanks!

**Comment by lpugin** [comment]
You are right that it is missing. To add it, you should:
* Add it to `emscripten/verovio-proxy.js`
* Add it to `tools/c_wrapper.h/cpp`
* Add it to `emscripten/buildToolkit`

That should be it...

**Comment by davidrizo** [comment]
I've implemented. Before uploading it I have one question. 

In order to use it the following methods must to be invoked:

```
    this.vrvToolkit.loadData(mei);
    plaineAndEasieCode = this.vrvToolkit.renderToPAE();
```

Is this method correct?

**Comment by lpugin** [comment]
Looks good to me

**Comment by davidrizo** [comment]
Added in the pull request https://github.com/rism-digital/verovio/pull/2145
