### ISSUE TITLE
QT build error

### ISSUE THREAD

**Issue by Lr-2002** [rism-digital/verovio#2146]
Hi , I'm interested in building a qt file in verovio.
But i've faced a little of problem which is in need of your help.
1. gl.h is missing for this one.i locate it for the loss of opengl
    and i fix it with 
    ```
    sudo apt install mesa-common-dev
    ```
2.  not fixed:
     after fixed problem 1,
     Now ,the build shell doesn't work well as well.
     such as 
     ```
             ../../../include/vrv/view.h:526:14: error: ‘std::optional’ has not been declared
            526 |         std::optional<TextDrawingParams> params = std::nullopt);
              |              ^~~~~~~~
            ../../../include/vrv/view.h:526:22: error: expected ‘,’ or ‘...’ before ‘<’ token
            526 |         std::optional<TextDrawingParams> params = std::nullopt);
              |                      ^
            ../../../include/vrv/view.h:526:9: error: default argument missing for parameter 4 of ‘void vrv::View::DrawLyricString(vrv::DeviceContext*, std::wstring, int, int)’
            526 |         std::optional<TextDrawingParams> params = std::nullopt);
              |         ^~~~~~~~~~~~~
     ```

Looking for your help plz.

**Comment by Lr-2002** [comment]
all right , the 2 problem have been fixed using 
``` CXX = g++ -std=c++17 ```  which was ```CXX = g++ ``` former
in /bindings/qt/build-demo

But now ,I'm facing a new problem which appeared with the former two problems.
still build 
```  
  ../lib/include/vrvqt/scenegraphdevicecontext.h:89:10: error: ‘void vrvQt::SceneGraphDeviceContext::DrawSimpleBezierPath(vrv::Point*)’ marked ‘override’, but does not override
     89 |     void DrawSimpleBezierPath(vrv::Point bezier[4]) override;
        |          ^~~~~~~~~~~~~~~~~~~~
  ../lib/include/vrvqt/scenegraphdevicecontext.h:90:10: error: ‘void vrvQt::SceneGraphDeviceContext::DrawComplexBezierPath(vrv::Point*, vrv::Point*)’ marked ‘override’, but does not override
     90 |     void DrawComplexBezierPath(vrv::Point bezier1[4], vrv::Point bezier2[4]) override;
        |   
```

**Comment by Lr-2002** [comment]
Well, I changed it in attmepting by delete ```override``` mark.
and it seems worked well? and the compline passed.
While the make still didn't passed with
```
  /usr/bin/ld: 找不到 -lverovio-qt 
  /usr/bin/ld: 找不到 -lverovio
  collect2: error: ld returned 1 exit status
```
(找不到 means  cannot find)
well , find some useful solution and just try again.

**Comment by lpugin** [comment]
Some method names have changed. I tried to fixed it https://github.com/rism-digital/verovio/commit/1e9eb04eda43b3cce5aa6e4adfd382fd103b5065
Does it work?

**Comment by Lr-2002** [comment]
All right ,that one seems fixed.
However ,things doesn't seem well.
1. There is a mistake about the textquickitem.cpp
``` 
  ../lib/src/textquickitem.cpp:59:62: error: ‘class QString’ has no member named ‘front’
     59 |             boundingRect = fm.boundingRect(textWithFont.text.front());
```
could it be fixed by ``` text[0]```

2. Missing lverovio and lverovio-qt
   I don't know how to get or generate them
plz

**Comment by yeonoson** [comment]
1) QString::front() was introduced with Qt 5.10, thus make sure to use a recent version of Qt 5.
2) There are build instructions for the required verovio and verovio-qt dependencies in the [README.md](https://github.com/rism-digital/verovio/blob/develop/bindings/qt/README.md) file.
