### ISSUE TITLE
compile error on Cygwin (ftello, fseeko)

### ISSUE THREAD

**Issue by frakel** [rism-digital/verovio#2173]
Hi, is there anyone in the community who is compiling the recent Verovio
sources successfully in Cygwin?
Since the extension of Verovio with support for MusicXML compressed files
some weeks ago I cannot any more compile the Verovio sources in Cygwin. Apparently my
Cygwin installation does not support `fseeko` and `ftello` which is used by the 
then added third party library `./include/zip/zip_file.hpp`

<details>
<summary>Error msg</summary>
<p>

```c++
[ 76%] Building CXX object CMakeFiles/verovio.dir/home/kelnreiter/verovio/src/toolkit.cpp.o
In file included from /home/kelnreiter/verovio/src/toolkit.cpp:46:
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp: In function 'size_t mz_zip_file_read_func(void*, mz_uint64, void*, size_t)':
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp:3015:24: error: 'ftello' was not declared in this scope; did you mean 'ftell'?
 3015 |     #define MZ_FTELL64 ftello
      |                        ^~~~~~
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp:3394:22: note: in expansion of macro 'MZ_FTELL64'
 3394 |   mz_int64 cur_ofs = MZ_FTELL64(pZip->m_pState->m_pFile);
      |                      ^~~~~~~~~~
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp:3016:24: error: 'fseeko' was not declared in this scope; did you mean 'fseek'?
 3016 |     #define MZ_FSEEK64 fseeko
      |                        ^~~~~~
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp:3395:74: note: in expansion of macro 'MZ_FSEEK64'
 3395 |   if (((mz_int64)file_ofs < 0) || (((cur_ofs != (mz_int64)file_ofs)) && (MZ_FSEEK64(pZip->m_pState->m_pFile, (mz_int64)file_ofs, SEEK_SET))))
      |                                                                          ^~~~~~~~~~
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp: In function 'mz_bool mz_zip_reader_init_file(mz_zip_archive*, const char*, mz_uint32)':
/home/kelnreiter/verovio/cmake/../include/zip/zip_file.hpp:3016:24: error: 'fseeko' was not declared in this scope; did you mean 'fseek'?
 3016 |     #define MZ_FSEEK64 fseeko
```
</p></details>
Does anyone know which packages are needed in Cygwin
or how to tweak the setup of Cygwin in a way to get fseeko, ftello references
correctly processed by cmake?

I am using a Cygwin installation on top of a Windows 10 Pro 64 bit OS.

Any hint is much appreciated - though admittedly this is very Cygwin specific... 

Thank you!
--franz

**Comment by lpugin** [comment]
I added a NO_MXL_SUPPORT preprocessor flag a6ffc58487b5c9a78249c73290cba917abd49005. It can be turned on with
```
cmake ../cmake -DNO_MXL_SUPPORT=ON
```
It should disable the use of the problematic code. Could you try this?

**Comment by frakel** [comment]
👍 compiles perfect now without MXL support! Thank you
