### ISSUE TITLE
Implement tstamp offset on control events

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2186]
For undelayed turns (measure 1), they are displayed on the correct side of the staff automatically when there are two layers on the staff and the turns are attached to notes in the different layers.  For delayed turns, the second layer turn should be displayed below the staff, but it is instead displayed above the staff:

<img width="544" alt="Screen Shot 2021-05-13 at 10 13 02 PM" src="https://user-images.githubusercontent.com/3487289/118224628-632d1800-b438-11eb-8096-030a489c570d.png">

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2021-05-13T22:11:20" version="3.3.0-dev-d6e9eed-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001488708485">
    <score xml:id="score-0000001468084829">
     <scoreDef xml:id="scoredef-0000000994342090">
      <staffGrp xml:id="staffgrp-0000002029747387">
       <staffDef xml:id="staffdef-0000001069672897" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <meterSig xml:id="metersig-L3F1" count="3" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001151721245" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L6F1" dur="2" oct="3" pname="c" accid.ges="n" />
         <beam xml:id="beam-L7F1-L11F1">
          <note xml:id="note-L7F1" dur="8" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L8F1" dur="32" oct="2" pname="b" accid.ges="n" />
          <note xml:id="note-L9F1" dur="32" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L10F1" dur="32" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L11F1" dur="32" oct="3" pname="e" accid.ges="n" />
         </beam>
        </layer>
        <layer xml:id="layer-L2F1N2" n="2">
         <note xml:id="note-L6F2" dur="2" oct="2" pname="c" accid.ges="n" />
         <beam xml:id="beam-L7F2-L11F2">
          <note xml:id="note-L7F2" dur="8" oct="2" pname="c" accid.ges="n" />
          <note xml:id="note-L8F2" dur="32" oct="1" pname="b" accid.ges="n" />
          <note xml:id="note-L9F2" dur="32" oct="2" pname="c" accid.ges="n" />
          <note xml:id="note-L10F2" dur="32" oct="2" pname="d" accid.ges="n" />
          <note xml:id="note-L11F2" dur="32" oct="2" pname="e" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <turn xml:id="turn-L6F1" staff="1" startid="#note-L6F1" form="upper" />
       <tie xml:id="tie-L6F1-L7F1" startid="#note-L6F1" endid="#note-L7F1" />
       <turn xml:id="turn-L6F2" staff="1" startid="#note-L6F2" form="upper" />
       <tie xml:id="tie-L6F2-L7F2" startid="#note-L6F2" endid="#note-L7F2" />
      </measure>
      <measure xml:id="measure-L13">
       <staff xml:id="staff-L13F1N1" n="1">
        <layer xml:id="layer-L13F1N1" n="1">
         <note xml:id="note-L15F1" dur="2" oct="3" pname="c" accid.ges="n" />
         <beam xml:id="beam-L16F1-L20F1">
          <note xml:id="note-L16F1" dur="8" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L17F1" dur="32" oct="2" pname="b" accid.ges="n" />
          <note xml:id="note-L18F1" dur="32" oct="3" pname="c" accid.ges="n" />
          <note xml:id="note-L19F1" dur="32" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L20F1" dur="32" oct="3" pname="e" accid.ges="n" />
         </beam>
        </layer>
        <layer xml:id="layer-L15F2N2" n="2">
         <note xml:id="note-L15F2" dur="2" oct="2" pname="c" accid.ges="n" />
         <beam xml:id="beam-L16F2-L20F2">
          <note xml:id="note-L16F2" dur="8" oct="2" pname="c" accid.ges="n" />
          <note xml:id="note-L17F2" dur="32" oct="1" pname="b" accid.ges="n" />
          <note xml:id="note-L18F2" dur="32" oct="2" pname="c" accid.ges="n" />
          <note xml:id="note-L19F2" dur="32" oct="2" pname="d" accid.ges="n" />
          <note xml:id="note-L20F2" dur="32" oct="2" pname="e" accid.ges="n" />
         </beam>
        </layer>
       </staff>
       <turn xml:id="turn-L15F1" staff="1" tstamp="2.000000" form="upper" />
       <tie xml:id="tie-L15F1-L16F1" startid="#note-L15F1" endid="#note-L16F1" />
       <turn xml:id="turn-L15F2" staff="1" tstamp="2.000000" form="upper" />
       <tie xml:id="tie-L15F2-L16F2" startid="#note-L15F2" endid="#note-L16F2" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by lpugin** [comment]
This will be problematic to handle with the current encoding because nothing in it indicates that the turn should be be placed below because it applies to the second layer. The solutions I can imagine are - starting from the simplest:

1. add `@place=below` to the turn. This works with the current version of Verovio
2. add support for `@layer` to control event. I have to evaluate how complicated this would be. We never make use or `@layer` elsewhere, so it might be not straightforward
3. another idea would be make `@to` with the turn pointing to the note. So it would become `<turn startid="note-L15F2" staff="1" to="1.0">`

For now you can do 1. but in the long-run it would be probably best to implement 3. I think this could be useful in quite some cases, including for slurs. BTW, I noticed that with control event featuring `@tstamp2`, there is both `@startto` and `@to`. This looks confusing to me. To make things consistent, we could have only `startto` on all control evants instead of `@to`. That would also probably apply to `@vo` and `@ho`, which might have deeper implications. So we could suggest to change it the other way around simply by removing `@startvo`, `startho` and `@startto`.

**Comment by craigsapp** [comment]
>  it would be probably best to implement 3. 

I am liking option 3 too, since it would be necessary associate a delayed turn with a note in order to realize the turn gesturally.

**Comment by lpugin** [comment]
See this https://github.com/music-encoding/music-encoding/issues/796

Verovio will use `@to` (relative to `@startid`) and `endto` (relative to `@endid) for control events that also that attribute too. For now, `@startto` is expected to have no effect.

**Comment by lpugin** [comment]
Another idea for turns would be to place turns that uses `@startid` and `@delayed="true" in the middle of the space between the startid note and the next note. We do not necessary have to expect an `@endid` for this to work. However, requiring `@endid` could make sense too but it would need to be added to MEI first. 

Placing the turn in the middle of the space would not be strictly compliant with the current description of `@delayed` which is: "When set to 'true', the turn begins on the second half of the beat. " Any thoughts?

**Comment by rettinghaus** [comment]
I don't see the need for an `@endid` on `turn` from a musical perspective. `@delayed` moves the played ornament from the begin of the note to the end of it. Usually it is placed in the middle of the note it is associated to and the following one. So the description is only correct if the note duration fills exactly one beat. Maybe a better wording would be "When set to 'true', the turn is placed on the second half of the note."
That said, placing the turn in the middle of the space would be excellent.

**Comment by rettinghaus** [comment]
@lpugin should I adapt the example from the test suite?

**Comment by lpugin** [comment]
I had already added a new example using `@startid`. I now change the wording of the description of the old one https://github.com/rism-digital/verovio.org/commit/c62874513a19f4fdf3fe41fc2039bf91b7b45163 so we should be good. But go ahead if you see something else that need to be adapted. Thanks
