### ISSUE TITLE
How to show the location of note?

### ISSUE THREAD

**Issue by Lr-2002** [rism-digital/verovio#2189]
I want to get the location of notes and make them buttons on my QT project.
But now ,I couldn't change the note into button or even just found its location with covering buttons .

For the location ,I've tried lots of output when run the qt demo ,while it seems a big number instead of the px numbers.

Could i get your help or suggestions which can change the note into buttons or just get the object.Plz .

**Comment by lpugin** [comment]
Sorry, but this is a QT question. Please ask where appropriate.

**Comment by Lr-2002** [comment]
Sorry for bothering again.

Maybe my problem is too fuzzy make you annoyed.

Plz give a chance to state it more correctly.

Could i get the location or landmark numbers in px in the project easily?

Thank you a lot!
