### ISSUE TITLE
Reduce number of programming languages 

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2191]
Around Verovio there are combinations of many different languages like JavaScript, Python, XSLT, and Shell scripts. This should be reduced in order to

1. improve maintainability 
2. improve cross-platform compatibility 
3. reduce dependencies
4. speed things up

**Comment by lpugin** [comment]
Every programming language has specificities that quite likely were a reason why it was chosen. We can certainly changes things but if nothing is problematic and works, I generally prefer not to - at least I do not see this as a top priority. Please list specific things you would like to change and why.

**Comment by rettinghaus** [comment]
- [ ] remove `get_version.sh`
- [ ] improve font generation

1. `get_version.sh` is slow and shows problems (e.g. [UUOC](https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat)). It would be faster and more reliable to do it directly within `setup.py`.
2. font generation depends on the correct version of `Saxon` and `phantomjs`. Apart from `phantomjs` being outdated, it made problems before on different platforms.

**Comment by ahankinson** [comment]
```
$ time ./get_version.sh                                                                                                                                                                                                                   develop*
3.5.0.dev
./get_version.sh  0.02s user 0.04s system 162% cpu 0.032 total
```

"slow" :-D

**Comment by lpugin** [comment]
```bash
laurent@laika tools % time ./get_version.sh 
3.5.0.dev
./get_version.sh  0.01s user 0.04s system 109% cpu 0.048 total
```
It is not slow for me but if you want to remove it that is fine.

Font generation can be updated. What do you want to used instead of phantomjs?

**Comment by rettinghaus** [comment]
I think the complete glyph extraction should be done with Python (i.e. no XSLT or JS).

**Comment by lpugin** [comment]
That's fine with me. It would be good to see in advance the dependencies you will rely on because if they are just wrappers (e.g., https://pypi.org/project/phantomjs/) that will be pretty much useless.

**Comment by lpugin** [comment]
This has been done.
