### ISSUE TITLE
ABC notation, many things are not supported

### ISSUE THREAD

**Issue by PatVNF** [rism-digital/verovio#2206]
ABC notation for JS / Known limitations:
1. Verovio imports only the first tune in a collection
2. Tuplets are not supported
3. User defined symbols are not supported
4. Multi-voice music is not supported
5. Lyrics are not supported yet

Would it be possible to fix these items : 2. / 4. / 5. / 3. ?
Tuplets are really common...
And then : Standard v2.1 ? may be v2.2 ?

Thank you so much !

**Comment by rettinghaus** [comment]
Everything is possible. You're kindly invited to contribute to this open source project.

**Comment by PatVNF** [comment]
I's really kind of you., thank you. I will try, but my level is still a bit weak, just like my knowledge about Git.

**Comment by lpugin** [comment]
@PatVNF this is a general feature request, so I am closing the issue. If you need help for any of these and already have something working or in the pipeline, just make a pull-request and we can advise you from there.
