### ISSUE TITLE
importing musicxml  to render the web example

### ISSUE THREAD

**Issue by ifredom** [rism-digital/verovio#2223]
Is there an example of importing musicxml to render the web? Only the import Mei file was found to render the web. I don't know the source code very much.

**Comment by craigsapp** [comment]
Loading MusicXML should be nearly identical to loading MEI.  By default the input format will be automatically identified.

https://book.verovio.org/first-steps/basic-rendering.html

If you want to ensure MusicXML import, you can set the `inputFrom` option to `xml`:

```
let options = { "inputFrom": "xml" };
toolkit.renderData(data, options);
```
