### ISSUE TITLE
Adjustments in SVG output to allow for better targeting of lyric verses with CSS

### ISSUE THREAD

**Issue by samuelbradshaw** [rism-digital/verovio#2236]
One thing I really appreciate about Verovio is how easy it is to style with CSS, with IDs and classes in the SVG output. However, I'm running into a limitation when trying to style a single verse in the lyrics, for a song with multiple verses. The idea is that the current verse would be rendered black and the other verses would be dimmed, when synced with audio.

Here's a test page to illustrate (note that the audio part is still in progress):
https://singpraises.net/meta/sheet-music/come-follow-me

This is the CSS I initially tried, thinking that :nth-child(3) would target the third verse:

```
    #sheet-music-container svg g.verse g {
      fill: var(--gray-67);
      color: var(--gray-67);
    }
    #sheet-music-container svg g.verse:nth-child(3) g {
      fill: var(--text-color);
      color: var(--text-color);
    }
```

Unfortunately, `.verse`, `.note`, `.stem`, and other elements are siblings, which means that the third element in the parent isn't necessarily the third verse. Also unfortunately, standard CSS doesn't have a `:nth-of-class()` selector.

Could Verovio's SVG output be adjusted to allow for targeting a single verse with CSS? There are two potential solutions I could think of:
1. Use the `n="1"`, `n="2"`, etc. attributes on the MEI `<verse>` element to add numbered classes on each `.verse` in the SVG output (for example: `class="verse verse1"`).
2. Group `.verse` elements into a `.lyric` (or similar) parent element in the SVG output.

**Comment by lpugin** [comment]
Can be solved with https://github.com/rism-digital/verovio/issues/1991

**Comment by musicEnfanthen** [comment]
@samuelbradshaw As you said, `nth-child(n)` and `nth-of-type(n)` selectors work only on the element, not on the classes. So you probably won't have luck with pure CSS. If traversing with JS is an option, you could try to use the sibling selector `~`. This approach is a bit odd and would need two steps: First, identify and style a certain sibling n, and then remove the applied styles from the following siblings (because `~` will find all siblings that are n or n+x). We applied this approach in Verovio's highlight tutorial: https://github.com/rism-ch/verovio-tutorial/pull/3/files

Something like this could work (without having tested it):

```
// to highlight second verses

// apply attributes to verses that are siblings of first verse in a layer
$("#sheet-music-container svg .layer .verse ~ .verse g" ).attr( ## set whatever is needed ## );

// remove attributes from verses that are later siblings of second verse
$("#sheet-music-container svg .layer .verse ~ .verse ~ .verse g").attr( ## set back to default ## );
```

**Comment by samuelbradshaw** [comment]
Thank you, @lpugin and @musicEnfanthen! I decided to use the workaround in #1991 for now, adding "verse1", "verse2", etc. to the `@type` attribute in the MEI file so that it flows through to the SVG as a class.

@lpugin, I was able to use `@type` to add classes to verse elements, but I wasn't able to add classes to label elements. Is `@type` only supported on `<verse>`?
