### ISSUE TITLE
getTimeForElement() and getElementsAtTime() for chords and measures

### ISSUE THREAD

**Issue by samuelbradshaw** [rism-digital/verovio#2237]
When I call vrvToolkit.getTimeForElement() with the ID of a note, Verovio returns the time in milliseconds where the note appears in the rendered MIDI (which is awesome!). Similarly, when I call vrvToolkit.getElementsAtTime(), Verovio returns a list of the IDs of notes being played from the MIDI at a given time.

It would be helpful if these methods worked for other types of elements besides notes – in particular, I'm interested in using these methods to get data for chords and/or measures. Here are some of the use cases:

- I'd like to sync the sheet music to a non-MIDI audio recording (for example, a recording that includes vocals). I have the average tempo of the audio recording. With Verovio, I can generate MIDI at that same tempo using toolkit.renderToMIDI() to get timing data. However, my audio recording isn't exactly note-for-note on tempo like the MIDI would be, so when I use getTimeForElement() and getElementsAtTime() to highlight notes, the timing of when notes are highlighted in the sheet music is slightly off. If I could highlight a measure at a time instead of each note, the time discrepancy when advancing in the sheet music would be less noticeable. To do that, I need to know the time in milliseconds (or seconds) when a measure begins.
- It can be difficult to style a full note consistently with CSS. It's easy to style the note head, which is always a child of the `.note` element in the SVG, but other parts of the note, like the stem or the dot, are sometimes children of the `.note` element, and sometimes not. If getElementsAtTime() could provide chord elements, I could highlight together all note heads, stems, and dots that are children of a `.chord` element or a `.note` element, at the appropriate time in the audio.
- I'd like a user to be able to click or tap at a certain place in the sheet music, and the audio would start playing from that point. However, the click/tap area for a note is small and can be difficult to tap. If a user could tap anywhere in the chord or measure to start playing from there, it would make it easier. To do that, I need to know where in the audio a given chord or measure begins.

**Comment by lpugin** [comment]
Added in #2280

**Comment by samuelbradshaw** [comment]
Sorry for the late reply, but it looks like getTimeForElement() was updated, but getElementsAtTime() was not. Would we be able to reopen this, or would you like me to open a separate issue?
