### ISSUE TITLE
Provide release binaries 

### ISSUE THREAD

**Issue by jjazzboss** [rism-digital/verovio#2249]
Hi, this issue is not a bug, but I could not find any mailing list or support forum...

I wish binaries were provided for all platforms since, as the online doc says "building ... is very straight-forward". It's probably straight forward for you guys when you have all build tools and computers ready. But it's not when you have to set up all the tools from scratch (in my case on Win10). My goal was just to make a test of the verovio lib with my java app, but I gave up after too many trials and errors just to build the java toolkit.

**Comment by lpugin** [comment]
This is not the most widely used binding and it might be out of date. The best for such questions is to ask on the #verovio slack channel of the music-encoding.slack.com environment. Please provide more information about the errors you encountered when building with java.
