### ISSUE TITLE
Crash in AlignHorizontally 

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2262]
Trying to render `note-005.mei` from the test suite crashes with 

> Assertion failed: (note), function AlignHorizontally, file /Users/rettinghaus/git/verovio/src/layerelement.cpp, line 1062.

**Comment by lpugin** [comment]
Weird. line 1062 is on about an `artic` and there is no artic in this file
```cpp
    else if (this->Is(ARTIC)) {
        // Refer to the note parent
        Note *note = vrv_cast<Note *>(this->GetFirstAncestor(NOTE));
        assert(note);
        m_alignment = note->GetAlignment();
    }
```
It does not crash for me and shows up https://www.verovio.org/test-suite.xhtml?cat=note. You should try to clean-up you build directory and rebuild

**Comment by rettinghaus** [comment]
I messed up the test file locally. Sorry for that.
