### ISSUE TITLE
Problem printing from Firefox

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#2300]
**Describe the problem**
When printing from Verovio the image is messed up.

**To Reproduce**
- Load any file in the Verovio MEI viewer
- Try to print the page (File->Print)
- The print preview shows a big black splotch and the notes do not render correctly.

**Expected behavior**
The page should print correctly

**Input data**
Any file from the Verovio MEI viewer will exhibit this problem

**Verovio information**
Latest development version, but all other versions were affected as well.

**Environment information (as appropriate)**
 - OS: macOS 11.4
 - Browser: Firefox 89.0.2

<img width="1680" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/163183/126171366-eca27fac-5a52-426d-be79-c60642c11447.png">

**Comment by lpugin** [comment]
This was a bug in Firefox that has been fixed. For the record https://support.mozilla.org/en-US/questions/1344017
