### ISSUE TITLE
Support '<tempo>' within '<staff>' for mensural notation

### ISSUE THREAD

**Issue by andrewacashner** [rism-digital/verovio#2318]
Verovio does not support `tempo` within `staff`. I believe that makes it impossible to change MIDI tempo in the middle of a piece in mensural notation, or any notation that puts `layer` within `staff` rather than `measure`. 

My suggestion is to accept a `tempo` element  with `@midi.bpm` within `staff`.

MEI says `tempo` may be contained by `staff`: https://music-encoding.org/guidelines/v4/elements/tempo.html#attributes

**Comment by lpugin** [comment]
I am not convinced that having `tempo` within `staff` is the proper way to handle this. On a more general level, this relates to the issue of control events in mensural notation. There are maybe other ways to handle the problem. As already suggested here #2285 maybe you want to encode it with measures, but of course it depends what your mensural piece is. Can you share more information about it?

**Comment by lpugin** [comment]
Discussion to be followed here https://github.com/music-encoding/music-encoding/issues/601
