### ISSUE TITLE
Make resources non-static

### ISSUE THREAD

**Issue by DavidBauer1984** [rism-digital/verovio#2343]
Following the discussing in #2253 we should move all vrv-resources into a non-static container object which is owned by the toolkit or document. This would allow passing a toolkit instance between different threads without loosing resource path and loaded fonts.

**Comment by lpugin** [comment]
In principle I don't see any problem with this proposal. Have you already identified the main implications and some possible problems?

**Comment by DavidBauer1984** [comment]
No, I haven't really looked into it. For me, it's rather low priority (since there are workarounds) and if there are any serious problems, I would leave it as is.
