### ISSUE TITLE
Change random integer ID values to use base-64 or base-16 encodings

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#2354]
**Is your feature request related to a problem? Please describe.**

Currently element IDs are generated randomly and their integer values stored directly as strings. This leads to fairly long IDs, e.g., `note-0000000743468986`, and the fact that they are actually (zero-padded) integers is never really used.

**Describe the solution you'd like**

The integer IDs can be more compactly represented using other base representations, like hexadecimal (base-16) or base64. These IDs would be equivalent to the random number string that is generated, but would be shorter and so consume much less space in longer encodings.

So `note-0000000743468986` would become `note-LFBvug` in base-64 (trailing equals signs for padding can be omitted, since this is not necessarily meant to be decoded back to an integer) or `note-2C506FBA` in base-16.

Changing these representations would reduce the size of the generated MEI or SVG output file.

**Comment by lpugin** [comment]
Base-64 might be problematic in XML because of the /. But base-62 (a-zA-Z0-9)or base-36 (A-Z0-9) would work.

Additionally, we could truncate the `note-` prefix to just the first letter `n-` or even `n` because these are actually redundant with the MEI element names or the SVG `g@class` and pretty much useless

**Comment by ahankinson** [comment]
If it's a quoted string then a slash should be OK?

`<g id="n-12/345" />`

Alternately, we can redefine the allowed base64 characters to include URI-safe characters like '-' and '_' instead. The built-in Python base64 encoding lets you specify the alternate characters to use for the `+` and `/`:

https://docs.python.org/3/library/base64.html

This is also part of the base64 RFC:

https://datatracker.ietf.org/doc/html/rfc4648#section-5

**Comment by wergo** [comment]
Is there/will there be an option to preserve the old-style xml:ids that have become so accustomed to?

**Comment by lpugin** [comment]
There is currently no option and not plan to have old-style xml:ids. Do you rely on them?
