### ISSUE TITLE
MIDI rendering of grace notes

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#237]
It would be nice to render grace notes in MIDI output from verovio.  A basic implementation should be easy since the midifile library allows inserting notes backwards in time.  The number of grace notes would be counted and could be inserted with a constant small time unit increment backwards from the current beat.  One grace-note time unit back for a single acciaccatura, two units for the previous grace note in a group and so on.

**Comment by wergo** [comment]
@craigsapp Has anything happened in this regard? We would need this for further computing. (Related to #720 and #1928)

**Comment by craigsapp** [comment]
A general solution is too complicated for me to work on while I am teaching (for the next month :-).  Maybe @lpugin  (or perhaps @rettinghaus) might want to add it?  Or at least basic infrastructure to refine grace notes later.  The main complication is linking a grace note (or grace-note group) to the previous/next note to apply time adjustments to those notes.  Also knowledge of the current tempo when processing a grace note is useful for assigning duration to acciaccaturas.

The general problem is that the current conversion to MIDI does not need to communicate between notes to decide durations, but for grace notes they need to  to share duration between themselves.   A simple solution might be to just insert grace notes as an overlay on top of the regular notes, which is probably sufficient for @wergo.  It will not be a problem to insert grace notes backwards in time (except at the start of the score) since the notes are all inserted in absolute-time mode (and the note order is sorted before the MIDI file is written).   The duration of a grace note in the simple implementation is a bit complicated.  Perhaps assigning a 32nd note duration would be a good start.

MEI documentation for grace notes: https://music-encoding.org/guidelines/v4/content/cmn.html#cmnNotesGrace

There are three general categories of grace notes:

(1) acciaccaturas (short note) before a regular note (`note@grace="unacc"`).  For monophonic instruments, any note preceding the grace note should be shortened by the duration of the grace note.   Shortening the preceding note should probably also be done for piano music, but not as necessary (and it will be complicated in the general case to identify the previous note in keyboard music).

(2) acciaccaturas to be played at the time of the note following it (`note@grace="acc"`) with the following note delayed by the duration of the grace note, and the duration of the grace note subtracted from the following note.

(3) appoggiaturas (usually a grace note without slash), to be played at the time of the note following it, and the performance duration of the grace note should match the visual duration of the grace note.

There is also `<graceGrp>` (and perhaps also multiple `note@grace` in sequence) which should only apply to cases 1 and 2.

Cases 2 and 3 seem to be difficult to distinguish from each other in MEI (acciaccatura versus appoggiatura).  `@grace.time` seems the main way, or alternately by looking at `note@slash`, which is always none for appoggiaturas, and almost always `1slash` for acciaccaturas.

For cases 1 and 2 (acciaccaturas), the time of the grace notes are not musical time but rather physical time, so `note@grace.time` as described (on https://music-encoding.org/guidelines/v4/elements/note.html) is not really appropriate.  Acciaccaturas should be played "as fast as possible" which would be in the range from about 50 to 100 milliseconds.  What this means is that the acciaccatura durations need to be calculated based on the current tempo.  Then there is a complication where inserting an acciaccatura between two fast notes, it should be placed half-way between the notes rather than with a specific duration (i.e., if the distance between two real notes is 150 milliseconds, the grace note between them should have a duration of 75 milliseconds rather than a default duration longer than 75 ms).

Here is an example where I implement case 1 (acciaccaturas), using a default duration of 100ms, subtracting duration from the previous note, and keeping the duration of the grace note constant regardless of tempo:
      https://ratioscore.humdrum.org/time/#gracenotes
Example application in a Turkish song:
     https://ratioscore.humdrum.org/turkish/?autoplay=1944
PDF score:
     https://github.com/MTG/SymbTr-pdf/blob/master/suzidil--sarki--senginsemai--ey_gonca--semseddin_ziya_bey.pdf

**Comment by wergo** [comment]
Thanky, @craigsapp, that's exactly what we would need (and thanks for the comprehensive overview!) 

It would not matter so much, if the grace notes overlap with the previous note. Having a constant duration value such as 70–100 ms (see https://doi.org/10.1525/mp.2002.20.1.3) would be sufficient. 

I don't think, I have the time and the ability to implement this...
