### ISSUE TITLE
Using override instead of virtual

### ISSUE THREAD

**Issue by DavidBauer1984** [rism-digital/verovio#2371]
C++11 introduced the keyword `override` to specify that a virtual function overrides another virtual function defined in a base class. Using this instead of `virtual` for overriding functions has two advantages:
- The compiler can check that we are indeed overriding some virtual function in a base class and throw an error if we accidentally define a new virtual function.
- It tells the human who is reading the code immediately whether we define or override a virtual function.

It is really impossible to break something by adding it. But if we use it, then it should be used consistently. Xcode throws warnings if it is used just here and there within a class.

What do you think about introducing it into Verovio's codebase? (Technically I've sneaked it in already into the class `OptionJson`. I didn't know at this point that it is not used anywhere else 😬 )

**Comment by lpugin** [comment]
Yes, I thought about adding them. They would be good because they can help avoiding bugs. Please a ahead.
