### ISSUE TITLE
Composite dynamics + font interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2406]
In the Bravura and Leland fonts, composite dynamics markings such as `sff` are not kerned properly, having a space between the `sf` and the `f`:

Bravura:

<img width="231" alt="Screen Shot 2021-10-02 at 9 47 54 PM" src="https://user-images.githubusercontent.com/3487289/135740410-c05a60a6-18e7-438f-9cac-9cd654613873.png">

Leland:

<img width="223" alt="Screen Shot 2021-10-02 at 9 50 02 PM" src="https://user-images.githubusercontent.com/3487289/135740418-5e063d0f-5067-4e2f-b825-4f0c57bd3012.png">

In the other music fonts, the kerning is as expected, with the `sf` and `f` touching:

Gootville:

<img width="233" alt="Screen Shot 2021-10-02 at 9 50 39 PM" src="https://user-images.githubusercontent.com/3487289/135740423-e86de8d1-8ed6-4115-abbd-eee1de7f8bd0.png">

Leipzig:

<img width="249" alt="Screen Shot 2021-10-02 at 9 51 07 PM" src="https://user-images.githubusercontent.com/3487289/135740429-aedb4511-c39c-42c1-b99a-693bc620067b.png">

Petaluma:

<img width="244" alt="Screen Shot 2021-10-02 at 9 51 33 PM" src="https://user-images.githubusercontent.com/3487289/135740443-f680a472-ebd4-470b-97ba-ba6dd6a3572d.png">

**Comment by rettinghaus** [comment]
This is a font problem and there's nothing Verovio could do about it. 
Here's the boundaries for Leland's forte glyph: 
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7693447/135763215-096dce63-7888-43f7-ba00-e0f4a041a05c.png">

You may open issues directly [here](https://github.com/steinbergmedia/bravura) and [here](https://github.com/MuseScoreFonts/Leland).

**Comment by craigsapp** [comment]
For reference, here are the bounding boxes in the other fonts:

Bravura:

<img width="540" alt="Screen Shot 2021-10-03 at 10 44 43 AM" src="https://user-images.githubusercontent.com/3487289/135765484-107b095b-38bc-4c0e-a612-71b93de13a25.png">


Gootville:

<img width="540" alt="Screen Shot 2021-10-03 at 10 39 37 AM" src="https://user-images.githubusercontent.com/3487289/135765446-ab3b6c91-7e24-47ca-be8d-09883e347610.png">


Leipzig:

<img width="540" alt="Screen Shot 2021-10-03 at 10 50 04 AM" src="https://user-images.githubusercontent.com/3487289/135765554-a2099854-5a41-4e2c-8d61-ecdd5ec121d1.png">


Petaluma:

<img width="540" alt="Screen Shot 2021-10-03 at 10 45 50 AM" src="https://user-images.githubusercontent.com/3487289/135765477-731231d0-2d03-48b6-8334-35dac56fdaaf.png">
