### ISSUE TITLE
Allow <dir> as a child of <staff>

### ISSUE THREAD

**Issue by davidrizo** [rism-digital/verovio#2434]
Currently MEI allows the encoding of ``<dir>`` as a child of staff. However, in mensural we can avoid the use of measures in the MEI encoding.

```xml
<scoreDef>
    <staffGrp>
        <staffDef clef.shape="G" clef.line="2" key.sig="0" n="1" lines="5"  notationtype="mensural.white" label="Default" />                            
    </staffGrp>
</scoreDef>
<section>                                               
        <staff n="1">
            <layer n="1">
                <rest dur="brevis"/>                                    
            </layer>
        </staff>
        <dir xml:id="dir-L19F1" place="above" staff="1" tstamp="6.000000">
            <rend>&#x1D10B;</rend>
        </dir>                        
</section>
```

Verovio does not support yet this encoding, it generates this error:
```[Warning] Unsupported '<dir>' within <section>```

Currently, ```<dir>``` just works inside a ```<measure>``` element.

**Comment by martha-thomae** [comment]
Sorry, @davidrizo, you mean that the encoding of `<dir>` within `<staff>` (which is permitted in MEI and is the best option for mensural notation where there are no measures) is not supported by Verovio yet, right? 

Editing your example a bit:
```xml
<scoreDef>
    <staffGrp>
        <staffDef clef.shape="G" clef.line="2" key.sig="0" n="1" lines="5"  notationtype="mensural.white" label="Default" />                            
    </staffGrp>
</scoreDef>
<section>                                               
        <staff n="1">
            <layer n="1">
                <rest dur="brevis"/>                                    
            </layer>
            <dir xml:id="dir-L19F1" place="above" staff="1" tstamp="6.000000">
                <rend>&#x1D10B;</rend>
            </dir>         
        </staff>
</section>
```
This is the way we want this to be encoded in MEI, but right now Verovio is not rendering it. Am I correct?

**Comment by lpugin** [comment]
One additional comment on this: there is no plan to support `@tstamp` / `@tstamp2` with mensural notation because these do not make any sense.

**Comment by martha-thomae** [comment]
Ooops, sorry. I am correcting it here to `@startid`. Thanks, @lpugin!

So, here is the corrected MEI example:

```xml
<scoreDef>
    <staffGrp>
        <staffDef clef.shape="G" clef.line="2" key.sig="0" n="1" lines="5"  notationtype="mensural.white" label="Default" />                            
    </staffGrp>
</scoreDef>
<section>                                               
        <staff n="1">
            <layer n="1">
                <rest dur="brevis" xml:id="note1"/>                                    
            </layer>
            <dir xml:id="dir-L19F1" place="above" startid="#note1">
                <rend>&#x1D10B;</rend>
            </dir>         
        </staff>
</section>
```

So, this seems to be valid MEI, but currently it is not rendered in Verovio. This is what you are requesting, right, @davidrizo? The only way for this to be rendered in Verovio as of now is to wrap things into a measure and move `<dir>` to be a child of that measure (which is not applicable for mensural notation).

**Comment by lpugin** [comment]
I am not too sure what is the best solution for this issue. Supporting `dir` within `staff` is only one part of the problem. The other is the positioning of element in between notes (e.g., a fermata). By restricting the use of `@startid`, positioning in between notes is not possible. So in my opinion, before starting the implementation of a solution, it would be good to think about this part of the problem too. Allowing them within `layer` could be a direction, but it would not solve the positioning problem out of the box. Any thoughts?

**Comment by lpugin** [comment]
Relates to the [general discussion](https://github.com/music-encoding/music-encoding/issues/601) on control event in mensural (non-measured) music.
