### ISSUE TITLE
Support for ESM/ES6

### ISSUE THREAD

**Issue by ghost** [rism-digital/verovio#2473]
**Is your feature request related to a problem? Please describe.**
Currently it is impossible to import the [verovio js (wasm) npm module](https://github.com/rism-digital/verovio/releases/download/version-3.6.0/verovio-toolkit-wasm.js.zip) for SPA frameworks like Angular which favor [ESM/ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) style modules without introducing significant changes to the js file. The ESM/ES6 modules are also widely [supported by modern browsers](https://caniuse.com/es6-module). The current approach also pollutes global namespace with global `Module` variable when imported using simple `<script>` tag, which conflicts with other emscripten modules that are setup in a same way.

Summary:
- impossible to simply import module for modern web SPA frameworks like Angular without significant changes 
- current approach pollutes global with Module variable which can cause conflicts for other emscripten modules

**Describe the solution you'd like**
The ideal solution is to have a release of verovio js (wasm) version that targets ESM/ES6 modules.

**Comment by lpugin** [comment]
Could you make a PR of the changes you want to be made? If that is not possible, please give more details about the conflicts you have and the solution you would like to see implemented.

**Comment by davidrizo** [comment]
I don't know how to solve this, but it seems it would help if all functions of Verovio are added into its namespace. I've facing with a problem difficult to solve:
```verovio-toolkit-wasm.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '367907')
    at runWithFS (verovio-toolkit-wasm.js:1:718)
    at callRuntimeCallbacks (opencv.js:21:21879)
    at preRun (opencv.js:21:22438)
    at run (opencv.js:56:18089)
    at cv (opencv.js:56:19694)
    at opencv.js:70:1
    at opencv.js:14:1
```
This seems to be to to the fact that ``runWithFS`` is defined both in Verovio and [OpenCV](https://docs.opencv.org/3.4/d0/d84/tutorial_js_usage.html), and depending on the import order it causes a different error because of the conflict.

**Comment by ahankinson** [comment]
This is probably because both OpenCV and Verovio are compiled with emscripten. I would guess that it's adding some helper functions into the global namespace.

**Comment by davidrizo** [comment]
I've just managed to make it work just by avoiding the use of npm packages and including directly the js file to run as a worker. Thank you @lpugin !!

**Comment by WolfgangDrescher** [comment]
> ```perl
> my $extra_exports = "-s EXPORTED_RUNTIME_METHODS='[\"cwrap\"]' -s EXPORT_NAME='\"VerovioModule\"'";
> ```
>makes any difference?

@lpugin I tested this and currently it does not seem to be possible with emscripten to pass a custom `EXPORT_NAME` without the `MODULARIZE=1` option. See here: https://github.com/emscripten-core/emscripten/issues/17274

The emscripten build will always output something like this:

```js
var Module=typeof VerovioModule!="undefined"?VerovioModule:{};...
```

And therefore `window.Module` will be set in a browser context.
