### ISSUE TITLE
Tablature: Augmentation dots on rhythm-signs

### ISSUE THREAD

**Issue by TimCrawford** [rism-digital/verovio#2525]
(Both Italian and French tab) Augmentation dots on the rhythm-signs are too small and close to the signs themselves
![Aug_dot_on_Italian _lute_tab_rhythmsign](https://user-images.githubusercontent.com/2544314/144839045-37a42888-c981-4519-a213-e1ccb4518951.jpg)

![Aug_dot_on_French _lute_tab_rhythmsign](https://user-images.githubusercontent.com/2544314/144839095-b7f887ee-a1fc-493e-ab6b-bc468de0d14a.jpg)

MEI for these examples is the same for Italian and French lute tablature, but with attribute 'notationtype' changed appropriately on line 17
```xml
<?xml version="1.0" standalone="no"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Augmentation dot on tablature rhythm sign - French lute tablature</title>
            </titleStmt>
            <pubStmt />
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv n="1">
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" lines="6" notationtype="tab.lute.french">
                                <tuning>
                                    <course n="1" pname="g" oct="4" />
                                    <course n="2" pname="d" oct="4" />
                                    <course n="3" pname="a" oct="3" />
                                    <course n="4" pname="f" oct="3" />
                                    <course n="5" pname="c" oct="3" />
                                    <course n="6" pname="g" oct="2" />
                                    <course n="7" pname="f" oct="2" />
                                    <course n="8" pname="e" oct="2" />
                                    <course n="9" pname="d" oct="2" />
                                    <course n="10" pname="c" oct="2" />
                                </tuning>
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section n="1">
                        <measure n="1">
                            <staff n="1">
                                <layer n="1">
                                    <tabGrp dur="2" dots="1">
                                        <tabDurSym />
                                        <note tab.course="2" tab.fret="0" />
                                    </tabGrp>
                                    <tabGrp dur="4">
                                        <tabDurSym />
                                        <note tab.course="2" tab.fret="2" />
                                    </tabGrp>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
(Updated 6 Dec 2021)

**Comment by craigsapp** [comment]
Ideally you should include a short example MEI file that demonstrates the problem. In other words, it is better to extract about a measure's worth of music that illustrates a problem rather than including an entire score.   There are two purposes for this: (1) It allows the person trying to fix the problem to test updates to the code to verify that a fix works, and (2) the short example can then be added to the verovio test suite: https://www.verovio.org/test-suite.xhtml, which can be used to monitor future changes to the verovio sourcecode that may break the notation rendering again.

This can be done in two ways:

(1) Zip an XML file and then drag-and-drop the file into the issue input editor.  This method   is the best for including complete scores of MEI data (about greater than 1000 lines of XML code).

or (2), I find this method more convenient for short examples: these can be displayed directly in the issue webpage by enclosing the MEI content between two lines that only contain three back quotes.  To colorize the XML structure, add the text "xml" (with or without a space) after the first line of backticks:

````
```xml
<xml content>
```
````

(3) For longer examples, or when there are multiple examples on a page that would disrupt reading of the text, then having a show/hide toggle of the example code is useful using `<details>` HTML element:

````
<details>
<summary>
Click to view MEI data for above example.
</summary

```xml
<xml condent>
```
````

Here is a on-page demo of the above Markdown code:
<details>
<summary>
Click to view MEI data for above example.
</summary

```xml
<xml condent>
```

**Comment by TimCrawford** [comment]
Dear Craig,

Nice to hear from you and thanks for the detailed advice. This was the first time I have opened a GitHub issue, so no wonder it was all wrong.

I will amend the issues on or after Monday when I get back to my laptop. Extracting minimal code to show these tab problems will take a bit of experimentation so it might take a while!

I hope you are well, still in CA ( I assume ) and not too bogged down with students etc. How is Eleanor these days?

Tim

On 4 Dec 2021, at 00:49, Craig Stuart Sapp ***@***.***> wrote:

﻿

Ideally you should include a short example MEI file that demonstrates the problem. In other words, it is better to extract about a measure's worth of music that illustrates a problem rather than including an entire score. There are two purposes for this: (1) It allows the person trying to fix the problem to test updates to the code to verify that a fix works, and (2) the short example can then be added to the verovio test suite: https://www.verovio.org/test-suite.xhtml<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.verovio.org%2Ftest-suite.xhtml&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C37e1cfefc5d84f3b971608d9b6bff524%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637741757859535429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2dmWOgxIxYUZffr0NRDTNIyPowDA41xho3kf2UAYVuU%3D&reserved=0>, which can be used to monitor future changes to the verovio sourcecode that may break the notation rendering again.

This can be done in two ways:

(1) Zip an XML file and then drag-and-drop the file into the issue input editor. This method is the best for including complete scores of MEI data (about greater than 1000 lines of XML code).

or (2), I find this method more convenient for short examples: these can be displayed directly in the issue webpage by enclosing the MEI content between two lines that only contain three back quotes. To colorize the XML structure, add the text "xml" (with or without a space) after the first line of backticks:

```xml
<xml content>
```


(3) For longer examples, or when there are multiple examples on a page that would disrupt reading of the text, then having a show/hide toggle of the example code is useful using <details> HTML element:

<details>
<summary>
Click to view MEI data for above example.
</summary

```xml
<xml condent>
```


Here is a on-page demo of the above Markdown code:

Click to view MEI data for above example. <xml condent>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frism-digital%2Fverovio%2Fissues%2F2525%23issuecomment-985932203&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C37e1cfefc5d84f3b971608d9b6bff524%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637741757859545419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lo9CV0XCDEZwOuZMuWARJ8YlkBoTvtnmmT%2Bbb8Sm3oo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAATNFOWIPOZDK6CHZFJLGX3UPFQSJANCNFSM5JKCRIPQ&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C37e1cfefc5d84f3b971608d9b6bff524%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637741757859545419%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EJ1IKLrBlWfW8%2B3hihrqvlPks3eVOTeQAZPhdaRBKEY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C37e1cfefc5d84f3b971608d9b6bff524%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637741757859555414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NbKJK1nm4byVgghXrs8yZ7s6EKOP8WuBGhTnBz7ImoM%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C37e1cfefc5d84f3b971608d9b6bff524%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637741757859565407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YrhvLxzbmX58emoRsCEgsmfz0YWrTxwjTGnQdNyt%2BMo%3D&reserved=0>.
