### ISSUE TITLE
Tablature: Symbol scaling not quite right

### ISSUE THREAD

**Issue by TimCrawford** [rism-digital/verovio#2527]
<details>
<summary>
Click to view MEI data for example below.
</summary>

```xml <score>
<scoreDef>
    <staffGrp>
	   <staffDef n="1" lines="6" notationtype="tab.lute.french">
		  <tuning>
			 <course n="1" pname="g" oct="4" />
			 <course n="2" pname="d" oct="4" />
			 <course n="3" pname="a" oct="3" />
			 <course n="4" pname="f" oct="3" />
			 <course n="5" pname="c" oct="3" />
			 <course n="6" pname="g" oct="2" />
		  </tuning>
	   </staffDef>
    </staffGrp>
</scoreDef>
<section n="1">
    <measure n="1">
	   <staff n="1">
		  <layer n="1">
			 <tabGrp dur="4" dots="1">
				<tabDurSym />
				<note tab.course="1" tab.fret="7" />
				<note tab.course="2" tab.fret="6" />
				<note tab.course="3" tab.fret="2" />
				<note tab.course="5" tab.fret="4" />
			 </tabGrp>
			 <tabGrp dur="8">
				<tabDurSym />
				<note tab.course="1" tab.fret="5" />
				<note tab.course="2" tab.fret="7" />
				<note tab.course="3" tab.fret="0" />
			 </tabGrp>
			 <tabGrp dur="4">
				<tabDurSym />
				<note tab.course="1" tab.fret="4" />
				<note tab.course="2" tab.fret="7" />
				<note tab.course="3" tab.fret="1" />
				<note tab.course="5" tab.fret="4" />
			 </tabGrp>
			 <tabGrp dur="4">
				<note tab.course="1" tab.fret="1" />
			 </tabGrp>
			 <tabGrp dur="2">
				<tabDurSym />
				<note tab.course="1" tab.fret="2" />
				<note tab.course="2" tab.fret="3" />
				<note tab.course="3" tab.fret="3" />
				<note tab.course="4" tab.fret="0" />
			 </tabGrp>
		  </layer>
	   </staff>
    </measure>
    <measure n="2">
	   <staff n="1">
		  <layer n="1">
			 <tabGrp dur="2">
				<note tab.course="1" tab.fret="0" />
				<note tab.course="2" tab.fret="1" />
				<note tab.course="3" tab.fret="2" />
				<note tab.course="4" tab.fret="3" />
				<note tab.course="5" tab.fret="4" />
				<note tab.course="6" tab.fret="5" />
			 </tabGrp>
			 <tabGrp dur="2">
				<note tab.course="1" tab.fret="6" />
				<note tab.course="2" tab.fret="7" />
				<note tab.course="3" tab.fret="8" />
				<note tab.course="4" tab.fret="9" />
				<note tab.course="5" tab.fret="10" />
				<note tab.course="6" tab.fret="11" />
			 </tabGrp>
			 <tabGrp dur="2">
				<note tab.course="1" tab.fret="12" />
				<note tab.course="2" tab.fret="13" />
				<note tab.course="3" tab.fret="14" />
			 </tabGrp>
		  </layer>
	   </staff>
    </measure>
</section>
</score>
```
</details>

**Describe the problem**
*[This is my original description:*
*(French tab only, probably:) Symbol scaling isn’t quite right. Staff-line distance probably needs to be still larger, and rhythm flags also a little larger at this overall scale. (put another way, fret symbols are too big, but would be hard to read if they were shrunk to fit). The current scaling causes collisions between tall symbols on adjacent lines [NB this seems to be mainly (exclusively??) a problem with French tablature, and is probably caused by poor metrics in the French-tablature font - what to do?]*

Here are the results of a little tweaking by TC in view_tab.cpp:
(NB that Verovio does not display tab beyond the 12 fret (octave from open string) - this definitely needs extending! Cittern tablatures frequently use these high frets, and one baroque source goes up to fret z, i.e. two octaves above the open string; same applies for modern guitar number-based tablature)
1. With Leipzig font:
![tall_glyphs_leipzig](https://user-images.githubusercontent.com/2544314/149808687-70ce66fc-cafe-4249-b1ff-307360f6c427.jpg)

2. With Bravura font:
![tall_glyphs_bravura](https://user-images.githubusercontent.com/2544314/149808720-caeb1f6a-287a-4679-9746-b8a02e981206.jpg)

My impression is that a small increase in the staffline-spacing and a few minor improvements to Leipzig's tablature symbols (originally scanned from historical examples) would solve the problem(s): the baseline of the g is too low (cf Bravura, here - NB, when p and q are added there will be the same problem) and with a slightly widened staff there should be no 'white-outs' of the staff-lines (alternatively, the Leipzig font-size could be a bit smaller).

The Bravura font (also, I think based on historical examples, but not quite consistently, perhaps) suffers from rather varying glyph-sizes which are typographically ugly (to me, anyway).

**Comment by lpugin** [comment]
It would be good to check what you get with the Bravura font. Could you post the result here?

**Comment by TimCrawford** [comment]
Laurent,

Phew, at last I have conquered the mysteries of markdown sufficiently to post the result in Issue #2527 following Craig’s slightly cryptic advice. (I may have said too much in the posting, but since this has already taken me more than one hour to do, I shall leave it for now.)

BTW the augmentation dot is probably now too high (it will clash with smaller note-values in Leipzig, where perhaps it should be displayed a bit bigger and somewhat to the right?). Dots are easy to miss in tab rhythm signs, so they should be  made clearly visible. Obviously it would be better if this was font-independent, but this may not be possible.

Sorry, but I’m still not clear how to present my code changes. I now have a new verovio git repo on my hard drive, which I cloned from my new fork (https://github.com/TimCrawford/verovio). How do I show these to anyone interested? Do I just push to this (new) repo and tell people to look there?

Please excuse my git/GitHub incompetence.

T

On 17 Jan 2022, at 14:26, Laurent Pugin ***@***.******@***.***>> wrote:



It would be good to check what you get with the Bravura font. Could you post the result here?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frism-digital%2Fverovio%2Fissues%2F2527%23issuecomment-1014601867&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Cc9171a80595941cb9a9808d9d9c5600d%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780264028593302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XgjmvSgHh7v3AE1LRqbFUV93Qgk5cBdvELOVTQd62AU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAATNFOVAKXYQWIJEEE54NXTUWQRJ3ANCNFSM5JKDZVBA&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Cc9171a80595941cb9a9808d9d9c5600d%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780264028593302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sKt0%2F3Fov3XmqFEhYNPupIK3rPRgEnaSzmNGnQMOH9A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Cc9171a80595941cb9a9808d9d9c5600d%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780264028593302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LeK3UjrfddYcPj5XSiVW0nbqnmEQ7LybNjAmpDBzxXo%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Cc9171a80595941cb9a9808d9d9c5600d%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780264028593302%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2qoBv%2Fsme8h12bQQuLnC63Jadxu22rTXspxyY6aH1cg%3D&reserved=0>.

**Comment by lpugin** [comment]
This is the current design for the *g* in Bravura and Leipzig, with a star at the origin of the glyph.
![image](https://user-images.githubusercontent.com/689412/149832484-faa67163-74aa-430d-960a-f955b3851b47.png)

![image](https://user-images.githubusercontent.com/689412/149832652-e749b38b-0ca0-4f14-bd66-8302570076cc.png)

If I understand correctly, we need to change its origin for the Leipzig one and scale it for it to fit between two lines. Is it correct?

**Comment by lpugin** [comment]
I made some adjustment to the font. This is what I am not obtaining. @TimCrawford let me know what you think (ignore the overlap with the duration symbols)
![image](https://user-images.githubusercontent.com/689412/149838659-4890d5b0-408a-494e-ac79-bec0ddd94f7e.png)

**Comment by lpugin** [comment]
This is now the current rendering with the `develop-tab` branch

![image](https://user-images.githubusercontent.com/689412/149907377-63d98034-b043-465c-a96e-66c7f0302cbb.png)

Re-open the issue if necessary
