### ISSUE TITLE
Tablature: French-tablature rhythm signs too low

### ISSUE THREAD

**Issue by TimCrawford** [rism-digital/verovio#2528]
Probably French tab only: Rhythm flags are a little low and can clash with symbols on the top course

![collisions](https://user-images.githubusercontent.com/2544314/144640991-7da35293-116e-4548-a6d7-d0c61fc61e82.jpg)
clash with symbols on the top course

**Comment by lpugin** [comment]
See https://github.com/rism-digital/verovio/issues/2527#issuecomment-1015215723
