### ISSUE TITLE
Tablature: bass string/course position logic inconsistent

### ISSUE THREAD

**Issue by TimCrawford** [rism-digital/verovio#2529]
Both Italian and French tab: Bass course display is inconsistent. For French tablature, they should appear consistently below the stave, for Italian, above. Currently, course 7 displays above, and then 8+ are below. [TC: Italian tab does completely the reverse - i.e. there is a logic problem somewhere. Also, bass-notes are not handled well in Italian tab.]
Current display, Italian:
![Basses_Italian](https://user-images.githubusercontent.com/2544314/144641963-4d83be7f-9309-4e95-9c14-f22276e98237.jpg)

Current display, French:
![Basses_French](https://user-images.githubusercontent.com/2544314/144642176-9ac6eead-5cb9-4b5c-bd74-6424c354550d.jpg)

**Comment by TimCrawford** [comment]
Seems to be resolved now

**Comment by lpugin** [comment]
That is good, but do you know when and how it has been resolved?

**Comment by TimCrawford** [comment]
Dear all,

I apologise for possibly causing confusion. This is an effect of my inexperience in raising GitHub issues, which I’d never done before these (tablature) ones.

The problem lies in our MEI, not in Verovio, as I have just now (this morning) been able to verify. (This MEI was generated as a first test of the part-merging .xls that Johannes helped us with, and the tablature ‘part’ was wrongly coded, as it turns out. I did not realise this at the time.)

My current local installation of Verovio (Verovio 3.8.0-dev-c1c8189) puts the bass notes in the right place from a corrected MEI score - for French tab, that is; I haven’t yet tried Italian.

Tim

On 10 Dec 2021, at 07:15, Laurent Pugin ***@***.******@***.***>> wrote:



That is good, but do you know when and how it has been resolved?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frism-digital%2Fverovio%2Fissues%2F2529%23issuecomment-990674757&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C4538c7f8401747e3677108d9bbacd575%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637747173274515003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h%2BxdSQgffbJufac6kUoKilNy%2BdnpmAnQr6ukjl6ctcc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAATNFOWCCV7TG3JXJ773ORTUQGSIVANCNFSM5JKEQ2NQ&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C4538c7f8401747e3677108d9bbacd575%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637747173274524998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3gTu3%2Bh3HGEMgM1mcHHM9nJhYS%2FRVzfpqLZTKXHFW04%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C4538c7f8401747e3677108d9bbacd575%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637747173274534983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=15uBPScZV22cK5K%2FID%2F%2Bw%2F5KgAi25AC3y0Z1mSK6YIM%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.crawford%40gold.ac.uk%7C4538c7f8401747e3677108d9bbacd575%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637747173274534983%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KkwFtEmfV%2BgredSn%2Bv2ErcUSn94uE816WIWMUjktXVI%3D&reserved=0>.
