### ISSUE TITLE
Tablature: French tab bass slashes ugly

### ISSUE THREAD

**Issue by TimCrawford** [rism-digital/verovio#2530]
French tab: Bass course slashes are too thick and take up too much space 

![Basses_French](https://user-images.githubusercontent.com/2544314/144642511-aa6163d8-d9fc-41c6-a58c-c2b7776afc7b.jpg)

**Comment by lpugin** [comment]
SMuFL has the slash directly combined with the fret number https://w3c.github.io/smufl/latest/tables/french-and-english-renaissance-lute-tablature.html

It seemed to me it would be simpler to have a single glyph for the slash and combine it appropriately. However, if `/a`, `//a` and `///a` (i.e., U+EBCE, U+EBCF and U+EBD0) are the only possible combinations we can still go that way, though.

**Comment by TimCrawford** [comment]
Laurent,

We need the notes and slashes to be separate: we could have ////a and even /////a ! (I could show you original sources for these.)

Though these are ‘logically’ replaceable by bass-number-glyphs ‘4’ and ‘5’, respectively, we may need to encode the original appearance. (I have not, I think, ever seen the equivalent of //////a - i.e. corresponding to ‘6’, where, as far as I know, the bass-number was always used.)

So your ‘simpler’ preference is preferable to me, too.

A further consideration is that the order of the letter and slashes in the bass-note can vary; in MSS, usually it’s like the encoding: ‘///a’, but in at least one prominent print (Thomas Mace, Musick’s Monument, 1676) and in fact several MSS, it’s like ‘a///‘ . In this case, however, there is so little ambiguity that we can possibly ignore this, at least for now.

On the other hand, there is yet another complication, where one or two printed sources give special notation for playing the two strings of a bass course as two notes (at the fundamental and at the higher octave, always in this order) separately; this is done in one way (Mouton, c1680) by using a smaller typeface for the second note and in another way (Radolt, 1701) using a capital letter for the bass note, lower-case for the second. In both cases the two notes are connected visually by a slur (or tie, rather). (I should say that both of these sources are engraved rather than typeset.)
Again, I could provide examples easily enough.

BTW, separating the letter and the slashes would simplify the SMUFL table’s ‘Recommended stylistic alternates’ which provide different Unicodes for several combinations. (The underline and strike-through ones are needed, too, I’m afraid!)

Tim

On 17 Jan 2022, at 15:43, Laurent Pugin ***@***.******@***.***>> wrote:



SMuFL has the slash directly combined with the fret number https://w3c.github.io/smufl/latest/tables/french-and-english-renaissance-lute-tablature.html<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fw3c.github.io%2Fsmufl%2Flatest%2Ftables%2Ffrench-and-english-renaissance-lute-tablature.html&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Ce069678e84a04d7f07c408d9d9d00c9f%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780309881445621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RnsjZjgQIrm6wbFIEv6DByWSuPHsw5Wvc6jmcR%2FF%2Fvg%3D&reserved=0>

It seemed to me it would be simpler to have a single glyph for the slash and combine it appropriately. However, if /a, //a and ///a (i.e., U+EBCE, U+EBCF and U+EBD0) are the only possible combinations we can still go that way, though.

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frism-digital%2Fverovio%2Fissues%2F2530%23issuecomment-1014675009&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Ce069678e84a04d7f07c408d9d9d00c9f%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780309881445621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R719WZ3cgx6KpTwwEhkUOv7OCZBEwFdw%2FbF2m6Pa7ss%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAATNFOWG22BAM2MGZZV6N5TUWQ2INANCNFSM5JKEU7RA&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Ce069678e84a04d7f07c408d9d9d00c9f%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780309881445621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fPUWkgTJIDC%2BWPM2%2FUffZzUEKt5ow%2FPQxBSaDXYAusk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Ce069678e84a04d7f07c408d9d9d00c9f%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780309881445621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Gg0OIbr%2F0WjGjFtRf68VIzkc1DVdCmp4ot1FSFgQtJE%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ct.crawford%40gold.ac.uk%7Ce069678e84a04d7f07c408d9d9d00c9f%7C0d431f3f20c1461c958a46b29d4e021b%7C0%7C0%7C637780309881445621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MUI2LB48jRqAto3NJZN0S6fKhfEJ%2BbwwFOpZQMRWhDQ%3D&reserved=0>.

**Comment by lpugin** [comment]
That makes perfect sense. Could you open an issue in the SMuFL repository about it https://github.com/w3c/smufl. You will have a much better wording and set of examples to provide. I will follow up for modification of the font and of the Verovio implementation.

**Comment by lpugin** [comment]
Mostly fiixed with #3401. Closing for now
