### ISSUE TITLE
[Warning] ABC import: Information field w is ignored

### ISSUE THREAD

**Issue by MervinPraison** [rism-digital/verovio#2558]
**Version**

Engraved by Verovio 3.9.0-dev-2f4dccb

**Describe the problem**
Considering below ABC notation, "w" is being ignored

**ABC Notation**
X: 1
T:Amazing Grace
C:John Newton
S:Soodlum's Irish Tin Whistle Book, John C. Campbell Folk School Song Book
M:3/4
L:1/8
K:G
  D2 | G4 (3(BAG) | B4 BA | G4 E2 | D4
w:1.~A-maz-ing__ grace, how_ sweet the sound
  D2 | G4 (3(BAG) | B4 AB | d6- | d4
w:That saved a__ wretch like_ me._
  Bd | d4 (3(BAG) | B4 BA | G4 E2 | D4
w:I_ once was__ lost, but_ now am found,
  D2 | G4 (3(BAG) | B4 BA | G6- | G4 |]
w:Was blind, but__ now I_ see.
%
W:2. 'Twas grace that taught my heart to fear
W:And grace that fear relieved;
W:How precious did that grace appear
W:The hour I first believed.
W:
W:3. Through many dangers, toils, and snares
W:I have already come;
W:'Tis grace hath bro't me safe thus far,
W:And grace will lead me home.
W:
W:4. When we've been here ten thousand years
W:Bright shining as the sun;
W:We've no less days to sing God's praise
W:Than when we first begun.

**Comment by ahankinson** [comment]
Tagging @rettinghaus
