### ISSUE TITLE
Switch RelaxNG to MEI 5

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2610]
As Verovio updates MEI files to the development version, wouldn't it be better to output an MEI 5 file (with pointing to the latest rng)?

**Comment by lpugin** [comment]
I am not sure I understand. Could you elaborate? MEI 5 does not exist yet. This is why the version is `5.0.0-dev` and the reference to `music-encoding.org/schema/dev`.

One thing I though could be useful is to have an option to specify the schema to be set in the output. But is this what you are talking about?

**Comment by lpugin** [comment]
Please reopen if necessary with more information.
