### ISSUE TITLE
Remove wheel build for Python 3.6, add support for 3.10

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#2635]
Python 3.6 support ended on 23 Dec 2021, and 3.10 was released on 04 Oct 2021. I suggest we remove 3.6 from the PyPI build matrix, and add 3.10. 

Users still using 3.6 will still be able to build from source.

Thoughts on this @musicEnfanthen @musicog @rettinghaus ?

**Comment by musicEnfanthen** [comment]
Totally fine with moving forward :)
