### ISSUE TITLE
Best practice for JavaScript toolkit with Humdrum support

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#2659]
What is currently best practice to implement the Verovio toolkit with Humdrum support on a website? `npm install verovio` works really well in most cases but in a new project I would like to also support the kern format. Do I have to build the toolkit myself for my use case and add the 10MB file to the git repository? Are there any plans to release a npm package with humdrum support?

If I download the humdrum toolkit from the latest release (https://github.com/rism-digital/verovio/releases/download/version-3.8.1/verovio-toolkit-hum.js.zip) there are missing the wrapping `verovio-npm-start.js` and `verovio-npm-end.js` snippets for direct node modules support. So the `module.exports` section at the end is missing to support `import` with Node.js. But if I add this manually I still get `[Message] Unsupported format` in the browser console. Am I missing something out?

I know for sure that Verovio can handle the kern file since it works just fine with the CLI: `verovio -a file.krn -o output`.

**Comment by lpugin** [comment]
> Do I have to build the toolkit myself for my use case and add the 10MB file to the git repository? Are there any plans to release a npm package with humdrum support?

There are no plan but it does not mean that this is not possible. As far as I understand it would need to be a separate npm package, wouldn't it? Other options?

I think we would need it to be in `wasm`. @craigsapp what do you think?

> But if I add this manually I still get [Message] Unsupported format in the browser console. 

Have you try setting the format as `inputFrom` option? Could you pose the file?

**Comment by lpugin** [comment]
OK, thanks for the proposal. However, because the size of the package can already be problematic I think it would be safer to have two distinct packages. I adjusted the build scripts and will publish it in the next release. You would need to do
```
import verovio from 'verovio-humdrum';
```
Would that work for you?

**Comment by ahankinson** [comment]
You could try publishing "scoped packages": https://docs.npmjs.com/creating-and-publishing-scoped-public-packages

`npm install @verovio/verovio`
`npm install @verovio/verovio-humdrum`

?

**Comment by lpugin** [comment]
We could, but if this means removing (or deprecating) the current package I would prefer not to do it. Do you know if we can move a package to a scoped package?

**Comment by ahankinson** [comment]
I think so. Seems you can't deprecate it, but you can give a message pointing people to the new way to install it.

https://stackoverflow.com/questions/43007471/how-to-migrate-npm-package-to-an-organization-scope

**Comment by lpugin** [comment]
Yeah, except people don't do it. We had `verovio-dev` marked as deprecated and when it was removed after 2 years people where still using it... I know this is not our problem, though.

**Comment by lpugin** [comment]
See https://www.npmjs.com/package/verovio-humdrum

**Comment by WolfgangDrescher** [comment]
Work like a charm. Thanks for implementing this so quickly!
