### ISSUE TITLE
Handling booleans

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2671]
Verovio cannot handle all allowed encodings of booleans in MEI.

Things like `num.visible="false"` work fine. 
What doesn't work (and throws a warning) is `num.visible=" false "`, although this is valid.

I think LibMEI is what would be needed to change here, but we can also deal with this while loading a file. Any thoughts?

**Comment by paul-bayleaf** [comment]
I can't find where in the MEI documentation " false " is allowed.  Do you have a reference?  Thanks.   (I parse MEI files for my own program luteconv and this would affect my code as well.)

**Comment by rettinghaus** [comment]
@paul-bayleaf This is a schema thing, i.e., for RelaxNG it's valid to have whitespace in there. Usually you would do it without, but if there's one in there somewhere, you'd never know.
