### ISSUE TITLE
MIDI rendering of cue notes

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2709]
Related to PR https://github.com/rism-digital/verovio/pull/2693 and somewhat related to issue https://github.com/rism-digital/verovio/issues/2625, another possibility is to use `note@vel` to control playback of cue notes instead of (or in addition to) a verovio option for MIDI rendering of cue notes.

If someone does not want cue notes to sound, then they can add `note@vel="0"`.   When `@vel` is set to zero, the note should not be exported to MIDI at all (i.e., do not output one or two note-offs for the note).

If someone wants the MIDI export to include the cue notes, but they do not want to hear them, then `note@vel=1` could be used.

Again it is better if cue notes are sounding as a default behavior in the MEI-to-MIDI exporter.  In particular because there is no clear encoding method yet for "cue" versus "small" notes (see https://github.com/rism-digital/verovio/issues/2625 related to this).

Probably `note@vel` is not implemented yet in the MEI-to-MIDI converter?  It should be very easy if not, and it would also be useful for future enhancement of dyanmics rendering in the MIDI output (i.e., have the dynamics inserted into the MIDI export).

**Comment by lpugin** [comment]
> Again it is better if cue notes are sounding as a default behavior in the MEI-to-MIDI exporter. In particular because there is no clear encoding method yet for "cue" versus "small" notes.

Yes, I changed my mind and agree with this. I asked @rettinghaus to changed the option in PR #2693 to `--midi-no-cue`. Then I think we can merge it.

For cases where we have a mix of cues and small notes (probably pretty rare) users can use `note@vel` as suggested until MEI features something else.

**Comment by craigsapp** [comment]
This could be revisited after issue https://github.com/music-encoding/music-encoding/issues/926 is resolved, but I still think that real cue notes should also be played by default.  For the most part people will not be listening to single parts of a score, but when they do, it will most likely be for proof-listening to the part (in which case proof-listening to the cues is also useful).
