### ISSUE TITLE
PAE Notes do not render with mensural head shapes without explicit duration

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#2727]
In PAE input, setting a clef to a mensural clef, but not adding any durations to the notes, results in modern note heads.

![image](https://user-images.githubusercontent.com/163183/159508834-b691b816-85cb-426b-b604-1228f8ce1960.png)

Setting an explicit duration fixes the rendering of the note heads to the correct shape:

![image](https://user-images.githubusercontent.com/163183/159508973-a217992e-3097-4723-ab69-3c44fd1902a2.png)

**Comment by lpugin** [comment]
Default value is set to semibrevis with mensural data

<img width="455" alt="image" src="https://user-images.githubusercontent.com/689412/159539713-b9d23092-b13f-4d20-8594-3d79a1302487.png">
