### ISSUE TITLE
fermata + spacingLinear interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2763]
When the `spacingLinear` option is small, strange things happen with the horizontal placement of the fermata in the following example (the fermata should remain centered on the final barline):

linearSpacing = 0.10:

<img width="309" alt="Screen Shot 2022-04-03 at 10 31 55 PM" src="https://user-images.githubusercontent.com/3487289/161480218-2f6444a7-dd5b-4221-ae6b-e1098d2ed37d.png">

linearSpacing = 0.08:

<img width="281" alt="Screen Shot 2022-04-03 at 10 32 03 PM" src="https://user-images.githubusercontent.com/3487289/161480238-e4005915-18bf-451b-ac24-0fe82db74280.png">

linearSpacing = 0.06:

<img width="292" alt="Screen Shot 2022-04-03 at 10 32 10 PM" src="https://user-images.githubusercontent.com/3487289/161480245-37ddbc1b-cfeb-469c-8b1a-35310048de47.png">

linearSpacing = 0.04:

<img width="258" alt="Screen Shot 2022-04-03 at 10 32 20 PM" src="https://user-images.githubusercontent.com/3487289/161480258-a1349789-5832-49e6-8dbf-0c083b99b995.png">

linearSpacing = 0.02:

<img width="266" alt="Screen Shot 2022-04-03 at 10 32 32 PM" src="https://user-images.githubusercontent.com/3487289/161480278-2bcce694-7b4d-4a69-8724-ad1900e68621.png">

linearSpacing = 0.00:

<img width="298" alt="Screen Shot 2022-04-03 at 10 32 43 PM" src="https://user-images.githubusercontent.com/3487289/161480295-faab14f3-af60-4532-8c76-68841ff71255.png">

<details>
<summary>
Click to view MEI data for above examples
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-04-03T22:32:49" version="3.10.0-dev-4a1d799">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m8opjql">
    <score xml:id="sbq1yuu">
     <scoreDef xml:id="s5ksdo4" midi.bpm="400.000000">
      <staffGrp xml:id="sb7gj0k">
       <staffDef xml:id="sbdrx1k" n="1" lines="5">
        <clef xml:id="clef-L2F1" shape="F" line="4" />
        <keySig xml:id="keysig-L3F1" pname="c" mode="major" sig="0" />
        <meterSig xml:id="metersig-L5F1" count="2" sym="cut" unit="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="s4jt7vl" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L10F1" type="placed" dur="2" oct="3" pname="f" stem.dir="up" accid.ges="n" />
         <note xml:id="note-L11F1" type="placed" dur="2" oct="3" pname="e" stem.dir="up" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L2F1N2" n="2">
         <note xml:id="note-L10F2" dur="1" oct="2" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L12" n="2">
       <staff xml:id="staff-L12F1N1" n="1">
        <layer xml:id="layer-L12F1N1" n="1">
         <note xml:id="note-L13F1" dur="1" oct="3" pname="g" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L12F2N2" n="2">
         <chord xml:id="chord-L13F2" dur="1">
          <note xml:id="note-L13F2S1" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L13F2S2" oct="2" pname="g" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L15" right="end" n="2">
       <staff xml:id="staff-L15F1N1" n="1">
        <layer xml:id="layer-L15F1N1" n="1">
         <note xml:id="note-L16F1" dur="1" oct="3" pname="c" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L15F2N2" n="2">
         <chord xml:id="chord-L16F2" dur="1">
          <note xml:id="note-L16F2S1" oct="2" pname="g" accid.ges="n" />
          <note xml:id="note-L16F2S2" oct="2" pname="e" accid.ges="n" />
          <note xml:id="note-L16F2S3" oct="2" pname="c" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <fermata xml:id="fermata-L18F1N1" staff="1" tstamp="3.000000" place="above" />
       <fermata xml:id="fermata-L18F1N2" staff="1" tstamp="3.000000" place="below" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

**Comment by rettinghaus** [comment]
Another thing I just noticed: Shouldn't the minimal space between notehead and bar line equal on both sides of the whole chord? So, shouldn't be there a minimum spacing _after_ the note whatever the value for `spacingLinear` is?

**Comment by craigsapp** [comment]
Yes, it would look nicer with equal spacing on either side.  The thin line of the double barline is not being taken into account &mdash; without the thin bar it looks about equal for `evenNoteSpacing`.
