### ISSUE TITLE
Wrong error message for ties following a chord

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/verovio#2855]
See the screenshot below where the error message "A tie using '+' must be preceded by a note" is shown, although the + _is_ in fact preceded by a note. Is it the chordal writing that throws the validation off track here? Perhaps in such cases Verovio only considers the first note as a "real note" and the rest as appendices to that?

![image](https://user-images.githubusercontent.com/70342380/167928187-27f9e889-bf63-4b21-a40e-b494a78591c7.png)

**Comment by lpugin** [comment]
Ties with the current specification of chords are more or less impossible to code and parse. See https://github.com/rism-digital/pae-code-spec/issues/2 for more on this issue and a proposal for improvement

**Comment by BaMikusi** [comment]
OK, thanks for putting the problem in a larger context. We can surely live with this problem for some time without major fallouts until the more general issue with chords gets adressed.
