### ISSUE TITLE
Complimentary hairpin spacing

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#2878]
Crescendo/Decrescendo hairpin pairs are currently too close to each other:

<img width="524" alt="Screen Shot 2022-05-20 at 3 31 28 PM" src="https://user-images.githubusercontent.com/3487289/169620612-a476234d-881f-43f8-ab1c-bab5a9c3eb14.png">

<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-05-20T15:31:35" version="3.10.0-dev-e51b2ff">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m9jh6ot">
    <score xml:id="slj34gz">
     <scoreDef xml:id="s6qutzh">
      <staffGrp xml:id="sj9oh4t">
       <staffDef xml:id="sj67m4m" n="1" lines="5">
        <clef xml:id="cqdnbbm" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="3" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="sc3iafa" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="2" oct="4" pname="c" accid.ges="n" />
         <note xml:id="note-L5F1" dur="4" oct="4" pname="e" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <hairpin xml:id="hairpin-L4F2" staff="1" tstamp="1.000000" tstamp2="0m+4.0000" form="cres" vgrp="100" />
       <hairpin xml:id="hairpin-L6F2" staff="1" tstamp="4.000000" tstamp2="1m+3.0000" form="dim" vgrp="100" />
      </measure>
      <measure xml:id="measure-L7" right="invis">
       <staff xml:id="staff-L7F1N1" n="1">
        <layer xml:id="layer-L7F1N1" n="1">
         <note xml:id="note-L8F1" dur="2" oct="4" pname="a" accid.ges="n" />
         <note xml:id="note-L9F1" dur="2" oct="4" pname="b" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

At a minimum, the separation should be no more than 1 VU:

<img width="488" alt="Screen Shot 2022-05-20 at 3 32 22 PM" src="https://user-images.githubusercontent.com/3487289/169620667-99a6aece-833b-4adc-8898-696436ae2119.png">

Although _Behind Bars_, page 104 recommends that they are spaced by a notehead width, the first ending at the left side of the notehead, and the second at the right side of the notehead (about 2 VU):

<img width="315" alt="Screen Shot 2022-05-20 at 3 29 49 PM" src="https://user-images.githubusercontent.com/3487289/169620695-a90d2f66-b3fe-4e01-9e36-4eb1471cf9bb.png">

If less than 2 VU, then probably center the gap at the middle of the notehead.   Smaller pairs that are not attached to any shared note can probably have a smaller gap.  There are also swell articulations that are implemented as hairpins currently?

https://www.smufl.org/version/latest/range/articulationSupplement/
<img width="390" alt="Screen Shot 2022-05-20 at 3 36 48 PM" src="https://user-images.githubusercontent.com/3487289/169620979-fb486fa8-fe98-48d7-a183-46d3798da0cc.png">
 which I do not see otherwise in the MEI articulation list:
https://music-encoding.org/guidelines/v4/data-types/data.articulation.html

Also this variant which more like a short hairpin pair:

https://www.smufl.org/version/latest/range/dynamics
<img width="412" alt="Screen Shot 2022-05-20 at 3 40 10 PM" src="https://user-images.githubusercontent.com/3487289/169621267-c413f9f9-bc0f-454a-b26e-1d728ab9e87c.png">

**Comment by rettinghaus** [comment]
Perhaps you should try to look at the dev version: https://music-encoding.org/guidelines/dev/data-types/data.ARTICULATION.html
`artic="acc-soft"` is already supported.

**Comment by craigsapp** [comment]
Toll!   That one is a pain to fake with hairpins, so I have a temporary articulation which is just a `<dir>` with the contents `<>`.

**Comment by lpugin** [comment]
I updated the `artic-001` in the [test-suite](https://www.verovio.org/test-suite.xhtml?cat=artic) and included `acc-soft`
