### ISSUE TITLE
PAE ignores @keysig in rendering to MIDI

### ISSUE THREAD

**Issue by peterkorgaard** [rism-digital/verovio#2916]
PAE ignores @keysig in rendering to MIDI

Example:
@clef:G-2\n@keysig:bBE\n@timesig:4/4\n@data:4'GAB''C/DEFG//

Renders this score

![paeeksample](https://user-images.githubusercontent.com/22868391/172367286-aca52d8e-1212-4ae9-894b-0ee90b6cb197.png)

The generated MIDI plays B and E instead of Bb and Eb

**Comment by rettinghaus** [comment]
Regression. Was first implemented with 47db65106ee4e849da61a05979a21b7652facee7 and updated with 6083eb338e861f373ce4337ff262b88ebfe45ca5.

**Comment by lpugin** [comment]
Yes. `KeySig::FillMap` seems to be broken.

**Comment by lpugin** [comment]
From https://github.com/rism-digital/verovio/commit/aef5f3e08c0c584b642074e2fad0892271763e55
