### ISSUE TITLE
How to activate musicXml condensing in v3.9? (Done automatically in v2.5)

### ISSUE THREAD

**Issue by cambiata** [rism-digital/verovio#2944]
Hi!

It seems that toolkit version 2.5 automatically condenses a musicXml score, while version 3.9 doesn't.
What option to use to get 3.9 to condense the score as well?

(I have tried `condense: 'auto'` and `condense:'encoded'` but none of them seems to affect the output.)

Thanks!

**Comment by rettinghaus** [comment]
A minimal example file could help.

**Comment by cambiata** [comment]
Version 3.10 and on seems to work as expected, so I'm closing this.
