### ISSUE TITLE
How to initalize Verovio in version 3.11.0

### ISSUE THREAD

**Issue by peterkorgaard** [rism-digital/verovio#2969]
I'm trying to update our software  to the latest version of verovio-toolkit.js (3.11.0)  from the previous version (3.10.0). To initialize the Verovio object I normally load the code until the page and then create the object from where I  access all the wonderful functions in Verovio.

const vrvToolkit = new verovio.toolkit();

This no longer works. In the new code I can see a new method is implemented, but I cannot get it to work. I do not use Node, so I need a plain JS method. Please help.

**Comment by lpugin** [comment]
Are you using the npm package? See [this](https://github.com/rism-digital/verovio/discussions/2897) discussion.

Instead of doing `Module.onRuntimeInitialized` you know need to do `verovio.module.onRuntimeInitialized`. However, I am not sure this is the issue for you. Could you provide some details about what you can see in the console?

**Comment by peterkorgaard** [comment]
I'm not using the npm package. I have downloaded verovio-toolkit.js from the release and added the file to the web-page. After everything is loaded I need to instantiate Verovio to get access to its functions. This fails. In previous versions this is done by. 

const vrvToolkit = new verovio.toolkit();

How is this supposed to be done in the new version? The change is new in version 3.11.0

**Comment by lpugin** [comment]
There was a problem when building the release files. I will update them ASAP.

**Comment by peterkorgaard** [comment]
Thanks

**Comment by lpugin** [comment]
I updated them. It should now work as before. Re-open if necessary.
