### ISSUE TITLE
Zip library compile warning

### ISSUE THREAD

**Issue by alpha0010** [rism-digital/verovio#2971]
**Describe the problem**

Changes (likely from https://github.com/rism-digital/verovio/issues/2679) yield the warning:

```
C/C++: In file included from verovio/src/toolkit.cpp:52:
C/C++: ../../../../../verovio/include/zip/zip_file.hpp:4551:21: warning: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files. [-W#pragma-messages]
```

**To Reproduce**
1. Checkout fresh copy of 3.11.0
2. Compile for Android

**Expected behavior**
No build warnings.

**Input data**
The smallest example (MEI unless about another input format) to reproduce the problem:
 - This repo?

**Verovio information**
 - Version of Verovio: 3.11.0
 - Binding: Android

**Additional context**
Appears to be hitting: https://github.com/rism-digital/verovio/blob/bb0c961574d0dbb5ce7253a82bec04fd32342e80/include/zip/zip_file.hpp#L4551

**Comment by lpugin** [comment]
Yes, the warning also appears in the WASM build:
https://github.com/rism-digital/verovio/runs/7379995763?check_suite_focus=true#step:7:215

I did try to fix it already but could not. However, it seems that this could really be an issue only if we have files larger that 4GB. I don't think this is a high risk, especially on Android or JavaScript environment.

I appreciate the willingness to have no build warnings, so please make a PR if you can find a solution. I do not feel it necessary to keep the issue open, though.
