### ISSUE TITLE
Support for new glyphs

### ISSUE THREAD

**Issue by annakijas1** [rism-digital/verovio#2976]
We would like to request that the following SMuFL glyphs be added so they can be rendered in Verovio:

[Medium xylophone stick up](https://www.smufl.org/version/latest/glyph/pictBeaterMediumXylophoneUp/), U+E774
<img width="633" alt="xylophone-up" src="https://user-images.githubusercontent.com/6841932/180288542-687aa4f2-8b5e-4058-ae47-8318405c0092.png">

[Medium xylophone stick down](https://www.smufl.org/version/latest/glyph/pictBeaterMediumXylophoneDown/), U+E775
<img width="508" alt="xylophone-down" src="https://user-images.githubusercontent.com/6841932/180288559-0aeeafa4-e890-420e-9928-7058a5b6e18e.png">

[Hand](https://www.smufl.org/version/latest/glyph/pictBeaterHand/), U+E7E3
<img width="521" alt="hand" src="https://user-images.githubusercontent.com/6841932/180288634-7b5428b2-fd38-49e2-9186-331e6c88eee0.png">

[Snare sticks up](https://www.smufl.org/version/latest/glyph/pictBeaterSnareSticksUp), U+E7D1
<img width="507" alt="snaresticks-up" src="https://user-images.githubusercontent.com/6841932/180288652-3b7e7ed4-c517-44c9-9514-e28b3c90e1df.png">

[Play](https://www.smufl.org/version/latest/glyph/elecPlay), U+EB1C
<img width="460" alt="play" src="https://user-images.githubusercontent.com/6841932/180288674-c4204d14-d4ce-4f7e-b539-f2d9e88ca0e3.png">

[Pause](https://www.smufl.org/version/latest/glyph/elecPause/), U+EB1E
<img width="453" alt="pause" src="https://user-images.githubusercontent.com/6841932/180288688-37c69b0c-224f-4900-9597-9028beda6083.png">

**Additional context**
We are using these for an [incipit encoding project ](https://rebalancing-music-canon.com/lizee-think-about-you-kb1/) and will add them to the MEI files where these graphics are used. For example we might encode them as:

```
<ornam tstamp="1">
<symbol glyph.auth="smufl" glyph.num="U+E774" glyph.name="pictBeaterMediumXylophoneUp"/>
</ornam>

```
<img width="280" alt="Screen Shot 2022-07-21 at 2 40 24 PM" src="https://user-images.githubusercontent.com/6841932/180289295-39128d19-5fb1-4568-83f5-d70245e0867b.png">

**Comment by ahankinson** [comment]
It's somewhat tangential to the issue, but `<dir>` is probably a better semantic element to use rather than `<ornam>`. `<ornam>` is intended for use as a generic note ornament, while `<dir>` is a performance direction:

```
<dir tstamp="1">
    <symbol glyph.auth="smufl" glyph.num="U+E774" glyph.name="pictBeaterMediumXylophoneUp"/>
</dir>
```

**Comment by lpugin** [comment]
We can make this work. Ideally, `symbol` could refer to any glyph we currently support in Verovio. However, this is not currently possible in Verovio. 

It is a bit technical, but SMuFL glyphs are included in two ways in Verovio. One is within `<g>` SVG elements, and one within `<text>`. Glyphs within `<g>` use SVG `<path>` – [This](https://github.com/rism-digital/verovio/blob/develop/include/vrv/smufl.h) is the list of glyph currently supported – and this is used for most of the glyphs (note head, stem flags, sharps, etc.). For glyhs within `<text>`, we have use a text font, which currently has only a very small subset of glyph (text elisions, coda, tempo small notes, etc.).

One idea would be not to require this type of glyphs to be added to the text font because this is complicated and not very flexible (see [this](https://github.com/rism-digital/verovio/issues/2651) issue on this matter). However, allowing any glyph supported means we would need to use SVG `<g>` and not a `<text>`. That means they glyphs could not be mixed with text. In other words, something like this would **not** work even though this is perfectly valid in MEI:
```xml
<dir tstamp="1">
    some text
    <symbol glyph.auth="smufl" glyph.num="U+E774" glyph.name="pictBeaterMediumXylophoneUp"/>
   some more text
</dir>
```
Any thoughts on this limitation? Would this be problematic?

**Comment by annakijas1** [comment]
Thanks for your explanation @lpugin. If we used the SVG `<g>` instead of `<text>` when rendering an MEI `<dir>` and did not mix it with text would that be valid? So if we want to use one of the symbols, like the snare sticks up, above a measure could we do that if it is included in the `<g>` SVG elements? Would adding these symbols there create any issues?

**Comment by lpugin** [comment]
> If we used the SVG <g> instead of <text> when rendering an MEI `<dir>` and did not mix it with text would that be valid? 

Yes, that would be valid MEI and will be supported by Verovio. This will work:
```xml
<dir>
    <symbol glyph.auth="smufl" glyph.num="U+E774" glyph.name="pictBeaterMediumXylophoneUp"/>
</dir>
```
BTW, specifying `@glyph.auth` but only `@glyph.name` or `@glyph.num` would be enough. If both are specified, the precedence will be given to `@glyph.name`.

Having more than one symbol is also expected work:
```xml
<dir>
    <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneUp"/>
    <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneDown"/>
</dir>
```

Having mixed content (text  and `<symbol>`) as in the example posted above is valid MEI, however that would not be supported by Verovio. The same with `<rend>` and editorial markup within `<dir>`, which are valid in MEI but that would also **not** be supported by Verovio:
```xml
<dir>
   <rend>
      <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneUp"/>
   </rend>
</dir>
```

```xml
<dir>
    <choice>
        <sic>
            <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneUp"/>
        </sic>
        <corr>
            <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneDown"/>
        </corr>
    </choice>
</dir>
```

For the second example, you would need to do
```xml
<choice>
    <sic>
        <dir>
            <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneUp"/>
        </dir>
    </sic>
    <corr>
        <div>
            <symbol glyph.auth="smufl" glyph.name="pictBeaterMediumXylophoneDown"/>
        </dir>
   </corr>
</choice>
```


> So if we want to use one of the symbols, like the snare sticks up, above a measure could we do that if it is included in the `<g>` SVG elements? Would adding these symbols there create any issues?

Yes, you will be able to it and it would not create any issues as long as it remains in the limitation above.

**Comment by annakijas1** [comment]
Thank you @lpugin. I'm not clear on one thing - will the glyphs be added to the <g> SVG elements?
