### ISSUE TITLE
Proposal for Functor Classes

### ISSUE THREAD

**Issue by DavidBauer1984** [rism-digital/verovio#3005]
### Motivation
Verovio currently implements functors as virtual methods of the Object class and stores the functor state in struct-like parameter objects (consisting only of public data members plus constructor for initialization). This approach has the following drawbacks:

1. The functor implementation is spread over several element classes. In order to understand what a certain functor does, one must search and inspect the code in several classes. Reversely, element classes are not self-contained and are crowded with functor code. An extreme example is the _Measure class_ which consists of 1700 LOC with 1000 LOC functor implementation.

2. There exists no mechanism for functors to share common functionality. For example, it would make sense to split the current transpose functor into three functors Transpose, TransposeMdiv and TransposeToSoundingPitch which share the core transposition functionality on KeySig, Note and Rest. Similarly, it would make sense to split the MEI export into several functors for page based, score based, filtered score based and MEI basic.

3. The functor state is currently not properly encapsulated. Usually parameters serve as input, output or intermediate values. However, there is no restriction for setting and getting parameter values.

4. The functor state must be passed as argument into the functor implementation and casted afterwards. Even though this does not have a negative impact on runtime (the casts are static), it adds a certain amount of boilerplate code.

5. There is no natural place to implement functor specific helper functions. This either leads to very long functor implementations (i.e. `LayerElement::CalcAlignmentPitchPos` with 260 LOC) or helper methods within an element class which are very functor specific (i.e. `Note::GenerateGraceNoteMIDI`).

### Proposal
These drawbacks could be overcome by implementing functors as classes and using a [Visitor Pattern](https://en.wikipedia.org/wiki/Visitor_pattern) to call them. The basic idea is to merge the functor implementation and state into one class for each functor.
There would be an interface class defining virtual methods for each element (i.e. `VisitorInterface::VisitMeasure(Measure *measure)`, `VisitorInterface::VisitNote(Note *note)`, `VisitorInterface::VisitRest(Rest *rest)`, … ) from which all functors are derived.
To transform a functor into a class, the following steps must be done:

1. Create a new class for the functor (say `CastOffPagesFunctor`)
2. Use the content of the param object (`CastOffPagesParams`) to define the member variables (`m_contentPage, m_doc, m_currentPage, …`)
3. Move the code of the functor implementation into the corresponding overridden interface methods (i.e. `System::CastOffPages` into `CastOffPagesFunctor::VisitPage`, `Score::CastOffPages` into `CastOffPagesFunctor::VisitScore`, etc.)
4. Clean up by removing the previous param object and functor implementation.

The visitor pattern consists of a virtual method `Object::Call(Functor *functor)` which is implemented by calling the corresponding visitor method in the object interface. For example, in the Measure class the call would be implemented as:
```cpp
Measure::Call(Functor *functor) override {
	functor->VisitMeasure(this);
}
```
This is called a dispatch method. Effectively, we create a second class hierarchy (one for elements and one for functors) and use the dispatch method to call virtual methods in one hierarchy from the other.

In my view, the biggest advantage of functor classes is that we would restructure the code in Verovio and create smaller classes which are more self-contained. Minor advantages include:
- We could merge functors and corresponding end functors into one class.
- Redirection of functors (i.e. to traverse the `ScoreDef`) would be simplified since functor classes naturally know the functor (via the `this` pointer)
An interesting application would be parallelisation of the layout.

### A glimpse towards parallelisation
Parallelising the layout is not straightforward, since most of the layout functors must be run in a fixed order. However, we have a lot of functors which could be evaluated in parallel on measures or systems. Examples are the search functors and all functors that only perform local changes like `CalcDots `or `AdjustSlurs`. That is, the calculation of dots can be done in parallel for measure 1, 2, 3, … and the slur adjustment can be done in parallel for system 1, 2, 3, … . To do this, the current functor object must be copied for each measure/system and passed into helper tasks (threads) which evaluate the functor. After all tasks have finished, the results must be combined (i.e. for search). The details are not important here, but the point is that the best place to implement this would be a base class Functor from which all functors derive. Something that only makes sense after switching to functor classes.

### Discussion
Switching to functor classes is a huge refactoring project that would take many months to complete. However, it could be done step by step turning functor by functor into classes. The question is whether this would be fine for everybody, since it would mean that for quite some time we would have to deal with a mixture of functors partially as classes and partially as virtual methods.

**Comment by lpugin** [comment]
Thank you for the proposal. I agree that reading and maintaining the functor codes is not great as it is because it is spread in multiple files. Here are a few points / questions that maybe you can clarify.

### File organization

How would you want to organize the files? If we have one per functor that would be a lot of them. If we group them or put them in existing classes we would not gain as much readability. Have you thought about it?

### Parent classes and interfaces

In many cases we call the parent class too. [This](https://github.com/rism-digital/verovio/blob/325028cd3758375e0165656c103e2bb8c9e8029e/src/artic.cpp#L522) is one example. That would need to work too, but I don't think it would be a problem.

We also [redirect](https://github.com/rism-digital/verovio/blob/f6a05665a25745ddafa58709734b4d7725213717/src/controlelement.cpp#L146-L159) to interfaces (pseudo) functors. You might want to look at this too, but I don't think there is anything very complicated there.

### Processing the functors

Would any thing need to be changed in `Object::Process`? If yes, how would it work and how would you incrementally make migrate the functors to classes. 

If not, the we can probably do it gradually as you suggest. We can have a branch dedicated to it and you could make one simple example to start with?

**Comment by DavidBauer1984** [comment]
Yes it's probably best to make a draft with a few functors to see how it all works out in code. 
Some thoughts regarding your points:
- We can probably put similar functors in one file (i.e. for search) as we do for elements. Merging functors with end functors into one class further reduces the amount of files.
- I have ideas regarding parent classes, but haven't thought about pseudo functors. Good point, I will have a look.
- The code itself that is executed in `Object::Process` will not change, but we will need to overload it such that the function can deal with the new functor objects.
