### ISSUE TITLE
Improve consistency between toolkits and core

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/verovio#3012]
Currently there are some methods that are not available in the JavaScript toolkit; for example `GetScale`, but are available in other toolkits (Python, C++).

We should try to improve the consistency between the toolkits so that most of the methods and options are available in all toolkits. (with some exceptions, like `SaveFile`, that wouldn't work in the JavaScript context). 

As part of this work, the options available from the `GetOptions` should be improved to allow getting additional state information from the Verovio toolkit, particularly the `scale` option. This was an older option that never got ported into the newer `Options` infrastructure.

**Comment by lpugin** [comment]
`scale` and `xmlIdSeed` are [now](https://github.com/rism-digital/verovio/commit/29ccdb588645e02b71da130d9c8da2e6cb5c8e89) available in `GetOptions`

**Comment by lpugin** [comment]
Some changes have been made to improve this. I will close the issue unless additional changes are desired.

## Documentation for method not available in the JS toolkit.

The methods not available in the JS toolkit belong now to the doxygen group `nojs`. See https://github.com/rism-digital/verovio/blob/4011ce1e56feeca6cc738a6ff58b58f6538fb63d/include/vrv/toolkit.h#L292

In the Verovio book, this triggers a warning in the method documentation section

![image](https://user-images.githubusercontent.com/689412/191263839-77747327-2d1c-499a-987f-a6da4f2f85d4.png)

(this will be visible only once we make the next release)

## Consistency for the method names

The JS toolkit used to have a helper method `renderData` not available in the original toolkit. This is now fixed and it is available everywhere.

https://github.com/rism-digital/verovio/commit/205fec96f0fd05dd7eeaeb6fd400be567f582c99

## Clean up

Additional clean up
* Removing a deprecated method https://github.com/rism-digital/verovio/commit/6d72cb06bd96493f63a4ab13e8f0740de62f3bb6
* Fix the documentation of some missing parameters
* Make changing font option consistent https://github.com/rism-digital/verovio/commit/898771f08be0675bd88d12be057ba09bfae09792
