### ISSUE TITLE
ToolKit.loadZipDataBuffer() stopped working: 'Module not defined'

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#3037]
Starting from release 3.11, the toolkit method `loadZipDataBuffer()` to load compressed musicXml files (.mxl) fails to work. The error message is `"Module is not defined."` This worked fine until including version 3.10 (as can be tested by dragging an .mxl file on https://mei-friend.mdw.ac.at/)

Please see below a command line example with a valid ArrayBuffer and a byteLength (and with the `inputFrom` option set to `xml`):

<img width="900" alt="grafik" src="https://user-images.githubusercontent.com/45632600/192733697-c2571b90-ae3b-47b8-b740-e0b88f3d9473.png">

Same situation with ToolKit 3.10 works just fine:

<img width="650" alt="Bildschirmfoto 2022-09-28 um 10 39 41" src="https://user-images.githubusercontent.com/45632600/192732037-4c356dfb-baaf-4a5a-96fb-c356a5e34966.png">

It seems that with the big changes for Version 3.11 this method broke (see #2937) as it still refers to a variable `Module` that apparently does not exist. @WolfgangDrescher, @rettinghaus, any ideas?

MXL test file: https://iwk.mdw.ac.at/goebl/mei/BeetAnGeSample.mxl

**Comment by lpugin** [comment]
It seems that the problem is with `https://www.verovio.org/javascript/latest/verovio-toolkit-hum.js`. It works fine for me with `https://www.verovio.org/javascript/latest/verovio-toolkit-wasm.js`. Could you confirm?

**Comment by WolfgangDrescher** [comment]
My first thought is that this probably has something to do with `verovio-toolkit-hum.js` because it is a synchronous build compared to the asynchronous `verovio-toolkit-wasm.js` file. I never used `loadZipDataBuffer` before. How can I test this? Do I need an ArrayBuffer for this in any case?

```js
import verovio from 'verovio';

document.addEventListener('DOMContentLoaded', (event) => {
    verovio.module.onRuntimeInitialized = () => {
        const tk = new verovio.toolkit();
        fetch('https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_4.0/Music/Encoding_alternatives/Mozart_Veilchen/Das_Veilchen_0Parameters.mei').then(response => {
            console.log({response});
            return response.arrayBuffer();
        }).then(arrayBuffer => {
            console.log({arrayBuffer});
            tk.loadZipDataBuffer(arrayBuffer, arrayBuffer.byteLength);
        }).catch(error => {
            console.error(error);
        });
    }
});
```

This throws an error for me.


<img width="276" alt="Bildschirmfoto 2022-09-28 um 11 39 22" src="https://user-images.githubusercontent.com/865594/192745861-b5cf6404-8c3f-4dd3-972b-3212d60faa62.png">

Also note that `verovio-toolkit-hum.js` is deprecated: https://github.com/rism-digital/verovio/discussions/2897. Probably its worth updating to the new setup syntax.

```js
import createVerovioModule from 'verovio/wasm'; // or verovio/wasm-hum
import { VerovioToolkit } from 'verovio/esm';
import fs from 'node:fs';

createVerovioModule().then(VerovioModule => {
   const verovioToolkit = new VerovioToolkit(VerovioModule);
   const score = fs.readFileSync('hello.mei').toString();
   verovioToolkit.loadData(score);
   const data = verovioToolkit.renderToSVG(1, {});
   console.log(data);
});
```

**Comment by lpugin** [comment]
Something went wrong when making the release. I will update `verovio-toolkit-hum.js`

**Comment by wergo** [comment]
> It seems that the problem is with `https://www.verovio.org/javascript/latest/verovio-toolkit-hum.js`. It works fine for me with `https://www.verovio.org/javascript/latest/verovio-toolkit-wasm.js`. Could you confirm?

I get the same error message in both toolkit releases (wasm and hum in version 3.11).

**Comment by lpugin** [comment]
Weird. This now works for me
```html
<div id="notation"></div>
<script src="https://www.verovio.org/javascript/latest/verovio-toolkit-hum.js"></script>
<script>
    const mxl =  'BeetAnGeSample.mxl';
    verovio.module.onRuntimeInitialized = function () {
        fetch(mxl).then(response => {
            return response.arrayBuffer();
        }).then(data => {
            const verovioToolkit = new verovio.toolkit();
            verovioToolkit.loadZipDataBuffer(data);
            console.log(verovioToolkit.getVersion());
            const svg = verovioToolkit.renderToSVG(1);
            document.getElementById('notation').innerHTML = svg;
        });
    }
</script>
```

**Comment by wergo** [comment]
This is really strange. Your example works on my machine as well. 

(using this filename: `const mxl =  'https://raw.githubusercontent.com/musicog/vrvtest/main/BeetAnGeSample.mxl';`)

**Comment by samuelbradshaw** [comment]
I'm using `loadZipDataBuffer()` to load MXL files with Verovio 3.11.0, without an issue. I'm not using wasm, though (if that makes a difference).

Live URL:
https://singpraises.net/collections/en/hymns/awake-and-arise?edition=2002&tab=sheet-music-interactive

Example code:
```
<script src="https://www.verovio.org/javascript/3.11.0/verovio-toolkit.js"></script>
<script>
  const mxlUrl = '/meta/cors-proxy/https://assets.ldscdn.org/c3/05/c305f13366d6fcf84d96535db011ca5ad3567c60/awake_and_arise.mxl';

  // Initialize Verovio
  var vrvToolkit = new verovio.toolkit();

  // Fetch the MusicXML file and kick off the initial rendering
  fetch(mxlUrl)
    .then(response => response.arrayBuffer())
    .then(data => {
    
      if (data instanceof ArrayBuffer) {
        // MXL (ArrayBuffer)
        vrvToolkit.loadZipDataBuffer(data);
      }
      
      // etc.
  })
</script>
```

**Comment by wergo** [comment]
I have debugged a little more and it seems that loading the toolkit from a web-worker is causing the problem.

Here: https://github.com/rism-digital/verovio/blob/5fc9e579f59c39644aedcdc8a05337d6019ef074/emscripten/npm/src/prebundle-module.js#L12-L14 the `DefaultVerovioModule` is exported to `window.Module`, which apparently is not happening when calling the toolkit from a web-worker (there is no window indeed). Thus, it does not have that variable Module that gets only called from `loadZipDataBuffer()`. 

So, I guess, renaming `Module` to `VerovioModule` or `DefaultVerovioModule` in https://github.com/rism-digital/verovio/blob/5fc9e579f59c39644aedcdc8a05337d6019ef074/emscripten/npm/src/verovio-toolkit.js#L115-L127

I will try it out, but it will take me some time...

**Comment by WolfgangDrescher** [comment]
Thank you for debugging. The Module is now stores in a class property of a Toolkit instance. Using `this.VerovioModule` there instead of `Module`. I will open a pull request.

**Comment by wergo** [comment]
Thanks a lot @WolfgangDrescher. 

Yes, I successfully tested it locally. `this.VerovioModule` three times replaced does the trick!
