### ISSUE TITLE
Option for controlling footer font size

### ISSUE THREAD

**Issue by abrink33** [rism-digital/verovio#3050]
**Is your feature request related to a problem? Please describe.**
Currently, we are adjusting the footer text font size by iterating through each element and setting the font-size.

**Describe the solution you'd like**
Being able to pass an option to control the font size of the footer text (similar to `--top-margin-pg-footer` but for font size in the `pgFoot`) would help produce the following more cleanly:

![image](https://user-images.githubusercontent.com/92746001/193618627-62de2d53-da8f-4ace-9e05-f84f704227ac.png)

**Comment by lpugin** [comment]
I am not sure I understand what is the problem with having the font size properly set in your data. This seems to be a workflow issue on your side.

I fear this is going to open many of option requests. Obviously people will want the same for the header, and the it will follow with header title, or header sub-title, etc. So unless we can find a generic way to implement this I don't think we should have it.

One workaround would be to add a css file / string that can be added by default to the SVG. However, that would not be taken into account during the layout calculation, so it is probably not satisfactory.

**Comment by samuelbradshaw** [comment]
When displaying sheet music on a webpage in my projects, I've found it easiest to only render the main body of the sheet music with Verovio, and add titles, subtitles, hymn numbers, credits, etc. above and below as HTML.

**Comment by lpugin** [comment]
Since this there is no clear need why this cannot be set in the data directly, and because the request is not generic enough, I am closing the issue.
