### ISSUE TITLE
Tiny errors in documentation

### ISSUE THREAD

**Issue by efreja** [rism-digital/verovio#3071]
Hello,

On page (https://book.verovio.org/toolkit-reference/input-formats.html#plaine-and-easie), some examples contain errors revealed probably from verovio 3.10.0 (PAE validations)

Here is the fix:

Beams and tuplets

@clef:G-2
@keysig:xFCGD
@timesig:3/8
@data:'6B/{8B+({6B''E'B})({AFD})/{6.E3G},8B-/({6'EGF})({FAG})({GEB})/4F6-

(revealing an error on the first bar)

Clef changes

@clef:F-4
@keysig:bB
@timesig:c
@data:,6{FA'CF}%G-2 {''6CEA'''C}%F-4 {,6FB'DF}%G-2 {''6DFA'''D}/

(only validation errors no display changes)

Ties

@clef:G-2
@keysig:xFCG
@timesig:3/8
@data:''8-{CD+}/{DC'B}/{xAB''F+}/{FED}/{CGB+}/{BAG+}/{GFE}/

(revealing a tie error between the anacrouse and the first bar)

Grace notes (acciaccaturas)

@clef:G-2
@keysig:bBE
@timesig:2/4
@data:''{8.F6D'8B}6-''F/{8.F6E8C}6-E/{8DC}{'8B''gC'gBgAgB''6FE}/2D

(revealing a grace note error on third bar)

Grace notes (appoggiaturas)

@clef:F-4
@keysig:xF
@timesig:c
@data:qq,3{DnF'D}r/2Fqq,3{DnF'D}r2Aqq3,{DF'D}r/1bB,qq3{EG'C}r/1A//

(revealing a missing accidental on 2nd bar)

Thanks

==Verovio version==
3.12.1

**Comment by lpugin** [comment]
Closed with https://github.com/rism-digital/verovio/commit/f9b95feda454e180f9ecf26ce261f17f7f5a55f0
