### ISSUE TITLE
Add signum congruentiae

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3075]
It would be useful to add signum congruentiae to the embedded font for SMuFL glyphs in text directions.   Here is an example showing the lack of the up/down variants of the s.c. when displaying as a `<symbol>`:

<img width="992" alt="Screen Shot 2022-10-12 at 3 52 38 PM" src="https://user-images.githubusercontent.com/3487289/195462376-72852cec-cfda-4d34-8e49-f9aa7ab05111.png">

The first measure shows a custos glyph as expected.  The second measure should have an s.c., and the third measure should have an inverted s.c. (which is typically used below the staff, similar to a fermata under the staff).

Examples of the s.c. up/down from the webpage   https://www.smufl.org/version/latest/range/medievalAndRenaissanceMiscellany:

<img width="613" alt="Screen Shot 2022-10-12 at 3 44 56 PM" src="https://user-images.githubusercontent.com/3487289/195461636-58622d8b-466c-4ff7-a028-add8c55d6977.png">

These symbols are commonly used in _formes fixes_, such as the [rondeau](https://en.wikipedia.org/wiki/Rondeau_(forme_fixe)) to mark the boundary between the A and B sections of the song (among other uses).

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
         </titleStmt>
         <pubStmt />
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application isodate="2022-10-12T15:52:30" version="3.13.0-dev-17b50cf">
               <name>Verovio</name>
               <p>Transcoded from Humdrum</p>
            </application>
         </appInfo>
      </encodingDesc>
      <workList>
         <work>
            <title />
         </work>
      </workList>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m1dix0qz">
            <score xml:id="sx0c1vf">
               <scoreDef xml:id="s1j35bvy">
                  <staffGrp xml:id="sjy66s7">
                     <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
                        <clef xml:id="c1f6soy" shape="G" line="2" />
                        <meterSig xml:id="metersig-L2F1" count="6" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-L1F1">
                  <measure xml:id="measure-L1" n="1">
                     <staff xml:id="staff-L1F1" n="1">
                        <layer xml:id="layer-L1F1N1" n="1">
                           <note xml:id="note-L6F1" dur="4" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L7F1" dur="4" oct="4" pname="d" accid.ges="n" />
                           <note xml:id="note-L8F1" dur="4" oct="4" pname="e" accid.ges="n" />
                           <note xml:id="note-L9F1" dur="4" oct="4" pname="f" accid.ges="n" />
                           <note xml:id="note-L10F1" dur="4" oct="4" pname="g" accid.ges="n" />
                           <note xml:id="note-L11F1" dur="4" oct="4" pname="a" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L4F1" place="above" staff="1" tstamp="1.000000">
                        <symbol xml:id="st7rrys" glyph.auth="smufl" glyph.name="mensuralCustosUp" />
                     </dir>
                     <dir xml:id="dir-L5F1" place="below" staff="1" tstamp="1.000000">
                        <rend xml:id="rm5fxhd" fontstyle="normal">mensuralCustosUp</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L12" n="2">
                     <staff xml:id="staff-L12F1N1" n="1">
                        <layer xml:id="layer-L12F1N1" n="1">
                           <note xml:id="note-L15F1" dur="4" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L16F1" dur="4" oct="4" pname="d" accid.ges="n" />
                           <note xml:id="note-L17F1" dur="4" oct="4" pname="e" accid.ges="n" />
                           <note xml:id="note-L18F1" dur="4" oct="4" pname="f" accid.ges="n" />
                           <note xml:id="note-L19F1" dur="4" oct="4" pname="g" accid.ges="n" />
                           <note xml:id="note-L20F1" dur="4" oct="4" pname="a" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L13F1" place="above" staff="1" tstamp="1.000000">
                        <symbol xml:id="s44ibas" glyph.auth="smufl" glyph.name="mensuralSignumUp" />
                     </dir>
                     <dir xml:id="dir-L14F1" place="below" staff="1" tstamp="1.000000">
                        <rend xml:id="r1g6yu9q" fontstyle="normal">mensuralSignumUp</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L21" n="2">
                     <staff xml:id="staff-L21F1N1" n="1">
                        <layer xml:id="layer-L21F1N1" n="1">
                           <note xml:id="note-L24F1" dur="4" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L25F1" dur="4" oct="4" pname="d" accid.ges="n" />
                           <note xml:id="note-L26F1" dur="4" oct="4" pname="e" accid.ges="n" />
                           <note xml:id="note-L27F1" dur="4" oct="4" pname="f" accid.ges="n" />
                           <note xml:id="note-L28F1" dur="4" oct="4" pname="g" accid.ges="n" />
                           <note xml:id="note-L29F1" dur="4" oct="4" pname="a" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L22F1" place="below" staff="1" tstamp="1.000000">
                        <symbol xml:id="scu74jk" glyph.auth="smufl" glyph.name="mensuralSignumDown" />
                     </dir>
                     <dir xml:id="dir-L23F1" place="above" staff="1" tstamp="1.000000">
                        <rend xml:id="r1d9khlj" fontstyle="normal">mensuralSignumDown</rend>
                     </dir>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by craigsapp** [comment]
Another possible solution would be for `<sc>` or `<signum>` to be implemented in MEI.   Signum congruentiae have a similar graphical syntax as `<fermata>`. (but they are not related to fermatas in terms of their semantics).

**Comment by ahankinson** [comment]
They are not fermata; they show voice entries for canons / rounds, among other things. 

https://en.wikipedia.org/wiki/Mensural_notation#Signum_congruentiae

**Comment by rettinghaus** [comment]
I know pretty well what _Signa congruentiae_ are. But they behave visually like a fermata. A `corona` is not completely identical to a fermata, also it is the same symbol. 
Trying to be semantically correct with a special element for every symbol that is out there seems pretty overkill.

**Comment by craigsapp** [comment]
> But why not use `<fermata glyph.name="mensuralSignumUp" />` ?

That would be good for the short term, but it has a different semantic meaning that a fermata (and better than my `<dir>` text idea).

A fermata (or often called a corona in mensural music) typically means to hold a note longer than the nominal duration of the note.  

S.c., have several uses: in canons, they are used to indicate when the second voice is supposed to enter (when the first voice arrives at the s.c.).   Most commonly as a separator between the A and B sections of _formes fixes_, and occasionally somewhat like rehearsal marks showing an alignment in the music that is otherwise hard to figure out without barlines and bar numbers.

Some related discussions in `music-encoding`:

https://github.com/music-encoding/music-encoding/issues/863
https://github.com/music-encoding/music-encoding/issues/520

I will close this issue and use the fermata method for now, but eventually it should be added as an element in MEI due to its very different semantic behavior as compared to a fermata.

> Feel free to add the needed symbols to Leipzig font. 😉

Meaning to add a PR to https://github.com/rism-digital/Leipzig?  Of course, but after instructions on how to convert to the various font formats is given in the readme (unless that is some automated Github services which I may have seen in the my emails this summer).   Also required is a tutorial for adding a glyph on that website (using fontforge I presume), and what SMuFL requirements are expected for font metrics, etc. (or a link in the readme to such a tutorial for adding a glyph to the Leipzig font).  

But I don't think that I need to add it to Leipzig?  It should be treated as an SVG glyph like most non-text content of the SVG, and in that case if Leipzig does not have the s.c., then it should fall back to the Bravura s.c.

**Comment by craigsapp** [comment]
> Trying to be semantically correct with a special element for every symbol that is out there seems pretty overkill.

Differentiating between coronae and fermatas would be overkill, but differentiating between fermatas and s.c. is not overkill.  Otherwise, why not just encode music using SCORE which focuses on graphical syntax over semantic meaning?

**Comment by ahankinson** [comment]
> Trying to be semantically correct with a special element for every symbol that is out there seems pretty overkill.

That's MEI. :-D

More seriously, though, this is why generic elements like `<dir>` exist, so that we can catch symbols for which we don't want to necessarily add semantics. This would be better than overloading an element with entirely different semantics simply because it rendered correctly.

**Comment by rettinghaus** [comment]
@craigsapp Without changing Leipzig at least you need to activate the needed glyphs in `supported.xml` in the fonts directory and re-generate the fonts.

**Comment by craigsapp** [comment]
> @craigsapp Without changing Leipzig at least you need to activate the needed glyphs in supported.xml in the fonts directory and re-generate the fonts.

Thanks!

**Comment by craigsapp** [comment]
> More seriously, though, this is why generic elements like <dir> exist, so that we can catch symbols for which we don't want to necessarily add semantics. This would be better than overloading an element with entirely different semantics simply because it rendered correctly.

There is a general problem with using s.c. and other uncommon symbols in`<dir>`, which is related to this discussion:
      https://github.com/rism-digital/verovio/discussions/3084
The problem is that `<dir>` will presumably treat its contents as text (with embedded musical fonts).   There is no font fallback implemented for missing glyphs (and doing it properly would require generating a TTF font on the fly).  

I don't think all glyphs are included in the SVG embedded fonts as well? (even for Bravura), but just commonly desired ones to minimize the size of the embedded font (I have not checked if this is true yet).

**Comment by ahankinson** [comment]
The README in the fonts directory should help you get started. The only Python dependency is `svgpathtools`; you can use Poetry if you want and it will set up and manage a virtual environment, or just "pip3 install svgpathtools". Be aware that svgpathtools also requires numpy, which requires BLAS/LAPACK, which can be a pain. I searched for a while to get something similar but lighter to replace it, but no luck. (`svgpathtools` is only used to calculate bounding boxes, but the SVG math is fairly complex, and the functionality not well isolated in the code, so it wasn't practical to replace it or just copy the desired function).

You will also need fontforge. Be aware that there is a bug with the current homebrew version of fontforge. I've been trying to get it fixed but... well, open source is fun. 

See: https://github.com/Homebrew/homebrew-core/pull/111520
Also: https://github.com/fontforge/fontforge/issues/5111

You can fix it by doing `brew edit fontforge` and then adding a `depends_on woff2` line. 

Note that homebrew has two versions of FF -- you want the homebrew-core one. If you don't see a `depends_on` list, you're looking at the wrong one.

> I don't think all glyphs are included in the SVG embedded fonts as well? (even for Bravura), but just commonly desired ones to minimize the size of the embedded font (I have not checked if this is true yet).

The list of glyphs included are those listed in the supported.xml file. If it's commented out, it's not included.

**Comment by craigsapp** [comment]
Are you going to put that in the Verovio book: https://book.verovio.org?  And then a link in the Leipzig font to that chapter? 😉

**Comment by ahankinson** [comment]
Nah. I like seeing people struggle with this stuff. 

(Of course we will. It's just a question of time and demand.)

**Comment by craigsapp** [comment]
😜

**Comment by ahankinson** [comment]
FYI: Fontforge in Homebrew is now fixed with the new WOFF2 support, so you no longer have to adjust the Homebrew installation.
