### ISSUE TITLE
Latest NPM releases both include version 3.11.0 code

### ISSUE THREAD

**Issue by bbloomf** [rism-digital/verovio#3092]
**Describe the problem**
NPM release v3.12.0 and v3.12.1 include the same code as NPM release v3.11.0

**To Reproduce**
```
npm i verovio@3.12.1
node -e 'const v=require("verovio"); v.module.onRuntimeInitialized = () => {const tk = new v.toolkit(); console.info(tk.getVersion());}'
```
or
```
node -e 'const createVerovioModule=require("verovio/wasm");
const { VerovioToolkit } = require("verovio/esm");
createVerovioModule().then(module => console.info(new VerovioToolkit(module).getVersion()));'
```

Both return `3.11.0-e2d6db8` as the version number

**Expected behavior**
version number should be `3.12.1-30d149fd`

**Comment by lpugin** [comment]
Something went wrong went making the release. I rebuild it and publish it. The NPM package version number for 3.12.1 is 3.12.1-1 (see https://www.npmjs.com/package/verovio) so I think you will need to do
```bash
npm i verovio@3.12.1-1
```

**Comment by lpugin** [comment]
I now tagged `3.12.1-1` as the latest, so
```bash
npm i verovio
```
will install it.
