### ISSUE TITLE
Display analytical numbers for scale degree of bass notes

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#3101]
Is it currently possible to display an analytical row with the scale degree of the bass notes below the bass line or lowest staff?

Typically we write scale degrees below the bass staff with a circle around the numbers to distinguish them from figured bass numbers.

![Zirkel-Uebung_Oktavregel_5-6-7-1](https://user-images.githubusercontent.com/865594/200270063-d03f4e2c-a0ee-43fb-aecd-6a1472dbec91.png)

In older sources like *Förster: Practische Beyspiele* they are displayed without a circle.

<img width="1355" alt="Bildschirm­foto 2022-11-07 um 09 48 42" src="https://user-images.githubusercontent.com/865594/200274853-c84e3d73-4c9b-4f8b-b810-7d4819bdbd30.png">

Ideally it should be possible to display multiple lines of scale degrees at the same time.

![Zirkel-Uebung_Oktavregel_4_3_2_1_Parallelbewegung](https://user-images.githubusercontent.com/865594/200280151-8bccf4b4-c9f4-41cc-a9be-9ec21ad333a0.png)

Note that the scale degree changes when the music modulates into another key.

If I understand the MEI documentation correctly this should be possible with the `@deg` attribute: https://music-encoding.org/guidelines/v4/content/analysisharm.html#analysisScaleDegrees.

I saw that @craigsapp was doing something similar, but in another context in https://github.com/rism-digital/verovio/issues/388. Could or should the `<harm> ` tag be used for this?

Is there a way to use an analytical scale degree within humdrum? If I understand the humdrum documentation (https://www.humdrum.org/rep/deg/index.html) correctly the *exclusive interpretation record* `**deg` is an alternative to `**kern` to write music and should not be used to annotate existing `**kern` spines with their corresponding scale degree. Is this correct or is there another way to do this in humdrum?

**Comment by lpugin** [comment]
The harm tag look good to me. You can have them represented like this

![image](https://user-images.githubusercontent.com/689412/208444439-8e81ce71-7aeb-450f-b7bf-1fff3f1381c0.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Harmony indications</title>
         </titleStmt>
         <pubStmt>
            <date>2017-05-09</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application version="3.14.0" label="2">
               <name>Verovio</name>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp symbol="bracket">
                     <staffDef n="1" lines="5" clef.shape="G" clef.line="2" />
                     <staffDef n="2" lines="5" clef.shape="F" clef.line="4" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <rest dur="4" />
                           <note dur="4" oct="5" pname="e" />
                           <note dur="4" oct="5" pname="d" />
                           <note dur="4" oct="5" pname="c" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <rest dur="4" />
                           <note dur="4" oct="4" pname="c" />
                           <note dur="4" oct="3" pname="b" />
                           <note dur="4" oct="3" pname="a" />
                        </layer>
                     </staff>
                     <harm n="1" place="below" staff="2" tstamp="2.000000">
                        <rend rend="circle">4</rend>
                     </harm>
                     <harm n="2" place="below" staff="2" tstamp="2.000000">
                        <rend rend="circle">3</rend>
                     </harm>
                     <harm n="1" place="below" staff="2" tstamp="3.000000">
                        <rend rend="circle">2</rend>
                     </harm>
                     <harm n="2" place="below" staff="2" tstamp="3.000000">
                        <rend rend="circle">1</rend>
                     </harm>
                     <harm n="1" place="below" staff="2" tstamp="4.000000">
                        <rend rend="circle">7</rend>
                     </harm>
                     <harm n="2" place="below" staff="2" tstamp="4.000000">
                        <rend rend="circle">2</rend>
                     </harm>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>

```

Re-open if necessary

**Comment by WolfgangDrescher** [comment]
Perfect, thank you for this example @lpugin! Would something like this also be possible?

![IMG_4081](https://user-images.githubusercontent.com/865594/208479584-64fb3f3c-514f-4e1e-915d-a52c3121888e.jpg)

Just an additional label with the key in front of the scale degree numbers. NB: they are not bound to a note but to a circled scale degree with a small margin. The scale degree number should ideally stay under the corresponding notes and the additional label should be on the left of it.

**Comment by WolfgangDrescher** [comment]
Just for reference: I started https://github.com/rism-digital/verovio/discussions/3166 with a discussion about the humdrum implementation for this feature.

**Comment by craigsapp** [comment]
> The harm tag look good to me. You can have them represented like this

A problem with using `<harm>`  is that `harm@label` and `harm@labelAbbr` are not available to display a key prefix as in the example:

![IMG_4081](https://user-images.githubusercontent.com/865594/208479584-64fb3f3c-514f-4e1e-915d-a52c3121888e.jpg)

This would be good to add to MEI/verovio (MEI allows `<label>` as a child of `<harm>`, but the documentation treats it differently than the use of `<label>` in verses:

https://music-encoding.org/guidelines/dev/elements/harm.html

where it says that `harm@label` should not be used for document content and is useful for creating "tool tips" (i.e., maps to `@title` in SVG content).

>  I saw that `@craigsapp` was doing something similar, but in another context in https://github.com/rism-digital/verovio/issues/388. Could or should the `<harm>`  tag be used for this?

See discussion in https://github.com/rism-digital/verovio/discussions/3166#discussioncomment-4452490.  Using `<harm>` is OK, but there are two problems compared to using `<verse>` at the moment: (1) is the lack of `<label>` and `<labelAbbr>` that behave as they do in `<verse>`.   (2) There is a display bug in verovio where the alignment of the `<harm>` content is not always consistent (this could be fixed).

In my example in the discussions, I am mapping to `@n=2` and `@n=3`:

```xml
       <harm xml:id="harm-L3F2" place="below" staff="1" tstamp="1.000000" n="2">i</harm>
       <harm xml:id="harm-L3F3" place="below" staff="1" tstamp="1.000000" n="3">I</harm>
       <harm xml:id="harm-L4F3" place="below" staff="1" tstamp="1.500000" n="3">II</harm>
       <harm xml:id="harm-L5F2" place="below" staff="1" tstamp="2.000000" n="2">iii</harm>
       <harm xml:id="harm-L5F3" place="below" staff="1" tstamp="2.000000" n="3">III</harm>
```

which may be manifesting the alignment problem in verovio (but I have not checked).  I was probably mapping to  2 & 3 to give more space between the notes and the harmony symbols.
