### ISSUE TITLE
Option "encoded breaks" stopped working in version 3.6.0

### ISSUE THREAD

**Issue by gribjo** [rism-digital/verovio#3111]
Using option "breaks: 'encoded'" toolkit delivers incomplete svg data.

tested in Mac Safari 16.1 with verovio-toolkit.js up to version 3.12.1

**Comment by lpugin** [comment]
I could not really detect a regression from 3.6.0. Please give some example MEI data that produces incomplete data SVG.

(I have noticed that some people use files where there is an `<sb/>` followed directly by an `<pb/>`. This does not make much sense, but is does cause Verovio to ignore the `<pb/>`. Could you double check if this is your issue?)

**Comment by gribjo** [comment]
You are right. There are such tags "<sb/><pb/>", coming from an earlier verovio version XML->mei conversion.
In this point conversion with latest verovio delivers correct output.
But this didn't cause the problem.

Rendered from XML by the same old verovio version there were double <pb> tags.
I cut them out. Now version 12.3 can break lines as encoded.
Thank you.
