### ISSUE TITLE
Humdrum parse of "''" for "`" (staccatissimo) is coming up with staccato instead

### ISSUE THREAD

**Issue by gregchapman-dev** [rism-digital/verovio#3116]
**Describe the problem**
The following lines of code in iohumdrum.cpp:
```
        else if ((ch == '\'') && (posch == '\'')) {
            // staccatissimo alternate (eventually remove)
            ch = '`';
            posch = i < tsize - 2 ? nohidden.at(i + 2) : 'g';
            i++;
        }
```
should be:
```
        else if ((ch == '\'') && (posch == '\'')) {
            // staccatissimo alternate (eventually remove)
            ch = '`';
            intch = (unsigned char)ch; // This is the added line that fixes the bug
            posch = i < tsize - 2 ? nohidden.at(i + 2) : 'g';
            i++;
        }
```

**Comment by gregchapman-dev** [comment]
There's a fix for this in PR #3150.

**Comment by craigsapp** [comment]
For issues/PRs that fix things, it would be useful to give a minimal example that demonstrates the problem (and the fix after applying the PR).   This is particularly useful for regressions.

Here is the test for this issue:

```tsv
**kern
4c'
4d'
4e'
4f'
=
! Wrong way of doing staccatissimos (but keep for backwards compatibility with some older files):
4c''
4d''
4e''
4f''
=
! Correct way of doing staccatissimos:
4c`
4d`
4e`
4f`
=
*-
```

Rendering before fix:

<img width="656" alt="Screen Shot 2022-12-06 at 2 26 33 PM" src="https://user-images.githubusercontent.com/3487289/206037452-e7c4e73a-31bb-4385-a488-def5f76053e4.png">

**Comment by craigsapp** [comment]
PR #3150 renders the alternate staccatissimos as expected now:

<img width="1021" alt="Screen Shot 2022-12-06 at 6 04 41 PM" src="https://user-images.githubusercontent.com/3487289/206069914-073b3e56-219a-4d13-bfb6-5deda59c0631.png">
