### ISSUE TITLE
`buildToolkit` fails with emscripten v3.1.25 due to `TOTAL_STACK` in strict mode

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#3120]
If I run `./buildToolkit -c -w -M -H` with the lastest emscripten version 3.1.25 the build fails.

```
em++: error: legacy setting used in strict mode: TOTAL_STACK
 Failed.
```

**To Reproduce**

1. update to the lastest emscripten following the docs: https://emscripten.org/docs/getting_started/downloads.html
2. `cd emscripten`
3. `./buildToolkit -c -w -M -H`

**Additional context**

In the changelog they wrote that the `TOTAL_STACK` setting was renamed to `STACK_SIZE`: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3125---110822. They also write that "the old name will continue to work as an alias". I'm not sure why the alias `TOTAL_STACK` will fail in strice mode but `STACK_SIZE` doesn't.

Renaming this in `./buildToolkit` seems to fix this. I can open a small PR if wanted. However, the GitHub actions don't seem to fail even though `EM_VERSION` is set to `latest` (https://github.com/rism-digital/verovio/blob/develop/.github/workflows/ci_build.yml#L45). So I'm not sure if this is even problematic right now.

**Comment by lpugin** [comment]
It was changed already https://github.com/rism-digital/verovio/commit/71c782770198b3fd1ecfe176c37ae4f88e717252
Have you pulled it?

**Comment by WolfgangDrescher** [comment]
I pulled on Nov 12. So I missed this commit.

**Comment by sonovice** [comment]
I get a similar error now:
```
Linking...
/usr/bin/em++ -v libverovio.a  -s WASM=1 -s INITIAL_MEMORY=512MB -s STACK_SIZE=256MB -s SINGLE_FILE=1 -O3 -DNDEBUG -std=c++17 -s STRICT=1 --embed-file data/ -s EXPORTED_FUNCTIONS="['_enableLog','_enableLogToBuffer','_vrvToolkit_constructor','_vrvToolkit_destructor','_vrvToolkit_edit','_vrvToolkit_editInfo','_vrvToolkit_getAvailableOptions','_vrvToolkit_getDefaultOptions','_vrvToolkit_getDescriptiveFeatures','_vrvToolkit_getElementAttr','_vrvToolkit_getElementsAtTime','_vrvToolkit_getExpansionIdsForElement','_vrvToolkit_getHumdrum','_vrvToolkit_convertHumdrumToHumdrum','_vrvToolkit_convertHumdrumToMIDI','_vrvToolkit_convertMEIToHumdrum','_vrvToolkit_getLog','_vrvToolkit_getMEI','_vrvToolkit_getMIDIValuesForElement','_vrvToolkit_getNotatedIdForElement','_vrvToolkit_getOptions','_vrvToolkit_getPageCount','_vrvToolkit_getPageWithElement','_vrvToolkit_getTimeForElement','_vrvToolkit_getTimesForElement','_vrvToolkit_getVersion','_vrvToolkit_loadData','_vrvToolkit_loadZipDataBase64','_vrvToolkit_loadZipDataBuffer','_vrvToolkit_redoLayout','_vrvToolkit_redoPagePitchPosLayout','_vrvToolkit_renderData','_vrvToolkit_renderToMIDI','_vrvToolkit_renderToPAE','_vrvToolkit_renderToSVG','_vrvToolkit_renderToTimemap','_vrvToolkit_resetOptions','_vrvToolkit_resetXmlIdSeed','_vrvToolkit_select','_vrvToolkit_setOptions','_vrvToolkit_validatePAE','_malloc','_free']" -s EXPORTED_RUNTIME_METHODS='["cwrap"]' -o build/verovio.js 
em++: error: Attempt to set a non-existent setting: 'STACK_SIZE'
 - did you mean one of STACK_BASE, ASYNCIFY_STACK_SIZE, STACK_MAX?
 - perhaps a typo in emcc's  -s X=Y  notation?
 - (see src/settings.js for valid values)
 Failed.
 ```

Repo is freshly cloned. Compilation runs under linux x64 Kernel 6.0.6.

**Comment by WolfgangDrescher** [comment]
What version of em++ do you have installed when running`em++ -v`? Make sure that it is version 3.1.25 or newer.

**Comment by sonovice** [comment]
> What version of em++ do you have installed when running`em++ -v`? Make sure that it is version 3.1.25 or newer.

Thanks! :+1:
