### ISSUE TITLE
keySig without keySig

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3128]
Currently Verovio calls `AlignHorizontally` for a key signature although no `keySig` is present, resulting in some unwanted extra horizontal space. 

Render this example with and without the commented line and see the difference. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>No key signature</title>
         </titleStmt>
         <pubStmt>
         </pubStmt>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef n="1" lines="5">
                        <!--<keySig sig="0" visible="false" />-->
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure type="m--1">
                     <staff n="1">
                        <layer n="1">
                           <rest dur="2" />
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by lpugin** [comment]
Could you be a bit more explicit about
> Verovio calls `AlignHorizontally` for a key signature although no `keySig` is present

? Thanks

**Comment by rettinghaus** [comment]
Sure. The upper rendering has an invisible keySig, the lower one none at all. But in the lower one there is some space reserved for the non-existing keySig and the rest moved further to the right.
 
![invKeySig](https://user-images.githubusercontent.com/7693447/202731795-30969bb8-241e-4c59-9082-495f2cc85dd3.png)
![noKeySig](https://user-images.githubusercontent.com/7693447/202731798-82fbe800-0ef5-4694-81a7-a64f9b4d26a0.png)

**Comment by rettinghaus** [comment]
It's happening here:

https://github.com/rism-digital/verovio/blob/3b32826d1c90486efd4fa5c3ffed33c719f13612/src/layer.cpp#L700-L704

**Comment by lpugin** [comment]
Thanks. Where is the call to `AlignHorizontally` for the key signature that do not exist? I can look for it, but since you already dug in the code it would be save me time if you tell me this
