### ISSUE TITLE
Integration in Wix Website

### ISSUE THREAD

**Issue by GimmeSomeJazz** [rism-digital/verovio#3143]
**Describe the problem**
Cannot succeed to integrate Verovio in Wix

**To Reproduce**
1. Copy/past the verovio-toolkit-wasm.js file in my "Public files", 
2. Add this snippet of code
`import verovio from 'public/verovio-toolkit-wasm.js';
console.log("tutu")`

**Expected behavior**
Should see "tutu" in the console.
Things are ok when removing the import

**Verovio information**
Last release of Verovio

Thank you all for this amazing work!!!!

**Comment by ahankinson** [comment]
Do you see “tutu” if you **don’t** try and integrate Verovio? We’ll need a lot more information to effectively help you.

Did your browser download the toolkit? (Check the “network” tab of your developer console). What does your HTML look like?

Feel free to jump on the Verovio slack channel for help, as it sounds like this is an application problem and not an actual issue with Verovio.

**Comment by GimmeSomeJazz** [comment]
> We’ll need a lot more information to effectively help you.
> 
> Did your browser download the toolkit? (Check the “network” tab of your developer console). What does your HTML look like?
> 
> Feel free to jump on the Verovio slack channel for help, as it sounds like this is an application problem and not an actual issue with Verovio.

thank you @ahankinson! I go into Slack
