### ISSUE TITLE
Handle Python path objects

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3158]
Instead of having filenames and paths as string in Python it is more common to handle these as path objects. Currently Verovio only handles strings, so one has to cast the path object to string. 

It would be good if Verovio could accept path objects (and simply casts them to strings):

```python
from pathlib import Path
import verovio

file = Path("path-to-mei-file")
tk = verovio.toolkit()
tk.loadFile(file)
```

**Comment by lpugin** [comment]
From the experience we have with the json conversion in the Python binding, there is an overhead when adjusting the binding and I think we should modify it as little as possible. So I am not convinced this would make a big difference for the user, at least not big enough to justify the hurdles.
