### ISSUE TITLE
Get note alterations in SVG using svgAdditionalAttribute

### ISSUE THREAD

**Issue by vitto32** [rism-digital/verovio#3163]
I use `svgAdditionalAttribute` with `not@oct `and `note@pname` but I can't find a way to get accidentals data. I've tried: 
`note@accid`
`note@accid.ges`
`accid@ges`
but none of those produces an output in the svg.
I've tried both on note accidentals and key accid.

**Comment by lpugin** [comment]
I am sorry but your problem is not very clear. It would be helpful to have a bit more context and some information about your data.

If I understand correctly, you want to have the `@accid` and `@accid.ges` values in the SVG. You need to  set both `--svg-additonal-attribute accid@accid` and `--svg-additonal-attribute accid@accid.ges`.

**Comment by vitto32** [comment]
I'm sorry, I'll try to elaborate it from scratch.

I want to display notes name (A#, Cbb, ..) when the user hovers or clicks them.
Is there a direct way to get that info from Verovio?

PS: I can get the info combining `data-*` (or `getElementAttr`) and `getMIDIValuesForElement `, but maybe there is a more straightforward way.

**Comment by rettinghaus** [comment]
This is not possible. I would use a little XSLT that takes the information and writes it into the `label` attribute of each note. Then you'll get it directly when hovering over a note.

**Comment by lpugin** [comment]
Using `data-*` and the methods for retrieving information about the note element is as straight forward as it can get with Verovio. Pre-processing your data can make it a bit simpler as @rettinghaus suggested.

**Comment by vitto32** [comment]
XSLT was my first choice but doesn't work with transposition.
I'll stick with the attr + MIDI approach.
Thanks both!
