### ISSUE TITLE
Problem with measure rests when importing musicxml 

### ISSUE THREAD

**Issue by Duanle** [rism-digital/verovio#3171]
**Describe the problem**
1.The tick calculation is incorrect
The tick duration in midi is also wrong（4/4 beats）
![WX20221221-020613@2x](https://user-images.githubusercontent.com/6520982/208745404-01adbb88-aaa8-4d65-81de-7bff66c2e888.png)

**Input data musicxml**

[That's me.txt](https://github.com/rism-digital/verovio/files/10271779/That.s.me.txt)

2.When midi plays to the box, it will pause for a while, but there is no similar mark on the score, and the time of each bar is filled with the time value of the note.And one section hasn't been rendered（6/8 beats）
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/6520982/208750893-f418596b-45aa-43ea-8000-fec7822eceb8.png">
input data musicxml
[tears.txt](https://github.com/rism-digital/verovio/files/10271883/tears.txt)

**Verovio information**
 - Version of Verovio [e.g. develop, commite - 920f37653 ]

**Environment information (as appropriate)**
 - OS: [e.g. MacOS, Android]
 - Browser [e.g. Chrome, Safari]

**Comment by lpugin** [comment]
It seems to be a problem when importing the musicxml. It yields rests instead of measure rests. Where did you get the musicxml from?

**Comment by Duanle** [comment]
> It seems to be a problem when importing the musicxml. It yields rests instead of measure rests. Where did you get the musicxml from?


Provided by the Employer，musicxml is placed under the picture in txt format 
I open it with musesocre, the display and playback are correct

> It seems to be a problem when importing the musicxml. It yields rests instead of measure rests. Where did you get the musicxml from?

> It seems to be a problem when importing the musicxml. It yields rests instead of measure rests. Where did you get the musicxml from?


Provided by the Employer，musicxml is placed under the picture in txt format 
I open it with musesocre, the display and playback are correct
