### ISSUE TITLE
Stem direction for maxima 

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#3193]
If a stem direction is not explicitly specified with `@stem.dir`, the stem for maxima will always be `down`:
<img width="366" alt="Bildschirm­foto 2023-01-08 um 21 29 59" src="https://user-images.githubusercontent.com/865594/211217587-027b5550-ce6b-44ce-b4c6-ebc826bd432d.png">

But when the stem is not explicitly specified I would expect that the stem of the maximae would go up when the note head is below the 3rd staff line. Compare with the longas on the left side of the example where in the lowest staff the stem is pointing up.

<details>
  <summary>Click to show kern</summary>

```tsv
**kern	**kern	**kern
*clefG2	*clefG2	*clefG2
*M2/1	*M2/1	*M2/1
0gl	0bl	0ddl
=	=	=
0gll	0bll	0ddll
==	==	==
*-	*-	*-
!!!RDF**kern: l = terminal long
```
</details>

<details>
  <summary>Click to show MEI</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-01-08T21:21:17" version="3.15.0-dev-0b53372">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="8" token="!!!RDF**kern: l = terminal long" xml:id="L9">
     <frameInfo>
      <startTime float="16" />
      <frameType>reference</frameType>
      <referenceKey>RDF**kern</referenceKey>
      <referenceValue>l = terminal long</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1665edy">
    <score xml:id="s1r1hl6x">
     <scoreDef xml:id="s1w41fed" midi.bpm="400.000000">
      <staffGrp xml:id="s1tfv93r" symbol="bracket">
       <staffDef xml:id="staffdef-L1F3" n="1" lines="5">
        <clef xml:id="clef-L2F3" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F3" count="2" unit="1" />
       </staffDef>
       <staffDef xml:id="staffdef-L1F2" n="2" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F2" count="2" unit="1" />
       </staffDef>
       <staffDef xml:id="staffdef-L1F1" n="3" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F1" count="2" unit="1" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-L1F3" n="1">
        <layer xml:id="layer-L1F3N1" n="1">
         <note xml:id="note-L4F3" dur.ges="breve" dur="long" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L1F2" n="2">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L4F2" dur.ges="breve" dur="long" oct="4" pname="b" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L1F1" n="3">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur.ges="breve" dur="long" oct="4" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L5" right="end">
       <staff xml:id="staff-L5F3N1" n="1">
        <layer xml:id="layer-L5F3N1" n="1">
         <note xml:id="note-L6F3" dur.ges="breve" dur="maxima" oct="5" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L5F2N1" n="2">
        <layer xml:id="layer-L5F2N1" n="1">
         <note xml:id="note-L6F2" dur.ges="breve" dur="maxima" oct="4" pname="b" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L5F1N1" n="3">
        <layer xml:id="layer-L5F1N1" n="1">
         <note xml:id="note-L6F1" dur.ges="breve" dur="maxima" oct="4" pname="g" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```
</details>

I tried to fix this but `View::DrawMensuralStem` does not get called. Note that when I force the stem direction with `stem.dir="up"` the stem is shown correctly but an additional line appears. When debugging this I noticed that with `@stem.dir` the `View::DrawMensuralStem` will get called.

<img width="362" alt="Bildschirm­foto 2023-01-08 um 21 35 44" src="https://user-images.githubusercontent.com/865594/211217820-08a0249a-9f84-4e7d-b722-856cbb360316.png">

Probably this should be an easy fix but since I'm new to the C++ code base of verovio and I could not figure things out. If I get some help I can hopefully do a PR.

Also I don't understand why `View::DrawMensuralNote` gets called 21 times for the example above when only 6 notes are displayed. Does Verovio render the data multiple times to improve the layout from iteration to iteration similar to LaTeX?

I saw that https://github.com/rism-digital/verovio/issues/542 should fix this. But since this is from 6 years ago, maybe something broke in the meantime. https://github.com/rism-digital/verovio/pull/1427 is related but seems to work only for longa. https://github.com/rism-digital/verovio/issues/1511 is also kind of related but another use case.

**Comment by rettinghaus** [comment]
This most likely can be traced back to #3008. #3194 should fix this.

**Comment by WolfgangDrescher** [comment]
Thank you for the fast answer. I tested your PR and it fixes the additional stem from my second screenshot. However, the stem direction of the 3rd staff, last note (`g`) is still pointing down but it should go up if it is not specified.

<img width="367" alt="Bildschirm­foto 2023-01-08 um 22 37 35" src="https://user-images.githubusercontent.com/865594/211220400-cf09a978-0fbc-4480-a39c-a4c3318b4a3c.png">

**Comment by rettinghaus** [comment]
Maxima notes are supposed to be mensural only and thus don't have a calculated stem direction. Changing this would mean a bigger restructuring.

**Comment by WolfgangDrescher** [comment]
I see. Does this mean, that longa notes are not mensural only and can also be used withing CMN and thus they have a calculated stem direction? Do you think it is worth to dive into this or is automatic stem direction not intended for mensural notes?

**Comment by craigsapp** [comment]
Are maximas illegal in MEI-CMN?  Verovio does allow it as shown in the above example (second two notes in this example):

<img width="338" alt="Screenshot 2023-01-09 at 11 37 12 PM" src="https://user-images.githubusercontent.com/3487289/211490127-200ad34e-1718-40ec-a800-0ff64939987c.png">

<details>
<summary> Click to view MEI data for the above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-01-09T23:39:33" version="3.15.0-dev-b9cceb1c5">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml">
    <metaFrame n="8" token="!!!verovio: spacingLinear 0.1" xml:id="L9">
     <frameInfo>
      <startTime float="96" />
      <frameType>reference</frameType>
      <referenceKey>verovio</referenceKey>
      <referenceValue>spacingLinear 0.1</referenceValue>
     </frameInfo>
    </metaFrame>
    <metaFrame n="9" token="!!!verovio: spacingNonLinear 0.5" xml:id="L10">
     <frameInfo>
      <startTime float="96" />
      <frameType>reference</frameType>
      <referenceKey>verovio</referenceKey>
      <referenceValue>spacingNonLinear 0.5</referenceValue>
     </frameInfo>
    </metaFrame>
   </frames>
  </extMeta>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="myqx3b7">
    <score xml:id="s5m1esa">
     <scoreDef xml:id="s1jc40up" midi.bpm="400.000000">
      <staffGrp xml:id="s10jswrx">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="c11smdlg" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dur="long" oct="4" pname="e" accid.ges="n" />
         <note xml:id="note-L4F1" dur="long" oct="5" pname="f" accid.ges="n" />
         <note xml:id="note-L5F1" dur="maxima" oct="4" pname="e" accid.ges="n" />
         <note xml:id="note-L6F1" dur="maxima" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

Also, if the maxima is at the end of the score, it is probably a stylized long instead (most scores in the Renaissance end in a long and not a maxima).

It would be useful to allow in CMN for modern editions of mensural music in CMN notation where the rhythms are not reduced.  They are very rare in JRP (late medieval) and Tasso (late Renaissance) projects music, and are usually converted to a series of tied notes (each tied note being one mensural cycle of the meter (so usually breves, but sometimes longs).  The exception would be if all parts all have maximas at the same time.

**Comment by lpugin** [comment]
> Are maximas illegal in MEI-CMN? 

Yes, there are illegal. The file you submitted is valid because is uses the `mei-all.rng`. If you change to `mei-CMN.rng` you will see this:

```
Schema: https://music-encoding.org/schema/dev/mei-CMN.rng
Engine name: Jing
Severity: error
Problem ID: invalid_attribute_value
Description: value of attribute "dur" is invalid; must be equal to "1", "1024", "128", "16", "2", "2048", "256", "32", "4", "512", "64", "8", "breve" or "long"
```

Verovio is not particularly picky about mixed mensural and CMN. It relies essentially on `staffdef@notationtype`.

If `maxima` is added to CMN, then we probably need to have another name that distinguishes it from the mensural `maxima` – in the same way we have `breve` / `brevis` and `long` / `longa`. This is obviously an MEI question.
