### ISSUE TITLE
--even-note-spacing option description

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3237]
The `--even-note-spacing` option when listing options information on the command-line  is vague and not useful:

```
 --even-note-spacing            Specify the linear spacing factor
```

Technically it is an option that sets  `--spacingLinear 0` (and perhaps by accident `--spacingNonLinear 0`).   "Specify the linear spacing factor" is probably taken accidentally from `--spacingLinear` option.

I don't find `--even-note-spacing` to be overly useful, and if I need it for mensural music display, I instead use `--spacing-linear 0.3` and `--spacing-non-linear 0` (because a spacing of spacingLinear=0 is often to tight of a display).

Perhaps change the meaning of `--even-note-spacing`?  Such as it should be a shortcut for manipulating the two parameters: `--spacingNonLinear 0`, which is the real way of creating even-note-spacing, and then allow a parameter which is the `--spacing-linear` parameters. 

Then `--even-note-spacing 0` would be the current behavior, and `--even-note-spacing 0.5` would be equivalent to changing two parameters at once:   `--spacingLinear 0.5 --spacingNonLinear 0`.

In that case the description could be:

```
 --even-note-spacing <f>           Equally space notes with the given linear spacing factor (default: 0.25; min: 0.00; max: 1.00)
```

Or another possibility to aovid confusion is to (gradually) retire `--even-note-spacing` and create a new option name `--spacing-even` which does what is described above (setting spacingNonLinear to 0, and then pass its parameter to spacingLinear).

**Comment by lpugin** [comment]
Maybe we can change the description to
```
--even-note-spacing            Align the notes without adding extra space according to their duration
```

**Comment by craigsapp** [comment]
That is good.  Here is a little shorter:

```
Align notes without adding extra space based on their duration
```

It is also related to rests, but that is not important (better to keep it short).
