### ISSUE TITLE
Problems with emcc v3.1.31 in combination with `-sMODULARIZE -sEXPORT_ES6`

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#3238]
Currently `buildToolkit` is not compatible with `emcc` v3.1.31 when running with `-s MODULARIZE=1 -s EXPORT_ES6=1`.

The JS build will contain `"use strict";` inside the async return function of `createVerovioModule()`:

```js
var createVerovioModule = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(config) {
  var createVerovioModule = config || {};

"use strict";var Module=...
```

This will run into:

```
Illegal 'use strict' directive in function with non-simple parameter list (Note that you need plugins to import files that are not JavaScript)
```

I will check if we need additional flags such as `-sSTRICT` or `-sSTRICT_JS` or if we need to wait for the next `emcc` release.

There seems to be already a merged pull request related to this: https://github.com/emscripten-core/emscripten/pull/18614. As well as related issues: https://github.com/emscripten-core/emscripten/issues/18610, https://github.com/emscripten-core/emscripten/issues/18620.

**Comment by lpugin** [comment]
Thanks. Hopefully this will be fixed when we make the next release. If not we can build it with an earlier version that still works.

**Comment by WolfgangDrescher** [comment]
I was able to compile it with `-s STRICT_JS=0`. This makes sense as ES module are always `"use strict";` anyways. But the current fix in emscripten will remove `-s STRICT_JS=1` as default value when `MODULARIZE` or `EXPORT_ES6 ` is set. So we should be fine with the `emcc` next release.

When this is not released yet for the next verovio release I can create a small PR: https://github.com/WolfgangDrescher/verovio/tree/fix-3238

Or we can implement something like this:

https://github.com/mackyle/sqlite/blob/a5de80effaf1e60d110e894a28bdf4144aff5311/ext/wasm/GNUmakefile#L527-L533

> If not we can build it with an earlier version that still works.

It looks like older version had the same problem but I only noticed it now because another dependency as more strict with strict mode (either Rollup.js oder Vite, but I'm not sure about this yet).

**Comment by lpugin** [comment]
@WolfgangDrescher any update on this?

**Comment by WolfgangDrescher** [comment]
Verovio `v3.15.0` was most likely build with a recent version of `emcc` where the liked PRs are already merged. `verovio-module.mjs` now looks like this:

```js
var createVerovioModule = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(createVerovioModule = {})  {

var Module=...
```

This looks good now, but I did not test it again. I will close this issue and reopen if I run into this problem again.

**Comment by lpugin** [comment]
Great! Many thanks for keeping an eye on this. It is all very helpful.
