### ISSUE TITLE
Petaluma font disappeared from Verovio

### ISSUE THREAD

**Issue by efreja** [rism-digital/verovio#3244]
Hello,
Between version 3.13.1 and version 3.14.0, Petaluma font has disappeared.
When using this font with v 3.14.0, browser console returns an error (see below)
and warns: [Warning] Font 'Petaluma' could not be loaded
Any other embedded font is unaffected.
Same issue with FireFox, Chrome..
Thanks
![Capture d’écran 2023-02-01 à 15 39 16](https://user-images.githubusercontent.com/16109195/216073948-a89d3990-e047-4b04-8698-58b26cf14695.png)

**Comment by lpugin** [comment]
Seems to work:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/689412/223388821-3d38cbab-b67a-4885-8df1-c1171b3ad926.png">
