### ISSUE TITLE
Verovio MIDI PLAY How do I change the playback speed？

### ISSUE THREAD

**Issue by junke365** [rism-digital/verovio#3246]
#define MIDI_TEMPO 120
Verovio MIDI PLAY How do I change the playback speed？
MIDI_TEMPO Have no effect

**Comment by rettinghaus** [comment]
In the encoding.

**Comment by lpugin** [comment]
You will find more information [here](https://book.verovio.org/toolkit-reference/output-formats.html#midi)

**Comment by junke365** [comment]
thank you
