### ISSUE TITLE
Glissando default styling

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3251]
Related to this pull request and the conversation in it:  https://github.com/rism-digital/verovio/pull/3205

Note that in Behind Bars, pp. 140&mdash;146, glissandos are discussed, and all glissandos are displayed as straight lines, showing her preference for using straight lines for glissandos.

On page 142, there is discussion about wavy lines:

<img width="773" alt="Screenshot 2023-02-03 at 6 36 04 PM" src="https://user-images.githubusercontent.com/3487289/216742174-6b0e61e8-ff24-4aef-9cc4-480658d54dbe.png">

It would be useful to add a styling option to glissandos that are not style as wavy lines in the data to chose between rendering glissandos as either wavy or staight, such as `--glissando-straight` to indicate that straight lines should be used for glissandos instead of the default rendering as wavy lines.  Or `--glissando-wavy` if straight-line glissandos are made the default rendering style.

Keyboards and harp cannot do portamento (as a general rule), so they would automatically assume a glissando when seeing a straight line.  Strings, woodwinds and brass cannot do glissandos and would interpret the line as a portamento.  So mostly an instrumentalist will presume the glissando or portamento, depending on the instrument.

**Comment by lpugin** [comment]
I would suggest to open an issue in the MEI repository because the distinction might be useful not only for Verovio

**Comment by craigsapp** [comment]
Previous discussions related to MEI would indicate that default styling is up to the renderer and none of MEI's business.  So I am not sure having a discussion on the MEI repository would accomplish anything.   It is a styling issue only, since the two visual types of glissandos have the exact same meaning.

**Comment by lpugin** [comment]
Looking back at this it seems that we have everything we need with `gliss@lform` that can be set to `wavy`. This issue can be closed
