### ISSUE TITLE
pageWidth and pageHeight maximum value

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3255]
Would there be a problem raising the maximum value of `--page-width` and `--page-height` from 60000 to 100000?

For orchestral scores on a single SVG page, the 60000 limit is easy to exceed (200000 or 500000 would be even better, but it will depend on what sort of memory problem web browsers will have with large SVG images...)

**Comment by lpugin** [comment]
Fix by https://github.com/rism-digital/verovio/commit/3eab703f6883429914f3d712747da37721d818b7
