### ISSUE TITLE
<clef dis="15" dis.place="above"/> delivers same result as <clef dis="8" dis.place="above">

### ISSUE THREAD

**Issue by gribjo** [rism-digital/verovio#3260]
Using verovio-toolkit.js 3.14.0 in svg I get octave 8 instead of 15 for dis="15" in clef element.
In the mei editor https://editor.verovio.org I find it running.

Full code example:
```
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
<music> <body> <mdiv> <score> 
<scoreDef> 
    <staffGrp> 
        <staffDef n="1" lines="5">
            <clef shape="G" line="2" dis="15" dis.place="above" />
        </staffDef>
    </staffGrp>
</scoreDef>
<section> <measure n="1" > <staff n="1"> <layer n="1"> </layer> </staff> </measure> </section> 
</score> </mdiv> </body> </music> </mei>
```

**Comment by lpugin** [comment]
Yes, this is because the editor is running the develop version, in which the issue has been [fixed](https://github.com/rism-digital/verovio/pull/3182).

**Comment by lpugin** [comment]
You can see the Verovio version used in the editor in the about dialog

<img width="634" alt="image" src="https://user-images.githubusercontent.com/689412/217367527-e1348876-101d-438d-822f-189ce8add9d6.png">
