### ISSUE TITLE
MusicXML: Absent divisions attribute causes errors in visual spacing and timemap output

### ISSUE THREAD

**Issue by cambiata** [rism-digital/verovio#3263]
**Describe the problem**

Major notation programs don't always include `<divisions>` information correctly in the `<measure><attributes>...` block.
Most of the time, this absence of the division information passes silently, not causing any rendering problems: The visual output looks fine, timemap output is correct. Obviously, Verovio infers the division information needed to handle the spacing correctly.

However, if there is for example a dynamic mark in the middle or end of the bar, the infered division calculation breaks, resulting in 
- incorrect placement of the dynamic mark
- incorrect "extra spacing" in the end of the bar
- incorrect timemap output 

![incorrect](https://user-images.githubusercontent.com/217074/217786063-90ced534-ba42-4752-a1ee-d2a4fe8ce802.png)

**To Reproduce**
1. Load the attached musicXml file
2. Render page X
3. See errors as described above

**Expected behavior**

The fact that Verovio handles absent divisions info without problem as long as there isn't a dynamic mark or anything like that, makes it hard to spot why the layout and the timemap output isn't correct.

The best case would of course be that Verovio could infer the divisions information needed, and make the calculations correctly based on that. The second best would be a clear console output telling that measure>attribute>divisions information is missing and that the necessary calculations for layout and timemap output couldn't be performed correctly.

The current behaviour, with Verovio "silently" rendering incorrectly and outputting incorrect timemap info, is unfortunate.

**Verovio information**
 - 3.15.0-dev

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
    <movement-title>Missing divisions problem</movement-title>
    <part-list>
        <score-part id="P1">
        </score-part>
    </part-list>

    <part id="P1">
        <measure number="1">
            <attributes>
                <key>
                    <fifths>0</fifths>
                </key>
                <clef>
                    <sign>G</sign>
                    <line>2</line>
                </clef>
                <time>
                    <beats>4</beats>
                    <beat-type>4</beat-type>
                </time>
                <!-- <divisions>2</divisions> -->
            </attributes>

            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <duration>8</duration>
                <voice>1</voice>
                <type>whole</type>
                <stem>down</stem>
            </note>
        </measure>

        <measure number="2">
            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <voice>1</voice>
                <type>quarter</type>
                <duration>2</duration>
                <stem>up</stem>
            </note>

            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <voice>1</voice>
                <type>quarter</type>
                <duration>2</duration>
                <stem>up</stem>
            </note>

            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <voice>1</voice>
                <type>quarter</type>
                <duration>2</duration>
                <stem>up</stem>
            </note>

            <direction>
                <direction-type>
                    <dynamics>
                        <mf/>
                    </dynamics>
                </direction-type>
            </direction>

            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <voice>1</voice>
                <type>quarter</type>
                <duration>2</duration>
                <stem>up</stem>
            </note>

        </measure>

        <measure number="3">
            <note>
                <pitch>
                    <step>G</step>
                    <octave>4</octave>
                </pitch>
                <duration>8</duration>
                <voice>1</voice>
                <type>whole</type>
                <stem>down</stem>
            </note>
        </measure>

    </part>

</score-partwise>


```

**Comment by rettinghaus** [comment]
Usually I would argue that Verovio doesn't try to fix bad encodings, but in this case I make an exception. 😄

**Comment by cambiata** [comment]
Glad to hear, very much appreciated! :-)
