### ISSUE TITLE
android compile time

### ISSUE THREAD

**Issue by junke365** [rism-digital/verovio#3264]
![image](https://user-images.githubusercontent.com/25856057/218075914-695f5f94-0b45-4737-a168-fb4ea854e828.png)
![image](https://user-images.githubusercontent.com/25856057/218076406-c3a0285b-3c5b-4e33-a469-bc77d9ea9a35.png)

  $(ROOT_PATH)/src/crc/crc.cpp \
  $(ROOT_PATH)/libmei/atts_usersymbols.cpp \
 $(ROOT_PATH)/include/crc\
 $(ROOT_PATH)/include/zip
It's not written
Can I contribute to your code?

**Comment by lpugin** [comment]
I added them. You are welcome to contribute. However, please make sure to:
* first open issues with detailed explanation with the issue template properly filled
* prepare a pull request following the [workflow guidelines](https://book.verovio.org/contributing/guidelines.html)
* verify the the PR follows the [coding guidelines](https://book.verovio.org/contributing/guidelines.html), including the clang-format
* fill, sign and send the [CLA](https://rism.digital/resources/verovio-cla.pdf)
