### ISSUE TITLE
Font generation problems

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3272]
I have trouble to regenerate the fonts. When I do it on macOS (M1) I get this:

![image](https://user-images.githubusercontent.com/7693447/218999742-fbbc3780-9619-4af9-8d7d-be5d83cd483d.png)

On Ubuntu 20.04 it works fine:

![image](https://user-images.githubusercontent.com/7693447/219000409-0e42a0be-8c5a-456f-955a-0ff9d3d7cd22.png)

Tried Python 3.10 and 3.11 with installed packages:
lxml==4.9.2
numpy==1.24.2
scipy==1.10.0
svgpathtools==1.6.0
svgwrite==1.4.3

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Tempo rendition</title>
         </titleStmt>
         <pubStmt>
         </pubStmt>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef n="1" lines="5">
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure>
                     <staff n="1">
                        <layer n="1">
                           <mRest />
                        </layer>
                     </staff>
                     <tempo place="above" staff="1" tstamp="1.0">
                        <rend fontfam="smufl" fontsize="70%"></rend> = <rend fontfam="smufl" fontsize="70%"></rend>
                     </tempo>
                     <dynam staff="1" tstamp="1.0">( p )</dynam>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by ahankinson** [comment]
What commands did you run?

I have an M1 as well, so I can test it. It worked for me previously, but maybe something in the dependencies has changed?

**Comment by rettinghaus** [comment]
I simply used the `generate_all.sh`.

**Comment by ahankinson** [comment]
Is there any difference in the files being generated between Mac and Ubuntu? To me it looks like the Verovio instance you're using can't find the data files on the Mac, or the text fonts aren't working correctly.

**Comment by lpugin** [comment]
It works for me on an M1 and running `generate_all.sh`

**Comment by rettinghaus** [comment]
I point to the data directory with `-r` option. I double-checked. The only thing changed in the svg is the encoding of the embedded css font.

**Comment by lpugin** [comment]
It looks like a fontforge issue to me. You should try with `--keep-intermediates` and check if the web fonts generated by fontforge are not corrupted.

**Comment by ahankinson** [comment]
Could you paste the output of running generate all here? That may also provide a clue.

**Comment by rettinghaus** [comment]
@ahankinson Thanks for the hint with the output! I noticed now that it was using an outdated fontforge version (although I installed the latest with homebrew). Fixed that and now everything works as expected! 
Sorry for the false alarm.
