### ISSUE TITLE
chord accidental and second interval interaction

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3276]
This rendering of accidentals in verovio is non-standard:

<img width="137" alt="Screenshot 2023-02-15 at 8 25 06 AM" src="https://user-images.githubusercontent.com/3487289/219089369-9b56392b-f84b-4d6c-96fe-5b565d9becb1.png">

<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-02-15T08:23:42" version="3.15.0-dev-2f1ce00-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1tni2c8">
    <score xml:id="s78ddeh">
     <scoreDef xml:id="scyd6gw">
      <staffGrp xml:id="sovbqwt">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="c9kwudn" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" right="invis">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <chord xml:id="chord-L2F1" dur="4">
          <note xml:id="note-L2F1S1" oct="5" pname="a" accid="f" />
          <note xml:id="note-L2F1S2" oct="4" pname="b" accid.ges="n" />
          <note xml:id="note-L2F1S3" oct="4" pname="a" accid="f" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

The two accidentals are aligned, but the top one should not have a gap to the note it is applied to.

This is from Beethoven's Hammerklavier sonata, first movement, measure 25.

Survey from various editions:

https://imslp.org/wiki/Piano_Sonata_No.29,_Op.106_(Beethoven,_Ludwig_van)

[Klaviersonaten](https://imslp.org/wiki/Klaviersonaten_(Beethoven,_Ludwig_van)), Band II (pp.227-72)
Munich: [G. Henle Verlag](https://imslp.org/wiki/G._Henle_Verlag), 1976. Plate HN 1034.

<img width="80" alt="Screenshot 2023-02-15 at 8 16 45 AM" src="https://user-images.githubusercontent.com/3487289/219090016-267c4999-19ac-4703-a5b9-afe45fbed00e.png">

Editor Artur Schnabel (1882-1951)
Milan: Curci, n.d.(ca.1949). Plate E. 4281 C.

<img width="58" alt="Screenshot 2023-02-15 at 8 28 14 AM" src="https://user-images.githubusercontent.com/3487289/219090363-5b73a78f-95d3-416d-9b58-ee041dbe39d4.png">

Editor Max Pauer (1866-1945) Carl Adolf Martienssen (1881-1955), revision
Publisher Info.	Sonaten für Klavier zu zwei Händen, Bd.2
Leipzig: C.F. Peters, n.d.(ca.1920). Plate 10543, 10555-56.
Reprinted	Martienssen revision, n.d.(1927). - #66418 (pp.515-560)

<img width="67" alt="Screenshot 2023-02-15 at 8 29 35 AM" src="https://user-images.githubusercontent.com/3487289/219090802-f175a798-d9c1-404e-a457-be3c0c2f472e.png">

This edition has an interesting octave line:

<img width="353" alt="Screenshot 2023-02-15 at 8 30 14 AM" src="https://user-images.githubusercontent.com/3487289/219091057-bf2c3be7-60fb-498c-915a-2bfb631128a5.png">

Editor Alfredo Casella (1883-1947)
Publisher Info.	Sonate per pianoforte, Vol.3 (pp.90-143)
Milan: Edizione Ricordi, 1920. Plate E.R. 3.

<img width="78" alt="Screenshot 2023-02-15 at 8 31 41 AM" src="https://user-images.githubusercontent.com/3487289/219091475-bc7385a8-7646-422d-a4d5-47fcf48a808d.png">

Editor Frederic Lamond (1868-1948)
Publisher Info.	Klaviersonaten, Band II
Berlin: Ullstein, n.d.(ca.1918).
Reissue - Leipzig: Breitkopf & Härtel, 1923. Plate 28727.

<img width="85" alt="Screenshot 2023-02-15 at 8 32 49 AM" src="https://user-images.githubusercontent.com/3487289/219091816-6be2e97e-67eb-4994-a7a7-1f0bedb6ccc5.png">

Editor Heinrich Schenker (1868-1935)
Publisher Info.	Vienna: Universal Edition, 1918-21.

<img width="76" alt="Screenshot 2023-02-15 at 8 34 21 AM" src="https://user-images.githubusercontent.com/3487289/219092255-9d920279-0e21-4f59-b73c-f84f1763b507.png">

Editors Louis Köhler (1820–1886), Adolf Ruthardt (1849-1934)
Publisher Info.	Sonaten für Pianoforte solo, Bd.2
Leipzig: C.F. Peters, n.d.(ca.1910). Plate 9427.

<img width="71" alt="Screenshot 2023-02-15 at 8 35 30 AM" src="https://user-images.githubusercontent.com/3487289/219092571-29d9d2af-dcad-42ba-a7fb-22112420c0ec.png">

Also has the interesting octave line:

<img width="333" alt="Screenshot 2023-02-15 at 8 35 19 AM" src="https://user-images.githubusercontent.com/3487289/219092632-eb738b5f-74a6-4284-99b8-9f77211f410f.png">

Editor	Hans von Bülow (1830-1894)
Translator	John Henry Cornell (1828-1894), English text
Publisher Info.	Stuttgart: J.G. Cotta, n.d.(ca.1875). Plate 35.
Reprinted	New York: Edward Schuberth & Co., 1891.

<img width="59" alt="Screenshot 2023-02-15 at 8 36 45 AM" src="https://user-images.githubusercontent.com/3487289/219092936-82442193-90ca-48be-bd2b-2c7cfa01399a.png">

Publisher Info.	Ludwig van Beethovens Werke, Serie 16, Nr.152 (pp.55-96)
Leipzig: Breitkopf und Härtel, n.d.[1862]. Plate B.152.

<img width="80" alt="Screenshot 2023-02-15 at 8 43 53 AM" src="https://user-images.githubusercontent.com/3487289/219095045-2bb2ec2a-c60d-49c2-99ab-e6a41c5986a7.png">

**Comment by DavidBauer1984** [comment]
This is a feature in Verovio: accidentals are horizontally aligned if the notes are an octave apart. It doesn't work for other intervals:
<img width="179" alt="Octave-Accids" src="https://user-images.githubusercontent.com/63608463/219349577-be16cebf-924e-485b-b8ad-a828252ff874.png">

Here is the corresponding rule in _Behind Bars_:
<img width="575" alt="OctaveAccids" src="https://user-images.githubusercontent.com/63608463/219349662-f0e60ef5-d254-499e-a8d2-91b096d4c443.png">

One could add a switch to enable/disable this feature.

**Comment by craigsapp** [comment]
Notice that all examples (excluding strange single-accidental cases in the first and second editions) behave the same way.   The first two editions only have one accidental, probably an engraving typo:

<img width="58" alt="Screenshot 2023-02-16 at 6 41 39 AM" src="https://user-images.githubusercontent.com/3487289/219395912-2448c162-f418-4364-922b-ca0db04fc127.png">

In other words, there is no edition that uses the aligned-octave rule on this chord.

For the rule in Behind Bars:

<img width="212" alt="Screenshot 2023-02-16 at 6 31 49 AM" src="https://user-images.githubusercontent.com/3487289/219393193-5609559d-18a3-447f-a361-8dc0d59dfa44.png">

note that no accidentals have an unexplained gap to the note.  When there is a gap, then it is because another accidental has priority.  Octave accidentals should be aligned in this case, but there is a more fundamental no-gap rule which overrides the aligned octave rule, at least in the two-accidental case.

One way to deal with this: if there are only two accidentals on the chord an octave apart, then the accidentals should not try to be vertically aligned.    If there were three accidentals on this chord, I think it would be more likely that the octave accidentals would be aligned (but a real-world example would have to be found to verify).

**Comment by DavidBauer1984** [comment]
Currently working on this, it should look better soon 😉
