### ISSUE TITLE
Implement clef@oct

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3292]
Related to the discussion for the issue https://github.com/music-encoding/music-encoding/pull/1044, it would be useful to implement `clef@oct`.

The function `Clef::GetClefLocOffset()` in `src/clef.cpp` is probably the only function that needs to be updated to implement `clef@oct`:

https://github.com/rism-digital/verovio/blob/9c90e9e8b32ee1f801928af59b7d5e7d1e2f0214/src/clef.cpp#L69-L102

The core of the update would be to modify the existing code with this:

```cpp
    int offset = 0;
    int defaultOct = 4; // C clef
    if (this->GetShape() == CLEFSHAPE_G) {
        defaultOct = 4;
        offset = -4;
    }
    else if (this->GetShape() == CLEFSHAPE_GG) {
        defaultOct = 3;
        offset = 3;
    }
    else if (this->GetShape() == CLEFSHAPE_F) {
        defaultOct = 3;
        offset = 4;
    }

    if ([HAS_CLEF_OCTAVE_ATTRIBUTE]) {
        int oct = this->GetOct();
        int octDifference = oct - defaultOct;
        offset -= octDifference * 7;
    }
```

Obviously `[HAS_CLEF_OCTAVE_ATTRIBUTE]` needs to be filled in (is there any generic way of asking an Object if it has a specific attribute that is unset?)

There are a few other things to adjust and fix in this function:

(1) These lines of code should be probably be removed:

```cpp
    // ignore disPlace for gClef8vbOld
    if (this->GetShape() == CLEFSHAPE_GG) disPlace = 0;
```

This disables `clef@dis` for `GG` clefs.  Currently this disallows using `clef@dis="0"` to handle the German system for `GG` clefs.  `GG` is hard-wired to transposing up an octave when written due to this code:

```cpp
    else if (this->GetShape() == CLEFSHAPE_GG) {
        offset = 3;
    }
```

The new system for indicating the German GG clef will be:

```xml
     <clef shape="GG" line="2" oct="4">
```

And the pitches in the `GG` clef will be encoded with the same `note@oct` as for `G` clef (sounding octave).

Piccolo flute and xylophone and vibraphone would best be encoded with this `clef@oct` system (and encoding the notes at sounding octave, as well as no transposition information on `staffDef`):

```xml
     <clef shape="G" line="2" oct="5">
```

Glockenspiel/celeste is written two octaves lower than sounding:

```xml
     <clef shape="G" line="2" oct="6">
```

Double bass is written one octave higher than sounding:

```xml
     <clef shape="F" line="4" oct="2">
```

(2) If `clef@oct` is given, then the `clef@dis`/`clef@dis.place` system should be disabled (or vice-verse).  The two methods are not compatible with figuring out what the sounding octave is (since `clef@oct` requires notes to be encoded at sounding pitch, which `clef@dis` requires notes to be encoded at written pitch).

(3) There is a violation of verovio C++ programming style in the `dis` code at the bottom of the function:
<img width="1351" alt="Screenshot 2023-02-25 at 3 19 08 PM" src="https://user-images.githubusercontent.com/3487289/221383980-734324ef-b9b4-40c6-a825-105c466d2f43.png">

(@lpugin is to blame for this :-)  Instead it should be (before updating to add `clef@oct`):

```cpp
    int disPlace = 0;
    if (this->GetDisPlace() == STAFFREL_basic_above) {
        disPlace = -1;
    }
    else if (this->GetDisPlace() == STAFFREL_basic_below) {
        disPlace = 1;
    }

    // ignore disPlace for gClef8vbOld
    if (this->GetShape() == CLEFSHAPE_GG) {
        disPlace = 0;
    }

    if ((disPlace != 0) && (this->GetDis() != OCTAVE_DIS_NONE)) {
        offset += (disPlace * (this->GetDis() - 1));
    }
```

which is also much easier to read since the conditions and the actions are visually separated.

**Comment by lpugin** [comment]
> (2) If `clef@oct` is given, then the `clef@dis`/`clef@dis.place` system should be disabled (or vice-verse). The two methods are not compatible with figuring out what the sounding octave is (since `clef@oct` requires notes to be encoded at sounding pitch, which `clef@dis` requires notes to be encoded at written pitch).

The `note@oct` is always the written octave, and also the sounding one unless `note@oct.ges` is given. Changing the encoding of the clef will not (and should not!) change that.

**Comment by lpugin** [comment]
This is what I mean and would expect with `clef@oct`: nothing changes in the encoding of the notes here, and they would all sound as a G3.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/689412/221410043-b64f4b55-fb1d-478b-9fee-9cfd6a54e9fc.png">

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Clef octaves</title>
            <respStmt />
         </titleStmt>
         <pubStmt/>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffGrp bar.thru="true">
                        <grpSym symbol="bracket" />
                        <staffDef n="1" lines="5">
                           <label>@dis / @displace</label>
                           <clef shape="G" line="2" dis="8" dis.place="below" />
                        </staffDef>
                        <staffDef n="2" lines="5">
                           <label>GG @shape</label>
                           <clef shape="GG" line="2" />
                        </staffDef>
                        <staffDef n="3" lines="5">
                           <label>@oct</label>
                           <clef shape="G" line="2" glyph.name="gClef8vb" oct="3" />
                        </staffDef>
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <note dur="1" oct="3" pname="g">
                              <verse>
                                 <syl>G3</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <note dur="1" oct="3" pname="g">
                              <verse>
                                 <syl>G3</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                     <staff n="3">
                        <layer n="1">
                           <note dur="1" oct="3" pname="g">
                              <verse>
                                 <syl>G3</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
For instruments producing an note an octave higher or lower, that can go either in `note@oct.ges` or `staffDef@trans.*`. If one really think it can go in the clef, then it looks more like an `clef@oct.ges` to me.

**Comment by ahankinson** [comment]
This is the only thing I was expecting:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/163183/221411306-d1ac23dc-c03b-430c-8652-88eae8b2dc46.png">


```xml
<staffDef n="2" lines="5">
    <label>GG @shape @oct="4"</label>
    <clef shape="GG" line="2" oct="4" />
</staffDef>

...
<layer n="1">
  <note dur="1" oct="4" pname="g">
    <verse>
      <syl>G4</syl>
    </verse>
  </note>
</layer>
```

**Comment by lpugin** [comment]
Yes, that looks fine. I am not sure @craigsapp has the same understanding, though. Reading that we are going to have two ways to encode note octaves, namely as written pitch or as sounding pitch, and that it depends on the presence of a `clef@oct` makes me worried.

**Comment by craigsapp** [comment]
> Yes, that looks fine. I am not sure @craigsapp has the same understanding, though. Reading that we are going to have two ways to encode note octaves, namely as written pitch or as sounding pitch, and that it depends on the presence of a clef@oct makes me worried.

Never mind my comments about differences between `clef@oct` and `clef@dis`.  I should have the same understanding of @ahankinson and the two systems seem to be exactly the same (other than one showing numbers on the clef and the other not).   Humdrum scores should always be encoded at concert pitch, and I was thinking that I had to transpose vocal tenor clef music up an octave when converting to MEI, but I do not.

I will slightly blame Sibelius (version 8.3 at least) which has a strange behavior with vocal tenor clefs.   Here is some music in Musescore:

<img width="1050" alt="Screenshot 2023-02-26 at 5 08 48 AM" src="https://user-images.githubusercontent.com/3487289/221412994-cfe0fd2b-3174-4840-9459-415eb3327cbc.png">

Exporting to MusicXML and loading into Sibelius (8.3):

<img width="1089" alt="Screenshot 2023-02-26 at 5 08 45 AM" src="https://user-images.githubusercontent.com/3487289/221413030-f6ad9292-b434-4141-bed4-39aad6e1428b.png">

Sibelius displays the notes at sounding pitch rather than moving them up an octave to display properly for the clef.   Fixing this and saving as MusicXML and then loading back into Sibelius has the same problem.

**Comment by craigsapp** [comment]
Maybe I have the same understanding as @ahinkinson, but in post
https://github.com/music-encoding/music-encoding/pull/1044#issuecomment-1445351041
he says that this is only for distinguishing between French/German interpretation of `GG` clefs.

I propose that the `clef@oct` system would also be useful for octave transposing parts, in particular because piccolo (et al.) music is never written at sounding pitch in both written and sounding scores.   The clef of a piccolo part can be thought of as being a treble clef with an invisible 8 above it.   For the case of `GG` clefs, this `8` can automatically be suppressed since there are no `GG` clefs with 8 (in particular in SMuFL).   But treble clefs using `clef@dis="8"`/`clef@dis.place="above"` will have an 8 displayed above the clef without an easy way to suppress it.   Using `clef@oct="5"` for piccolo parts will do the same thing, but the 8 will not be displayed above the treble clef.

**Comment by lpugin** [comment]
Sibelius is notoriously problematic with octava clefs. I remember having to pass the output through an XSLT to fix them, so I would recommend not to base tests on it.

Regarding the implementation of `@oct` I am happy to go ahead unless there are some remaining open questions.

**Comment by ahankinson** [comment]
It's been a problem for a long time: https://music.stackexchange.com/questions/4700/notating-tenor-vocal-parts-with-8va-g-clef-in-sibelius-6

The way to do it "correctly" is to set it up as an instrument, and not just change the clef sign.
