### ISSUE TITLE
can not compile android

### ISSUE THREAD

**Issue by imiskolee** [rism-digital/verovio#3321]
## steps

```bash
export ANDROID_NDK_ROOT="/xxxxx/xxxxxxx/develop/android-ndk-r21e"
ndk_build=$ANDROID_NDK_ROOT/ndk-build
$ndk_build
```

output error:
```text
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
[armeabi-v7a] Compile++ thumb: verovio-android <= *.cpp
clang++: error: cannot specify -o when generating multiple output files
make: *** [/Users/miskolee/develop/android-ndk-r21e/build/core/build-binary.mk:478: /Users/miskolee/develop/src/noiselabs/verovio/bindings/android/obj/local/armeabi-v7a/objs/verovio-android//Users/miskolee/develop/src/noiselabs/verovio/bindings/android/jni/__/__/__/libmei/dist/*.o] Error 1

```

**Comment by lpugin** [comment]
I do not have an Android development setup on my current machine, so I will not be able to help. Hopefully somebody with some Android experience can comment and help you. It seems to me, however, that a bit more information could be useful.

**Comment by imiskolee** [comment]
I already fix it with CMake

**Comment by ahankinson** [comment]
Could you add a note to say how you fixed it, please? So that if someone else has the same problem, they don't have to figure it out on their own.

**Comment by imiskolee** [comment]
Sure, I just use cmake function `add_subdictrory` included the project, and it works fine. not any exceptions.

**Comment by lpugin** [comment]
Could you point to the `add_subdictrory` function? And give a bit more details? Thanks
