### ISSUE TITLE
Setting bpm has no effect

### ISSUE THREAD

**Issue by junke365** [rism-digital/verovio#3339]
**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
1. Load the data attached
2. Render page X
3. See error

**Expected behavior**

**Input data**
The smallest example (MEI unless about another input format) to reproduce the problem

**Verovio information**
 - Version of Verovio [e.g. develop, 3.15.0]
 - Binding [e.g. command-line, JavaScript, Python]

**Environment information (as appropriate)**
linux
double tempo = 160;

bpm inoperative
![image](https://user-images.githubusercontent.com/25856057/226542782-36c54700-e4f6-41dc-a065-2a322c41a8a3.png)

![image](https://user-images.githubusercontent.com/25856057/226542837-2d7c3329-7abc-4285-b68e-7f2c49e6ef41.png)

![image](https://user-images.githubusercontent.com/25856057/226542934-eb490d91-9361-4fce-a0de-547936f48210.png)

**Screenshots**

**Additional context**

**Comment by lpugin** [comment]
Opening issues without describing the problem properly, without providing minimal test data to reproduce the problem, and without indicating the environment precisely has no effect.

**Comment by junke365** [comment]
midi bpm Settings are not used when midi files are exported

**Comment by junke365** [comment]
midi bpm Settings do not work when midi files are exported

**Comment by lpugin** [comment]
Since you are working with a modified version of Verovio we cannot help you. Sorry.
