### ISSUE TITLE
Installing Python toolkit from repo

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3344]
**Describe the problem**
When I want to test a specific branch in Python it is possible to check it out locally and just do

```terminal
pip install <path_to_local_repo>
```

But trying to install it directly from GitHub by running 

```terminal
pip install git+https://github.com/rism-digital/verovio
```

it tells me it has "Successfully installed" verovio, but when I try it I get an error:

```Python
>>> import verovio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./venv/lib/python3.9/site-packages/verovio/__init__.py", line 6, in <module>
    from .verovio import *
ModuleNotFoundError: No module named 'verovio.verovio'
```

**Expected behavior**
It should be possible to install Verovio directly from GitHub.

**Environment information (as appropriate)**
 - macOS and Ubuntu
 - pip 23.0.1

**Comment by ahankinson** [comment]
(I've removed the `bug` label because we don't really support installation this way, so it's not something that's broken, it's an enhancement that is being requested.)

**Comment by ahankinson** [comment]
Not building in parallel is not a "problem," but it's just very very slow. It will do it, but there are better ways. And yes -- installing with that method is not documented, because it's not currently supported.

It's easy to write a shell script if you want a one-liner. 😁 

No idea about SWIG, but you're welcome to try and figure it out.

**Comment by lpugin** [comment]
Considering that we have pre-build binaries and different documented ways to build it locally, I am closing the issue. I added a [comment](https://book.verovio.org/installing-or-building-from-sources/python.html#building-with-pip) to the documentation, though.

**Comment by rettinghaus** [comment]
The issue here is that pip install simply packages everything first and _than_ builds the module, resulting with the `verovio.py` not copied. One has to pass the `build_ext` over with pip:

```shell
pip install --global-option=build_ext git+https://github.com/rism-digital/verovio
```

However, `global-option` is deprecated and building with `setup.py` is seen as legacy and will stop working with future releases.
