### ISSUE TITLE
Implement meterSig@visible

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3365]
Clefs can be made invisible, but time signature cannot:

<img width="186" alt="Screen Shot 2023-04-06 at 02 39 10" src="https://user-images.githubusercontent.com/3487289/230338429-530e0181-e53e-4445-8d33-d564ec1a65cb.png">

<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-04-06T02:37:21" version="3.16.0-dev-0b9dff2">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1ns8ori">
    <score xml:id="s1ior7rr">
     <scoreDef xml:id="sl5k7sh" midi.bpm="400.000000">
      <staffGrp xml:id="skjg1vl">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="c16sryh3" shape="G" line="2" visible="false" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" visible="false" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

In the above example the treble clef is made invisible, but the time signature remains visible when `meterSig@visible="false"` is used.

There are two main reasons for the need of invisible time signatures:

(1) When extracting measures from a full score (as an example)

(2) To be able to attach items such as slur and fermatas to the ends of measures in a non-metrical region such as a cadenza.

Also display of clef, key signatures and time signature changes are incorrect after a free meter measure and providing an invisible time signature will probably fix the problem. (And/or I can post an issue about this point later).

**Comment by rettinghaus** [comment]
Incorrect encoding. Use form="invis".

**Comment by rettinghaus** [comment]
Maybe it would be a good idea to make sure your files are actually valid?

**Comment by craigsapp** [comment]
Thanks!:

<img width="167" alt="Screen Shot 2023-04-06 at 03 15 26" src="https://user-images.githubusercontent.com/3487289/230348000-326be0bc-e0f2-4728-a8aa-48f60b18136a.png">


I was mixing up the pages:

https://music-encoding.org/guidelines/v4/elements/clef.html
https://music-encoding.org/guidelines/v4/elements/metersig.html

`clef@visible` exists, but `meterSig@visible` does not.  It would be good to add `meterSig@visible` to MEI.

**Comment by rettinghaus** [comment]
Maybe. Please open an issue on MEI.

**Comment by craigsapp** [comment]
> Maybe it would be a good idea to make sure your files are actually valid?

How do I do that?

**Comment by rettinghaus** [comment]
> I now know how to do it properly in MEI, thanks to you :-), but such things should be made uniform across elements as a general rule.

Don't tell me, tell MEI.

**Comment by craigsapp** [comment]
OK, OK.  But are you not MEI? :-)

https://music-encoding.org/community/mei-board.html

<img width="1223" alt="Screen Shot 2023-04-06 at 04 00 40" src="https://user-images.githubusercontent.com/3487289/230358423-cbce7107-83fa-45ef-a1eb-7a4f1a652e71.png">
