### ISSUE TITLE
Change order of rendering rectangle and text of boxed directions

### ISSUE THREAD

**Issue by sonovice** [rism-digital/verovio#3380]
I am using directions to write "section names" in my SVGs like this:
```xml
<dir xml:id="d1swj9nt.6" type="sectionBlock" place="above" staff="1" tstamp="1.000000" vgrp="250">
    <rend xml:id="r1rm0zbh.6" rend="box" fontstyle="normal" fontweight="normal">Pre-Chorus</rend>
</dir>
```
and use CSS to style the boxes:
```css
.sectionBlock > rect {
    stroke-width: 40;
    stroke-opacity: 0;
    fill-opacity: 1;
    fill: gold;
}
```

However, due to the order in the SVG file, the text gets rendered first and then the rectangle, resulting in the text not being visible:
![image](https://user-images.githubusercontent.com/8217108/232480752-2fab98eb-c7c7-4711-925e-aa81883b6e08.png)

If I change the order in the SVG manually, it works as intended:
![image](https://user-images.githubusercontent.com/8217108/232480823-204d3f81-ae1c-4706-8b74-ac63182e7e17.png)

If there is no reason to keep the current order switching it would be great to allow for such things.

I tried to do it on my own but could not find the correct code lines. :/

**Comment by ahankinson** [comment]
> If I change the order in the SVG manually

Change the order of what?

It would be helpful to provide the full SVG, and an MEI encoding. This makes reproducing and fixing easier.

**Comment by sonovice** [comment]
> Change the order of what?

Sorry for not being clear enough. I would like to have the `<rect>` element before the `<text>` element in the SVG for `<dir rend="box" ...>` elements.

Here is an MWE:
```xml
<mei xmlns="http://www.music-encoding.org/ns/mei">
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" n="1" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer>
                  <note pname="c" oct="4" dur="4"/>
                  <note pname="e" oct="4" dur="4"/>
                  <note pname="g" oct="4" dur="4"/>
                  <note pname="c" oct="5" dur="4"/>
                </layer>
              </staff>
              <dir type="sectionBlock" place="above" staff="1" tstamp="1.0">
                <rend rend="box">Pre-Chorus</rend>
              </dir>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

Verovio generates this part for the `<dir>` element:
```xml
<g id="d1ugfsia" class="dir sectionBlock">
  <!-- This should go after <rect> -->
  <text x="825" y="376" font-size="0px">
    <tspan id="r1g5rifj" class="rend">
      <tspan id="t15ifpcc" class="text">
        <tspan font-size="405px" class="text">Pre-Chorus</tspan>
      </tspan>
    </tspan>
  </text>

  <!-- This should go first -->
  <rect stroke="currentColor" stroke-width="20" fill-opacity="0.000000" x="735" y="10" height="494" width="2030"/>
</g>
```

**Comment by sonovice** [comment]
Thanks, Laurent!
