### ISSUE TITLE
Dynamics with mixed content not rendered properly anymore

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#3459]
Changing the SVG output in this [PR](https://github.com/rism-digital/verovio/pull/3448) broke rendering of dynamics with mixed content

Example dynam-006.mei from the test suite

Before 
![image](https://github.com/rism-digital/verovio/assets/689412/fd50f6dd-bd19-4e85-b491-043b27b72f31)

After
![image](https://github.com/rism-digital/verovio/assets/689412/0de32dd6-091f-4e4a-94dc-8798a6252ae3)

**Comment by rettinghaus** [comment]
Why didn't this show up in the test? https://github.com/rism-digital/verovio/actions/runs/5224014847

**Comment by lpugin** [comment]
I can happen when the diff is not significant enough.
