### ISSUE TITLE
Create GH Action to update homebrew 

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3470]
It would be nice to have a small GitHub Action that automatically creates a PR to the `homebrew-core` repo to update the Verovio formula on each release.

**Comment by lpugin** [comment]
It is on the list of things to do for a release. I don't think we need a GH Action for that

**Comment by rettinghaus** [comment]
I still think it would be nice to just reduce the manual tasks for a release. 

See https://github.com/marketplace/actions/homebrew-releaser
and https://github.com/pypa/gh-action-pypi-publish
