### ISSUE TITLE
Missing glyph in develop_tab branch

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#3473]
There is a missing glyph ornamentLeftVerticalStrokeWithCross used in the develop_tab branch.

https://github.com/rism-digital/verovio/blob/4812281fe7c96c37d5962fef14970887b1bbfe4c/src/note.cpp#L364

It should be added to Leipzig first

**Comment by lpugin** [comment]
Tagging @paul-bayleaf

**Comment by rettinghaus** [comment]
This is a replacement glyph for the slashed number one: 

![](https://user-images.githubusercontent.com/7693447/251417797-2615acfb-6ed5-4adf-8afc-b8fd3c85daf1.png)

Maybe it would make sense to use primitives for this (until SMuFL provides a proper glyph)?

**Comment by craigsapp** [comment]
Related: _Scaramella fa la galla_ by Loyset Compere

https://verovio.humdrum.org/?file=https://raw.githubusercontent.com/josquin-research-project/Com/master/Com3052-Scaramella_fa_la_galla.krn&v=evenNoteSpacing

<img width="907" alt="Screenshot 2023-07-11 at 11 46 13 PM" src="https://github.com/rism-digital/verovio/assets/3487289/fc6600f9-bda7-46de-b47c-119d4efad03b">

Josquin's _Scaramella_:

https://verovio.humdrum.org/?file=https://raw.githubusercontent.com/josquin-research-project/Jos/master/Jos2830-Scaramella.krn&v=evenNoteSpacing

<img width="765" alt="Screenshot 2023-07-11 at 11 49 31 PM" src="https://github.com/rism-digital/verovio/assets/3487289/2af71170-e179-4e68-bf23-eec4c4dcee3d">

**Comment by rettinghaus** [comment]
@craigsapp how's that related?

**Comment by craigsapp** [comment]
They have the same name 😉    The Compere Bassus first two measures are the same rhythm as the tablature (but I cannot read the tablature pitches so I don't know about that).  The Josquin one has similar pitch contour as Compere but in a triple meter.

**Comment by paul-bayleaf** [comment]
I'm preparing a pull request for the E-LAUTE project for vertical positioning of notes and rhythm signs and for @notationsubtype.   I'll replace SMUFL_E595_ornamentLeftVerticalStrokeWithCross with a struck through  digit 1 at the same time, so SMUFL_E595 won't be needed.

**Comment by paul-bayleaf** [comment]
This issue can be closed, since https://github.com/rism-digital/verovio/pull/3512 was merged GLT no longer uses SMUFL_E595_ornamentLeftVerticalStrokeWithCross
