### ISSUE TITLE
Issue with Verovio JS App when Rendering

### ISSUE THREAD

**Issue by eleon024** [rism-digital/verovio#3491]
**Issue Description**
I have a JS app that takes three parameters. Piece_URL (a raw MEI file), EMA_expression, and measure_range, and pass it to verovio to render. However, when sending too many requests or refreshing the page too often, it fails to render. 

Is this a Verovio issue, an issue with the 'await fetch(pieceURL)' line, an issue with getting the MEI from GitHub, GitHub Pages, or something else?

**To Reproduce**
1. Visit my GitHub pages endpoint that is serving the JS app: https://eleon024.github.io/ema_react_app/?pieceURL=https%3A%2F%2Fraw.githubusercontent.com%2FCRIM-Project%2FCRIM-online%2Fmaster%2Fcrim%2Fstatic%2Fmei%2FMEI_4.0%2FCRIM_Mass_0002_2.mei&ema_expression=%2F4-5%2F3%2B5%2C3%2B5%2F%402-4%2B%402-all%2C%401%2B%401%2Fhighlight&measure_range=%257B%2522measureRange%2522%253A%2520%25222-5%2522%257D

2. Sometimes, the page is blank, but upon refreshing a few times, it loads. 

3. Also, when changing the parameters in the URL to: 
CRIM_Mass_0002_1.mei or measure_range=%257B%2522measureRange%2522%253A%2520%25221-5%2522%257D,
the page is also blank and fails to load.

**Expected behavior**
I would expect Verovio to render the specific measures of the score with highlighted annotations on the first request as seen below:
<img width="1265" alt="Screenshot 2023-07-25 at 2 46 37 PM" src="https://github.com/rism-digital/verovio/assets/124386731/88e7b9b4-93ce-4612-acff-a2e690b96ec3">

**Verovio information**
 - This is on Verovio 3.16.0, but was also happening on 3.15.0.

**Environment information (as appropriate)**
 - OS: MacOS, but also happening on Windows
 - Browser: The issue is occurring in both Safari and Chrome. I have not tried it on other browsers.

**Code**
```Javascript
import React, { useEffect } from "react";
import ReactDOM from "react-dom";
import EmaMei from "./ema-mei.js";
import verovio from "verovio";
import { createRoot } from "react-dom/client";
import { render } from "react-dom";

const fetch = require("node-fetch");
const urlParams = new URLSearchParams(window.location.search);
const pieceURL = urlParams.get("pieceURL");
const ema_expression = urlParams.get("ema_expression");
const measure_range = JSON.parse(decodeURIComponent(urlParams.get("measure_range")));

const App = ({ pieceURL, ema_expression, measure_range }) => {
  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(pieceURL);
      const meiXML = await response.text();

      // Process EMA expression on the MEI data
      const processor = await EmaMei.withDocumentString(meiXML, ema_expression);
      const highlightedMei = await processor.getSelection();
      const selectedIds = await highlightedMei
        .querySelector("annot[type=ema_highlight]")
        .getAttribute("plist");

      // Render MEI data to Verovio
      const tk = new verovio.toolkit();
      tk.setOptions({
        scale: 50,
        adjustPageWidth: true,
      });
       tk.select(measure_range);
      tk.redoLayout();
      
      const svg =  tk.renderData(
        new XMLSerializer().serializeToString(highlightedMei),
        {}
      );

      const meiEl =  document.getElementById("mei");
      meiEl.innerHTML = svg;
      selectedIds.split(" ").map((id) => {
        const eventEl =  meiEl.querySelector(id);
        eventEl.style.fill = "red";
      });
    };

     fetchData();
  }, [pieceURL, ema_expression, measure_range]);

  return (
    <div className="App" style={{ width: "400px" }}>
      <h1>EMA Sandbox</h1>
      <h2>Verovio Score:</h2>
      <div id="mei" style={{ width: "400px" }}></div>
      <div className="panel-body">
        <div id="app" className="panel"></div>
      </div>
    </div>
  );
};

createRoot(document.getElementById("root")).render(
  <App
    pieceURL={pieceURL}
    ema_expression={ema_expression}
    measure_range={measure_range}
  />
);



export default App;
```

**Comment by lpugin** [comment]
The problem is very likely that you are not waiting for the `onRuntimeInitialized` to be triggered before creating the toolkit instance. That means that it can randomly fail or succeed depending if the module has loaded or not.

Have a look at the documentation here https://book.verovio.org/installing-or-building-from-sources/javascript-and-webassembly.html

You code should look like:
```js
verovio.module.onRuntimeInitialized = function ()
{
    // create the toolkit instance
    const vrvToolkit = new verovio.toolkit();
    // proceed with rendering
    ....
}

**Comment by eleon024** [comment]
After making the changes, it now seems to work more reliably and after refreshing only once!

**Comment by lpugin** [comment]
Good. Reliably, or just more reliably?

**Comment by eleon024** [comment]
Locally, it renders every time. When deployed on GitHub pages, just more reliably. It still fails occasionally. I will try deploying it on a different host or see if there's a way to run the javascript directly in Streamlit. I will keep you updated!

**Comment by lpugin** [comment]
What can you see in the console when it fails?
