### ISSUE TITLE
midi-player defunct? 

### ISSUE THREAD

**Issue by minusdavid** [rism-digital/verovio#3507]
Hi folks,

We're using both "verovio" and "midi-player" from rism-digital. I notice "verovio" seems quite active but "midi-player" does not. Is it defunct now?

**Comment by ahankinson** [comment]
I’m not sure what you mean. Verovio has a MIDI output, but we don’t produce any MIDI player. Do you have a link?

**Comment by ahankinson** [comment]
Ah I see. It’s just a wrapper around Wild Web MIDI as far as I can tell. Are you having specific problems with it?

**Comment by minusdavid** [comment]
Yeah, it's the wrapper around Wild Web MIDI at https://github.com/rism-digital/midi-player

I'm in the process of implementing a Content-Security-Policy which will prevent the inline "onclick" event handlers working for the Start/Pause/Stop buttons. 

I do have a pull request for it though: https://github.com/rism-digital/midi-player/pull/32
