### ISSUE TITLE
JS toolkit generates invalid MEI-Basic

### ISSUE THREAD

**Issue by musicog** [rism-digital/verovio#3529]
Discovered by @wergo 

**Describe the problem**
When loading a valid MEI 4.0.1 encoding as MEI-Basic, invalid MEI is generated.

**To Reproduce**
1. Inspect [this valid MEI 4.0.1 encoding](https://mei-friend.mdw.ac.at/?file=https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_WoO70_BreitkopfHaertel/master/Beethoven_WoO70-Breitkopf.mei) in mei-friend. Note that it validates successfully.
2. Click on `File->Save as MEI Basic` to generate an MEI Basic version using the Verovio JS Toolkit's `tk.getMEI({ basic: true })` and store the file locally
3. Open the generated file using `File->Open file` (or, [click here to open the GitHub gist I've uploaded](https://mei-friend.mdw.ac.at/?file=https://gist.githubusercontent.com/musicog/39754d97b2927c055ba59675aa085ced/raw/991f6832d2d1a497a28a98ef81fa7eab71a29b70/Beethoven_WoO70-Breitkopf-basic.mei) of the file). 
4. Note that mei-friend correctly loads the MEI 5.0 Basic schema, but the validator produces five validation errors:

```
Line 17: Did not expect element respStmt there
Line 22: Did not expect element encodingDesc there
Line 34: Did not expect element scoreDef there
Line 35: Element score has extra content: scoreDef
Line 65: Element scoreDef has extra content: pgFoot
```

**Expected behavior**
Valid MEI should produce valid MEI Basic.

**Input data**
Valid MEI 4.0.1 encoding: <https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_WoO70_BreitkopfHaertel/master/Beethoven_WoO70-Breitkopf.mei>
Invalid MEI 5.0 Basic encoding: <https://gist.githubusercontent.com/musicog/39754d97b2927c055ba59675aa085ced/raw/991f6832d2d1a497a28a98ef81fa7eab71a29b70/Beethoven_WoO70-Breitkopf-basic.mei>

**Verovio information**
 - Verovio 4.0.1a99660b, JavaScript toolkit
 - mei-friend v1.0.2

**Environment information (as appropriate)**
 - OS: MacOS 13.3.1
 - Browser: Firefox 117.0

**Comment by lpugin** [comment]
It would make sense to prune / adjust the header to something valid. I will see what I can do.
