### ISSUE TITLE
What version of Emscripten did you use?

### ISSUE THREAD

**Issue by ammatwain** [rism-digital/verovio#3533]
Hello everyone, lovely people! I'm a Verovio newbie. I've been trying to compile its WebAssembly version for days, but there's something escaping me, and at this point, I believe it might be in the compilation toolchain used by the Emscripten SDK. Before attempting all possible and imaginable combinations, I'll ask you: what version of Emscripten did you use to produce the code released on Npm?
Thank you in advance to anyone willing to pay attention to my requests. Have a great day, everyone!
Amedeo

**Comment by lpugin** [comment]
We use the latest stable version: 
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.45 (ef3e4e3b044de98e1811546e0bc605c65d3412f4)
clang version 18.0.0 (https://github.com/llvm/llvm-project d1e685df45dc5944b43d2547d0138cd4a3ee4efe)
```
What problems are you having?

**Comment by lpugin** [comment]
This looks similar to https://github.com/rism-digital/verovio/issues/3523. Which OS / Browser are you using?

**Comment by ammatwain** [comment]
OS: Ubuntu 22.04.3 LTS
BROWSER: Electron 25.8.0 (which should be chromium 114 based)
I used Emsdk version 3.1.47
...
BUT
...
Just about an hour ago, I installed emsdk version 3.1.45 as you suggested,
and the code recompiled with this version worked perfectly on the first
attempt!

I downgraded before reading the advice to clear the Chromium cache, so
right now, I can't tell you if this trick would have worked. I should
reinstall everything on a backup system and try to reproduce the issue by
installing Emsdk version 3.1.17, and I'll let you know.

**Comment by lpugin** [comment]
I opened an [issue](https://github.com/emscripten-core/emscripten/issues/20445) on emcripten-core.

**Comment by ammatwain** [comment]
Hi @lpugin,  I'm confirming what you already know. I reinstalled everything on a different machine and compiled with Emsdk 3.1.47: it doesn't work. I installed 3.1.45, and it works. I also recompiled with 3.1.45, setting Node to a very recent version, 20.8.0, and it continues to work (until this morning, I thought it was a Node version issue).

Hi Laurent, thank you for your support!
Amedeo
