### ISSUE TITLE
Verovio does not display neume components when providing their position in the staff with 'loc'

### ISSUE THREAD

**Issue by martha-thomae** [rism-digital/verovio#3534]
Neumes are not rendered when the `<nc>` does not have the pair of attributes `@pname` and `@oct` that define the pitch of a note. The issue is that sometimes we want to encode the position of the note without providing the interpretation of its pitch, for which we can use the `@loc` attribute of the neume component `<nc>` element. Currently, Verovio does not render the neume components when providing a`@loc` attribute in the `<nc>,` rather than a `@pname` and `@oct` attributes.

**Describe the solution you'd like:** That Verovio would display the `<nc>` when providing a `@loc` attribute on it.

#### Example of `<nc>` with `@pname` and `@oct` attributes - Verovio renders it
![nc_with_pname_and_oct](https://github.com/rism-digital/verovio/assets/13948831/101399de-2018-4aa0-a655-dd864f19d7a9)

#### Same example, but `<nc>` with `@loc` attribute - Verovio doesn't render it
![nc_with_loc](https://github.com/rism-digital/verovio/assets/13948831/f4670cc7-72ce-48e8-8f51-6d52ce90bc84)

Here are the two example files: [example_files.zip](https://github.com/rism-digital/verovio/files/12906623/example_files.zip)

**Comment by martha-thomae** [comment]
Could I get some help with this issue, @rettinghaus, @lpugin, @craigsapp? Maybe a pointer on where to look to implement this. Thank you!

**Comment by rettinghaus** [comment]
@martha-thomae I wanted to explain, but it seemed easier to just implement it.

**Comment by martha-thomae** [comment]
Oh, thank you @rettinghaus! :)
And thanks @lpugin for the revision.
