### ISSUE TITLE
Implement fontname attr support on clef and meterSig elements 

### ISSUE THREAD

**Issue by fernandoherreradelasheras** [rism-digital/verovio#3575]
It would be great to have support for using a different fontname for some of the symbols in the score.

My main use case for this is to include, as an indication, the first or two first measures of the score with the original keys, clefs and meters along the original initial notes so the reader can know what changes has been done in the transcription. This is a usual practice when editing early baroque music that involves meter adaptations (like for example the ternary CZ in the iberian baroque). For example: 
![Informational measures on a baroque score](https://github.com/rism-digital/verovio/assets/20201639/4fd40ff3-1671-4e35-8a9b-ed27b1aa02f8)

I have been trying to achieve this with MEI+verovio using different approaches and none of them worked out well:
* editorial content: cannot layout in the same line
* using mensural notation for one section and then switching to CMN: not supported and also the mensural symbols doesn't fit perfectly with the intended look. 
* rendering those measures from a separate score as an incipit and the importing it as a graphic: hard to get it looking nice and not responsibe
* add those specific bits as svgs symbolDef in the symbolTable and then use altsym="#xxx" to render a custom graphic: this was problematic because of the symbols rendered as svg are supported mostly for floating elements and getting anything in the staff with the proper size and spacing was too complicated. (At leas from playing with this code I got a cuple of bug fixed on the bounding boxes that will sumit later)

So at this point my only viable option was via custom font, but maybe I am missing something and there could be other options. This would look like this using MEI fontname attribute:
```
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Custom fonts</title>
         </titleStmt>
         <pubStmt>
            <date isodate="2024-01-21"/>
         </pubStmt>
         <seriesStmt>
            <title>Verovio test suite</title>
         </seriesStmt>
         <notesStmt>
            <annot>Verovio supports fontname attribute in clef and meterSig elements</annot>
         </notesStmt>
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application version="4.2.0" label="2">
               <name>Verovio</name>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef keysig="2s">
                  <meterSig glyph.num="U+E080" count="3" unit="2" fontname="Patriarca"/>
                  <staffGrp>
                     <staffDef n="1" lines="5">
                        <clef shape="G" line="2" glyph.name="gClef" glyph.num="U+E050" fontname="Patriarca"/>
                     </staffDef>
                     <staffDef n="2" lines="5">
                        <clef shape="G" line="2" fontname="Patriarca"/>
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <note dur="2" dots="1" oct="5" pname="g"/>
                           <note dur="4" oct="5" pname="g"/>
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <clef shape="G" line="2" glyph.name="gClef" glyph.num="U+E050"/>
                           <note dur="4" oct="4" pname="g" xml:id="n1"/>
                           <note dur="4" oct="4" pname="g"/>
                           <note dur="4" oct="4" pname="g"/>
                           <note dur="4" oct="4" pname="g"/>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

using different combinations of sym, glyph.num/name. I am using for this example "Patriarca" font, that was created by the Hispamus project based on another iberian font, "El Capitán". And the result is:
![custom fonts use with fontname attr](https://github.com/rism-digital/verovio/assets/20201639/c407b781-7cb8-444d-a089-3a1ca2c2fedd)

While implementing this and adding support for multiple music fonts I realized that the required changes are too deep and would require some discussion, knowing the plan from the team etc...

The current code I have is at: 

https://github.com/fernandoherreradelasheras/verovio/tree/fontname_for_meter_and_clef

with the part of loading/keeping/selecting those extra fonts added via addCustomFont option a bit patchy and hacky but I think good enough to kick some thinking and discussion about this.

That do you think?

Thanks!

**Comment by lpugin** [comment]
This looks like a good start. I created a dedicated `develop-fonts` branch to work on it. Could you:
* Make a PR to the `develop-fonts` branch
* Sign the CLA

? Thanks

**Comment by lpugin** [comment]
Your initial PR adding the custom font looks good. Since it relies on having the custom font in the resource directory, I would suggest to make the following modifications:
* Have a `--font-init-all` option to load all the fonts available in the resource directory as custom fonts. That way you would not need to do `--font-add-custom YourFont` specifically.
* Use `--font-add-custom` to load fonts passed as ZIP files. This is quite a significant development, but it would make it more useful for the JS binding.

**Comment by lpugin** [comment]
WIP here https://github.com/rism-digital/verovio/pull/3586
