### ISSUE TITLE
switch to CITATION.cff

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3579]
For releases on Zenodo it would be good to have a proper [CITATION.cff](https://citation-file-format.github.io/#/supported-by-zenodo-) file for the metadata to have e.g. all ORCID profiles linked. 

In order to not have to update the `CodeMeta` **and** `CITATION.cff` at the same time we could either replace the first by the latter or try to use the [CodeMeta2CFF](https://github.com/marketplace/actions/codemeta2cff) action.

**Comment by lpugin** [comment]
Thanks for the tip! I added one. It seems that Zenodo pulls the contributors from GitHub, so I don't think we want to have all the profiles listed there.

**Comment by lpugin** [comment]
As far I understand, having a `CITATION.cff` file means Zenodo will not pull contributors from the GitHub repository anymore. Am I wrong?

**Comment by rettinghaus** [comment]
Yes, that is the idea. 

However I think the `preferred-citation` is not correct, the paper should go into `references`, see https://github.com/citation-file-format/citation-file-format/tree/main/examples/1.2.0/pass/software-with-reference

Furthermore there are several known issues with the integration, see https://github.com/zenodo/zenodo/issues?q=is%3Aissue+is%3Aopen+Citation

**Comment by lpugin** [comment]
I think having the contributors pulled from the GitHub repository has a higher priority, so I am going to remove the `CITATION.cff` for now. We can have one once this is solved.

**Comment by lpugin** [comment]
Can be re-open once the Zenodo issue is solved.
