### ISSUE TITLE
Use Transposition Function in Verovio for Score in Concert Pitch

### ISSUE THREAD

**Issue by cividini** [rism-digital/verovio#3593]
I think it could be very useful for both practical (performance practice) and analytical (harmonic analysis) purposes to use the transposition function in Verovio in order to have the entire orchestral score in concert pitch (applying the existing transposition function selectively to the staves of the transposing instruments to bring them into concert pitch).

For example, in Mozart's Symphony in E-flat Major, K. 543:

<img src="https://github.com/rism-digital/verovio/assets/45197272/ee2aa836-a0c1-417f-b837-403937e2fad8" width="350"/>

the clarinets, horns, clarini (i.e. trumpets) and timpani would be written in E-flat major with the corresponding key signature and the corresponding pitch names like the other instruments.

The information needed for this is already given in `<scoreDef>` (`<keySig>`) and in the `<staffDef>` of the transposing instrument (`@keysig`, `@trans.diat` and/or `@trans.semi`).

It is important to note that since the beginning of the 20th century some composers have written orchestral scores entirely in concert pitch, e.g. the score of Prokofiev's Piano Concerto No. 1 (in D flat major):
https://s9.imslp.org/files/imglnks/usimg/a/a3/IMSLP66129-PMLP04499-Prokofiev_-_Piano_Concerto_No._1,_Op._10_(orch._score).pdf

**Comment by rettinghaus** [comment]
This is actually implemented already, see the options: `--transpose-to-sounding-pitch`
