### ISSUE TITLE
Notes rendered twice with tab notation

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#3600]
**Describe the problem**
When rendering tab notation, the note elements are rendered twice (one inside the other). The rendered SVG image looks ok, but the SVG DOM is incorrect.

**To Reproduce**
- Go to this link: http://mei-friend.mdw.ac.at/?file=https://raw.githubusercontent.com/wergo/tablature-ig/master/examples/lute/milano-1546_6-no_8.mei&scale=55&breaks=auto&page=1&speed=true&notationOrientation=left&notationProportion=0.58&facsimileOrientation=bottom&facsimileProportion=0.58
- Open developer tools of browser and
- Inspect a note in the rendered SVG
- The SVG tree looks like this:

<img width="606" alt="grafik" src="https://github.com/rism-digital/verovio/assets/45632600/5fc60c8d-ae52-4cd8-9e5a-5d7225531771">

**Expected behavior**
Only one `<g>` element of `class="note"` should be present.

**Verovio information**
 - Tested with Verovio JS toolkit versions 3.15 onwards to latest (4.1.0) with mei-friend

**Comment by wergo** [comment]
Thanks a lot!

**Comment by rettinghaus** [comment]
not yet merged
