### ISSUE TITLE
Fermata over rest removed after PAE normalization

### ISSUE THREAD

**Issue by carlolic** [rism-digital/verovio#3603]
**Describe the problem**
The normalization of PAE music using the method _renderToPAE()_ doesn't behave as expected in case of fermatas over rest. The problem is that fermatas over rest are removed after normalization. Example: 4(-) -> 4-

**Expected behavior**
Fermatas over rest shouldn't be deleted after normalization. Example: 4(-) -> 4(-)

**Comment by lpugin** [comment]
Solved with 383dcaf54fade21ceb206565a61b446edfa01ee4
