### ISSUE TITLE
Verovio.dll has no exports

### ISSUE THREAD

**Issue by andre2007** [rism-digital/verovio#3608]
**Describe the problem**
After creating the verovio.dll, `dumpbin /exports verovio.dll` shows that no functions are exported. Command `dumpbin /imports verovio.dll` gives the correct result.

Also trying to access a function from code fails, as the function does not exists.

**To Reproduce**
On Windows 11 install `Visual Studio Build Tools 2022` and `make`. Open `x64 Native Tools Command Prompt` and enter

```
cd cmake
cmake -G "Unix Makefiles" -DBUILD_AS_LIBRARY=ON .
make
```
The file `verovio.dll` is created succesfully.

**Expected behavior**
The command `dumpbin /exports verovio.dll` should give a list of functions, containing e.g. `enableLog, vrvToolkit_constructor`

**Input data**

**Verovio information**
 - Version of Verovio 4.1.0
 - Binding C

**Environment information (as appropriate)**
 - OS: Windows 11
 - Browser Chrome

**Screenshots**

![image](https://github.com/rism-digital/verovio/assets/1451047/e514b233-fdc6-4bec-b7a1-bec58a9c376d)

![image](https://github.com/rism-digital/verovio/assets/1451047/f8022e41-a830-4c08-b018-40acaa250052)

**Additional context**
If I understand it correctly, functions which should be exported in CMake needs the suffix _EXPORT?

See
https://stackoverflow.com/questions/77261094/how-do-i-specify-cmake-exports-macro-when-building-a-dll

**Comment by andre2007** [comment]
As workaround, argument `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` will export any symbol. This is a lot more, than needed, but seems to work until it is properly fixed via CMake configuration.

**Comment by lpugin** [comment]
That looks actually good to me. When it is built as a library there is not necessarily a reason for exporting all symbols. Users might want to do more than just creating a `Toolkit` instance or using the `C` wrapper functions.

**Comment by lpugin** [comment]
Could you check if this works https://github.com/rism-digital/verovio/commit/43e44f84fdfd9178867ebc10e9478af896e4317a ?

**Comment by andre2007** [comment]
@lpugin thanks for the fix, but this works only for win32 and not for win64. 

```
    if(WIN32)
		add_definitions(-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS)
    endif()
```

**Comment by Matthew-w56** [comment]
Would this same issue and situation be the cause to the discussion I opened here (https://github.com/rism-digital/verovio/discussions/3604)?  Basically, I build the dll but I can't get it to work with a c++ project. Just says everything isn't defined

**Comment by andre2007** [comment]
> ```
>     if(WIN32)
> 		add_definitions(-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS)
>     endif()
> ```
> 
> ChatGPT 3.5 is saying that this also works for 64-bit Windows:
> 
> <img alt="Screenshot 2024-02-27 at 10 29 17" width="665" src="https://private-user-images.githubusercontent.com/3487289/308293789-8c287539-ad6c-4d1b-a06a-1fbcd45ad181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjA2MDQsIm5iZiI6MTcwOTA2MDMwNCwicGF0aCI6Ii8zNDg3Mjg5LzMwODI5Mzc4OS04YzI4NzUzOS1hZDZjLTRkMWItYTA2YS0xZmJjZDQ1YWQxODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTg1ODI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZjMDc4YWRiZWNhNWNlZjc0OTEzOTRjNjFmMGJlMmVlYTA0ZGZkOGIzOWMzYWNhNzAwNWI3ODAyYThmZWJiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yGs9DuNVlTckWiZpVZkraMD_Gv1AfpS8zJzTpZWBeIM">

I tested it with a x64 toolchain on windows 11 and dumpbin showed that nothing was exported, therefore I think WIN32 condition is not sufficient.

**Comment by andre2007** [comment]
> Would this same issue and situation be the cause to the discussion I opened here (#3604)? Basically, I build the dll but I can't get it to work with a c++ project. Just says everything isn't defined

Likely it is the same issue. You can check with a dll viewer like dumpbin (contained in Microsoft Build Tools) or any other tool, whether the Dll you build, contains export functions.

**Comment by Matthew-w56** [comment]
Okay.  I did what you did with the flag, and got it to list something like 24K names and functions.  However, when I attempt to add them into my visual studio project, it still says toolkit.h and vrv.h are undefined..

**Comment by andre2007** [comment]
> Okay. I did what you did with the flag, and got it to list something like 24K names and functions. However, when I attempt to add them into my visual studio project, it still says toolkit.h and vrv.h are undefined..

Sorry, I am not a c++ developer ( I am using the D Programming Language). For D, dynamically accessing the exported functions works fine.

**Comment by Matthew-w56** [comment]
Okay no worries.  Ideally I'd access the functions through either a Dart or Rust FFI.  Would this dll be ready for a conversion process to a FFI?  I haven't done much with building libraries so I'm pretty lost sorry

**Comment by Matthew-w56** [comment]
Or, rather, what steps do you need to do to export the C interface specifically?  The build instructions really only cover how to build the command line tool but I'd like to interact more programmatically with it

**Comment by lpugin** [comment]
@andre2007 could you make a PR with what works for you? Thanks

**Comment by andre2007** [comment]
> @andre2007 could you make a PR with what works for you? Thanks

So far only the command line argument works. I can make a pull request for the C binding readme (https://github.com/rism-digital/verovio/blob/develop/bindings/c/README.md), describing the steps to build it on windows using MS build tools.

**Comment by Matthew-w56** [comment]
Oh wow okay I was unaware that there were specific README files for each binding.  I will follow that, thank you for mentioning that!  Some mention in the main readme or in the reference book that there are other readmes would be a lifesaver for others.

**Comment by andre2007** [comment]
Pull request for the readme https://github.com/rism-digital/verovio/pull/3609

**Comment by andre2007** [comment]
Closing this issue as solved, thanks.
