### ISSUE TITLE
Probable issues with locale

### ISSUE THREAD

**Issue by ammatwain** [rism-digital/verovio#3610]
Hello, fantastic Verovio!

I noticed that in `vrv.cpp`, the method `std::string StringFormat(const char *fmt, ...)` produces inconsistent results. For example, when compiling with QtCreator under Linux, in the SVG output of the Verovio logo, the values of `scale(x y)` become `scale(10,000000, 10,000000)` instead of `scale(10 10)`, which means four values separated by commas, effectively rendering the logo illegible.

I resolved this by modifying the method as follows:
Before any other instruction: `std::locale previousLocale = std::locale::global(std::locale("C"));`
Before the return statement: `std::locale::global(previousLocale);`

I hope this is helpful.

Have a great day!
@ammatwain

**Comment by lpugin** [comment]
Thanks. Could you make a PR so we can see if the builds properly on all platforms?

**Comment by craigsapp** [comment]
Similar to issue https://github.com/rism-digital/verovio/issues/975 where I was too lazy to fix it, and your solution is likely better than mine (I would have probably used `stringstream` to format floating-point numbers, which may avoid locale problems).

**Comment by lpugin** [comment]
Fixed with https://github.com/rism-digital/verovio/pull/3611
