### ISSUE TITLE
c_wrapper is missing functions compared to the documentation (toolkit-methods.html)

### ISSUE THREAD

**Issue by andre2007** [rism-digital/verovio#3612]
The c_wrapper 
https://github.com/rism-digital/verovio/blob/05b107209d013238173e0e12180518fe65531bd8/tools/c_wrapper.h#L1 is missing functions which are mentioned here: https://book.verovio.org/toolkit-reference/toolkit-methods.html

These are the missing functions:
- editInfo
- GetHumdrumFile
- GetID
- GetResourcePath
- GetTimesForElement
- getscale
- loadFile
- PrintOptionUsage
- RenderToExpansionMapFile
- RenderToMIDIFile
- RenderToPAEFile
- RenderToSVGFile
- RenderToTimemapFile
- SaveFile
- SetInputFrom
- SetOutputTo
- SetResourcePath
- SetScale
- ValidatePAEFile

What I also noticed, there is difference between the C function RenderToMIDI which has an argument `c_options`
https://github.com/rism-digital/verovio/blob/05b107209d013238173e0e12180518fe65531bd8/tools/c_wrapper.h#L51 but this argument is not mentioned on the toolkit-methods.html page. The C++ method does not have this argument `std::string vrv::Toolkit::RenderToMIDI()`

**Comment by rettinghaus** [comment]
I guess the c wrapper wasn't in focus for some time. It would be good if you could open a PR to bring it in line with Python and wasm.

**Comment by andre2007** [comment]
I do not have C or C++ knowledge but I will try to add the missing functions by imitating the existing functions. (My main language is D ) .
I also plan to add a D wrapper to Verovio when the C functions are on pair with the C++ Toolkit methods.

**Comment by Matthew-w56** [comment]
It's worth noting that two of these methods have implementations in the c_wrapper.cpp already, namely:

- editInfo
- GetTimesForElement

**Comment by andre2007** [comment]
@Matthew-w56 
I do not know how it exactly works, but the functions (editInfo, GetTimesForElement)  are missing in the file `c_wrapper.h` while they exists in `c_wrapper.cpp`. Therefore I thought, they are not exported to the shared library file. I will include the functions in the header file.

**Comment by andre2007** [comment]
Pull request: https://github.com/rism-digital/verovio/pull/3615

All toolkit methods added except PrintOptionUsage (has an std::ostream argument)
