### ISSUE TITLE
Program Crashes after Edit Toolkit Update

### ISSUE THREAD

**Issue by Matthew-w56** [rism-digital/verovio#3614]
### Discussed in https://github.com/rism-digital/verovio/discussions/3613

Hello everybody!  I opened this discussion, but as I look into it, it strikes me as possibly some bug somewhere, so I'm opening up an issue.  Then if it turns out not to be an issue we can just close this and use the discussion, and if it is an issue, we can close the discussion and use this thread.

In original post below, (1) was really just a question, while (2) points out my issue, which is: If I try to render my score after making edit actions (which report to succeed), then the whole thing crashes and I don't get any feedback as to why.  Any insights into this?

<div type='discussions-op-text'>

<sup>Originally posted by **Matthew-w56** March  2, 2024</sup>
Hello!

I really like your library, and I am in the process of using for a sheet music editing application.  But refeeding an entire score and re-rendering each edit is obviously much too slow (~1 second per page).  I notice that there is an edit functionality, to edit the internal representation directly.  That's great!  I have a few questions about it:

1) The documentation page says that it is still experimental.  Does it have enough functionality to support an editing application?  Is the experimental tag an out-of-date relic?

2) I can get it to delete a note (by reverse engineering the syntax expected), but when I try to render SVG from an edited score, it crashes.  At the same time, if I save the edited version to MEI and then load and render THAT to svg, it works just fine.  What might I be missing here?  Is it something to do with whatever "commit" does?

Thanks for the help!
Matthew Williams

My Code (written in Dart, through a FFI binding) (for reference):

```dart
  static final _binding = VerovioWrapper(DynamicLibrary.open("path-to-dll"));
  final _toolkitPointer = _binding.vrvToolkit_constructorResourcePath("path-to-resource-folder".toNativeUtf8().cast());
  String content = IOWorker.getFileText("normal-mei-file.mei");
  _binding.vrvToolkit_loadData(_toolkitPointer, _stringToCharPointer(content));
  verovio.executeEdit("{'action': 'delete', 'param': {'elementId': 'd1e966'}}");
  verovio.executeEdit("{'action': 'commit', 'param': {}}");
  // This svg render is what crashes the program
  String svgContent = _charPointerToString(_binding.vrvToolkit_renderToSVG(_toolkitPointer, 1, false));
  File file = File("my-desktop-path/alteredOutput.svg");
  file.writeAsString(svgContent);
```

</div>

**Comment by craigsapp** [comment]
I just tried the MacOS command-line non-editing version of verovio on the current `develop` branch, and it is behaving, so likely related to the editing code and not a new but in the rendering code.

**Comment by Matthew-w56** [comment]
Yeah, sorry if that wasn't clear.  Rendering works just fine, and the editing is doing the job it should (when I save the mei after editing, then reload that new file and render it, it all works just fine).  The problem is that if I directly try to edit and re render the score, then it crashes.

**Comment by Matthew-w56** [comment]
Relevant info for anyone more familiar with the system than I who might try to look into this issue:

When I put in a ton of log statements to track where it breaks down, it gives some really weird behavior.  Even when just trying to draw the first page of a 1-page score (after an edit, of course), the logs show the program going into and out of the view_page DrawCurrentPage method multiple times.  The first 2 or 3 times it will still log that it enters the loop to draw elements and systems, but eventually it does in and out a few times not logging any entry into the loop, then just stops somewhere within that method.

**Comment by Matthew-w56** [comment]
Okay I found and fixed that problem, PR link:
https://github.com/rism-digital/verovio/pull/3617
