### ISSUE TITLE
In Python 3 and Windows environment, the redoLayout method seems to cause Python to crash.

### ISSUE THREAD

**Issue by RichardFreedman** [rism-digital/verovio#3624]
Below is code that will take in MEI, then render just a selection of measures (as for an incipit or example).  It works fine in Mac and in Google Collab.  But in a Windows environment the `redoLayout() `method will cause the kernel to crash.  If we leave this method out of the code--no problem.  But in that case we render the entire piece, and not the selection.

```
import urllib.request
import verovio
from IPython.display import SVG, HTML

# file to import:
url = 'https://crimproject.org/mei/CRIM_Model_0008.mei'

# Open the URL and read the content
with urllib.request.urlopen(url) as response:
    fetched_mei_string = response.read().decode('utf-8')

tk = verovio.toolkit()
tk.loadData(fetched_mei_string)
tk.setScale(30)
tk.setOptions({"pageHeight":  1200, 
               "pageWidth":  1500    
               })

mr = str(1) + "-" + str(2)
mdict = {'measureRange': mr}

tk.select(mdict)
tk.redoLayout()

count = tk.getPageCount()
for c in range(1, count + 1):
    music = tk.renderToSVG(c)
    display(SVG(music))
```

**Comment by RichardFreedman** [comment]
After further experimentation, we notice that the problem does NOT occur with Verovio 3.15.0.  We have not yet tested with versions between 3.15 and the current one.  But perhaps this is a clue.

**Comment by bigorenski** [comment]
Same on android

**Comment by lpugin** [comment]
@bigorenski your log does not have a call to `RedoLayout`, does it?

**Comment by bigorenski** [comment]
> @bigorenski your log does not have a call to `RedoLayout`, does it?

It doesn't.

Same thing happens if I call tk->select before loading a file, or RedoLayout after loading a file, but I don't see the call in the logs. I couldn't understand why

**Comment by lpugin** [comment]
I am closing the issue since there is not enough information to do anything about it. Please re-open with more details if needed.
