### ISSUE TITLE
Dynamics not centered between staves

### ISSUE THREAD

**Issue by Matthew-w56** [rism-digital/verovio#3626]
**Describe the problem**
I am rendering a piece from a repository of sample encodings in MEI and the dynamics are drawing off center from where they should be. (too high or low)

**To Reproduce**
1. Load data linked to here: https://github.com/music-encoding/sample-encodings/blob/main/MEI_5.0/Music/Complete_examples/Joplin_Maple_leaf_Rag.mei
2. Render page 1 (only page)
3. See error multiple times throughout piece, namely measures 1, 8, 10, 19, 36

**Expected behavior**
Dynamics drawn equally spaced between staves, like in this pdf of the same song from the same repository of encodings:

**Input data**
https://github.com/music-encoding/sample-encodings/blob/main/MEI_5.0/Music/Complete_examples/Joplin_Maple_leaf_Rag.mei

**Verovio information**
 - Version of Verovio: develop, latest version
 - Binding command-line (built as library and used as dll)

**Environment information (as appropriate)**
 - OS: Windows
 - Browser N/A

**Screenshots**
Seen:
![line](https://github.com/rism-digital/verovio/assets/26423158/a0f24127-69f4-4b6f-abd0-26bb4388d75d)

Expected:
![right](https://github.com/rism-digital/verovio/assets/26423158/53238e54-bd8a-44ef-ae37-08120aece348)

**Comment by craigsapp** [comment]
That is a problem in the data not the renderer.    This score was produced before `@place="between"` was invented.   Change first forte for example to:

```
<dynam  place="between" staff="1 2" tstamp="1">f</dynam>
```

More modern version: 
[mapleleaf.zip](https://github.com/rism-digital/verovio/files/14644851/mapleleaf.zip)

First measure:

<img width="233" alt="Screenshot 2024-03-18 at 20 21 55" src="https://github.com/rism-digital/verovio/assets/3487289/539be93f-b552-4e86-9a87-af4cb03a9082">

Original source:
<img width="272" alt="Screenshot 2024-03-18 at 20 21 44" src="https://github.com/rism-digital/verovio/assets/3487289/ee1fbe5c-e494-46d5-a3c4-ce3732ee9611">

For the piano, there is an interaction with text "l.h." and "r.h.":

<img width="314" alt="Screenshot 2024-03-18 at 20 22 46" src="https://github.com/rism-digital/verovio/assets/3487289/205a12cf-9b9c-48b9-80bb-c34b53af390c">

There *is* a problem when there is text near the `@place="between"` dynamic:
<img width="220" alt="Screenshot 2024-03-18 at 20 27 26" src="https://github.com/rism-digital/verovio/assets/3487289/bfc45fac-da5d-45e1-8336-8fff3b2e12ba">

But with no text, the dynamic is placed properly:

<img width="225" alt="Screenshot 2024-03-18 at 20 27 45" src="https://github.com/rism-digital/verovio/assets/3487289/511cc217-ea09-4a8f-b48d-0ddb155dccf8">

`mf` example:

<img width="561" alt="Screenshot 2024-03-18 at 20 29 10" src="https://github.com/rism-digital/verovio/assets/3487289/a2fb4174-2319-4ff4-bfc8-f42c0611394f">

Verovio centers literally between the staves, not in the space left over:

<img width="400" alt="Screenshot 2024-03-18 at 20 29 36" src="https://github.com/rism-digital/verovio/assets/3487289/69a0dae2-bad8-4254-8487-852eddc239e6">

**Comment by Matthew-w56** [comment]
Thank you, I was unfamiliar with that tag

**Comment by craigsapp** [comment]
Initial discussion about adding it (from 2016):
https://github.com/music-encoding/music-encoding/issues/331
(and the example was encoded in 2011).

It is not easy to find, but here are the "between" and "within" values for `@place` which are labeled as "extended":

https://music-encoding.org/guidelines/v5/data-types/data.STAFFREL.extended.html
