### ISSUE TITLE
Missing SMuFL codes for ornamental neume-components in square notation

### ISSUE THREAD

**Issue by martha-thomae** [rism-digital/verovio#3627]
We are missing some SMuFL symbols for some "ornamental" neumes in square notation: quilisma, oriscus, and liquescent. These are just rendered as regular square neume components (like punctums), when they should be rendered differently. However, these "ornamental neumes" are already supported with SMuFL. In this issue, I am including the MEI code for each of these ornamental neumes and their suggested SMuFL code:

### (i) Quilisma

- MEI Encoding:
  ```xml
  <nc>
    <quilisma/>
  </nc>
  ```

- Proposed SMuFL code: 
**U+E99B** (_chantQuilisma_) in [Medieval and Renaissance plainchant single-note forms](https://w3c.github.io/smufl/latest/tables/medieval-and-renaissance-plainchant-single-note-forms.html)

  <img src="https://github.com/rism-digital/verovio/assets/13948831/210e2f22-c750-45c6-b0ae-afeaa741dbe3" alt="drawing" width="350"/>

### (ii) Oriscus

  - MEI Encoding:
    ```xml
    <nc>
      <oriscus/>
    </nc>
    ```

  - Proposed SMuFL code: 
  **U+EA2A** (_medRenOriscusCMN_) in [Medieval and Renaissance plainchant in CMN](https://w3c.github.io/smufl/latest/tables/medieval-and-renaissance-symbols-in-cmn.html)

    <img src="https://github.com/rism-digital/verovio/assets/13948831/31fce5c3-e885-42a2-87d8-2cf5f7a89c89" alt="drawing" width="350"/>

###  (iii) Liquescent as small punctum
  This liquescent looks like a small square note. It can happen in two instances: **(Case A)** in a neume with a single component but no `@curve`; or **(Case B)** in a neume with at least two neume components (one of them with a `liquescent`). 

  - **Case A:** MEI Encoding (neume with only one `<nc>`, no `@curve` in the `<nc>`)
    ```xml
    <neume>
      <nc>
        <liquescent/>
      </nc>
    </neume>
    ```

  - **Case B:** MEI Encoding (neume with at least two `<nc>`)
    ```xml
    <neume>
      <nc/>
      ...
      <nc>
        <liquescent/>
      </nc>
      ...
      <nc/>
    </neume>
    ```

  - Proposed SMuFL code: 
  **U+E9A1** (_chantPunctumDeminutum_) in [Medieval and Renaissance plainchant single-note forms](https://w3c.github.io/smufl/latest/tables/medieval-and-renaissance-plainchant-single-note-forms.html)

    <img src="https://github.com/rism-digital/verovio/assets/13948831/18133aa6-b5e6-4b1e-94a6-05331101fcf0" alt="drawing" width="350"/>

### (iv) Two-tails liquescent (single neume component, it includes `@curve`)
  Liquescent with two tails up or down (depending on the `@curve` attribute). It is made up of a neume with a single component (a `<neume>` with only one child `<nc>`, which has a `<liquescent>`). The one `<nc>` has a `@curve`.

#### Two tails down

  - MEI Encoding:
    ```xml
    <neume>
      <nc curve="c">
        <liquescent/>
      </nc>
    </neume>
    ```

  - Proposed symbol: 
    The one in Neon with two tails down 
![two_tails_down](https://github.com/rism-digital/verovio/assets/13948831/b5f6060d-f8ea-41af-bdc2-507084be94b8)

#### Two tails up

  - MEI Encoding:
    ```xml
    <neume>
      <nc curve="a">
        <liquescent/>
      </nc>
    </neume>
    ```

  - Proposed symbol: 
    The one in Neon with two tails up 
![two_tails_up](https://github.com/rism-digital/verovio/assets/13948831/4f0c33ad-e490-4aa5-9fab-a69d9c5a3f05)

Neon interface: the 'insert' panel contains the examples of the two-tails up/down liquescent (I am not sure how these were implemented)
![Neon](https://github.com/rism-digital/verovio/assets/13948831/4faaa916-b346-4e55-b22f-612102e3d233)

Thank you!

**Comment by lpugin** [comment]
> Neon interface: the 'insert' panel contains the examples of the two-tails up/down liquescent (I am not sure how these were implemented)

Yes, Neon uses a fork. We are working on merging it into this repository and make Neon use it.

**Comment by martha-thomae** [comment]
> Yes, Neon uses a fork. We are working on merging it into this repository and make Neon use it.

Perfect! That would be awesome. Sorry to bother you with this question, but do you already have a timeframe for this?


And what about the other symbols? Given that they are already in SMuFL, would they be easy to include in Verovio for the corresponding MEI encodings?

Thanks, Laurent!

**Comment by martha-thomae** [comment]
Hi @lpugin!

Now that the Neon changes are integrated into Verovio, liquescents with a `@curve` in their corresponding `<nc>` parent element look perfect! In the green region of the following screenshot, you can see how these liquescents are distinguished from the regular punctum: the first glyph is a regular punctum `<nc>`, while the following two are `<nc curve="c"><liquescent/></nc>` and `<nc curve="a"><liquescent/></nc>`. So this behaves as expected and solves case **(iv)** of the [abovementioned cases](https://github.com/rism-digital/verovio/issues/3627#issue-2193808150). Thank you and thanks @yinanazhou! 

![ornamental_neumeshapes copy](https://github.com/rism-digital/verovio/assets/13948831/0bc41266-6a98-4472-8f3e-ff2dcb8f4fd0)

---

Now, the only ornamental neume shapes missing are the ones in the red region of the screenshot, as (currently) they are not distinguishable from a regular punctum. These ornamental neume shapes are described in the [original issue](https://github.com/rism-digital/verovio/issues/3627#issue-2193808150): **(i) quilisma**, **(ii) oriscus**, and **(iii) liquescent punctum** (i.e., a liquescent whose `<nc>` doesn't have any `@curve`).

The [original issue](https://github.com/rism-digital/verovio/issues/3627#issue-2193808150) describes the SMuFL codes to use for these three ornamental neume shapes and their corresponding MEI code. Would this be easy to implement, @lpugin? Do you think we can have it ready for MedRen at the beginning of July (or sooner to prepare for it)?

I am providing here the MEI code to test this. This is the same MEI code used for rendering what you saw on the screenshot.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title/>
         </titleStmt>
         <pubStmt/>
      </fileDesc>
      <encodingDesc xml:id="e4mfxqk2">
         <appInfo xml:id="ac53ewi2">
            <application xml:id="a5cawx9" enddate="2024-05-27T12:11:47" startdate="2024-05-27T11:57:31" version="1.0.14">
               <name xml:id="nyaqhsr1">mei-friend</name>
               <p xml:id="pct1sxm2">First edit by mei-friend 1.0.14, 23 May 2024.</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef clef.line="3" clef.shape="C" lines="4" n="1" notationtype="neume"/>
                  </staffGrp>
               </scoreDef>
               <section>
                  <staff n="1">
                     <layer n="1">
                        <syllable xml:id="regPuncum_syllable">
                           <syl xml:id="regPuncum_syl">regPunctum</syl>
                           <neume xml:id="regPuncum_neume">
                              <nc xml:id="regPuncum_nc" pname="d" oct="3"/>
                           </neume>
                        </syllable>
                        <syllable xml:id="liqCurveC_syllable">
                           <syl xml:id="liqCurveC_syl">liqCurveC</syl>
                           <neume xml:id="liqCurveC_neume">
                              <nc xml:id="liqCurveC_nc" pname="d" oct="3" curve="c">
                              	<liquescent/>
                              </nc>
                           </neume>
                        </syllable>
                        <syllable xml:id="liqCurveA_syllable">
                           <syl xml:id="liqCurveA_syl">liqCurveA</syl>
                           <neume xml:id="liqCurveA_neume">
                              <nc xml:id="liqCurveA_nc" pname="d" oct="3" curve="a">
                              	<liquescent/>
                              </nc>
                           </neume>
                        </syllable>
                        <syllable xml:id="liqNoCurve_syllable">
                           <syl xml:id="liqNoCurve_syl">liqNoCurve</syl>
                           <neume xml:id="liqNoCurve_neume">
                              <nc xml:id="liqNoCurve_nc" pname="d" oct="3">
                              	<liquescent/>
                              </nc>
                           </neume>
                        </syllable>
                        <syllable xml:id="quilisma_syllable">
                           <syl xml:id="quilisma_syl">quilisma</syl>
                           <neume xml:id="quilisma_neume">
                              <nc xml:id="quilisma_nc" pname="d" oct="3">
                              	<quilisma/>
                              </nc>
                           </neume>
                        </syllable>
                        <syllable xml:id="oriscus_syllable">
                           <syl xml:id="oriscus_syl">oriscus</syl>
                           <neume xml:id="oriscus_neume">
                              <nc xml:id="oriscus_nc" pname="d" oct="3">
                              	<oriscus/>
                              </nc>
                           </neume>
                        </syllable>
                     </layer>
                  </staff>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by martha-thomae** [comment]
Hello @rettinghaus and @lpugin! I was wondering how is this issue going and if you need any more information from our side? Thank you!

**Comment by lpugin** [comment]
I am working on it. I've done some more significant refactoring than planned, but it will be ready before MedRen.

**Comment by martha-thomae** [comment]
Thank you so much, Laurent!

(From Elsa and Martha)

**Comment by lpugin** [comment]
@martha-thomae please review the [PR](https://github.com/rism-digital/verovio/pull/3718)

**Comment by martha-thomae** [comment]
Thank you, Laurent! Although I wasn't able to check it when you tagged me, this looks awesome! I did find a related issue, though, which you can see in #3720. When using a one-line staff and ornamental figures (e.g., liquescents), the whole text and the ornamental figures get rendered way below the rest of the music. Could you please take a look at #3720? Thank you so much!
