### ISSUE TITLE
justifyVertically not working on last page

### ISSUE THREAD

**Issue by riscodes** [rism-digital/verovio#3631]
It seems justifyVertically option is not working for last page when using the Javascript library since justifyIncludeLast option was removed in version 2.2.0 ([here](https://github.com/rism-ch/verovio/pull/1671)).

To reproduce the issue, use the full example code from the manual ([here](https://book.verovio.org/interactive-notation/css-and-svg.html#full-example)) and add justifyVertically: true and breaks: 'line' to the options (also can change pageHeight and pageWidth to a fixed size of 2700 and 2100 and zoom to 30 for easier viewing).

First page rendering works as expected with the correct vertical justification, but when rendering the second page the vertical justification does not work.

<img width="649" alt="page1" src="https://github.com/rism-digital/verovio/assets/52918630/ad6b5fae-fe37-4a9a-9d2f-ccfeed4027ab">
<img width="654" alt="page2" src="https://github.com/rism-digital/verovio/assets/52918630/d33fa697-25d1-4f95-b846-be39856cb8c3">

Thanks!

**Comment by craigsapp** [comment]
This could potentially be related to the option:

```
 --justification-max-vertical <f>	Maximum ratio of justifiable height to page height that can be used for the vertical justification (default: 0.30; min: 0.00; max: 1.00)
```

Although the last page seems to be about 0.50 full which is more than the default value of 0.30.   Or maybe 0.30 means that the score has to be at least 0.70 of the page height.
