### ISSUE TITLE
Classical guitar example rendered an octave too high

### ISSUE THREAD

**Issue by paul-bayleaf** [rism-digital/verovio#3641]
**Describe the problem**
Classical guitar music is played an octave lower than notated, this enables a single stave with a G suboctave clef to cover the whole range of the instrument.  In the sample encodings for MEI there is a classical guitar piece, Aguado-Walzer_G-dur, but when rendered with Verovio all the notes are rendered one octave too high.

Original image of the first bar:
![original-1st-bar](https://github.com/rism-digital/verovio/assets/76966668/8c62a6fd-8ac9-42e0-978d-562447420111)

Verovio rendering of first bar:
![verovio-1st-bar](https://github.com/rism-digital/verovio/assets/76966668/c2207eb2-434a-4674-ba9c-895b982722c1)

**To Reproduce**
Render  https://github.com/music-encoding/sample-encodings/blob/main/MEI_5.0/Music/Complete_examples/Aguado_Walzer_G-major.mei

Compare with original: https://github.com/music-encoding/sample-encodings/blob/main/MEI_5.0/Music/Complete_examples/Aguado_Walzer_G-major.pdf

**Expected behavior**
Notes should be rendered an octave lower.

**Input data**
The smallest example (MEI unless about another input format) to reproduce the problem

     <?xml version="1.0" standalone="no"?>
    <mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Cut down</title>
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
        </encodingDesc>
        <workList>
            <work>
                <title>Cut down</title>
            </work>
        </workList>
    </meiHead>
    <music>
        <body>
            <mdiv n="1">
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" clef.line="2" clef.shape="G" clef.dis="8" clef.dis.place="below" lines="5"/>
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure n="1" xml:id="d30278e50">
                          <staff n="1">
                              <layer n="1">
                                  <note pname="b" oct="4" dur="4" stem.dir="down"/>
                              </layer>
                           </staff>
                       </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
    </mei>

Should render the single note as B4, not as B5.  I'm assuming here that the sample MEI encoding is correct: in it all pitches are encoded one octave higher than the sounding pitch.

**Verovio information**
Built this morning from develop branch.

**Environment information (as appropriate)**
OpenSUSE 15.5

**Comment by rettinghaus** [comment]
As you can see in the example (`revisionDesc`) this file came from a [Capella](https://www.capella-software.com/) file, which ha been exported to MusicXML and then converted into MEI 14 years ago. I can only assume that some information was lost along the way. But IMHO this isn't a Verovio issue at all but a problem with the used encoding. Please file a report over at https://github.com/music-encoding/sample-encodings/
