### ISSUE TITLE
Half note up stem issue

### ISSUE THREAD

**Issue by ammatwain** [rism-digital/verovio#3652]
Hello fantastic Verovio team, I continue to use your toolkit with satisfaction and enjoyment!
I hope not to duplicate the reporting of an already known issue by mentioning that the stem of the half note, when facing upwards, appears horizontally misaligned with its head.

![Screenshot_20240421_111529](https://github.com/rism-digital/verovio/assets/8464862/9f7765b0-d8be-4fa1-8751-01393d196af8)

I realize it's a minor problem, but Verovio renders music scores very well, which makes this small imperfection even more noticeable!

Have a great day everyone!

ammatwain

**Comment by ahankinson** [comment]
I suspect this is a problem with the file you are using. Could you please include a file with a minimal encoding of the problem, as well as what version of Verovio you are using?

**Comment by craigsapp** [comment]
For example, a simple case sees to work:

<img width="381" alt="Screenshot 2024-04-21 at 8 40 49 PM" src="https://github.com/rism-digital/verovio/assets/3487289/6c3825ad-503c-4a7b-8669-0475d481b8d4">


<details>
<summary> Click to view MEI data for above example. </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2024-04-21T20:40:52" version="4.2.0-dev-3d89370-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml" />
  </extMeta>
 </meiHead>
 <music decls="#work1_encoded">
  <body>
   <mdiv xml:id="mx1gwcy">
    <score xml:id="sb65926">
     <scoreDef xml:id="s13nwws">
      <staffGrp xml:id="s192mvws" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-L1F2" n="1" lines="5">
        <clef xml:id="c16p4xca" shape="G" line="2" />
       </staffDef>
       <staffDef xml:id="staffdef-L1F1" n="2" lines="5">
        <clef xml:id="c15qzcw1" shape="F" line="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" right="invis">
       <staff xml:id="staff-L1F2" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L3F3" dots="1" dur="2" oct="4" pname="g" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L1F4N2" n="2">
         <chord xml:id="chord-L3F4" dots="1" dur="2">
          <note xml:id="note-L3F4S1" oct="4" pname="d" accid.ges="n" />
          <note xml:id="note-L3F4S2" oct="3" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <staff xml:id="staff-L1F1" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dots="1" dur="2" oct="2" pname="b" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L1F2N2" n="2">
         <chord xml:id="chord-L3F2" dots="1" dur="2">
          <note xml:id="note-L3F2S1" oct="2" pname="d" accid.ges="n" />
          <note xml:id="note-L3F2S2" oct="2" pname="f" accid.ges="n" />
         </chord>
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>


Possibly a font-related problem, but I tried in Bravura, Gootville, Leipzig, Leland, and Petaluma, and I did not see any problems. (Bravura shown above.)

**Comment by ammatwain** [comment]
I think you are absolutely right, it must be a coding or font problem. I'm using the development version of verovio on a very recent, non-LTS, Ubuntu distro.
On another distro, LTS this problem does not exist.
Although it's probably a procedural error on my part.
I'm trying to figure out where I'm going wrong, thanks everyone for the assistance
