### ISSUE TITLE
JavaScript error in verovio-reference-book

### ISSUE THREAD

**Issue by raiatea** [rism-digital/verovio#3659]
Some scripts include the code:
`<script src="https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js" defer></script>`

The execution generates an error:
An error occurred when loading the file!
TypeError: this.VerovioModule.HEAPU8 is undefined

Seems to work with:
`<script src="https://www.verovio.org/javascript/latest/verovio-toolkit-wasm.js" defer></script>`

**Comment by lpugin** [comment]
Please reopen with more browser / OS information if necessary

**Comment by ahankinson** [comment]
The Verovio Book works for me on Safari and Chrome.

**Comment by raiatea** [comment]
The issue is in the javascript p.24-25 in the PDF downloaded from this [page](https://book.verovio.org/) Verovio version 4.2 Generated on 16 May 2024
Tested on Windows 10 with Firefox 126.0 .and Microsoft Edge 124.0

The javascript example p.24-25 is copied in a file Verovio_p24.html [Verovio_p24.zip](https://github.com/rism-digital/verovio/files/15347316/Verovio_p24.zip)

The example is opened in a browser.
The display shows a button "Save my MEI!", and nothing else. The MEI is saved is an empty file.

Error displayed in the console of the Developer tool of Firefox :
> An error occurred when loading the file! [Verovio_p24.html:34:9](file:///C:/Temp/Verovio_p24.html)
> TypeError: this.VerovioModule.HEAPU8 is undefined
>     loadZipDataBuffer https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:290
>     onRuntimeInitialized file:///C:/Temp/Verovio_p24.html:30
>     promise callback*verovio.module.onRuntimeInitialized file:///C:/Temp/Verovio_p24.html:29
>     doRun https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     run https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     runCaller https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     removeRunDependency https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     receiveInstance https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     receiveInstantiationResult https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     promise callback*instantiateArrayBuffer https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     instantiateAsync https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     createWasm https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     <anonymous> https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:14
>     <anonymous> https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:17
>     <anonymous> https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:4
>     <anonymous> https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js:5

Error displayed in the console of DevTools of Edge :
> An error occurred when loading the file!
> TypeError: Cannot read properties of undefined (reading 'set')
>     at VerovioToolkitDefaultModule.loadZipDataBuffer (verovio-toolkit-wasm.js:290:36)
>     at Verovio_p24.html:30:4

Quick fix in the javascript:
`<script src="https://www.verovio.org/javascript/develop/verovio-toolkit-wasm.js" defer></script>`
replaced by 
`<script src="https://www.verovio.org/javascript/latest/verovio-toolkit-wasm.js" defer></script>`

After editing the javascript, it works, the score is displayed in both browsers, the MEI is saved correctly.

​
