### ISSUE TITLE
Windows 10 MSYS2 Mingw64 compilation error

### ISSUE THREAD

**Issue by uliss** [rism-digital/verovio#3662]
**Compilation fails**
Under Win10 MSYS2 platform

**To Reproduce**
1. ``mkdir build && cd build/ && cmake ../cmake  -DBUILD_AS_LIBRARY=ON``
2.``ninja or make``
3. See huge error log

The main error reason is here:

> CMakeFiles\verovio.dir\C_\msys64\home\serge\src\verovio\src\filereader.cpp.obj.d -o CMakeFiles/ve
> rovio.dir/C_/msys64/home/serge/src/verovio/src/filereader.cpp.obj -c C:/msys64/home/serge/src/verovi
> o/src/filereader.cpp
> In file included from C:/msys64/ucrt64/include/c++/13.2.0/functional:59,
>                  from C:/msys64/home/serge/src/verovio/include/vrv/vrvdef.h:12,
>                  from C:/msys64/home/serge/src/verovio/include/vrv/io.h:16,
>                  from C:/msys64/ucrt64/include/sys/stat.h:14,
>                  from C:/msys64/home/serge/src/verovio/include/zip/zip_file.hpp:4459,
>                  from C:/msys64/home/serge/src/verovio/src/filereader.cpp:20:
> C:/msys64/ucrt64/include/c++/13.2.0/bits/std_function.h:68:3: error: template with C linkage
>    68 |   template<typename _Tp>

**zip_fille.h** includes **sys/stat.h** which include **io.h** but include paths search finds **vrv/io.h** instead of system file.
I think the simple fix is rename **io.h** to prevent name clashing. 

Another option is to remove **include/vrv** directory from **CMakeLists.txt**, but we will need to prefix all inner includes as **"vrv/add.h"** etc.

**Comment by craigsapp** [comment]
Maybe renaming `include/vrv/io.h` to something like `include/vrv/iobase.h` would be good to avoid filename conflicts with system include files.
