### ISSUE TITLE
MusicXML to MEI - timing change ignored in last voice

### ISSUE THREAD

**Issue by sonicnkt** [rism-digital/verovio#3677]
**Describe the problem**

In our workflow we edit in Finale, then do a MusicXML export which finally gets converted using verovio (python) to MEI.

Now i noticed that in the last voice, but only in that one, verovio seems to ignore the timing change in the score when generating the dynamics code in mei. Eg it still assumes a 4/4 timing for those parts even tho the switch works fine in the other voices. 

**To Reproduce**
1. Load the attached MusicXML Example file
2. Convert using verovio (default settings)
3. Notice the wrong timestamps for the dynamics in "bassus continuo" after measure 4.

**Expected behavior**
Verovio just respect the timing change in all voices.

**Input data**
Small zip file containing a small test file *.mxl and converted *.mei
[testfile_dynamics.zip](https://github.com/rism-digital/verovio/files/15308897/testfile_dynamics.zip)

**Verovio information**
 - Version of Verovio [4.2.1-28c73a1 Pypi]
 - Binding [Python]

**Environment information (as appropriate)**
 - OS: [Linux]

**Screenshots**

Original MusicXML (rendered using MuseScore 4.2):
![test_musicxml_musescore](https://github.com/rism-digital/verovio/assets/5454622/e1f084df-5045-4988-89f3-3671e3ed737c)

MEI, converted and rendered (SVG) using verovio 4.2.1-28c73a1 (Python Toolkit):
![test_mei_verovio_1](https://github.com/rism-digital/verovio/assets/5454622/730db91f-e2ff-4f6e-8ab4-5f7212a98653)

MEI, manually removed timing change after conversion:
![test_mei_verovio_2](https://github.com/rism-digital/verovio/assets/5454622/42a393a3-ec26-41cd-ab23-7f716a5d8d68)

As you can see the dynamics now look correct, of course it is broken in the other voice.

**Additional context**

I can reproduce the issue using the latest online converter on verovio.org.
Speaking of which, the page still mentions that this feature is still under development and you should try the MEI XSL stylesheets for the conversion instead.
Is this still the recommended method? 

I tried the MusicXML Partwise conversion on [MeiGrage](https://meigarage.edirom.de/) and tho this seems to do the dynamics correctly the resulting mei 
has other issues that would need to be fixed. The Verovio Conversion works much better except for the mentioned issue.

**Comment by sonicnkt** [comment]
Thanks for the detailed explanation and the already merged fix :)

Yes i am using the python toolkit version of verovio without any inputFrom Options. 
I am in the process of writing a python conversion script for our project that does the initial mei conversion using verovio and then modifies the mei further with our custom editorial settings, adding figured_bass and other stuff.

I will try the `musicxm-hum` option with a full score which contains more timing changes but this looks promising! 

Have not tried (or heard) about converter21 before but i will also give this one a try.

**Comment by ahankinson** [comment]
The Python toolkit can be built locally if you want. We can also merge the develop branch into the develop-pypi branch, and it will test and upload a dev version to test.pypi.org. You can use that with pip to install the latest develop version. 

The fix will be available on the regular PyPi when the next stable release is made.
