### ISSUE TITLE
vrv c wrapper

### ISSUE THREAD

**Issue by phamconganh** [rism-digital/verovio#3704]
I'm trying to use Dart ffigen to gen link verovio headers, but I only see vrvToolkit has a c wrapper. Can you have a c wrapper for vrv. Or am I wrong, I don't have much knowledge about this.

**Comment by lpugin** [comment]
There is a c wrapper in `./tools`. See https://github.com/rism-digital/verovio/blob/develop/tools/c_wrapper.h and https://github.com/rism-digital/verovio/blob/develop/tools/c_wrapper.cpp. It seems this is what you are looking for.
