### ISSUE TITLE
Ledger line too short

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3713]
**Describe the problem**
If ledger lines are required between different note heads, the width of the ledger line is defined by the head further out..

**To Reproduce**
1. Load the data attached
2. Render
3. See error

**Expected behavior**
Ledger line widths between different note head should be defined by the wider head.

**Input data**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei meiversion="5.0" xmlns="http://www.music-encoding.org/ns/mei">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title></title>
      </titleStmt>
      <pubStmt>
      </pubStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.sym="common" meter.unit="4">
            <staffGrp>
              <staffDef clef.line="2" clef.shape="G" lines="5" n="1">
              </staffDef>
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer n="1">
                  <note dur="1" oct="4" pname="d" />
                </layer>
                <layer n="2">
                  <note dur="2" oct="3" pname="b" />
                  <note dur="2" oct="4" pname="c" />
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Verovio information**
 - latest develop
 - command-line

**Screenshots**
<img width="222" alt="image" src="https://github.com/rism-digital/verovio/assets/7693447/c082bbb5-ad0c-4bcd-bcbb-d03a29d4e080">

#### reference print (around 1900)
![image](https://github.com/rism-digital/verovio/assets/7693447/85ac0a78-6bb5-45f5-960e-84a028b87337)

**Comment by brdvd** [comment]
I have thought about this example quite a bit and I don't see an easy way to extend the current implementation such that this example works without adding complications in the codebase.

The current ledger line calculation is based on the assumption that noteheads don't change the length of ledger lines which are vertically further away from the staff center than the notehead itself. This assumption perfectly captures the rules for ledger lines in `Behind Bars, p. 27`.

<img width="425" alt="BehindBars" src="https://github.com/user-attachments/assets/14004f95-0502-4d31-8654-d7746f36a5ae">

Corresponding examples are rendered as described in Verovio:

<img width="400" alt="Double-stemmed" src="https://github.com/user-attachments/assets/d8bf0dbf-d326-4cf4-84e9-f84d6f401b6d">

Here the upper B notehead does not lead to an extension of the ledger line through the lower A notehead. 

Compare this to the example in the issue where the upper D notehead would suddenly extend the ledger line above the lower B notehead. It is also unclear to me, how those extensions should behave for different pitches. Which ledger lines would you expect to be extended in the following examples?

<img width="400" alt="Example1" src="https://github.com/user-attachments/assets/b4c17ffa-0de3-4e2a-9ce5-7d875481b2d1">
<img width="390" alt="Example2" src="https://github.com/user-attachments/assets/ffaab1bd-5742-4bd3-8b90-3eacfe78a9d2">

**Comment by craigsapp** [comment]
This one looks a little weird:

<img width="710" alt="Screenshot 2024-09-07 at 3 43 16 PM" src="https://github.com/user-attachments/assets/92f2b429-18a2-404d-8180-672f04e0c08a">

But I don't remember seeing any real world case for this.  However, it does seem to be following the rules of *Behind Bars* where each voice has separate ledgerlines that match their own notes's width.

This one is definitely correct, with no extension of the ledger lines for the whole notes which does not have ledger lines itself:

<img width="680" alt="Screenshot 2024-09-07 at 3 43 55 PM" src="https://github.com/user-attachments/assets/4bc46d53-9c25-4769-a1bc-0aa3088b361b">

Also, I do not find this one objectionable, and it follows the examples in *Behind Bars*:

<img width="705" alt="Screenshot 2024-09-07 at 3 44 26 PM" src="https://github.com/user-attachments/assets/11f3cbc1-8f0b-4575-92ba-bde3b896aac9">

But I also would have to find real-word examples to see if there is a convention one way or the other.

**Comment by lpugin** [comment]
Thanks for the additional input. I am closing it since there is no clear consensus on how this can be changed.
