### ISSUE TITLE
Overlapping neume components when there is a liquescent

### ISSUE THREAD

**Issue by martha-thomae** [rism-digital/verovio#3721]
**Describe the problem**
When a neume includes a liquescent, and this liquescent is not the final neume component of the neume, the liquescent and the following neume component overlap when rendered. You can see an example in the following code and screenshot below. Here the neume has three neume components (with the pitches `g`, `a`, and `f`). The liqesucent is the second of them. The liquescent (in `a`) and the following neume component (in `f`) share the same horizontal position. Could this be fixed so that the neume components don't overlap when a liquescent appears? Thank you!

![Screenshot 2024-07-03 at 1 46 56 AM](https://github.com/rism-digital/verovio/assets/13948831/05b151d6-c99e-4849-b62b-ac8447bff940)

```xml
<?xml version="1.0" ?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Psallite domino</title>
         </titleStmt>
         <pubStmt/>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m-7715e450-e879-11ee-a2f1-f2b2e3f0b573">
            <score xml:id="m-7715e4b4-e879-11ee-a2f1-f2b2e3f0b573">
               <scoreDef xml:id="m-7715e4e6-e879-11ee-a2f1-f2b2e3f0b573">
                  <staffGrp xml:id="m-7715e504-e879-11ee-a2f1-f2b2e3f0b573">
                     <staffDef n="1" lines="5" notationtype="neume" xml:id="m-7715e54a-e879-11ee-a2f1-f2b2e3f0b573"/>
                  </staffGrp>
               </scoreDef>
               <section xml:id="m-7715e572-e879-11ee-a2f1-f2b2e3f0b573">
                  <staff n="1" xml:id="m-7715e59a-e879-11ee-a2f1-f2b2e3f0b573">
                     <layer n="1" xml:id="m-7715e5cc-e879-11ee-a2f1-f2b2e3f0b573">
                        <clef shape="F" line="3" xml:id="m-7715e5f4-e879-11ee-a2f1-f2b2e3f0b573"/>
                        <syllable xml:id="m-7715ec3e-e879-11ee-a2f1-f2b2e3f0b573">
                           <syl wordpos="m" con="d" xml:id="m-7715ec5c-e879-11ee-a2f1-f2b2e3f0b573">scen</syl>
                           <neume xml:id="m-7715ec8e-e879-11ee-a2f1-f2b2e3f0b573">
                              <nc xml:id="m-7715ee32-e879-11ee-a2f1-f2b2e3f0b573" pname="g" oct="3"/>
                              <nc curve="c" xml:id="m-7715ecb6-e879-11ee-a2f1-f2b2e3f0b573" pname="a" oct="3">
                                 <liquescent xml:id="m-7715ede2-e879-11ee-a2f1-f2b2e3f0b573"/>
                              </nc>
                              <nc xml:id="m-7715ee32-e879-11ee-a2f1" pname="f" oct="3"/>
                           </neume>
                        </syllable>
                     </layer>
                  </staff>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by martha-thomae** [comment]
@lpugin: This is part of the file I will use as an example for MedRen. Can this be fixed on time? If it can, I will continue working on this example file for the slides. If not, I can look for another one. Thanks!

**Comment by martha-thomae** [comment]
Actually, it happens with neume components that follow the liquescent, regardless of whether they belong to the same neume or syllable. See the following screenshot. The liquescent is the only neume in the syllable "in". The next syllable, "te", has also a single neume component. Despite belonging to different syllables, both are overlapped in the rendition.

![Screenshot 2024-07-03 at 2 12 41 AM](https://github.com/rism-digital/verovio/assets/13948831/09c73efa-1b4a-4ba9-bbf9-6d88ecf59f87)


```xml
<?xml version="1.0" ?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Benedixit</title>
         </titleStmt>
         <pubStmt/>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m-7848fbaa-e879-11ee-ba2d-f2b2e3f0b573">
            <score xml:id="m-7848fc22-e879-11ee-ba2d-f2b2e3f0b573">
               <scoreDef xml:id="m-7848fc54-e879-11ee-ba2d-f2b2e3f0b573">
                  <staffGrp xml:id="m-7848fc7c-e879-11ee-ba2d-f2b2e3f0b573">
                     <staffDef n="1" lines="5" notationtype="neume" xml:id="m-7848fcc2-e879-11ee-ba2d-f2b2e3f0b573">
                        <clef shape="F" line="3" xml:id="m-7848fd76-e879-11ee-ba2d-f2b2e3f0b573"/>
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="m-7848fcea-e879-11ee-ba2d-f2b2e3f0b573">
                  <staff n="1" xml:id="m-7848fd12-e879-11ee-ba2d-f2b2e3f0b573">
                     <layer n="1" xml:id="m-7848fd4e-e879-11ee-ba2d-f2b2e3f0b573">
                        <syllable xml:id="m-78490244-e879-11ee-ba2d-f2b2e3f0b573">
                           <syl wordpos="t" xml:id="m-7849026c-e879-11ee-ba2d-f2b2e3f0b573">is</syl>
                           <neume xml:id="m-7849028a-e879-11ee-ba2d-f2b2e3f0b573">
                              <nc xml:id="m-784902b2-e879-11ee-ba2d-f2b2e3f0b573" pname="g" oct="3"/>
                           </neume>
                        </syllable>
                        <syllable xml:id="m-784902f8-e879-11ee-ba2d-f2b2e3f0b573">
                           <syl wordpos="s" xml:id="m-78490316-e879-11ee-ba2d-f2b2e3f0b573">in</syl>
                           <neume xml:id="m-7849033e-e879-11ee-ba2d-f2b2e3f0b573">
                              <nc curve="c" xml:id="m-7849035c-e879-11ee-ba2d-f2b2e3f0b573" pname="g" oct="3">
                                 <liquescent xml:id="m-78490384-e879-11ee-ba2d-f2b2e3f0b573"/>
                              </nc>
                           </neume>
                        </syllable>
                        <syllable xml:id="m-784903a2-e879-11ee-ba2d-f2b2e3f0b573">
                           <syl wordpos="s" xml:id="m-784903ca-e879-11ee-ba2d-f2b2e3f0b573">te</syl>
                           <neume xml:id="m-784903e8-e879-11ee-ba2d-f2b2e3f0b573">
                              <nc xml:id="m-78490406-e879-11ee-ba2d-f2b2e3f0b573" pname="f" oct="3"/>
                           </neume>
                        </syllable>
                     </layer>
                  </staff>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by lpugin** [comment]
This is what I am seeing for the second example:

![image](https://github.com/rism-digital/verovio/assets/689412/5203e495-a814-46d5-95ad-161522ecb59a)

There is a problem with the first one:

![image](https://github.com/rism-digital/verovio/assets/689412/e75be09c-6482-4386-816e-ec0f758b9dd1)

The clef is not properly placed because it is not in the `scoreDef`, which we should handle separately. I can fix the liquescent, but you need to give me an example of how it should look like.

**Comment by martha-thomae** [comment]
> This is what I am seeing for the second example:
> 
> ![image](https://private-user-images.githubusercontent.com/689412/345332048-5203e495-a814-46d5-95ad-161522ecb59a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTQzNDYsIm5iZiI6MTcxOTk5NDA0NiwicGF0aCI6Ii82ODk0MTIvMzQ1MzMyMDQ4LTUyMDNlNDk1LWE4MTQtNDZkNS05NWFkLTE2MTUyMmVjYjU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwODA3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTBiMTc5MzA2NzNiN2U2MzZjZWRmYTNiM2UzNDg3MDVhZDc0MjJmYzFlYjVjZWQwMzg3NDcxYTJmY2QyZTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QGZxFylBeUxdUxBRUe-eCFe-bYTGHlmEPiLN_GOudn4)
> 
> There is a problem with the first one:
> 
> ![image](https://private-user-images.githubusercontent.com/689412/345332510-e75be09c-6482-4386-816e-ec0f758b9dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTQzNDYsIm5iZiI6MTcxOTk5NDA0NiwicGF0aCI6Ii82ODk0MTIvMzQ1MzMyNTEwLWU3NWJlMDljLTY0ODItNDM4Ni04MTZlLWVjMGY3NThiOWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwODA3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTBlN2I3Y2ZjYjVmNThkZjg3NTRmNjgwYzcxMTIzZjU2ZGJkNDdmNmRiY2MxNWE1ZGQxZjEyYzNhODc3ZGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pwswH6xoC9avm9Ip7xLTkkPZOZ4cFGA-8i8bkcypMDo)
> 
> The clef is not properly placed because it is not in the `scoreDef`, which we should handle separately. I can fix the liquescent, but you need to give me an example of how it should look like.

You are absolutely right! Sorry about that.

So, for the last of these examples, the liquescent within those three neume components should look like this instead:

<img width="173" alt="Screenshot 2024-07-03 at 10 14 24" src="https://github.com/rism-digital/verovio/assets/13948831/784a30a7-8210-4cb0-af02-b5aebdb353df">

**Comment by martha-thomae** [comment]
Ok, this seems to be a more general issue that is happening with or without the use of liquescents. All neume components within a neume are getting squished together. So I am closing this issue and adding the more general one in #3722
