### ISSUE TITLE
build steps

### ISSUE THREAD

**Issue by mwolfthal** [rism-digital/verovio#3742]
CMake -G

The document says to run cmake -G from ./tools. This means that the build directory cannot be deleted without deleting the source files that are in ./tools. Instead it should be run from ./build.

**Comment by lpugin** [comment]
Run `cmake ../cmake --fresh` as explained [here](https://book.verovio.org/installing-or-building-from-sources/command-line.html#troubleshooting)

**Comment by mwolfthal** [comment]
This will work but I believe it is not a good practice to keep source files in the build directory.
