### ISSUE TITLE
MusicXML import of turn missing @accidupper, @accidlower

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3761]
Related to issue https://github.com/rism-digital/verovio/issues/3759 (or more properly the second one #3760)

In the MusicXML example for An Chloe, K. 524 by Mozart on this page: https://www.musicxml.com/music-in-musicxml/example-set

The lower accidentals on the turns are not transmitted to the MEI conversion.

For example, the first one in measure 2:

```xml
<ornaments>
   <turn default-x="-6" default-y="34" placement="above"/>
      <accidental-mark default-x="4" default-y="14">natural</accidental-mark>
</ornaments>
```

Is converted to:

```xml
<turn xml:id="th90i95" staff="2" startid="#n1384ct1" 
   place="above" form="upper" />
```

which does not preserve the natural sign below the turn.   The `accidental-mark@default-y` is 14 which is less than `turm@default-y` of 34, so therefore the accidental is `turn@accidlower="n"` for the MEI conversion:

```xml
<turn xml:id="th90i95" staff="2" startid="#n1384ct1" 
    place="above" form="upper" accidlower="n" />
```

Target rendering (https://wpmedia.musicxml.com/wp-content/uploads/2017/12/MozaChloSample.pdf):

<img width="781" alt="Screenshot 2024-09-04 at 9 28 55 AM" src="https://github.com/user-attachments/assets/3f3a377b-0887-466a-9aa0-169e31a28e42">

Current rendering in verovio (after conversion from MusicXML to MEI):

<img width="930" alt="Screenshot 2024-09-04 at 9 37 15 AM" src="https://github.com/user-attachments/assets/932e3874-4153-4b8c-a967-688a5ad617ad">

(Notice that the pickup measure is displayed incorrectly, with a gap after the two eighth notes, which indicates that verovio is thinking this is a full measure and is leaving extra space for quarter notes 2&ndash;4 in the measure.  Instead this is really quarter note 4, or else automatically identify that there is only one quarter note in the measure and do not add padding for non-existant rest of the measure).   Also the stems on the eighth notes are unacceptably long.  Compare to measure 6 which is acceptable (but not optimal since lowering by a diatonic step as in the Finale export is more traditional to avoid the wedge between the staff line and the beam:

<img width="107" alt="Screenshot 2024-09-04 at 9 33 26 AM" src="https://github.com/user-attachments/assets/bc90543b-0381-4cb6-acde-0e0877853700">

<img width="94" alt="Screenshot 2024-09-04 at 9 33 34 AM" src="https://github.com/user-attachments/assets/2cae0e81-524f-4a55-b768-4e5b6f79412b">

Verovio is moving the beam up a diatonic step for the pickup, but it should be moving it down a diatonic step as in the Finale rendering:

Here is the same MusicXML file loaded into Musescore 4.4:

<img width="1035" alt="Screenshot 2024-09-04 at 9 58 01 AM" src="https://github.com/user-attachments/assets/c6ba3852-7d78-4feb-b165-9935fab78e88">

The turns also do not preserve the accidentals in Musescore's conversion of the MusicXML.  Also the delayed turn in the 4th measure is not converted properly in Musescore 4.4.

Here is the import for Dorico v4 for the example:

<img width="1150" alt="Screenshot 2024-09-04 at 10 03 28 AM" src="https://github.com/user-attachments/assets/30ca8d8e-7a6d-4764-ab83-2969fa070145">

Also no accidentals on the turns.

Finale version 27 does import the turn accidentals:

<img width="1144" alt="Screenshot 2024-09-04 at 10 05 16 AM" src="https://github.com/user-attachments/assets/311d51bf-235c-40a5-a2ab-e2017c04077e">

The general problem of why only Finale imports the MusicXML sample correctly is that the documentation for the turn:

https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/turn/

List only attributes and not child elements.

Documentation for `<accidental-mark>`:
https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/accidental-mark

Shows parents at top (actually the grandparent `<ornaments>`).  So other than examples like this, there is no way a programmer can guess how turns are to interact with accidentals (there seem to be alternate representations in turn attributes as well).

**Comment by craigsapp** [comment]
Here is the import results in Sibelius 8.3:

<img width="1001" alt="Screenshot 2024-09-04 at 10 42 44 AM" src="https://github.com/user-attachments/assets/61ec2ce2-2f5a-40f7-bcf3-6b7a174b99f2">

Turn accidentals are ignored, and delayed turn is not observed (or is not positioned properly since the turn does seem to be moved a little to the right).

**Comment by craigsapp** [comment]
Another problem with the conversion of this is the pickup measure in the voice part:

```
      <note>
        <rest measure="yes"/>
        <duration>4</duration>
        <voice>1</voice>
      </note>
```

The MEI conversion correctly converts this to a whole-measure rest:

```
<staff xml:id="s3ldw5z" n="1">
   <layer xml:id="l1ksqlvl" n="1">
      <mRest xml:id="m1qfnjh2" />
   </layer>
</staff>
```

But the problem is that this is a pickup measure which has 4 quarter notes in it, but the MusicXML whole-measure rest explicitly states that it has a duration of a quarter note.

The MusicXML data is technically incorrect, since this rests should not be displayed as a whole-measure rest, and instead as a quarter note.  But the conversion to MEI is also not correct by transferring the information that the whole-measure rest does not have the same duration as the time siganture (one quarter versues four quarters).

This in turn causes problems with the verovio rendering of the measure:

<img width="399" alt="Screenshot 2024-09-04 at 11 07 25 AM" src="https://github.com/user-attachments/assets/9798092c-e6e5-455b-9a9d-d604a8e1e091">


The `<mRest>` is assumed to have a duration of 4 quarter notes, which in turn casues there to be a extra space added to the end of the pickup measure.   Instead, the MEI conversion should preserve the non-standard duration of the full-measure rest, and then verovio should detect that the measure is underfilled with only one quarter in each staff, which should removed the unwanted gap.

See the Dorico rendering for the expected rendering of this measure with verovio (the whole-measure rest should be displayed, even though that notation is incorrect).

**Comment by rettinghaus** [comment]
Verovio adds all accidentals to turns during import, but only if they are properly encoded with `@placement`. That is why no proper program exports or imports accidental marks like this except that crappy abandonware Finale. It is futile trying to base a semantic encoding on visual attributes like `default-y` or `relative-y`.

**Comment by craigsapp** [comment]
> Verovio adds all accidentals to turns during import, but only if they are properly encoded with `@placement`. That is why no proper program exports or imports accidental marks like this except that crappy abandonware Finale. It is futile trying to base a semantic encoding on visual attributes like `default-y` or `relative-y`.

Oh &mdash; I did not notice that the `<accidental-mark>` is a sibling of `<turn>` rather than a child:

```xml
<ornaments>
   <turn default-x="-6" default-y="34" placement="above"/>
      <accidental-mark default-x="4" default-y="14">natural</accidental-mark>
</ornaments>
```

I was thinking it was the following due to the indentation:

```xml
<ornaments>
   <turn default-x="-6" default-y="34" placement="above">
      <accidental-mark default-x="4" default-y="14">natural</accidental-mark>
   </turn>
</ornaments>
```

And the former is very bad, since that is ambiguous with an editorial accidental on the note and not on the turn.

In Finale the accidental and turn are being merged into a turn with a lower accidental (rather than a separate editorial accidental and an independent turn, for example):

<img width="671" alt="Screenshot 2024-09-04 at 12 08 57 PM" src="https://github.com/user-attachments/assets/3686a31c-b48a-40b1-a030-c449476fc3bb">

Placing the accidentals above the turn also converts them to `@accidupper`:

<img width="499" alt="Screenshot 2024-09-04 at 12 13 42 PM" src="https://github.com/user-attachments/assets/cdc66c61-229f-4784-92b2-4732286e1979">

(the y positions are ignored otherwise).

**Comment by craigsapp** [comment]
Here is the `@placement` attribute on MusicXML turns, as exported by Musescore v4.4:

<details>
<summary> Click to view MusicXML data </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work>
    <work-title>Untitled score</work-title>
    </work>
  <identification>
    <creator type="composer">Composer / arranger</creator>
    <encoding>
      <software>MuseScore 4.4.0</software>
      <encoding-date>2024-09-04</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>6.99911</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1596.77</page-height>
      <page-width>1233.87</page-width>
      <page-margins type="even">
        <left-margin>85.7252</left-margin>
        <right-margin>85.7252</right-margin>
        <top-margin>85.7252</top-margin>
        <bottom-margin>85.7252</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>85.7252</left-margin>
        <right-margin>85.7252</right-margin>
        <top-margin>85.7252</top-margin>
        <bottom-margin>85.7252</bottom-margin>
        </page-margins>
      </page-layout>
    <appearance>
      <line-width type="light barline">1.8</line-width>
      <line-width type="heavy barline">5.5</line-width>
      <line-width type="beam">5</line-width>
      <line-width type="bracket">4.5</line-width>
      <line-width type="dashes">1</line-width>
      <line-width type="enclosure">1</line-width>
      <line-width type="ending">1.1</line-width>
      <line-width type="extend">1</line-width>
      <line-width type="leger">1.6</line-width>
      <line-width type="pedal">1.1</line-width>
      <line-width type="octave shift">1.1</line-width>
      <line-width type="slur middle">2.1</line-width>
      <line-width type="slur tip">0.5</line-width>
      <line-width type="staff">1.1</line-width>
      <line-width type="stem">1</line-width>
      <line-width type="tie middle">2.1</line-width>
      <line-width type="tie tip">0.5</line-width>
      <line-width type="tuplet bracket">1</line-width>
      <line-width type="wedge">1.2</line-width>
      <note-size type="cue">70</note-size>
      <note-size type="grace">70</note-size>
      <note-size type="grace-cue">49</note-size>
      </appearance>
    <music-font font-family="Leland"/>
    <word-font font-family="Edwin" font-size="10"/>
    <lyric-font font-family="Edwin" font-size="10"/>
    </defaults>
  <credit page="1">
    <credit-type>title</credit-type>
    <credit-words default-x="616.935484" default-y="1511.049022" justify="center" valign="top" font-size="22">Turn accidental test</credit-words>
    </credit>
  <part-list>
    <score-part id="P1">
      <part-name>Oboe</part-name>
      <part-abbreviation>Ob.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Oboe</instrument-name>
        <instrument-sound>wind.reed.oboe</instrument-sound>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>69</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="379.55">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>50</left-margin>
            <right-margin>0</right-margin>
            </system-margins>
          <top-system-distance>170</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="80.21" default-y="-35">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        <notations>
          <ornaments>
            <turn/>
            </ornaments>
          </notations>
        </note>
      <note default-x="228.98" default-y="-30">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="2" width="311.84">
      <note default-x="12.5" default-y="-35">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        <notations>
          <ornaments>
            <turn/>
            <accidental-mark placement="above">flat</accidental-mark>
            </ornaments>
          </notations>
        </note>
      <note default-x="161.27" default-y="-30">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <accidental>natural</accidental>
        <stem>up</stem>
        </note>
      </measure>
    <measure number="3" width="321.04">
      <note default-x="12.5" default-y="-35">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        <notations>
          <ornaments>
            <turn/>
            <accidental-mark placement="above">flat</accidental-mark>
            <accidental-mark placement="below">flat</accidental-mark>
            </ornaments>
          </notations>
        </note>
      <note default-x="161.27" default-y="-30">
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <accidental>natural</accidental>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
```

</details>

I don't see a way of making a `<delayed-turn>` in Musescore 4.4, discussion about this from 2020: https://musescore.org/en/node/309348 (I was able to fake it by dragging the turn visually, but that does not convert from turn to delayed-turn in the MusicXML export from Musescore 4.4).

Rendering in verovio which preserves the accidentals on the turn:
<img width="628" alt="Screenshot 2024-09-04 at 1 09 08 PM" src="https://github.com/user-attachments/assets/8189e412-5e12-4820-9266-a0c023cb2034">

MEI conversion is as expected:

<details> 
<summary> Click for MEI conversion of the MusicXML data with verovio. </summary>


```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead xml:id="m1odbmd2">
  <fileDesc xml:id="fmeg7m6">
   <titleStmt xml:id="t1ar8yl">
    <title>Untitled score</title>
    <respStmt>
     <persName role="composer">Composer / arranger</persName>
    </respStmt>
   </titleStmt>
   <pubStmt xml:id="p1bpzsbd">
    <date isodate="2024-09-04" type="encoding-date">2024-09-04</date>
   </pubStmt>
  </fileDesc>
  <encodingDesc xml:id="e1rrg17y">
   <appInfo xml:id="akvknop">
    <application xml:id="a1pud80p" isodate="2024-09-04T13:10:33" version="4.3.0-dev-6e49bf7-dirty">
     <name xml:id="n321ew9">Verovio</name>
     <p xml:id="pmf8au0">Transcoded from MusicXML</p>
    </application>
   </appInfo>
  </encodingDesc>
 </meiHead>
 <music decls="#work0_encoded">
  <body>
   <mdiv xml:id="mp007th">
    <score xml:id="s1m3fl0z">
     <scoreDef xml:id="s1a7z5yd">
      <pgHead xml:id="paw4kpb">
       <rend xml:id="r3b0j56" halign="center" valign="top">Turn accidental test</rend>
      </pgHead>
      <staffGrp xml:id="s325h10">
       <staffDef xml:id="P1" n="1" lines="5" ppq="1">
        <label xml:id="lknezjc">Oboe</label>
        <labelAbbr xml:id="l7dthkp">Ob.</labelAbbr>
        <instrDef xml:id="i14sc2r" midi.channel="0" midi.instrnum="68" midi.volume="78.00%" />
        <clef xml:id="c1iliq8s" shape="G" line="2" />
        <keySig xml:id="k187z0c3" sig="0" />
        <meterSig xml:id="m1qh8w55" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="s10iy99u">
      <measure xml:id="m225t5p" n="1">
       <staff xml:id="s1cvsewu" n="1">
        <layer xml:id="lf7278a" n="1">
         <note xml:id="n15txgof" dur.ppq="2" dur="2" oct="4" pname="f" stem.dir="up" />
         <note xml:id="niv5eq8" dur.ppq="2" dur="2" oct="4" pname="g" stem.dir="up" />
        </layer>
       </staff>
       <turn xml:id="t1wpst1u" staff="1" startid="#n15txgof" form="upper" />
      </measure>
      <measure xml:id="m1bagck5" n="2">
       <staff xml:id="s1ynxhrt" n="1">
        <layer xml:id="lag5tei" n="1">
         <note xml:id="nbch03l" dur.ppq="2" dur="2" oct="4" pname="f" stem.dir="up" />
         <note xml:id="ngdhs0u" dur.ppq="2" dur="2" oct="4" pname="g" stem.dir="up">
          <accid xml:id="a1idlkwr" accid="n" />
         </note>
        </layer>
       </staff>
       <turn xml:id="t3hv0qx" staff="1" startid="#nbch03l" accidupper="f" form="upper" />
      </measure>
      <measure xml:id="mo44n6u" right="end" n="3">
       <staff xml:id="s1w6kkl5" n="1">
        <layer xml:id="lvlo9j4" n="1">
         <note xml:id="n120n4sf" dur.ppq="2" dur="2" oct="4" pname="f" stem.dir="up" />
         <note xml:id="nkrldya" dur.ppq="2" dur="2" oct="4" pname="g" stem.dir="up">
          <accid xml:id="a1tt5i2u" accid="n" />
         </note>
        </layer>
       </staff>
       <turn xml:id="t10htmbk" staff="1" startid="#n120n4sf" accidupper="f" accidlower="f" form="upper" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>


```xml
<ornaments>
   <turn/>
   <accidental-mark placement="above">flat</accidental-mark>
   <accidental-mark placement="below">flat</accidental-mark>
</ornaments>
```

As you note, there will be an increase of Finale MusicXML exports happening, so if these turns have an `<accidental-mark>` after them and these are supposed to be modifiers of the turn, then the `y` parameters should be used as a fall-back to assign `@placement`.   In other words, there is an accidental on the turn, and it is not useful to users to omit this accidental if `@placement` is missing but the vertical positions can be used to infer the `@placement`.  I don't have the last version of Finale, so I don't know if it behaves in this manner for MusicXML export, so maybe irrelevant if the last version includes `@placement` for such accidentals.
