### ISSUE TITLE
Verovio miss a staff in generated svg

### ISSUE THREAD

**Issue by stereomatchingkiss** [rism-digital/verovio#3773]
I download the mei generated from [this page](https://www.verovio.org/musicxml.html), you could download the mei from 
[Vivaldi_Concerto_No.4_in_F_Minor_Winter.zip](https://github.com/user-attachments/files/16948046/Vivaldi_Concerto_No.4_in_F_Minor_Winter.zip) too

I am using verovio (version-4.3.1), run on win11, compiled with vs2022, release build

source codes

```
#include <vrv/toolkit.h>

#include <format>
#include <iostream>

using namespace std;

int main()
{
    vrv::Toolkit tk(false);
    tk.SetResourcePath("data");

    auto const fname = "resources/Vivaldi_Concerto_No.4_in_F_Minor_Winter.mei";
    tk.LoadFile(fname);

    for(int i = 0; i != tk.GetPageCount(); ++i){
        tk.RenderToSVGFile(format("page_{}.svg", i + 1), i + 1);
    }

    cout<<"page count = "<<tk.GetPageCount()<<endl;
}
```

The page_2.svg should contain staff with id "sxyhgc1", but it do not. I search for this id from page_1.svg~page_4.svg, this staff do not exist.

[pages.zip](https://github.com/user-attachments/files/16948079/pages.zip)

**Comment by stereomatchingkiss** [comment]
Command of build

```
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_AS_LIBRARY=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE .
cmake --build . --config Release

```

I add this line in the CMakeLists.txt directly

`add_compile_options(/bigobj)`

**Comment by lpugin** [comment]
I suspect this is because the content of the staff is empty on page 2, and for that reason it is not rendered on that page. Try with the `--condense none` option.

**Comment by stereomatchingkiss** [comment]
> I suspect this is because the content of the staff is empty on page 2, and for that reason it is not rendered on that page. Try with the `--condense none` option.

How could I set it from the c++ codes?

Tried

`tk.GetOptionsObj()->m_condense.SetValueBool(false);`

But it give me output 

`[Error] Unsupported type bool for condense`

Thanks

**Comment by lpugin** [comment]
both
```cpp
tk.SetOptions("{'condense': 'none'}");
```
or
```cpp
tk.GetOptionsObj()->m_condense.SetValue("none");
```
should work

**Comment by stereomatchingkiss** [comment]
> both
> 
> ```c++
> tk.SetOptions("{'condense': 'none'}");
> ```
> 
> or
> 
> ```c++
> tk.GetOptionsObj()->m_condense.SetValue("none");
> ```
> 
> should work

Thanks, it works
