### ISSUE TITLE
Can Verovio be used in Mobile / React Native environment

### ISSUE THREAD

**Issue by xe4me** [rism-digital/verovio#3774]
Hi 
First of all, thank you for your wonderful work on rendering musical notation which is very complicated.

I'm wondering if this library can be used in any way to render MusicXML files in a React Naive , or Swift environment ? 

Thank you

**Comment by ahankinson** [comment]
There are JavaScript and Cocoa bindings. 

https://book.verovio.org/installing-or-building-from-sources/other-bindings.html
