### ISSUE TITLE
Missing implementation of some note@head.shapes

### ISSUE THREAD

**Issue by stereomatchingkiss** [rism-digital/verovio#3798]
Verovio version == 4.3.1

What I tried

```
<note xml:id="n1wmxbyj" dur.ppq="8" dur="4" oct="4" pname="d" stem.dir="down" shape="diamond"/>
<note xml:id="n1wmxbyj" dur.ppq="8" dur="4" oct="4" pname="d" stem.dir="down" head.shape="diamond"/>
<note xml:id="n1wmxbyj" dur.ppq="8" dur="4" oct="4" pname="d" stem.dir="down" headshape="diamond"/>
```

Everyone of them do not work, do verovio support changing shape? I check the source codes, changelog.md do mentioned `"Support for `note@head.fill` with `@headshape="diammond"`"`

But not sure how could I make this work, thanks

Edit : Tried with diammond too

**Comment by craigsapp** [comment]
It should be the second one, `@head.shape`.  Here is viewing on the most recent version of verovio:

<img width="374" alt="Screenshot 2024-09-22 at 8 43 50 PM" src="https://github.com/user-attachments/assets/1331bd99-ea53-404d-9e65-21ef5910c300">

<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt>
   </pubStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2024-09-22T20:43:41" version="4.3.0-dev-bf6b697-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml" />
  </extMeta>
 </meiHead>
 <music decls="#work1_encoded">
  <body>
   <mdiv xml:id="mb2lo6u">
    <score xml:id="sxq1agr">
     <scoreDef xml:id="s1lxa7hc" tempo.dist="3.0000vu">
      <staffGrp xml:id="sasko47">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="cocfzzl" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="4" oct="4" pname="c" head.shape="diamond" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="d" head.fill="void" head.shape="diamond" accid.ges="n" />
         <note xml:id="note-L8F1" dur="4" oct="4" pname="e" head.shape="x" accid.ges="n" />
         <note xml:id="note-L10F1" dur="4" oct="4" pname="f" head.shape="slash" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

```xml
<note dur="4" oct="4" pname="c" head.shape="diamond" />
<note dur="4" oct="4" pname="d" head.fill="void" head.shape="diamond" />
<note dur="4" oct="4" pname="e" head.shape="x" />
<note dur="4" oct="4" pname="f" head.shape="slash" />
```

**Comment by stereomatchingkiss** [comment]
> It should be the second one, `@head.shape`. Here is viewing on the most recent version of verovio:
> <img alt="Screenshot 2024-09-22 at 8 43 50 PM" width="374" src="https://private-user-images.githubusercontent.com/3487289/369746214-1331bd99-ea53-404d-9e65-21ef5910c300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjM2MjcsIm5iZiI6MTcyNzA2MzMyNywicGF0aCI6Ii8zNDg3Mjg5LzM2OTc0NjIxNC0xMzMxYmQ5OS1lYTUzLTQwNGQtOWU2NS0yMWVmNTkxMGMzMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDM0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBiYTY4YmRlMDhiMWU4NDI0ZDhhZjI5OGE5MzMyMGZjMDAwOGI4YWYzNzExMjg4ODdhNWY4MzBjZjEyZWUwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5XyyGDo6otrZNZsDs_-P8fh8TCdU4KymOpVrAyt4uyg">
> Click to view MEI data for above example
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
> <?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
> <mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
>  <meiHead>
>   <fileDesc>
>    <titleStmt>
>     <title />
>    </titleStmt>
>    <pubStmt>
>    </pubStmt>
>   </fileDesc>
>   <encodingDesc>
>    <appInfo>
>     <application isodate="2024-09-22T20:43:41" version="4.3.0-dev-bf6b697-dirty">
>      <name>Verovio</name>
>      <p>Transcoded from Humdrum</p>
>     </application>
>    </appInfo>
>   </encodingDesc>
>   <extMeta>
>    <frames xmlns="http://www.humdrum.org/ns/humxml" />
>   </extMeta>
>  </meiHead>
>  <music decls="#work1_encoded">
>   <body>
>    <mdiv xml:id="mb2lo6u">
>     <score xml:id="sxq1agr">
>      <scoreDef xml:id="s1lxa7hc" tempo.dist="3.0000vu">
>       <staffGrp xml:id="sasko47">
>        <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
>         <clef xml:id="cocfzzl" shape="G" line="2" />
>         <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
>        </staffDef>
>       </staffGrp>
>      </scoreDef>
>      <section xml:id="section-L1F1">
>       <measure xml:id="measure-L1">
>        <staff xml:id="staff-L1F1" n="1">
>         <layer xml:id="layer-L1F1N1" n="1">
>          <note xml:id="note-L4F1" dur="4" oct="4" pname="c" head.shape="diamond" accid.ges="n" />
>          <note xml:id="note-L6F1" dur="4" oct="4" pname="d" head.fill="void" head.shape="diamond" accid.ges="n" />
>          <note xml:id="note-L8F1" dur="4" oct="4" pname="e" head.shape="x" accid.ges="n" />
>          <note xml:id="note-L10F1" dur="4" oct="4" pname="f" head.shape="slash" accid.ges="n" />
>         </layer>
>        </staff>
>       </measure>
>      </section>
>     </score>
>    </mdiv>
>   </body>
>  </music>
> </mei>
> ```
> 
> ```
> <note dur="4" oct="4" pname="c" head.shape="diamond" />
> <note dur="4" oct="4" pname="d" head.fill="void" head.shape="diamond" />
> <note dur="4" oct="4" pname="e" head.shape="x" />
> <note dur="4" oct="4" pname="f" head.shape="slash" />
> ```

Thanks, it works. I checked the source codes(StrToHeadshapeList), tried every examples, find out following do not works

<note dur="4" oct="4" pname="f" head.shape="quarter" />
<note dur="4" oct="4" pname="f" head.shape="rectangle" />
<note dur="4" oct="4" pname="f" head.shape="backslash" />
<note dur="4" oct="4" pname="f" head.shape="isotriangle" />
<note dur="4" oct="4" pname="f" head.shape="oval" />
<note dur="4" oct="4" pname="f" head.shape="rtriangle" />
<note dur="4" oct="4" pname="f" head.shape="rectangle" />
<note dur="4" oct="4" pname="f" head.shape="semicircle" />
<note dur="4" oct="4" pname="f" head.shape="square" />

I guess one of them is the default shape(it works, but since it is default shape I do not find out), but not sure which one

**Comment by stereomatchingkiss** [comment]
About the source codes locate in the file attconverter.cpp

```
data_HEADSHAPE_list AttConverterBase::StrToHeadshapeList(const std::string &value, bool logWarning) const
{
    if (value == "quarter") return HEADSHAPE_list_quarter;
    if (value == "half") return HEADSHAPE_list_half;
    if (value == "whole") return HEADSHAPE_list_whole;
    if (value == "backslash") return HEADSHAPE_list_backslash;
    if (value == "circle") return HEADSHAPE_list_circle;
    if (value == "+") return HEADSHAPE_list_plus;
    if (value == "diamond") return HEADSHAPE_list_diamond;
    if (value == "isotriangle") return HEADSHAPE_list_isotriangle;
    if (value == "oval") return HEADSHAPE_list_oval;
    if (value == "piewedge") return HEADSHAPE_list_piewedge;
    if (value == "rectangle") return HEADSHAPE_list_rectangle;
    if (value == "rtriangle") return HEADSHAPE_list_rtriangle;
    if (value == "semicircle") return HEADSHAPE_list_semicircle;
    if (value == "slash") return HEADSHAPE_list_slash;
    if (value == "square") return HEADSHAPE_list_square;
    if (value == "x") return HEADSHAPE_list_x;
    if (logWarning && !value.empty())
        LogWarning("Unsupported value '%s' for data.HEADSHAPE.list", value.c_str());
    return HEADSHAPE_list_NONE;
}


```

**Comment by craigsapp** [comment]
The notes marked in red have notehead shapes that are not implemented in verovio (but it knows that they are supposed to exist):

<details>
<summary> Click to view MEI data for above example </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt>
   </pubStmt>
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2024-09-22T20:43:41" version="4.3.0-dev-bf6b697-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <extMeta>
   <frames xmlns="http://www.humdrum.org/ns/humxml" />
  </extMeta>
 </meiHead>
 <music decls="#work1_encoded">
  <body>
   <mdiv xml:id="mb2lo6u">
    <score xml:id="sxq1agr">
     <scoreDef xml:id="s1lxa7hc" tempo.dist="3.0000vu">
      <staffGrp xml:id="sasko47">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="cocfzzl" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="17" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="2" oct="4" pname="c" head.shape="quarter" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="d" head.shape="half" accid.ges="n" />
         <note xml:id="note-L8F1" dur="4" oct="4" pname="e" head.shape="whole" accid.ges="n" />
         <note xml:id="note-L10F1" color="red" dur="4" oct="4" pname="f" head.shape="backslash" accid.ges="n" />
         <note xml:id="note-L11F1" color="red" dur="4" oct="4" pname="f" head.shape="circle" accid.ges="n" />
         <note xml:id="note-L12F1" dur="4" oct="4" pname="f" head.shape="+" accid.ges="n" />
         <note xml:id="note-L13F1" dur="4" oct="4" pname="f" head.shape="diamond" accid.ges="n" />
         <note xml:id="note-L14F1" color="red" dur="4" oct="4" pname="f" head.shape="isotriangle" accid.ges="n" />
         <note xml:id="note-L15F1" color="red" dur="4" oct="4" pname="f" head.shape="oval" accid.ges="n" />
         <note xml:id="note-L16F1" color="red" dur="4" oct="4" pname="f" head.shape="piewedge" accid.ges="n" />
         <note xml:id="note-L17F1" color="red" dur="4" oct="4" pname="f" head.shape="rectangle" accid.ges="n" />
         <note xml:id="note-L18F1" color="red" dur="4" oct="4" pname="f" head.shape="rtriangle" accid.ges="n" />
         <note xml:id="note-L19F1" color="red" dur="4" oct="4" pname="f" head.shape="semicirclel" accid.ges="n" />
         <note xml:id="note-L20F1" dur="4" oct="4" pname="f" head.shape="slash" accid.ges="n" />
         <note xml:id="note-L21F1" color="red" dur="4" oct="4" pname="f" head.shape="square" accid.ges="n" />
         <note xml:id="note-L22F1" dur="4" oct="4" pname="f" head.shape="x" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

Note in example data:

```xml
<note             dur="2" oct="4" pname="c" head.shape="quarter" />
<note             dur="4" oct="4" pname="d" head.shape="half" />
<note             dur="4" oct="4" pname="e" head.shape="whole" />
<note color="red" dur="4" oct="4" pname="f" head.shape="backslash" />
<note color="red" dur="4" oct="4" pname="f" head.shape="circle" />
<note             dur="4" oct="4" pname="f" head.shape="+" />
<note             dur="4" oct="4" pname="f" head.shape="diamond" />
<note color="red" dur="4" oct="4" pname="f" head.shape="isotriangle" />
<note color="red" dur="4" oct="4" pname="f" head.shape="oval" />
<note color="red" dur="4" oct="4" pname="f" head.shape="piewedge" />
<note color="red" dur="4" oct="4" pname="f" head.shape="rectangle" />
<note color="red" dur="4" oct="4" pname="f" head.shape="rtriangle" />
<note color="red" dur="4" oct="4" pname="f" head.shape="semicirclel" />
<note             dur="4" oct="4" pname="f" head.shape="slash" />
<note color="red" dur="4" oct="4" pname="f" head.shape="square" />
<note             dur="4" oct="4" pname="f" head.shape="x" />
```

**Comment by craigsapp** [comment]
Here are the SMuFL notehead shapes (not exactly a one-to-one mapping for all notehead shapes, which is probably the main problem with implementation):

https://w3c.github.io/smufl/latest/tables/noteheads.html

But ones that do map:

isotriangle (SMuFL has duration qualifications for this shape):

<img width="535" alt="Screenshot 2024-09-22 at 9 43 52 PM" src="https://github.com/user-attachments/assets/fd55df6d-11f2-4aed-8fad-039f4e615219">

<img width="676" alt="Screenshot 2024-09-22 at 9 45 22 PM" src="https://github.com/user-attachments/assets/a7c3e513-d6d2-4195-8f27-3fb4f307ee7d">

square (they don't look square and maybe map better to rectangle):

<img width="1288" alt="Screenshot 2024-09-22 at 9 46 29 PM" src="https://github.com/user-attachments/assets/92248a2a-40a5-476e-8d5f-859c62733f96">

`+` has duration qualifications, which verovio does not yet address:

<img width="1220" alt="Screenshot 2024-09-22 at 9 47 57 PM" src="https://github.com/user-attachments/assets/3200c985-0786-4ba8-99f7-7edf5a799c9c">


`triangle` (don't know what `rtriangle` is supposed to mean`):

<img width="663" alt="Screenshot 2024-09-22 at 9 48 49 PM" src="https://github.com/user-attachments/assets/65946bbb-e5b7-40d2-aadb-cde13110017c">

<img width="620" alt="Screenshot 2024-09-22 at 9 48 42 PM" src="https://github.com/user-attachments/assets/1ba340c4-c324-4045-a024-d7718eb3a239">

`semicircle` might map to SMuFL`moon`:

<img width="1286" alt="Screenshot 2024-09-22 at 9 49 38 PM" src="https://github.com/user-attachments/assets/0f210ed4-2ec9-47d8-aba3-731d8121dea9">

`piewedge` might map to these:

<img width="1347" alt="Screenshot 2024-09-22 at 9 50 42 PM" src="https://github.com/user-attachments/assets/5f922c7d-05c9-41da-b5f6-9142ba7793e4">

Nothing that looks like it maps to `oval` and `backslash` is probably in the SMuFL font related to `slash` which is not on this page.

**Comment by stereomatchingkiss** [comment]
Tried to implement square by myself, quite difficult to do. Could you give me some suggestions of implementing this shape for the note? Should I start from SMuFL? Thanks

**Comment by rettinghaus** [comment]
You need to activate the needed glyphs [here](https://github.com/rism-digital/verovio/blob/develop/fonts/supported.xml), regenerate the fonts and adjust `GetNoteheadGlyph` in https://github.com/rism-digital/verovio/blob/develop/src/note.cpp.

**Comment by stereomatchingkiss** [comment]
> You need to activate the needed glyphs [here](https://github.com/rism-digital/verovio/blob/develop/fonts/supported.xml), regenerate the fonts and adjust `GetNoteheadGlyph` in https://github.com/rism-digital/verovio/blob/develop/src/note.cpp.

OS : ubuntu22.04.3 LTS

Thanks, trying to generate the glyphs by generate.py, do following steps ok?

- Intall fontforge by following cmd
  - sudo add-apt-repository ppa:fontforge/fontforge
  -sudo apt-get update
  -sudo apt-get install fontforge python-fontforge 
- virtualenv pyenv/verovio
- source pyenv/verovio
- cd verovio/fonts
- pip install verovio
- enable E0B8 and E0B9 from supported.xml
- python generate.py smufl
- python generate.py extract Leipzig
- python generate.py css Leipzig
- python generate.py svg Leipzig

The last cmd give me error message

`generate.py svg: error: the following arguments are required: fontfile`

Not sure which fontfile I should, then I found this doc ["Adding SMuFL glyphs"](https://book.verovio.org/contributing/adding-smufl-glyphs.html), clone the [leipzig](https://github.com/rism-digital/leipzig) repo, edit the [Leipzig.sfd](https://github.com/rism-digital/leipzig/blob/main/Leipzig.sfd) by fontforge. I copy E0DB as the basic of E0B8 , E0DD as the basic of E0B9.

I assume my next steps is study how to edit the glyph by fontforge, update the fonts of the Leipzig repository then call the generate.py again?

**Comment by lpugin** [comment]
> I assume my next steps is study how to edit the glyph by fontforge, update the fonts of the Leipzig repository then call the generate.py again?

Yes, this is right. The documentation is up-to-date, which means you will need to do to PRs. One to the Leipzig repository, and one to this one.

**Comment by stereomatchingkiss** [comment]
I am able to draw E0B8 and E0B9 by verovio, problem is they do not looks good

![Screenshot 2024-09-27 135244](https://github.com/user-attachments/assets/dc0260f9-66c5-4c76-937b-62b0d0c4f845)
![Screenshot 2024-09-27 135301](https://github.com/user-attachments/assets/494b8aa1-6f48-4ddb-9e46-b45990052f7b)


At first I use rectangle to draw E0B8, but the results are not that good, after some trials and errors, I simply copy E0DB and E0DD to E0B8 and E0B9 then rotate 45 degree. I tried to adjust them after that in order to make them looks closer to square but fail, I guess I need more times to study how to draw the font by fontpage. Totally new to font drawing

**Comment by lpugin** [comment]
I added this [here](https://github.com/rism-digital/leipzig/commit/597442e747284050d7f59374d73b7cb04b9df8a9)

![image](https://github.com/user-attachments/assets/2aa7ebfe-ab82-463b-bf29-69bd151e9b44)

I'll integrate them into Verovio

**Comment by lpugin** [comment]
I appreciate your effort. Here is a complete [PR](https://github.com/rism-digital/verovio/pull/3802). You can follow it if you need additional glyphs.

**Comment by stereomatchingkiss** [comment]
> I appreciate your effort. Here is a complete [PR](https://github.com/rism-digital/verovio/pull/3802). You can follow it if you need additional glyphs.

Thanks, this save my life. I pull the develop branch(c93d2fca9f5f1677d47e6a4a02e4ef0f9951f2aa), it works on simple mei(shape.mei) but crash on a bigger mei(Bach_Nun_komm_der_Heiden_Heiland_BWV.659.mei) when I try to load the file.

I upload both of the files, maybe a bug. I would try to add the glyph into 4.3.1 and test again

[Bach_Nun_komm_der_Heiden_Heiland_BWV.659.zip](https://github.com/user-attachments/files/17164378/Bach_Nun_komm_der_Heiden_Heiland_BWV.659.zip)

**Comment by stereomatchingkiss** [comment]
Tested, 4.3.1 work. What I done is copy smufl.h, copy data to verovio folder, enable E0B8 and E0B9 of supported.xml, and 

```
case HEADSHAPE_rectangle:{
            if (duration < DUR_4) {
                return (this->GetHeadFill() == FILL_solid) ? SMUFL_E0B9_noteheadSquareBlack
                                                           : SMUFL_E0B8_noteheadSquareWhite;
            }else {
                return (this->GetHeadFill() == FILL_void) ? SMUFL_E0B8_noteheadSquareWhite
                                                          : SMUFL_E0B9_noteheadSquareBlack;
            }
        }
```
into GetNoteheadGlyph of note.cpp. I guess it is a bug

**Comment by craigsapp** [comment]
> but crash on a bigger mei(Bach_Nun_komm_der_Heiden_Heiland_BWV.659.mei) when I try to load the file.

>  What I done is copy smufl.h, copy data to verovio folder, enable E0B8 and E0B9 of supported.xml

When a glpyh is missing, verovio complains (and at least in the past will crash, although I am careful to update the fonts in the terminal when updating verovio, so I don't know if it still will do that).

**Comment by stereomatchingkiss** [comment]
> > but crash on a bigger mei(Bach_Nun_komm_der_Heiden_Heiland_BWV.659.mei) when I try to load the file.
> 
> > What I done is copy smufl.h, copy data to verovio folder, enable E0B8 and E0B9 of supported.xml
> 
> When a glpyh is missing, verovio complains (and at least in the past will crash, although I am careful to update the fonts in the terminal when updating verovio, so I don't know if it still will do that).

No sure, no exception thrown or error message.

**Comment by lpugin** [comment]
Nothing is crashing for me, so if you have a problem open an issue with all the necessary details.
