### ISSUE TITLE
New compiler warning in src/alignfunctor.cpp

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3803]
There is a new compiler warning that should be checked out for `src/alignfunctor.cpp`:

```
[  9%] Building CXX object CMakeFiles/verovio.dir/verovio/src/alignfunctor.cpp.o
In file included from verovio/src/alignfunctor.cpp:8:
verovio/cmake/../include/vrv/alignfunctor.h:24:1: warning: 'AlignMeterParams' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
struct AlignMeterParams {
^
/Users/craig/git-cloud/vhv/verovio/cmake/../include/vrv/layerelement.h:23:1: note: did you mean struct here?
class AlignMeterParams;
```

(1) Warning says that there may be problems when compiling in Microsoft C++
(2) The warning seems to be caused by using `struct AlignMeterParams` in `alignfunctor.cpp` but defining as `class AlignMeterParams` in `include/vrv/layerelement.h` (so choose one or the other).

Secondary warnings as a result of this are given when compiling `src/doc.cpp`,  `src/findlayerelementsfunctor.cpp`, `src/layer.cpp`, `midifunctor.cpp`, `src/page.cpp`, `src/rest.cpp`, `src/slur.cpp`, `src/system.cpp` and `src/layerelement.cpp`.

Compiled on MacOS Sonoma with clang version `Apple clang version 15.0.0 (clang-1500.3.9.4)`.

**Comment by lpugin** [comment]
Fixed with https://github.com/rism-digital/verovio/commit/769a0bd076f5791f469c828f3a3209ea1d7fe29b
