### ISSUE TITLE
[Pytest] discovery error when using verovio

### ISSUE THREAD

**Issue by Daniel63656** [rism-digital/verovio#3809]
When using `import verovio` in any python file, trying to run pytests for that file (or any file that imports a file that imports verovio) will fail (pytest Discovery error). Using verovio in a jupyter notebook works fine, though.
Even more strangey, running `$ pytest --collect-only` will not report any errors.

**Verovio information**
 I use verovio 4.3.1 (installed with pip install verovio).

**Comment by lpugin** [comment]
You need to give some detailed instructions on how to reproduce this.
