### ISSUE TITLE
Italian lute tablature bass notes: ledger lines too long and clash with the rhythm signs

### ISSUE THREAD

**Issue by paul-bayleaf** [rism-digital/verovio#3828]
Italian lute tablature bass notes are currently implemented using ledger lines.  These ledger lines are too long and clash with the rhythm signs.  Example: the open notes on a 13 course lute from highest pitch to lowest.

![bassdemo-before mei](https://github.com/user-attachments/assets/eac11206-3b55-49a9-8920-6093db246d74)

A common notation in historic Italian lute tablature sources is to use some ledger lines, but most bass courses are notated by their course number.  Although there are variations.  E.g.

https://browse.lutemusic.org/facsimiles/MelliP/Intavolatura_di_Liuto_Attiorbato/v.4_1616/01.png
 
![Melli-1616](https://github.com/user-attachments/assets/bfdb9499-f735-4e13-afae-c32c78a359ae)

Here the 7th course uses a "0" with a ledger line; the 8th, 9th and 11th courses use "8", "9" and "11";  the 10th course uses a Roman "X".  All positioned on the (virtual) 7th staff line.

**Proposal:**
Notate all bass notes on the 7th staff line.
7 course: fret number with a ledger line.
Open 8th, 9th, ... :  course number on 7th staff line.
Fretted 8th, 9th ... (rare):  fret number with a ledger line, but positioned on 7th staff line with the remaining ledger lines compressed below.

Fix ledger line length.
Raise rhythm flags above the 7th staff line.

I'll raise a pull request to implement this proposal.   This issue was a result of a discussion with Tim  Crawford.

Mei for above.
[bassdemo.mei.zip](https://github.com/user-attachments/files/17363121/bassdemo.mei.zip)

**Comment by lpugin** [comment]
Would you expect the encoding you posted? There is nothing in it that indicates that all courses above 6 should be rendered on a same ledger line. Are you categorical that there is never more than one ledger line?

**Comment by paul-bayleaf** [comment]
There is much variety in historical tablatures.  There are certainly tablatures for 8 course lutes that use two ledger lines for the 8th course, e.g.

![two-ledger](https://github.com/user-attachments/assets/9f2ce764-e5ca-45dc-bb13-4a6e78440c69)

Were there rhythm signs here then they would need to be raised even higher.  I have also seen two slashes used instead of ledger lines, one through the fret number the other after, keeping the note on the 7th line.   But where more courses are used course numbering, all placed on line 7, seems to be common.  Fretting the 8th or above is rare, they are usually open so course numbering usually suffices.  In my proposal if a second (or more) ledger line is needed then it is compressed below the fret number.  Example of my proposal, a fretted 8th, first chord in the second bar, with an open 8th course later:

![fretted8th](https://github.com/user-attachments/assets/5508eac5-dc94-47e4-a648-9bbabbecff2c)

**Comment by lpugin** [comment]
Thanks. Could you post the encoding for the example above? Again, I am not sure I understand what in the encoding indicates the number of ledger lines to render.

**Comment by Ailin-Ricerar** [comment]
If I understood your question correctly @lpugin, I think the fact that you define the tablature for a 7-course (or more) lute will render the associated notes on ledger lines.

**Comment by Ailin-Ricerar** [comment]
@paul-bayleaf I would also appreciate it if you could provide the encoding for "raised rhythm signs".

**Comment by paul-bayleaf** [comment]
My proposal is that the 7th course always uses one ledger line through the fret number.   Open 8th and above always use course number on the 7th line, no ledger.   Fretted (stopped) 8th and above use a ledger line through the fret number on the 7th line, then compressed ledger lines below the fret number - 1 below for 8th course, 2 for 9th ...   They are compressed so that all bass notes are notated on the 7th line.   All rhythm signs are all at the same level just above the 7th line.

These features can be seen in the example of my proposal above.  I will produce a cut down MEI encoding for it (the above is a screen shot from a full piece of MEI encoded Italian tablature).  But no special encoding is required for this proposal, the existing tab.fret and tab.course is all that is required to determine whether to use course numbering or fret numbering with ledger lines, and if so how many.

I am not proposing raising individual rhythm signs - although that does occur in some historic Italian tablatures.  Nor am I attempting to emulate other variations in Italian tablature - just a single scheme, reasonably historically accurate (see Milli facsimile above) , using course numbering for open basses 8th and above so that it can cope with Italian tablature with any number of courses.

**Comment by Ailin-Ricerar** [comment]
Thank you. I see what you mean. But for me, the problem also occurs for the 7th course. When I have my mei encoding rendered in Verovio, the rhythmic signs clash with the 7th course (the first ledger line) as you can see in the screen shot.
![Screenshot 2024-10-16 085532](https://github.com/user-attachments/assets/54e50102-f8db-4a1f-a495-859b136f8fbb)

**Comment by paul-bayleaf** [comment]
@Ailin-Ricerar No problem, with my proposal all rhythm signs in Italian tablature are positioned above the 7th line, regardless of the number of courses.  Here is your example rendered using my proposal.

![ailin tab mei](https://github.com/user-attachments/assets/5f723c2d-b68f-408f-b146-0e825c09e114)

**Comment by lpugin** [comment]
@musicog ? @DILewis ? How does it look from your point of view?

**Comment by DILewis** [comment]
This seems sensible to me, at least as a default. We will probably want to be able to say in the MEI how the bass courses are indicated at some point (for French tab too), but what @paul-bayleaf describes is the most common case (well, probably the most common case is probably for 6/7/8 course instruments anyway)

**Comment by Ailin-Ricerar** [comment]
@paul-bayleaf I still don't understand what I need to  change in the code for renderin to have all rhythmic signs above the 7th course? for <note tab.course="7" tab.fret="0"> ?

**Comment by paul-bayleaf** [comment]
@Ailin-Ricerar You don't need to change anything - I need to submit my PR to change the Italian tablature rendering C++ code in Verovio.

**Comment by Ailin-Ricerar** [comment]
@paul-bayleaf Thank you! That is great! So, I can wait for it to be rendered correctly soon. :)

**Comment by Ailin-Ricerar** [comment]
@paul-bayleaf The problem is still unresolved (at least as far as I can see!).

**Comment by paul-bayleaf** [comment]
@lpugin My mistake, branch develop indeed has the fix https://github.com/rism-digital/verovio/pull/3831.  Thanks.

@Ailin-Ricerar what version or branch were you running for which the problem is unresolved?

**Comment by Ailin-Ricerar** [comment]
I was not using the latest version, Sorry! Indeed, the latest version has the fix. Thanks again!
