### ISSUE TITLE
Tempo specified in musicxml is ignored in generated midi file

### ISSUE THREAD

**Issue by andre2007** [rism-digital/verovio#3844]
Hi,

Please find attached a sample musicxml file. In essence it contains the tempo tag

``` xml
    <direction placement="above">
                                <sound tempo="50.0" />
                        </direction>
```

While importing the file into MuseScore and press the play button, the slow tempo is recognized and it is played slowly.
But while using Verovio api (`RenderToMIDIFile`) to generate the midi file, the tempo is ignored. 

I am using latest version of Verovio (4.3.0).
I tried various things, but cannot find out, why the midi file is not played slowly as defined.

[sample_tempo.zip](https://github.com/user-attachments/files/17604273/sample_tempo.zip)

Kind regards
André

**Comment by rettinghaus** [comment]
I tested the file with the latest release and the development version, and it works fine. The tempe is set to 50 bpm.
