### ISSUE TITLE
GetElementsAtTime function does not return rests data if there is a whole measure rest(mRest) in a measure.

### ISSUE THREAD

**Issue by lzgofsc** [rism-digital/verovio#3850]
**Describe the problem**
GetElementsAtTime function does not return rests data if there is a whole measure rest(mRest) in a measure.

**Input data**
```xml
<measure xml:id="m-198" n="15">
    <staff xml:id="m-200" n="1">
        <layer xml:id="m-201" n="1">
            <mRest xml:id="m-202" tstamp.real="00:00:33.6"/>
        </layer>
    </staff>
</measure>
```

**Verovio information**
 - 4.2.1
 - C++

**Environment information (as appropriate)**
 - OS: MacOS
 - Browser: Safari

**Comment by lpugin** [comment]
Please provide a complete MEI file posted with [backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) and the command call with the parameters.
