### ISSUE TITLE
Specify bracketSpan in Verovio customisation

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3851]
**Is your feature request related to a problem? Please describe.**
Dealing with semi closed lists for attribute values is suboptimal. But using only the predefined ones in the ODD will lead to lost information while importing other formats.

**Describe the solution you'd like**
To handle bracketSpan@func values better in Verovio, we could add specific values to the list and make it a closed one in the Verovio customisation.

**Additional context**

**Comment by lpugin** [comment]
I've been always hoping we could avoid to have a Verovio customization that adds things to the MEI schema. However, in that case it might be acceptable since the generated MEI would still be valid with the official schema, wouldn't it?

**Comment by rettinghaus** [comment]
Yes, as full MEI has specified an open list, basically every value is valid. And we wouldn't mess with the MEI structure, only specify the values we want to generate with `libmei` for Verovio.
