### ISSUE TITLE
Compatibility issue with Object.hasOwn on lower versions of iOS Safari.

### ISSUE THREAD

**Issue by csa8280** [rism-digital/verovio#3856]
**Describe the problem**
Compatibility issue with Object.hasOwn on lower versions of iOS Safari.

**Screenshots**
<img width="841" alt="image" src="https://github.com/user-attachments/assets/b4e2d5d9-a2a6-4e25-8f13-602d7bc6d6e4">

Replace Object.hasOwn with Object.prototype.hasOwnProperty.call.

**Comment by lpugin** [comment]
This has already been [fixed](https://github.com/rism-digital/verovio/commit/62069bb3c15122e0bef147164cb927be452a2422). I would assume it to be a problem only with old versions of Safari, though.

**Comment by csa8280** [comment]
Not fixed
```
Object.prototype.hasOwnProperty.call(options, 'fontAddCustom')
```
OK
