### ISSUE TITLE
connect ledger lines with related events

### ISSUE THREAD

**Issue by kepper** [rism-digital/verovio#3858]
**Is your feature request related to a problem? Please describe.**
The current SVG output of Verovio structurally separates ledger lines from the events (notes, accids, chords) that triggers them. This is perfectly fine as a single ledger line may hold more than one such event, for example in case of the first ledger line that is shared by the notes of a chord. However, for post-processing the SVG, it would be extremely helpful to have a reference from the rendered ledger line to the events that require it's presence. As there is no MEI element for ledger lines, there is no external solution for this, except for guessing these relations. 

**Describe the solution you'd like**
As this is a very special use case, it seems fine to make it available only with `--svg-html5` enabled. A solution might then look like so:
```xml
<g class="ledgerLines above">
   <g class="ledgerLine" data-events="note1">…</g>
</g>
```
`@data-events` would then have a whitespace-separated list of IDs of relevant events. I don't mind if it gets a prepended hash, but would not need that. For ledger lines sharing events (as in the second example / chord in the attached file), an encoding might look like so:
```xml
<g class="ledgerLines above">
   <g class="ledgerLine" data-events="note2 note3">…</g>
   <g class="ledgerLine" data-events="note3">…</g>
</g>
```
Alternatively, a reference from all ledger lines to just the chord would be equally possible, but less flexible than the solution above. 

**Additional context**
The attached file would be the input file for which the above output is expected. 
[ledgerlines.mei.zip](https://github.com/user-attachments/files/17706420/ledgerlines.mei.zip)

**Comment by lpugin** [comment]
I think it would be good for it also to work without `--svg-html5`. Maybe it could be without it:
```xml
<g class="ledgerLines above">
   <g class="ledgerLine mei-id-note2 mei-id-note3">…</g>
   <g class="ledgerLine mei-id-note3">…</g>
</g>
```
and with it:
```xml
<g class="ledgerLines above">
   <g class="ledgerLine" data-mei-id="note2 note3">…</g>
   <g class="ledgerLine" data-mei-id="note3">…</g>
</g>
```
even though I believe the second approach might be preferable. Any thoughts?

**Comment by kepper** [comment]
I don't mind if it's available without that option as well. That said, it feels a bit like tag abuse to put that information into a regular class. also, if I get that right, you're planning to prefix the actual ID with `mei-id-`, which is certainly doable, but maybe already indicates that there is a problem. If SVG 1.0 as an output format does not permit to transport certain information, then users have to use a different output format, using `--svg-html5`. However, I have no strong opinions on this – all I can say is that I will always use `--svg-html5` anyway, as it resolves some other relevant issues for me.

**Comment by lpugin** [comment]
OK, let's forget about the use of `@class`. Is `@data-mei-id` as name OK for you? I find "event" quite overloaded.

**Comment by ahankinson** [comment]
What about `data-note`? Would the same concept apply to accidentals? Can you have anything other than note ids in there?

**Comment by kepper** [comment]
`@data-mei-id` is certainly fine with me. `@data-note` seems a bit too restricted – you're already mentioning accids, @ahankinson, and also it seems to be a bit too close to `@data-annot` and the like… ;-) But again, I have no strong opinions on this, and as long as you consider this at all, I'm quite happy…

**Comment by ahankinson** [comment]
Yeah, I was just noting that `data-mei-id` says what it is (should it be `#note2`?) but doesn't give any idea of its function. Maybe `data-note-group` or `data-element-group` also? If I saw "mei-id" I wouldn't necessarily see that as a way of grouping things...

**Comment by lpugin** [comment]
Not sure about it is about grouping. It is more about saying that the ledger line corresponds to a certain MEI element, or more precisely that is it there because of it.

**Comment by kepper** [comment]
Sorry for dropping the ball on this. I'm loosely with @ahankinson on this – I was also struggling to find the right name. However, I also don't see it as a grouping mechanism in the first place – it just `connects`, or `relatesTo` something else. I believe it's good to avoid MEI lingo like `corresp`. Prefixing a `#` to indicate this linking nature is perfectly fine, but that doesn't necessarily resolves the problem completely. What about `@data-holds="#note1"`?

**Comment by lpugin** [comment]
`data-relation` ?

**Comment by kepper** [comment]
yes, thought about that as well. It's just very generic, and I was unsure if that could stand in the way at some point… If we ignore that possibility for now, I'm perfectly happy…

**Comment by ahankinson** [comment]
My English grammar instinct tells me that `data-related` is probably preferable, over `data-relation`.
