### ISSUE TITLE
Neumes under the staff -> score height incorrectly determined

### ISSUE THREAD

**Issue by igneus** [rism-digital/verovio#3863]
**Describe the problem**
When rendering a neumes score with bottom whitespace stripped (`--adjust-page-height --page-margin-bottom 0`) and the score has notation elements reaching under the staff, it seems that these (while affecting vertical position of lyrics) are not taken into account when computing score height, resulting in lyrics being partially cropped or ending up completely out of the image.

![093](https://github.com/user-attachments/assets/20a15049-125b-41b5-9e48-dcaf5892dc0d)

(This behavior is not specific to scores on a one-line staff.)

**To Reproduce**
`verovio --outfile 093.svg --adjust-page-height --page-margin-bottom 0 093_F27_benedictus_pem80159_aquit_AQUIT.mei`

(The input file is available [here](https://github.com/ECHOES-from-the-Past/GABCtoMEI/blob/main/MEI_outfiles/antiphonae_feriale/093_F27_benedictus_pem80159_aquit_AQUIT.mei), several other examples of similar Verovio behavior can be found in the same directory.)

**Expected behavior**
The output height is computed so as to accomodate complete lyrics, no matter how deep below the staff some notation elements may reach.

**Input data**

```xml
<?xml version="1.0" ?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-Neumes.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
	<music>
		<body>
			<mdiv xml:id="m-57e08acc-90a3-11ef-a61e-f2b2e3f0b574">
				<score xml:id="m-57e08b6c-90a3-11ef-a61e-f2b2e3f0b574">
					<scoreDef xml:id="m-57e08bb2-90a3-11ef-a61e-f2b2e3f0b574">
						<staffGrp xml:id="m-57e08be4-90a3-11ef-a61e-f2b2e3f0b574">
							<staffDef n="1" lines="1" notationtype="neume" xml:id="m-57e08c16-90a3-11ef-a61e-f2b2e3f0b574"/>
						</staffGrp>
					</scoreDef>
					<section xml:id="m-57e08c52-90a3-11ef-a61e-f2b2e3f0b574">
						<staff n="1" xml:id="m-57e08c84-90a3-11ef-a61e-f2b2e3f0b574">
							<layer n="1" xml:id="m-57e08cb6-90a3-11ef-a61e-f2b2e3f0b574">
								<syllable xml:id="m-57e093e6-90a3-11ef-a61e-f2b2e3f0b574">
									<syl wordpos="i" xml:id="m-57e0942c-90a3-11ef-a61e-f2b2e3f0b574">nus</syl>
									<neume xml:id="m-57e0945e-90a3-11ef-a61e-f2b2e3f0b574">
										<nc loc="-2" xml:id="m-57e09490-90a3-11ef-a61e-f2b2e3f0b574"/>
										<nc loc="-3" xml:id="m-57e094c2-90a3-11ef-a61e-f2b2e3f0b574"/>
									</neume>
								</syllable>
							</layer>
						</staff>
					</section>
				</score>
			</mdiv>
		</body>
	</music>
</mei>

```

**Verovio information**
 - Version of Verovio: develop (verovio --version prints "Verovio 4.4.0-dev-f562935")
 - Binding: command-line

**Environment information (as appropriate)**
 - OS: Linux

**Comment by lpugin** [comment]
<img width="326" alt="image" src="https://github.com/user-attachments/assets/4adcb1d7-aa08-4e19-b33b-b0392f77375b">

**Comment by igneus** [comment]
Thanks! I confirm the issue is gone.
