### ISSUE TITLE
[LibMEI] default values are ignored

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3887]
Currently TEI's `defaultVal` element for attributes is ignored on generating LibMEI. Ideally the converter should return the `defaultVal` as default.

**Comment by lpugin** [comment]
Could you give an example? What do you mean by return? Which method?

**Comment by rettinghaus** [comment]
See in `AttConverterBase` `HarpPedalLogAToStr`:

https://github.com/rism-digital/verovio/blob/e5f06264fc1226924ca18b5b44ed2cee15000163/libmei/dist/attconverter.cpp#L4458-L4461

The `defaultVal` in the schema is "n", so I would expect it to return an n.

The inverse then should return `harpPedalLog_A_n` instead of `harpPedalLog_A_NONE`.

**Comment by lpugin** [comment]
I am not sure why we have a default value for these attributes. Your proposal will cause problems because if you read a file with no `@a` - which is perfectly valid - the converter will set the value to `n` and export it when you do so. Since in general MEI has no strong concept of default values I think a better proposal would be to drop these.

**Comment by rettinghaus** [comment]
If these default values make sense is a different topic, isn't it?

We also have a default value of 0 for `@rotate`:

https://github.com/rism-digital/verovio/blob/e5f06264fc1226924ca18b5b44ed2cee15000163/libmei/mei/mei-all_compiled.odd#L12755-L12768

But in this case it's the other way around: all values that are treated as double in LibMEI are lost if set to `0.0`.

(Still I agree with you that these default values should be removed.)

**Comment by lpugin** [comment]
So we should probably keep ignoring them if they should be removed, shouldn't we?

**Comment by lpugin** [comment]
Can be closed here.
