### ISSUE TITLE
What happens if getElementAttr is called with an invalid ID

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#3895]
### Discussed in https://github.com/rism-digital/verovio/discussions/3894

<div type='discussions-op-text'>

<sup>Originally posted by **andre2007** December 16, 2024</sup>
Hi,
I trying to track down a very weird behavior in my application. For some reasons `renderToTimemap` returns in `on` array a xml ID which causes weired memory issues when calling method `getElementAttr`.

It looks like that calling method `getElementAttr` with an invalid xml ID causes strange behavior. What is the expected behavior if the method is called with an invalid XML ID? Does it make sense to return a JSON like this from the method `getElementAttr`, in case the xml Id is invalid?

```json
{
"error": true,
"errorText": "XML Id ABC is invalid"
}
````

Kind regards
André</div>

**Comment by lpugin** [comment]
Testing and looking at the code shows that it returns and empty JSON object and that everything works as expected - tested with JavaScript and Python with the latest version. 

You need to provide more information about your environment and your data for the issue to be reproduced.

**Comment by andre2007** [comment]
Thanks for having a look. I was trying to minimize the issue and was not able to. I assume something very strange is going on in my application and it is not related to Verovio. Sorry for the noise 😥.
You can close the incident.
