### ISSUE TITLE
Stem-side staccato placement

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#398]
When staccatos are placed on the stem-side of notes, they should be aligned with the stem, not the center of the note.

In other words this:

<img width="422" alt="screen shot 2016-12-27 at 07 29 00" src="https://cloud.githubusercontent.com/assets/3487289/21502809/6328b436-cc07-11e6-83e7-5e2ee4ddb678.png">

should instead be this:

<img width="422" alt="staccstem" src="https://cloud.githubusercontent.com/assets/3487289/21502817/6ef2ae0c-cc07-11e6-96d7-53d5ce9cfba3.png">

I like to justify the staccato to the outside edge of the stem so that it is shifted slightly towards the center of the notehead.

Test MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt>
                <date>2016-12-27 07:41:30</date>
            </pubStmt>
        </fileDesc>
        <encodingDesc>
            <projectDesc>
                <p>Transcoded from Humdrum with Verovio version 0.9.13-dev-a3ff6a7-dirty</p>
            </projectDesc>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000017527934">
                        <staffGrp xml:id="m-000000199810059">
                            <staffDef xml:id="staffdef-000000187497925" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000176594407">
                        <measure xml:id="measure-L3" right="end">
                            <staff xml:id="staff-L3F1" n="1">
                                <layer xml:id="layer-L3F1" n="1">
                                    <note xml:id="note-L5F1" dur="4" oct="4" pname="e" accid.ges="n">
                                        <artic xml:id="artic-000000161837572" artic="stacc" />
                                    </note>
                                    <note xml:id="note-L6F1" dur="2" oct="4" pname="g" accid.ges="n">
                                        <artic xml:id="artic-000000127432566" artic="stacc" />
                                    </note>
                                    <note xml:id="note-L7F1" dur="4" accid="s" oct="4" pname="f">
                                        <artic xml:id="artic-000000103016342" artic="stacc" />
                                    </note>
                                </layer>
                                <layer xml:id="layer-L5F2" n="2">
                                    <note xml:id="note-L5F2" dur="4" oct="4" pname="c" accid.ges="n">
                                        <artic xml:id="artic-000000137061567" artic="stacc" />
                                    </note>
                                    <note xml:id="note-L6F2" dur="2" oct="4" pname="c" accid.ges="n">
                                        <artic xml:id="artic-000000190962713" artic="stacc" />
                                    </note>
                                    <note xml:id="note-L7F2" dur="4" oct="4" pname="d" accid.ges="n">
                                        <artic xml:id="artic-000000167320565" artic="stacc" />
                                    </note>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
I think both alignment with the note head and alignment with the stem is OK. This is a styling issue.

**Comment by craigsapp** [comment]
Thin articulations (staccatos and staccatissimos) should be aligned with stems when on the stem side.  This is a fairly strong convention and typically would be violated only for specific reasons where the articulation has to be placed between the notehead and the end of the stem.  So in terms of styling, the default styling should be centering on the stem when placed on the stem side.  When implementing a styling feature for this sort of case, a value of 0 through 1 (or 1 through 0) would control centering on notehead to centering on stem (when staccato is on the stem side).  A value of 0.5 would be to center half-way between the edge of the notehead and the center of the note.

Beethoven sonata no. 1, op. 2/1:

Peters edition, c1920 (staccato placement parameter might be "0.5" for this case):

http://ks.petruccimusiclibrary.org/files/imglnks/usimg/1/13/IMSLP66390-PMLP01446-Sonata_F_minor_Opus_2_no_1.pdf
<img width="581" alt="screen shot 2016-12-31 at 08 28 57" src="https://cloud.githubusercontent.com/assets/3487289/21578419/d9e469ce-cf33-11e6-8a18-c3dde77ff885.png">

Riccordi, 1919:

http://ks.imslp.net/files/imglnks/usimg/1/17/IMSLP66279-PMLP01446-Opus_2_no_1.pdf
<img width="685" alt="screen shot 2016-12-31 at 08 35 16" src="https://cloud.githubusercontent.com/assets/3487289/21578431/1cbc5e5a-cf34-11e6-807f-23ffec139b80.png">

Universal editions, c1920:

http://petrucci.mus.auth.gr/imglnks/usimg/8/8e/IMSLP00001-Beethoven__L.v._-_Piano_Sonata_01.pdf
<img width="597" alt="screen shot 2016-12-31 at 08 36 30" src="https://cloud.githubusercontent.com/assets/3487289/21578437/4602ffee-cf34-11e6-8a85-6b39dc2b8880.png">

Peters, c1910 (hybrid centered 1/4 of notehead due to staccato placed inside stem):

http://ks.imslp.net/files/imglnks/usimg/9/94/IMSLP27752-PMLP01446-Beethoven_Sonaten_Piano_Band1_Peters_No1_Op2.pdf
<img width="592" alt="screen shot 2016-12-31 at 08 37 33" src="https://cloud.githubusercontent.com/assets/3487289/21578439/7d3c0b68-cf34-11e6-8ee0-45fbe26f392e.png">

Cotta, c1875:
http://hz.imslp.info/files/imglnks/usimg/c/cc/IMSLP19667-PMLP01446-Beethoven_-_Piano_Sonata_No.1_Cotta.pdf
<img width="349" alt="screen shot 2016-12-31 at 08 39 48" src="https://cloud.githubusercontent.com/assets/3487289/21578441/b6d0d962-cf34-11e6-8263-d29dedda6d2a.png">

Breitkopf & Haertel, 1862:

<img wihttp://imslp.nl/imglnks/usimg/8/85/IMSLP243106-PMLP01446-Beethoven__Ludwig_van-Werke_Breitkopf_Kalmus_Band_20_B124_Op_2_No_1_scan.pdfdth="375" alt="screen shot 2016-12-31 at 08 41 27" src="https://cloud.githubusercontent.com/assets/3487289/21578450/f9be1dc0-cf34-11e6-92bc-45a1dc11cd17.png">

Hallberger, 1860 (the only edition which does not do stem alignment):

http://imslp.nl/imglnks/usimg/d/d1/IMSLP90564-PMLP01446-Beethoven__Lv__Piano_Sonata_No.1__Op.2_No.1__Moscheles.pdf
<img width="345" alt="screen shot 2016-12-31 at 08 42 38" src="https://cloud.githubusercontent.com/assets/3487289/21578454/20987814-cf35-11e6-822e-1e0733db27f3.png">

Earlier editions follow the first edition and put the staccato on the notehead side:

Cranz, 1821:
http://ks.imslp.info/files/imglnks/usimg/4/43/IMSLP333393-PMLP01446-b1027215x.pdf
<img width="370" alt="screen shot 2016-12-31 at 08 44 22" src="https://cloud.githubusercontent.com/assets/3487289/21578468/f952a986-cf35-11e6-8494-c6af5924d74f.png">

Royal Harmonic Institution, c. 1821:
http://imslp.nl/imglnks/usimg/d/da/IMSLP328877-PMLP01446-b25669825.pdf
<img width="372" alt="screen shot 2016-12-31 at 08 49 55" src="https://cloud.githubusercontent.com/assets/3487289/21578472/2794b41a-cf36-11e6-9669-a3e21305c996.png">

First edition, 1796:
http://hz.imslp.info/files/imglnks/usimg/6/60/IMSLP51970-PMLP01446-Beethoven_-_Piano_Sonata_No.1__Artaria_.pdf
<img width="436" alt="screen shot 2016-12-31 at 08 51 18" src="https://cloud.githubusercontent.com/assets/3487289/21578475/5412af4c-cf36-11e6-9cb5-52fd6e5ea1df.png">

Digitally typeset editions, both strangely centering on notehead:

Using Finale:
http://petrucci.mus.auth.gr/imglnks/usimg/2/27/IMSLP176505-WIMA.e1a5-SONATA_I_beethoven_f_minor.pdf
<img width="563" alt="screen shot 2016-12-31 at 08 58 04" src="https://cloud.githubusercontent.com/assets/3487289/21578496/50868672-cf37-11e6-8ebc-314f53cb4552.png">

Using lilypond:
http://javanese.imslp.info/files/imglnks/usimg/3/3e/IMSLP25015-PMLP01446-mutopiabeethovenop2no1mvmnt1.pdf
<img width="629" alt="screen shot 2016-12-31 at 08 59 07" src="https://cloud.githubusercontent.com/assets/3487289/21578506/6da15bf6-cf37-11e6-9354-a18c4c93a732.png">

**Comment by craigsapp** [comment]
In *Behind Bars*, both alignment methods are accpetable (page 118):

<img width="597" alt="screen shot 2016-12-31 at 09 13 15" src="https://cloud.githubusercontent.com/assets/3487289/21578549/78c144f4-cf39-11e6-8535-6b5da1903a1e.png">

**Comment by craigsapp** [comment]
Here is a case where stem aligned staccatos look better:

<img width="172" alt="screen shot 2017-01-26 at 08 04 10" src="https://cloud.githubusercontent.com/assets/3487289/22339291/4aba333a-e39e-11e6-8181-5a0b2b6762c4.png">

Compared to:

<img width="202" alt="screen shot 2017-01-26 at 08 04 18" src="https://cloud.githubusercontent.com/assets/3487289/22339294/4f3ad09a-e39e-11e6-86c4-8f49b7ccccd8.png">

MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-01-26T08:08:14" version="0.9.14-dev-77d1faa">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-000000040244513">
                        <staffGrp xml:id="m-000000134891573" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-000000029531765" clef.shape="G" clef.line="2" key.sig="3f" n="1" lines="5" />
                            <staffDef xml:id="staffdef-000000077335064" clef.shape="F" clef.line="4" key.sig="3f" n="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-000000033899572">
                        <measure xml:id="measure-L6" n="4">
                            <staff xml:id="staff-L6F2" n="1">
                                <layer xml:id="layer-L6F2" n="1">
                                    <beam xml:id="beam-000000133029351">
                                        <note xml:id="note-L7F2" dur="8" oct="5" pname="d">
                                            <accid xml:id="accid-L7F2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L8F2" dur="8" oct="5" pname="e">
                                            <accid xml:id="accid-L8F2" accid.ges="f" />
                                        </note>
                                    </beam>
                                    <note xml:id="note-L9F2" dur="2" oct="5" pname="c">
                                        <accid xml:id="accid-L9F2" accid.ges="n" />
                                    </note>
                                </layer>
                                <layer xml:id="layer-L6F3" n="2">
                                    <rest xml:id="rest-L7F3" dur="4" />
                                    <note xml:id="note-L9F3" dur="4" oct="4" pname="e">
                                        <accid xml:id="accid-L9F3" accid.ges="f" />
                                        <artic xml:id="artic-000000109076242" artic="stacc" />
                                    </note>
                                    <note xml:id="note-L10F3" dur="4" oct="4" pname="e">
                                        <accid xml:id="accid-L10F3" accid.ges="f" />
                                        <artic xml:id="artic-000000201687481" artic="stacc" />
                                    </note>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L6F1" n="2">
                                <layer xml:id="layer-L6F1" n="1">
                                    <rest xml:id="rest-L7F1" dur="4" />
                                    <chord xml:id="chord-L9F1" dur="4">
                                        <note xml:id="note-L9F1S1" oct="3" pname="c">
                                            <accid xml:id="accid-L9F1S1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L9F1S2" oct="3" pname="g">
                                            <accid xml:id="accid-L9F1S2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L9F1S3" oct="4" pname="c">
                                            <accid xml:id="accid-L9F1S3" accid.ges="n" />
                                        </note>
                                        <artic xml:id="artic-000000011899188" artic="stacc" />
                                    </chord>
                                    <chord xml:id="chord-L10F1" dur="4">
                                        <note xml:id="note-L10F1S1" oct="3" pname="c">
                                            <accid xml:id="accid-L10F1S1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L10F1S2" oct="3" pname="g">
                                            <accid xml:id="accid-L10F1S2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L10F1S3" oct="4" pname="c">
                                            <accid xml:id="accid-L10F1S3" accid.ges="n" />
                                        </note>
                                        <artic xml:id="artic-000000101023939" artic="stacc" />
                                    </chord>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
