### ISSUE TITLE
layout interaction with horizontal justification

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#515]
When music on a system is stretched or compressed to justify it to the full width of the page, the layout becomes sub-optimal.

Here is an example of making it noticeable:

```bash
verovio input.krn -w 1000 -h 1000 --spacing-system=0 --spacing-non-linear=0.5 --spacing-linear=0.05
```
<img width="748" alt="screen shot 2017-03-11 at 8 29 35 am" src="https://cloud.githubusercontent.com/assets/3487289/23824923/f8547326-0634-11e7-837b-73b98c88384b.png">

The algorithm is:
(1) layout the music in a long single system
(2) find the points to break the long system into shorter lines to fit on the page
(3) stretch or compress the notation to justify to the full width of the page.

The problem is that the stretching or compression will cause problems such as the non-uniform spacing of eighth-notes in the first line of this example:

<img width="784" alt="screen shot 2017-03-11 at 8 34 07 am" src="https://cloud.githubusercontent.com/assets/3487289/23825062/a87e89f6-0637-11e7-970e-f726782d2bce.png">

Notice the two red lines which are the same length.  For the distance between the second and third notes, there is an extra space added to fit in the accidental.  In the original layout before stretching, this extra space was required to avoid colliding the accidental with the previous note.  When the music is stretched, the accidental does not need extra space to avoid colliding with the previous note.

Originally this music was layed out similar to the second line of music:

<img width="741" alt="screen shot 2017-03-11 at 8 34 54 am" src="https://cloud.githubusercontent.com/assets/3487289/23824954/a6370242-0635-11e7-9612-85804b0c457f.png">

But then it was stretched to fill the entire width of the page, and as it was stretched, the extra space added to the original layout to insert the accidentals was exaggerated, causing the eighth notes to not be spaced properly.  With the extra space added by the stretching, the spaces added for the accidentals are no longer needed for this line.

It is usually a minor effect in normal music with sufficient width, but would be important to fix for published music intended for performance or aesthetics.  The obvious solution is that the music on each line would be re-spaced horizontally after being broken up into shorter segments, giving the width of the page as the available space to fill.  

This basically will double the layout calculation time, so one possible solution is to add an option to verovio which would enable the double layout system: once to chop up the music into system lines, and once more to refine the spacing on each line.  Users who want fast notation would not turn on this option, and those who need more accuracy could turn it on.

Alternatively, a layout system that keeps track of regions of extra space might be able to redo the layout faster on the broken systems by reverting to the pure rhythmic spacing, and then checking to see if each extra space region is still needed (that would work for stretching cases, but not for compression cases where new extra spaces may be needed).  Perhaps some sort of hierarchical system for horizontal spacing that would allow efficient re-calculation of layout refinements might be possible...

Humdrum test data:

```
**kern
*clefF4
*k[b-e-a-]
*c:
*M3/4
=1-
(8G\L
8E-\)
(8BBn\
8C\J)
4AA-/
=2
(8c\L
8A-\)
(8En\
8F\J)
4BBn/
=3
(8d\L
8A-\)
(8En\
8F\J)
(8GG\L
8G\J)
=4
(8F\L
8E-\)
(8BBn\
8C\J)
4CC/
=5
(8C\L
8E-\
8A-\)
(8G\
8d-X\
8c\J)
=6
(8D\L
8F\
8B-\)
(8A-\
8c\
8B-\J)
=7
(8A-\L
8G\)
(8D\
8E-\)
(8BB-\
8D\J)
=8
2.EE-/
=9:|!|:
(8B-\L
8G\)
(8D\
8E-\J)
4DD-X/
=10
(8B-\L
8G\)
(8En\
8F\J)
4GG/
=11
(8d-X\L
8B-\)
(8En\
8F\J)
8CC\L
8c\J
=12
(8B-\L
8A-\)
(8En\
8F\J)
4FF/
=13
(8EE-\L
8C\
8F\)
(8E-\
8B-\
8An\J)
=14
(8DD\L
8D\
8G\)
(8F\
8c\
8Bn\J)
=15
(8c\L
8A-\)
(8F#X\
8G\)
8BBn\
8C\J
=16
(8GG\L
8D\)
(8G\
8F#X\)
8c\
8Bn\J
=17
(8e-\L
8c\)
(8F#X\
8G\J)
8AAn\L
8e-\J
=18
(8d\L
8A-X\)
(8En\
8F\J)
8BBn\L
8G\J
=19
(8F\L
8E-\
8BBn\
8C\J)
(8GG\L
8Bn\J)
=20
(8CC/L
8GG/
8F/
8E-/J
4c\)
=:|!
*-
```

**Comment by rettinghaus** [comment]
@craigsapp could you please test again? This should be fine now.

**Comment by rettinghaus** [comment]
@craigsapp Could you please close this one?
