### ISSUE TITLE
grace note ledger lines touch regular note ledger lines

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#647]
When a regular note is preceded by a beamed grace note with ledger lines, the ledger lines of the two notes touch (which they should not):

<img width="368" alt="screen shot 2017-07-01 at 12 20 23 pm" src="https://user-images.githubusercontent.com/3487289/27761198-ad0edaf2-5e57-11e7-8ab9-246cdc147304.png">

Test data:

```
**kern
16aaqL
16bbqJ
4ccc
*-
```

**Comment by lpugin** [comment]
Not actually touching ;-)

![image](https://user-images.githubusercontent.com/689412/100642611-43e27880-3339-11eb-8480-b83b8aba72c1.png)
