### ISSUE TITLE
Slash placement for grace notes

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#648]
Here is the way that grace note slashes are rendered in verovio:

<img width="634" alt="screen shot 2017-07-01 at 12 36 02 pm" src="https://user-images.githubusercontent.com/3487289/27761315-e4879292-5e59-11e7-899d-c5b8f002a0fc.png">

Test data:

```
**kern
8gq
4f
16gq
4f
32gq
4f
64gq
4f
128gq
4f
=
*-
```

In a survey of two other notation programs, the slash follows the top flag of the grace note, not the bottom flag:

SCORE:

<img width="822" alt="screen shot 2017-07-01 at 12 37 57 pm" src="https://user-images.githubusercontent.com/3487289/27761332-21454198-5e5a-11e7-95a3-6fb8e0117768.png">

MuseScore:

![acciaccatura values](https://user-images.githubusercontent.com/3487289/27761334-291c6900-5e5a-11e7-98de-53ae191bec9e.png)

[also note in tight spacing conditions, the grace note is closer to the previous note than to the following note (this might already be a submitted issue)].

**Comment by rettinghaus** [comment]
This is a stem length problem and a variant of #630

**Comment by lpugin** [comment]
Example added https://github.com/rism-digital/verovio.org/commit/b2dbf4d6f3c3af6cc618bcde5e323fdbf0bab7df
