### ISSUE TITLE
Ledger lines too narrow for eighth notes and shorter

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#684]
Ledger lines for whole notes, half notes and quarter notes look great.  However, ledger lines for eighth notes and smaller are different from quarter/half notes.  Is there a reason for that?  It seems to be a newer behavior (otherwise this is an enhancement rather than a bug report):

<img width="860" alt="screen shot 2017-08-27 at 8 26 44 pm" src="https://user-images.githubusercontent.com/3487289/29758160-24767cf4-8b66-11e7-8b03-c436863c9c28.png">

The stems for 8th notes and smaller are distractingly too close to the edge of the ledger lines, so the ledger lines for them should match the length for quarter/half notes.  If notes with ledger lines are crowded and the ledger lines touch, then the current lengths would be ideal to switch to (so don't just throw out the current style as it can be used in crowded situations).

Also notice that breve/long ledger lines need to be shifted to the left to account for the new placement of notes left-justified to the timestamp positions.  Also for completeness, the maxima ledger lines could be lengthened...

Test data:

```
**kern
=1
1eee
=2
2eee
=3
4eee
=4
8eee
=5
16eee
=6
0eee
=7
00eee
=8
000eee
==
*-
!!!filter: msearch -qe
```

Transcoded into MEI:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-08-27T20:27:30" version="2.0.0-dev-4781b92-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title xml:id="title-L20" analog="humdrum:Xfi" type="translated">msearch -qe</title>
                </titleStmt>
            </work>
        </workDesc>
        <extMeta>
            <frames xmlns:humxml="http://www.humdrum.org/ns/humxml">
                <metaFrame n="20" token="!!!RDF**kern: @ = marked note" xml:id="loc20">
                    <frameInfo>
                        <startTime float="63.75" ratfrac="3/4" />
                        <frameType>reference</frameType>
                        <referenceKey>RDF**kern</referenceKey>
                        <referenceValue>@ = marked note</referenceValue>
                    </frameInfo>
                </metaFrame>
            </frames>
        </extMeta>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001046439247" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000000057228057">
                            <staffDef xml:id="staffdef-0000001374527676" clef.shape="G" clef.line="2" n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001556906253">
                        <measure xml:id="measure-L2" n="1">
                            <staff xml:id="staff-L2F1N1" n="1">
                                <layer xml:id="layer-L2F1N1" n="1">
                                    <note xml:id="note-L3F1" type="marked" dur="1" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L4" n="2">
                            <staff xml:id="staff-L4F1N1" n="1">
                                <layer xml:id="layer-L4F1N1" n="1">
                                    <note xml:id="note-L5F1" type="marked" dur="2" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L6" n="3">
                            <staff xml:id="staff-L6F1N1" n="1">
                                <layer xml:id="layer-L6F1N1" n="1">
                                    <note xml:id="note-L7F1" type="marked" dur="4" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L8" n="4">
                            <staff xml:id="staff-L8F1N1" n="1">
                                <layer xml:id="layer-L8F1N1" n="1">
                                    <note xml:id="note-L9F1" type="marked" dur="8" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L10" n="5">
                            <staff xml:id="staff-L10F1N1" n="1">
                                <layer xml:id="layer-L10F1N1" n="1">
                                    <note xml:id="note-L11F1" type="marked" dur="16" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L12" n="6">
                            <staff xml:id="staff-L12F1N1" n="1">
                                <layer xml:id="layer-L12F1N1" n="1">
                                    <note xml:id="note-L13F1" type="marked" dur="breve" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L14" n="7">
                            <staff xml:id="staff-L14F1N1" n="1">
                                <layer xml:id="layer-L14F1N1" n="1">
                                    <note xml:id="note-L15F1" type="marked" dur="long" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L16" right="end" n="8">
                            <staff xml:id="staff-L16F1N1" n="1">
                                <layer xml:id="layer-L16F1N1" n="1">
                                    <note xml:id="note-L17F1" type="marked" dur="maxima" oct="6" pname="e" color="red" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
I guess the hard-coded way doesn't work well with ledger lines …

**Comment by lpugin** [comment]
Ledger lines are shorter with shorter duration notes in order to avoid them to connect.

**Comment by donbyrd** [comment]
If I understand what you're saying, @lpugin, the proper way to keep ledger lines on successive notes from touching each other is to increase the margins around the notes, not to shorten the ledger lines.

**Comment by lpugin** [comment]
No, the opposite. That is, have shorter ledger lines. Nothing was changed in Verovio recently, so I will change the ticket to enhancement.

**Comment by craigsapp** [comment]
> No, the opposite. That is, have shorter ledger lines. Nothing was changed in Verovio recently, so I will change the ticket to enhancement.

OK :-)

The ledger lines on the short notes can be shorter, but only in context.

In this context it is OK:

<img width="141" alt="screen shot 2017-08-28 at 6 52 29 am" src="https://user-images.githubusercontent.com/3487289/29776459-8386b9f0-8bbd-11e7-952a-afb3d32c282d.png">

But in these it is not OK because there is more than enough space:

<img width="551" alt="screen shot 2017-08-28 at 6 53 17 am" src="https://user-images.githubusercontent.com/3487289/29776507-a1a39372-8bbd-11e7-8dfc-61011c082c3c.png">

Also notice that the ledger lines look lopsided (longer on one side than another).  This is probably due to piexlation rather than in the vector graphics, so nothing can really be done (other than avoiding shortened ledger lines when they are not needed).  Probably the interaction with the stem makes the right side of the ledger line shorter in the first note.  Here is a zoom-in where you can see the stem anti-aliasing one pixel into the ledger line:

<img width="521" alt="screen shot 2017-08-28 at 6 56 29 am" src="https://user-images.githubusercontent.com/3487289/29776612-080e44f4-8bbe-11e7-9e64-da2b47a70c1a.png">

So another possibility is to either shift the ledger lines slightly towards the stem, or to slightly lengthen the stem-side of the ledger line (but this is difficult to predict since it is related to pixelization on the screen).

**Comment by lpugin** [comment]
> The ledger lines on the short notes can be shorter, but only in context.

Yes, we need to determine the context. I will think about it

(The length difference is a visual artefact.)

**Comment by craigsapp** [comment]
Mostly I think that you would do layout with long ledger lines (not worrying about their bounding boxes perhaps), and then if the gap between ledger lines is within a certain tolerance, the adjacent ledger lines would switch to the short form to widen the gap.

**Comment by rettinghaus** [comment]
I'd like to add a ledger lines feature request: 
use ledger line calculation for rests (and mRests), too. 
At the moment it simply adds a single line when above/below the system, but should instead use the same mechanism like notes. 

![rests](https://user-images.githubusercontent.com/7693447/36933329-65c25264-1ed7-11e8-8f54-6f51c3f97f6a.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt>
      </pubStmt>
    </fileDesc>
    <encodingDesc>
    </encodingDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef midi.bpm="120">
            <staffGrp>
              <staffDef clef.shape="C" clef.line="1" key.mode="major" meter.count="3" meter.unit="4" n="1" lines="1" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer n="1">
                  <mRest/>
                </layer>
              </staff>
            </measure>
            <measure>
              <staff n="1">
                <layer n="1">
                  <mRest loc="2"/>
                </layer>
              </staff>
            </measure>
            <measure>
              <staff n="1">
                <layer n="1">
                  <mRest loc="4"/>
                </layer>
              </staff>
            </measure>
            <measure>
              <staff n="1">
                <layer n="1">
                  <mRest loc="-2"/>
                </layer>
              </staff>
            </measure>
            <measure>
              <staff n="1">
                <layer n="1">
                  <mRest loc="-4"/>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by craigsapp** [comment]
> At the moment it simply adds a single line when above/below the system, but should instead use the same mechanism like notes.

Are you sure?  I have never seen ledger lines used for rests.

**Comment by donbyrd** [comment]
Neither have I -- unless you consider the single line for half and whole rests to be a ledger line, of course. I wouldn't be too surprised if someone has used "real" ledger lines for rests, but the standard usage is certainly just the one line.

**Comment by rettinghaus** [comment]
Okay, I take it back.

**Comment by Monceber** [comment]
This has been fixed for a while now.
![image](https://user-images.githubusercontent.com/1819669/172900702-785dd096-76e6-4499-ae92-245a0dc5c9a9.png)
