### ISSUE TITLE
staffDef@proport.numbase without @proport.num?

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#863]
Nearly all mensuration signs in JRP can be now be displayed in verovio.  The last remaining ones involve a number under the mensuration sign, such as:

<img width="111" alt="screen shot 2018-05-14 at 9 29 12 am" src="https://user-images.githubusercontent.com/3487289/40010364-589c043a-5759-11e8-9b60-26cfe26c5de7.png">

Perhaps these should be done by giving `@proport.numbase="2"` without giving any `@proport.num`?

The list:

http://ribbon.humdrum.org/doc/mensuration-sampler

**Comment by rettinghaus** [comment]
I'm totally sure, how to encode this. Or where the `@num` or `@numbase` in `<mensur>` should be displayed. Should _C2_ be encoded as `<mensur sign="C" num="2"  />` or rather combined with a `<proport num="2" />`? 
Perhaps @donbyrd or @pe-ro could shed some light on this?

**Comment by craigsapp** [comment]
Yes, [white] mensuration meanings can get messy and change slightly in meaning over time and location.  It would be useful to have graphic and logical meanings separable (specify graphical meaning usually, but qualify logical meaning when graphical symbol conflicts with standard meaning).

I am thinking `proport` should be used as a form of tempo control, and `mensur@num` should be used for visual numbers.  But `@mensur.num` and `@mensur.numbase` are not currently available in `<staffDef>`.

The meaning of the C2 mensuration is that the beat (tactus) is at the breve level rather than at the semibreve level of C and Cut-C mensurations (perhaps would be called hypermeter in modern music).  So in this case it is a form of proportion, but in this case I don't think there is a tempo implication, and therefore it may not exactly be a proportion.  There is also Cut-C 2, which is 2:1 ratio of C2 (tempo is twice as fast)

However the Reverse-C mensuration is a form of proportion, representing 4:3 (33% faster tempo than C mensuration).  This proportion is implied but not written (i.e., it is a logical proportion).

Similarly the slash originally meant 2:1 ratio.  Cut-C is played at a faster tempo than C, but the ratio is not always strictly 2:1 over time.

There are also mensuration signs proposed by Tinctoris (but not used by anyone else) that are essentially explicit proportions.  For example he would write 4 over 3 rather than reverse C to indicate a 4:3 proportion.  The 3 mensuration sign would be written as 3:2 by Tinctoris, but usually everyone else drops the 2.  The modern meaning of 3 mensuration is triplets.

Here is a table of mensuration signs for JRP with notes about meaning:

http://wiki.ccarh.org/wiki/Josquin_Project_encoding_standards#Mensural_signs

The most common mensurations and their slashed (2:1) versions:

<img width="713" alt="screen shot 2018-05-15 at 4 49 15 am" src="https://user-images.githubusercontent.com/3487289/40054910-2a796a00-57fb-11e8-8f89-06f87de481dc.png">

Mensurations that involve higher rhythmic levels:

<img width="716" alt="screen shot 2018-05-15 at 4 50 25 am" src="https://user-images.githubusercontent.com/3487289/40054967-4e332a30-57fb-11e8-8b6f-8a86994d6273.png">

Other mensurations:

<img width="711" alt="screen shot 2018-05-15 at 4 51 04 am" src="https://user-images.githubusercontent.com/3487289/40055016-64d1e9ca-57fb-11e8-979b-9ad0d779c710.png">

Ars nova: Italian pre-white mensural mensurations (more than just 2 or 3 divisions between each note level):

<img width="713" alt="screen shot 2018-05-15 at 4 52 05 am" src="https://user-images.githubusercontent.com/3487289/40055055-85f115a4-57fb-11e8-8eec-d69fbcd866ff.png">

**Comment by lpugin** [comment]
This should now be encoded with `mensur@sign` and `mensur@numbase`.
